<?php

namespace Database\Seeders\TreeSpecies;

use App\Models\Tree\Tree;
use Illuminate\Database\Seeder;

class TreeSpeciesSeeder7 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $trees = array(
            array('id' => '4910','genus_name' => 'Picea','species_name' => 'jezoensis','common_name' => 'Yeddo spruce','growth_rate' => 'Moderate','height_at_maturity' => '115'),
            array('id' => '4911','genus_name' => 'Pinus','species_name' => 'jeffreyi','common_name' => 'Jeffery pine','growth_rate' => 'Fast','height_at_maturity' => '180'),
            array('id' => '4913','genus_name' => 'Pittosporum','species_name' => 'kauaiense','common_name' => 'Kauai cheesewood','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '4914','genus_name' => 'Pithecellobium','species_name' => 'keyense','common_name' => 'Florida keys blackbead','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '4915','genus_name' => 'Pinus','species_name' => 'kesiya','common_name' => 'Khasia pine','growth_rate' => 'Slow','height_at_maturity' => '115'),
            array('id' => '4916','genus_name' => 'Pinus','species_name' => 'koraiensis','common_name' => 'Korean pine','growth_rate' => '','height_at_maturity' => '35'),
            array('id' => '4917','genus_name' => 'Picea','species_name' => 'koraiensis','common_name' => 'Korean spruce','growth_rate' => 'Moderate','height_at_maturity' => '100'),
            array('id' => '4918','genus_name' => 'Picea','species_name' => 'koyamae','common_name' => 'Koyame spruce','growth_rate' => 'Moderate','height_at_maturity' => '67'),
            array('id' => '4919','genus_name' => 'Pinus','species_name' => 'lambertiana','common_name' => 'Sugar pine','growth_rate' => 'Fast','height_at_maturity' => '229'),
            array('id' => '4920','genus_name' => 'Pinus','species_name' => 'leiophylla','common_name' => 'Chihuahua pine','growth_rate' => 'Slow','height_at_maturity' => '115'),
            array('id' => '4921','genus_name' => 'Pistacia','species_name' => 'lentiscus','common_name' => 'Mastic tree','growth_rate' => '','height_at_maturity' => '16'),
            array('id' => '4922','genus_name' => 'Pinus','species_name' => 'leucodermis','common_name' => 'Bosnian pine','growth_rate' => 'Slow','height_at_maturity' => '70'),
            array('id' => '4923','genus_name' => 'Picea','species_name' => 'likiangensis','common_name' => 'Lijiang Spruce','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '4924','genus_name' => 'Pinus','species_name' => 'longaeva','common_name' => 'Intermountain bristlecone pine','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '4925','genus_name' => 'Picea','species_name' => 'x lutzii','common_name' => 'Lutz\'s spruce','growth_rate' => 'Moderate','height_at_maturity' => '76'),
            array('id' => '4926','genus_name' => 'Picea','species_name' => 'mariana','common_name' => 'Black spruce','growth_rate' => 'Slow','height_at_maturity' => '65'),
            array('id' => '4927','genus_name' => 'Pinus','species_name' => 'maximartinezii','common_name' => 'Martinez pinyon','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '4928','genus_name' => 'Pinus','species_name' => 'massoniana','common_name' => 'Chinese red pine','growth_rate' => 'Slow','height_at_maturity' => '150'),
            array('id' => '4929','genus_name' => 'Pinus','species_name' => 'maritima','common_name' => 'Pinus maritima','growth_rate' => 'Slow','height_at_maturity' => '70'),
            array('id' => '4930','genus_name' => 'Piper','species_name' => 'marginatum','common_name' => 'Marigold pepper','growth_rate' => '','height_at_maturity' => '9'),
            array('id' => '4932','genus_name' => 'Picea','species_name' => 'meyeri','common_name' => 'Meyers spruce','growth_rate' => '','height_at_maturity' => '90'),
            array('id' => '4933','genus_name' => 'Pinus','species_name' => 'merkusii','common_name' => 'Merkus pine','growth_rate' => '','height_at_maturity' => '100'),
            array('id' => '4934','genus_name' => 'Picea','species_name' => 'montigena','common_name' => 'Picea montigena','growth_rate' => 'Slow','height_at_maturity' => '60'),
            array('id' => '4935','genus_name' => 'Pittosporum','species_name' => 'moluccanum','common_name' => 'Prices Point Orange','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '4936','genus_name' => 'Pinus','species_name' => 'monophylla','common_name' => 'Singleleaf pinyon pine','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '4937','genus_name' => 'Pinus','species_name' => 'monticola','common_name' => 'Western white pine','growth_rate' => 'Fast','height_at_maturity' => '200'),
            array('id' => '4938','genus_name' => 'Pittosporum','species_name' => 'x monae','common_name' => 'Mona cheesewood','growth_rate' => 'Moderate','height_at_maturity' => '43'),
            array('id' => '4940','genus_name' => 'Pinus','species_name' => 'montezumae','common_name' => 'Montezuma pine','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '4941','genus_name' => 'Pinus','species_name' => 'mugo','common_name' => 'Swiss mountain pine','growth_rate' => 'Fast','height_at_maturity' => '70'),
            array('id' => '4942','genus_name' => 'Pinus','species_name' => 'muricata','common_name' => 'Bishop pine','growth_rate' => 'Fast','height_at_maturity' => '90'),
            array('id' => '4943','genus_name' => 'Pittosporum','species_name' => 'napaliense','common_name' => 'Royal cheesewood','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '4944','genus_name' => 'Pinus','species_name' => 'nigra','common_name' => 'Austrian pine','growth_rate' => 'Moderate','height_at_maturity' => '120'),
            array('id' => '4945','genus_name' => 'Pinus','species_name' => 'nigricans','common_name' => 'Pinus nigricans','growth_rate' => 'Slow','height_at_maturity' => '70'),
            array('id' => '4946','genus_name' => 'Pinus','species_name' => 'nigra ssp. salzmannii','common_name' => 'Corsican pine','growth_rate' => 'Slow','height_at_maturity' => '70'),
            array('id' => '4947','genus_name' => 'Pinus','species_name' => 'nigra ssp. pallisiana','common_name' => 'Anatolian black pine','growth_rate' => 'Moderate','height_at_maturity' => '131'),
            array('id' => '4948','genus_name' => 'Pinus','species_name' => 'nigra corsicana','common_name' => 'Pinus nigra corsicana','growth_rate' => 'Moderate','height_at_maturity' => '45'),
            array('id' => '4949','genus_name' => 'Pinus','species_name' => 'nigra ssp. Nigra','common_name' => 'Black pine','growth_rate' => 'Moderate','height_at_maturity' => '45'),
            array('id' => '4950','genus_name' => 'Pinus','species_name' => 'oaxacana','common_name' => 'Pinus oaxacana','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '4951','genus_name' => 'Picea','species_name' => 'obovata','common_name' => 'Siberian Spruce','growth_rate' => 'Slow','height_at_maturity' => '42'),
            array('id' => '4952','genus_name' => 'Picea','species_name' => 'omorika','common_name' => 'Serbian spruce','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '4954','genus_name' => 'Picea','species_name' => 'orientalis','common_name' => 'Oriental spruce','growth_rate' => '','height_at_maturity' => '55'),
            array('id' => '4955','genus_name' => 'Pinus','species_name' => 'palustris','common_name' => 'Longleaf pine','growth_rate' => 'Fast','height_at_maturity' => '120'),
            array('id' => '4957','genus_name' => 'Pinus','species_name' => 'parviflora','common_name' => 'Japanese white pine','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '4958','genus_name' => 'Pinus','species_name' => 'pallasiana','common_name' => 'Pinus pallasiana','growth_rate' => 'Slow','height_at_maturity' => '70'),
            array('id' => '4959','genus_name' => 'Pinus','species_name' => 'patula','common_name' => 'Mexican weeping pine','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '4962','genus_name' => 'Pinus','species_name' => 'peuce','common_name' => 'Macedonian Pine','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '4963','genus_name' => 'Pittosporum','species_name' => 'pentandrum','common_name' => 'Taiwanese cheesewood','growth_rate' => 'Moderate','height_at_maturity' => '67'),
            array('id' => '4965','genus_name' => 'Pittosporum','species_name' => 'phillyreoides','common_name' => 'Weeping Pittosporum','growth_rate' => 'Fast','height_at_maturity' => '7'),
            array('id' => '4967','genus_name' => 'Pinus','species_name' => 'pithyusa','common_name' => 'Pitsundian pine','growth_rate' => 'Slow','height_at_maturity' => '70'),
            array('id' => '4968','genus_name' => 'Piscidia','species_name' => 'piscipula','common_name' => 'Florida fishpoision tree','growth_rate' => 'Fast','height_at_maturity' => '35'),
            array('id' => '4969','genus_name' => 'Pinus','species_name' => 'pinea','common_name' => 'Italian stone pine','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '4970','genus_name' => 'Pinus','species_name' => 'pinceana','common_name' => 'Weeping pinyon pine','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '4971','genus_name' => 'Pinus','species_name' => 'pinaster','common_name' => 'Maritime pine','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '4972','genus_name' => 'Pinus','species_name' => 'ponderosa','common_name' => 'Ponderosa pine','growth_rate' => 'Moderate','height_at_maturity' => '223'),
            array('id' => '4973','genus_name' => 'Pittocaullon','species_name' => 'praecox','common_name' => 'Pittocaullon praecox','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '4974','genus_name' => 'Pinus','species_name' => 'pseudostrobus','common_name' => 'Smooth-bark Mexican pine','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '4975','genus_name' => 'Picea','species_name' => 'pungens','common_name' => 'Blue spruce','growth_rate' => 'Slow','height_at_maturity' => '100'),
            array('id' => '4976','genus_name' => 'Pinckneya','species_name' => 'bracteata','common_name' => 'Fever bark','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '4977','genus_name' => 'Pinus','species_name' => 'pungens','common_name' => 'Table mountain pine','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '4978','genus_name' => 'Pinus','species_name' => 'quadrifolia','common_name' => 'Parry pinyon','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '4979','genus_name' => 'Picrasma','species_name' => 'quassioides','common_name' => 'Nigaki','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '4980','genus_name' => 'Pinus','species_name' => 'radiata','common_name' => 'Monterey pine','growth_rate' => 'Fast','height_at_maturity' => '120'),
            array('id' => '4981','genus_name' => 'Pittosporum','species_name' => 'ralphii','common_name' => 'Ralphs Desert Willow','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '4982','genus_name' => 'Pimenta','species_name' => 'racemosa','common_name' => 'Bay rum tree','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '4984','genus_name' => 'Pinus','species_name' => 'resinosa','common_name' => 'Red pine','growth_rate' => 'Fast','height_at_maturity' => '80'),
            array('id' => '4985','genus_name' => 'Pittosporum','species_name' => 'revolutum','common_name' => 'Rough-fruit Pittosporum','growth_rate' => 'Fast','height_at_maturity' => '3'),
            array('id' => '4986','genus_name' => 'Pinus','species_name' => 'remota','common_name' => 'Papershell pinyon','growth_rate' => 'Slow','height_at_maturity' => '70'),
            array('id' => '4987','genus_name' => 'Pittosporum','species_name' => 'rhombifolium','common_name' => 'Queensland pittosporum','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '4988','genus_name' => 'Pinus','species_name' => 'rigida','common_name' => 'Pitch pine','growth_rate' => 'Fast','height_at_maturity' => '80'),
            array('id' => '4991','genus_name' => 'Pinus','species_name' => 'roxburghii','common_name' => 'Chir pine','growth_rate' => '','height_at_maturity' => '181'),
            array('id' => '4992','genus_name' => 'Pisonia','species_name' => 'rotundata','common_name' => 'Smooth devil\'s-claws','growth_rate' => 'Fast','height_at_maturity' => '17'),
            array('id' => '4995','genus_name' => 'Picea','species_name' => 'rubens','common_name' => 'Red spruce','growth_rate' => 'Moderate','height_at_maturity' => '110'),
            array('id' => '4997','genus_name' => 'Pinus','species_name' => 'sabiniana','common_name' => 'Digger pine','growth_rate' => 'Slow','height_at_maturity' => '80'),
            array('id' => '4998','genus_name' => 'Samanea','species_name' => 'saman','common_name' => 'Raintree','growth_rate' => 'Fast','height_at_maturity' => '80'),
            array('id' => '4999','genus_name' => 'Pisonia','species_name' => 'sandwicensis','common_name' => 'Aulu','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '5000','genus_name' => 'Pinus','species_name' => 'serotina','common_name' => 'Pond pine','growth_rate' => 'Moderate','height_at_maturity' => '80'),
            array('id' => '5001','genus_name' => 'Picea','species_name' => 'sitchensis','common_name' => 'Sitka spruce','growth_rate' => 'Moderate','height_at_maturity' => '200'),
            array('id' => '5002','genus_name' => 'Picea','species_name' => 'smithiana','common_name' => 'Morinda Spruce','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '5003','genus_name' => 'Pinus','species_name' => 'x sondereggeri','common_name' => 'Sonderegger pine','growth_rate' => 'Slow','height_at_maturity' => '70'),
            array('id' => '5004','genus_name' => 'Picea','species_name' => 'spinulosa','common_name' => 'East Himalayan Spruce','growth_rate' => 'Slow','height_at_maturity' => '60'),
            array('id' => '5005','genus_name' => 'Pinus','species_name' => 'strobus','common_name' => 'Eastern white pine','growth_rate' => 'Fast','height_at_maturity' => '150'),
            array('id' => '5006','genus_name' => 'Pinus','species_name' => 'strobiformis','common_name' => 'Southwestern white pine','growth_rate' => 'Fast','height_at_maturity' => '80'),
            array('id' => '5007','genus_name' => 'Pisonia','species_name' => 'subcordata','common_name' => 'Water mampoo','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '5008','genus_name' => 'Piper','species_name' => 'swartzianum','common_name' => 'Spanish elder','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '5009','genus_name' => 'Pinus','species_name' => 'sylvestris','common_name' => 'Scots pine','growth_rate' => 'Fast','height_at_maturity' => '110'),
            array('id' => '5010','genus_name' => 'Pinus','species_name' => 'sylvestris var. hamata','common_name' => 'Baklan scotch pine','growth_rate' => 'Moderate','height_at_maturity' => '110'),
            array('id' => '5011','genus_name' => 'Pinus','species_name' => 'taeda','common_name' => 'Loblolly pine','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '5012','genus_name' => 'Pinus','species_name' => 'tabuliformis','common_name' => 'Chinese Pine','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '5013','genus_name' => 'Pinus','species_name' => 'tabulaeformis','common_name' => 'Southern chinese pine','growth_rate' => 'Moderate','height_at_maturity' => '53'),
            array('id' => '5014','genus_name' => 'Pistacia','species_name' => 'mexicana','common_name' => 'Texas pistache','growth_rate' => 'Slow','height_at_maturity' => '42'),
            array('id' => '5015','genus_name' => 'Pinus','species_name' => 'tenuifolia','common_name' => 'Pinus tenuifolia','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '5016','genus_name' => 'Pittosporum','species_name' => 'tenuifolium','common_name' => 'Tawhiwhi','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '5017','genus_name' => 'Pittosporum','species_name' => 'tenuifolium \'James Stirling\'','common_name' => '\'James Stirling\' pittosporum','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '5018','genus_name' => 'Pittosporum','species_name' => 'tenuifolium \'Limelight\'','common_name' => 'Limelight','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '5019','genus_name' => 'Pittosporum','species_name' => 'tenuifolium \'Variegatum\'','common_name' => 'Cheesewood','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '5020','genus_name' => 'Pinus','species_name' => 'teocote','common_name' => 'Aztec pine','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '5021','genus_name' => 'Pittosporum','species_name' => 'terminalioides','common_name' => 'Cream cheesewood','growth_rate' => 'Moderate','height_at_maturity' => '16'),
            array('id' => '5023','genus_name' => 'Pinus','species_name' => 'thunbergiana','common_name' => 'Japanese pine','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '5024','genus_name' => 'Pinus','species_name' => 'thunbergii','common_name' => 'Japanese black pines','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '5025','genus_name' => 'Pittosporum','species_name' => 'tobira','common_name' => 'Japanese pittosporum','growth_rate' => 'Slow','height_at_maturity' => '43'),
            array('id' => '5026','genus_name' => 'Picea','species_name' => 'torano','common_name' => 'Tiger-tail Spruce','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '5027','genus_name' => 'Pinus','species_name' => 'torreyana','common_name' => 'Torrey pine','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '5028','genus_name' => 'Pittosporum','species_name' => 'tobira \'Nanum\'','common_name' => 'Japanese mock orange','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '5029','genus_name' => 'Pisonia','species_name' => 'umbellifera \'Variegata\'','common_name' => 'Bird catcher tree','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '5030','genus_name' => 'Pisonia','species_name' => 'umbellifera','common_name' => 'Umbrella catchbirdtree','growth_rate' => 'Fast','height_at_maturity' => '67'),
            array('id' => '5031','genus_name' => 'Pittosporum','species_name' => 'undulatum','common_name' => 'Victorian box','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '5032','genus_name' => 'Pithecellobium','species_name' => 'unguis-cati','common_name' => 'Catclaw blackbead','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '5033','genus_name' => 'Pinus','species_name' => 'uncinata','common_name' => 'Mountain pine','growth_rate' => 'Slow','height_at_maturity' => '70'),
            array('id' => '5034','genus_name' => 'Pistacia','species_name' => 'vera','common_name' => 'Pistachio','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '5035','genus_name' => 'Pinus','species_name' => 'virginiana','common_name' => 'Virginia pine','growth_rate' => 'Fast','height_at_maturity' => '70'),
            array('id' => '5036','genus_name' => 'Pittosporum','species_name' => 'viridiflorum','common_name' => 'Cape cheesewood','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '5037','genus_name' => 'Pinus','species_name' => 'washoensis','common_name' => 'Washoe pine','growth_rate' => 'Slow','height_at_maturity' => '115'),
            array('id' => '5038','genus_name' => 'Pinus','species_name' => 'wallichiana','common_name' => 'Bhutan pine','growth_rate' => 'Moderate','height_at_maturity' => '165'),
            array('id' => '5039','genus_name' => 'Pisonia','species_name' => 'wagneriana','common_name' => 'Kauai catchbirdtree','growth_rate' => '','height_at_maturity' => '35'),
            array('id' => '5040','genus_name' => 'Picea','species_name' => 'wilsonii','common_name' => 'Wilson spruce','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '5041','genus_name' => 'Pinus','species_name' => 'yunnanensis','common_name' => 'Yunnan pine','growth_rate' => 'Slow','height_at_maturity' => '80'),
            array('id' => '5042','genus_name' => 'Platanus','species_name' => 'hybrida','common_name' => 'London plane','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '5045','genus_name' => 'Platanus','species_name' => 'x acerifolia \'Bloodgood\'','common_name' => 'London planetree Bloodgood','growth_rate' => '','height_at_maturity' => '78'),
            array('id' => '5047','genus_name' => 'Plumeria','species_name' => 'alba','common_name' => 'Nosegay tree','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '5049','genus_name' => 'Planera','species_name' => 'aquatica','common_name' => 'Water elm','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '5050','genus_name' => 'Planchonella','species_name' => 'australis','common_name' => 'Black plum','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '5051','genus_name' => 'Plumbago','species_name' => 'auriculata','common_name' => 'Cape leadwort','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '5054','genus_name' => 'Plectranthus','species_name' => 'barbatus','common_name' => 'Indian Coleus','growth_rate' => 'Fast','height_at_maturity' => '7'),
            array('id' => '5059','genus_name' => 'Platypodium','species_name' => 'elegans','common_name' => 'Canoito','growth_rate' => 'Slow','height_at_maturity' => '98'),
            array('id' => '5066','genus_name' => 'Platanus','species_name' => 'mexicana','common_name' => 'Mexican sycamore','growth_rate' => 'Moderate','height_at_maturity' => '60'),
            array('id' => '5067','genus_name' => 'Plumeria','species_name' => 'obtusa','common_name' => 'Singapore graveyard flower','growth_rate' => 'Slow','height_at_maturity' => '17'),
            array('id' => '5068','genus_name' => 'Platanus','species_name' => 'occidentalis','common_name' => 'American sycamore','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '5069','genus_name' => 'Platanus','species_name' => 'orientalis','common_name' => 'Oriental planetree','growth_rate' => 'Fast','height_at_maturity' => '80'),
            array('id' => '5070','genus_name' => 'Platanus','species_name' => 'orientalis digitata','common_name' => 'Cut leaf plane','growth_rate' => 'Moderate','height_at_maturity' => '83'),
            array('id' => '5071','genus_name' => 'Platanus','species_name' => 'insularis','common_name' => 'Cyprus plane','growth_rate' => 'Moderate','height_at_maturity' => '83'),
            array('id' => '5074','genus_name' => 'Platanus','species_name' => 'racemosa','common_name' => 'California sycamore','growth_rate' => 'Slow','height_at_maturity' => '75'),
            array('id' => '5077','genus_name' => 'Platydesma','species_name' => 'remyi','common_name' => 'Hawai\'i pilo kea','growth_rate' => '','height_at_maturity' => '7'),
            array('id' => '5079','genus_name' => 'Plumeria','species_name' => 'rubra','common_name' => 'Frangipani','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '5081','genus_name' => 'Platydesma','species_name' => 'spathulata','common_name' => 'Maui pilo kea','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '5082','genus_name' => 'Platanus','species_name' => 'wrightii','common_name' => 'Arizona sycamore','growth_rate' => 'Slow','height_at_maturity' => '80'),
            array('id' => '5084','genus_name' => 'Populus','species_name' => 'x acuminata','common_name' => 'Lanceleaf cottonwood','growth_rate' => 'Moderate','height_at_maturity' => '45'),
            array('id' => '5085','genus_name' => 'Pouteria','species_name' => 'adolfi-friederici','common_name' => 'Qararoo','growth_rate' => 'Fast','height_at_maturity' => '185'),
            array('id' => '5086','genus_name' => 'Populus','species_name' => 'alba','common_name' => 'White poplar','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '5087','genus_name' => 'Populus','species_name' => 'alba ssp. Pyramidalis','common_name' => 'White poplar Pyramidalis','growth_rate' => 'Fast','height_at_maturity' => '80'),
            array('id' => '5088','genus_name' => 'Populus','species_name' => 'angustifolia','common_name' => 'Narrowleaf cottonwood','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '5089','genus_name' => 'Prumnopitys','species_name' => 'andina','common_name' => 'Plum-fruited yew','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '5090','genus_name' => 'Pomaderris','species_name' => 'apetala','common_name' => 'Tainui','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '5091','genus_name' => 'Pomaderris','species_name' => 'aspera','common_name' => 'Hazel Pomaderris','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '5092','genus_name' => 'Polyalthia','species_name' => 'australis','common_name' => 'Cape Canary Beech','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '5093','genus_name' => 'Populus','species_name' => 'balsamifera','common_name' => 'Balsam poplar','growth_rate' => 'Fast','height_at_maturity' => '80'),
            array('id' => '5095','genus_name' => 'Populus','species_name' => 'x brayshawii','common_name' => 'Hybrid balsam poplar','growth_rate' => 'Fast','height_at_maturity' => '99'),
            array('id' => '5096','genus_name' => 'Populus','species_name' => 'x canescens','common_name' => 'Grey poplar','growth_rate' => 'Fast','height_at_maturity' => '63'),
            array('id' => '5097','genus_name' => 'Populus','species_name' => 'canescens','common_name' => 'Populus canescens','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '5098','genus_name' => 'Populus','species_name' => 'x canadensis','common_name' => 'Carolina poplar','growth_rate' => 'Fast','height_at_maturity' => '110'),
            array('id' => '5099','genus_name' => 'Pouteria','species_name' => 'campechiana','common_name' => 'Canistel','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '5100','genus_name' => 'Populus','species_name' => 'x canadensis \'Aurea\'','common_name' => 'Golden carolina poplar','growth_rate' => 'Fast','height_at_maturity' => '16'),
            array('id' => '5102','genus_name' => 'Podocarpus','species_name' => 'coriaceus','common_name' => 'Yucca plum pine','growth_rate' => 'Slow','height_at_maturity' => '48'),
            array('id' => '5103','genus_name' => 'Polygala','species_name' => 'cowellii','common_name' => 'Violet tree','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '5106','genus_name' => 'Populus','species_name' => 'davidiana','common_name' => 'Korean aspen','growth_rate' => '','height_at_maturity' => '82'),
            array('id' => '5107','genus_name' => 'Populus','species_name' => 'deltoides','common_name' => 'Eastern cottonwood','growth_rate' => 'Fast','height_at_maturity' => '190'),
            array('id' => '5110','genus_name' => 'Podocarpus','species_name' => 'elatus','common_name' => 'Plum pine','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '5111','genus_name' => 'Polyscias','species_name' => 'elegans','common_name' => 'Celerywood','growth_rate' => 'Moderate','height_at_maturity' => '82'),
            array('id' => '5112','genus_name' => 'Pomaderris','species_name' => 'elliptica','common_name' => 'Yellow Dogwood','growth_rate' => 'Fast','height_at_maturity' => '4'),
            array('id' => '5113','genus_name' => 'Podachaenium','species_name' => 'eminens','common_name' => 'Giant Tree Daisy','growth_rate' => 'Fast','height_at_maturity' => '5'),
            array('id' => '5114','genus_name' => 'Populus','species_name' => 'euramericana x nigra','common_name' => 'Crows Nest poplar','growth_rate' => 'Fast','height_at_maturity' => '18'),
            array('id' => '5115','genus_name' => 'Podocarpus','species_name' => 'falcatus','common_name' => 'Common Yellowwood','growth_rate' => 'Fast','height_at_maturity' => '45'),
            array('id' => '5117','genus_name' => 'Populus','species_name' => 'fremontii','common_name' => 'Fremont cottonwood','growth_rate' => 'Fast','height_at_maturity' => '90'),
            array('id' => '5118','genus_name' => 'Dasiphora','species_name' => 'floribunda','common_name' => 'Shrubby cinquefoil','growth_rate' => 'Fast','height_at_maturity' => '90'),
            array('id' => '5119','genus_name' => 'Potentilla','species_name' => 'fruiticosa','common_name' => 'Shrubby cinquifoil','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '5121','genus_name' => 'Populus','species_name' => 'grandidentata','common_name' => 'Bigtooth aspen','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '5122','genus_name' => 'Podocarpus','species_name' => 'gracilior','common_name' => 'Fern pine','growth_rate' => 'Slow','height_at_maturity' => '65'),
            array('id' => '5124','genus_name' => 'Polyscias','species_name' => 'guilfoylei','common_name' => 'Geranium aralia','growth_rate' => '','height_at_maturity' => '24'),
            array('id' => '5125','genus_name' => 'Populus','species_name' => 'heterophylla','common_name' => 'Swamp cottonwood','growth_rate' => 'Moderate','height_at_maturity' => '100'),
            array('id' => '5127','genus_name' => 'Populus','species_name' => 'x heimburgeri','common_name' => 'Heiburger\'s poplar','growth_rate' => 'Fast','height_at_maturity' => '99'),
            array('id' => '5129','genus_name' => 'Populus','species_name' => 'x hinckleyana','common_name' => 'Hinckley poplar','growth_rate' => 'Fast','height_at_maturity' => '99'),
            array('id' => '5132','genus_name' => 'Populus','species_name' => 'x inopina','common_name' => 'Populus x inopina','growth_rate' => 'Fast','height_at_maturity' => '99'),
            array('id' => '5133','genus_name' => 'Populus','species_name' => 'x jackii','common_name' => 'Balm-of-gilead','growth_rate' => 'Fast','height_at_maturity' => '99'),
            array('id' => '5134','genus_name' => 'Populus','species_name' => 'koreana','common_name' => 'Korean poplar','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '5135','genus_name' => 'Populus','species_name' => 'lasiocarpa','common_name' => 'Chinese Necklace Poplar','growth_rate' => 'Fast','height_at_maturity' => '18'),
            array('id' => '5136','genus_name' => 'Podocarpus','species_name' => 'lawrencei','common_name' => 'Mountain Plum Pine','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '5138','genus_name' => 'Polyalthia','species_name' => 'longifolia','common_name' => 'Cemetery tree','growth_rate' => '','height_at_maturity' => '65'),
            array('id' => '5139','genus_name' => 'Polyalthia','species_name' => 'longifolia v. pendula','common_name' => 'Weeping Mast Tree','growth_rate' => 'Fast','height_at_maturity' => '16'),
            array('id' => '5140','genus_name' => 'Podocarpus','species_name' => 'macrophyllus','common_name' => 'Yew podocarpus','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '5141','genus_name' => 'Populus','species_name' => 'maximowiczii','common_name' => 'Japanese poplar','growth_rate' => 'Fast','height_at_maturity' => '99'),
            array('id' => '5142','genus_name' => 'Pouteria','species_name' => 'multiflora','common_name' => 'Bullytree','growth_rate' => 'Moderate','height_at_maturity' => '92'),
            array('id' => '5143','genus_name' => 'Podocarpus','species_name' => 'nagi','common_name' => 'Broad leaf podocarpus','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '5145','genus_name' => 'Populus','species_name' => 'nigra','common_name' => 'Black poplar','growth_rate' => 'Fast','height_at_maturity' => '190'),
            array('id' => '5146','genus_name' => 'Populus','species_name' => 'nigra betulifolia','common_name' => 'Wild black poplar','growth_rate' => 'Slow','height_at_maturity' => '125'),
            array('id' => '5147','genus_name' => 'Populus','species_name' => 'nigra v. italica','common_name' => 'Lombardy poplar','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '5148','genus_name' => 'Pouteria','species_name' => 'obovata','common_name' => 'Yellow boxwood','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '5150','genus_name' => 'Populus','species_name' => 'x parryi','common_name' => 'Parry\'s cottonwood','growth_rate' => 'Fast','height_at_maturity' => '99'),
            array('id' => '5153','genus_name' => 'Derris','species_name' => 'indica','common_name' => 'Poonga oil tree','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '5157','genus_name' => 'Pontederia','species_name' => 'rotundifolia','common_name' => 'Tropical pickerelweed','growth_rate' => '','height_at_maturity' => '90'),
            array('id' => '5158','genus_name' => 'Populus','species_name' => 'x rouleauana','common_name' => 'Populus x rouleauana','growth_rate' => 'Fast','height_at_maturity' => '99'),
            array('id' => '5159','genus_name' => 'Populus','species_name' => 'deltoides ssp. monilifera','common_name' => 'Plains cottonwood','growth_rate' => 'Fast','height_at_maturity' => '85'),
            array('id' => '5160','genus_name' => 'Pouteria','species_name' => 'sandwicensis','common_name' => 'ala\'a','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '5161','genus_name' => 'Pouteria','species_name' => 'sapota','common_name' => 'Naseberry','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '5162','genus_name' => 'Podocarpus','species_name' => 'salignus','common_name' => 'Manio de hojas largas','growth_rate' => 'Slow','height_at_maturity' => '67'),
            array('id' => '5163','genus_name' => 'Polyscias','species_name' => 'scutellaria','common_name' => 'Shield aralia','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '5164','genus_name' => 'Populus','species_name' => 'simonii','common_name' => 'Chinese popular','growth_rate' => 'Moderate','height_at_maturity' => '67'),
            array('id' => '5165','genus_name' => 'Populus','species_name' => 'simonii fastigiata','common_name' => 'Simon poplar','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '5166','genus_name' => 'Populus','species_name' => 'x smithii','common_name' => 'Smith\'s poplar','growth_rate' => 'Fast','height_at_maturity' => '99'),
            array('id' => '5167','genus_name' => 'Populus','species_name' => 'tomentosa','common_name' => 'Chinese white poplar','growth_rate' => 'Fast','height_at_maturity' => '99'),
            array('id' => '5168','genus_name' => 'Podocarpus','species_name' => 'totara','common_name' => 'Mahogany pine','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '5171','genus_name' => 'Populus','species_name' => 'trichocarpa','common_name' => 'Black cottonwood','growth_rate' => 'Moderate','height_at_maturity' => '165'),
            array('id' => '5172','genus_name' => 'Populus','species_name' => 'tremuloides','common_name' => 'Quaking aspen','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '5173','genus_name' => 'Populus','species_name' => 'tremula','common_name' => 'European aspen','growth_rate' => 'Fast','height_at_maturity' => '67'),
            array('id' => '5174','genus_name' => 'Populus','species_name' => 'balsamifera ssp. Trichocarp','common_name' => 'Brayshaw black cottonwood','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '5175','genus_name' => 'Poncirus','species_name' => 'trifoliata','common_name' => 'Hardy orange','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '5177','genus_name' => 'Populus','species_name' => 'yunnanensis','common_name' => 'Yunnan poplar','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '5179','genus_name' => 'Pritchardia','species_name' => 'affinis','common_name' => 'Hawai\'i pritchardia','growth_rate' => 'Slow','height_at_maturity' => '60'),
            array('id' => '5180','genus_name' => 'Prunus','species_name' => 'alleghaniensis','common_name' => 'Allegheny plum','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '5181','genus_name' => 'Prosopis','species_name' => 'alpataco','common_name' => 'Prosopis alpataco','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '5182','genus_name' => 'Prosopis','species_name' => 'alba','common_name' => 'Argentine mesquite','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '5183','genus_name' => 'Prunus','species_name' => 'alabamensis','common_name' => 'Alabama cherry','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5184','genus_name' => 'Prunus','species_name' => 'americana','common_name' => 'American plum','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '5185','genus_name' => 'Prunus','species_name' => 'amygdalus','common_name' => 'Almendro','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5186','genus_name' => 'Prunus','species_name' => 'angustifolia','common_name' => 'Chickasaw plum','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '5187','genus_name' => 'Prumnopitys','species_name' => 'andinus','common_name' => 'Chilean Yew','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '5188','genus_name' => 'Prunus','species_name' => 'andersonii','common_name' => 'Desert peach','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5189','genus_name' => 'Premna','species_name' => 'angolensis','common_name' => 'Muhorro','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '5190','genus_name' => 'Prunus','species_name' => 'armeniaca','common_name' => 'Apricot','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '5191','genus_name' => 'Pritchardia','species_name' => 'arecina','common_name' => 'Maui pritchardia','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '5192','genus_name' => 'Prosopis','species_name' => 'argentina','common_name' => 'Algarobilla','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '5193','genus_name' => 'Prunus','species_name' => 'avium','common_name' => 'Sweet cherry','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '5194','genus_name' => 'Pritchardia','species_name' => 'beccariana','common_name' => 'Kilauea pritchardia','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '5195','genus_name' => 'Prunus','species_name' => 'blieriana','common_name' => 'Blierana plum','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5196','genus_name' => 'Prosopis','species_name' => 'burkartii','common_name' => 'Prosopis burkartii','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '5197','genus_name' => 'Prunus','species_name' => 'caroliniana','common_name' => 'Carolina laurelcherry','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '5198','genus_name' => 'Prosopis','species_name' => 'calingastana','common_name' => 'Cusqui','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '5199','genus_name' => 'Prosopis','species_name' => 'campestris','common_name' => 'Prosopis campestris','growth_rate' => 'Moderate','height_at_maturity' => '2'),
            array('id' => '5200','genus_name' => 'Prosopis','species_name' => 'castellanosii','common_name' => 'Prosopis castellanosii','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '5201','genus_name' => 'Prunus','species_name' => 'campanulata','common_name' => 'Taiwan cherry','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '5202','genus_name' => 'Prosopis','species_name' => 'caldenia','common_name' => 'the CaldÃ©n','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '5203','genus_name' => 'Prunus','species_name' => 'cerasifera','common_name' => 'Cherry plum','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '5204','genus_name' => 'Prunus','species_name' => 'cerasifera \'Nigra\'','common_name' => 'Black cherry plum','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5205','genus_name' => 'Prunus','species_name' => 'cerasus','common_name' => 'Sour Cherry','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '5206','genus_name' => 'Prunus','species_name' => 'cerasifera \'Krauter Vesuvius\'','common_name' => 'Krauter vesuvius plum','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '5207','genus_name' => 'Prunus','species_name' => 'cerasifera \'Thundercloud\'','common_name' => '\'Thundercloud\' Purple-leaf plum','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '5208','genus_name' => 'Prosopis','species_name' => 'chilensis','common_name' => 'Chilean mesquite','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '5209','genus_name' => 'Prunus','species_name' => 'cisten','common_name' => 'Purpleleaf sand cherry','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5210','genus_name' => 'Prosopis','species_name' => 'cineraria','common_name' => 'jand','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '5211','genus_name' => 'Pradosia','species_name' => 'colombiana','common_name' => 'Mamon de leche','growth_rate' => 'Moderate','height_at_maturity' => '190'),
            array('id' => '5213','genus_name' => 'Prosopis','species_name' => 'denudans','common_name' => 'Prosopis denudans','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '5214','genus_name' => 'Prunus','species_name' => 'domestica','common_name' => 'Common plum','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '5216','genus_name' => 'Prunus','species_name' => 'dulcis','common_name' => 'Sweet almond','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5217','genus_name' => 'Prunus','species_name' => 'Elvin','common_name' => 'Autumn Flowering Cherry','growth_rate' => 'Fast','height_at_maturity' => '3'),
            array('id' => '5218','genus_name' => 'Prosopis','species_name' => 'elata','common_name' => 'Prosopis elata','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '5219','genus_name' => 'Prunus','species_name' => 'emarginata','common_name' => 'Bitter cherry','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5220','genus_name' => 'Prunus','species_name' => 'fasciculata','common_name' => 'Desert almond','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5221','genus_name' => 'Prosopis','species_name' => 'farcta','common_name' => 'Syrian mesquite','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '5222','genus_name' => 'Prosopis','species_name' => 'ferox','common_name' => 'Prosopis ferox','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '5223','genus_name' => 'Prosopis','species_name' => 'fiebrigii','common_name' => 'Prosopis fiebrigii','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '5224','genus_name' => 'Pritchardia','species_name' => 'forbesiana','common_name' => 'Mt. eke pritchardia','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '5225','genus_name' => 'Prunus','species_name' => 'fremontii','common_name' => 'Desert apricot','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '5226','genus_name' => 'Prunus','species_name' => 'fruticosa','common_name' => 'European dwarf cherry','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5227','genus_name' => 'Prunus','species_name' => 'geniculata','common_name' => 'Scrub plum','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5228','genus_name' => 'Prunus','species_name' => 'glandulosa','common_name' => 'Dwarf flowering almond','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5229','genus_name' => 'Prosopis','species_name' => 'glandulosa','common_name' => 'Honey mesquite','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '5230','genus_name' => 'Prunus','species_name' => 'gracilis','common_name' => 'Oklahoma plum','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5231','genus_name' => 'Prunus','species_name' => 'havardii','common_name' => 'Havard\'s plum','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5232','genus_name' => 'Pritchardia','species_name' => 'hardyi','common_name' => 'Makaleha pritchardia','growth_rate' => 'Slow','height_at_maturity' => '67'),
            array('id' => '5233','genus_name' => 'Prosopis','species_name' => 'hassleri','common_name' => 'Algarrobo paraguayo','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '5234','genus_name' => 'Prunus','species_name' => '\'Hally Jolivette\'','common_name' => 'Hally jolivette cherry','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '5236','genus_name' => 'Pritchardia','species_name' => 'hillebrandii','common_name' => 'Lo\'ulu lelo','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '5237','genus_name' => 'Prunus','species_name' => 'hortulana','common_name' => 'Hortulan plum','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5238','genus_name' => 'Prosopis','species_name' => 'humilis','common_name' => 'Prosopis humilis','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '5239','genus_name' => 'Prosopis','species_name' => 'Phoeni','common_name' => 'Phoenix thornless mesquite','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '5240','genus_name' => 'Prunus','species_name' => 'ilicifolia','common_name' => 'Hollyleaf cherry','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '5241','genus_name' => 'Prunus','species_name' => 'incamp \'Okame','common_name' => 'Okame cherry','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '5242','genus_name' => 'Prunus','species_name' => 'incisa','common_name' => 'Fuji Cherry','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '5243','genus_name' => 'Prunus','species_name' => 'japonica','common_name' => 'Japanese plum','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5244','genus_name' => 'Prosopis','species_name' => 'juliflora','common_name' => 'Mesquite','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '5245','genus_name' => 'Pritchardia','species_name' => 'kaalae','common_name' => 'Waianae range pritchardia','growth_rate' => 'Slow','height_at_maturity' => '17'),
            array('id' => '5246','genus_name' => 'Prunus','species_name' => 'Kanzan','common_name' => 'Kanzan cherry','growth_rate' => 'Moderate','height_at_maturity' => '46'),
            array('id' => '5247','genus_name' => 'Prosopis','species_name' => 'kuntzei','common_name' => 'Caranda','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '5248','genus_name' => 'Prunus','species_name' => 'laurocerasus','common_name' => 'Cherry laurel','growth_rate' => 'Fast','height_at_maturity' => '16'),
            array('id' => '5249','genus_name' => 'Prostanthera','species_name' => 'lasianthos','common_name' => 'Victorian Christmas Bush','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '5250','genus_name' => 'Pritchardia','species_name' => 'lanaiensis','common_name' => 'Lanai pritchardia','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '5251','genus_name' => 'Pritchardia','species_name' => 'lanigera','common_name' => 'Lo\'ulu','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '5252','genus_name' => 'Prosopis','species_name' => 'laevigata','common_name' => 'Smooth mesquite','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '5253','genus_name' => 'Pritchardia','species_name' => 'limahuliensis','common_name' => 'Limahuli pritchardia','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '5254','genus_name' => 'Pritchardia','species_name' => 'lowreyana','common_name' => 'Molokai pritchardia','growth_rate' => 'Slow','height_at_maturity' => '13'),
            array('id' => '5255','genus_name' => 'Prunus','species_name' => 'lusitanica','common_name' => 'Portugal laurel','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '5256','genus_name' => 'Prunus','species_name' => 'ilicifolia ssp. lyonii','common_name' => 'Catalina cherry','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '5257','genus_name' => 'Prunus','species_name' => 'maackii','common_name' => 'Amur chokecherry','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '5258','genus_name' => 'Prunus','species_name' => 'mahaleb','common_name' => 'Mahaleb Cherry','growth_rate' => 'Moderate','height_at_maturity' => '9'),
            array('id' => '5259','genus_name' => 'Prunus','species_name' => 'maritima','common_name' => 'Beach plum','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5260','genus_name' => 'Pritchardia','species_name' => 'martii','common_name' => 'Koolau range pritchardia','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '5261','genus_name' => 'Prunus','species_name' => 'mexicana','common_name' => 'Mexican plum','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '5262','genus_name' => 'Prunus','species_name' => 'minutiflora','common_name' => 'Texas almond','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5263','genus_name' => 'Pritchardia','species_name' => 'minor','common_name' => 'Alakai swamp pritchardia','growth_rate' => 'Slow','height_at_maturity' => '40'),
            array('id' => '5264','genus_name' => 'Prunus','species_name' => 'munsoniana','common_name' => 'Wildgoose plum','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '5265','genus_name' => 'Prunus','species_name' => 'mume','common_name' => 'Japanese apricot','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '5266','genus_name' => 'Pritchardia','species_name' => 'munroi','common_name' => 'Kamalo pritchardia','growth_rate' => 'Moderate','height_at_maturity' => '16'),
            array('id' => '5267','genus_name' => 'Prunus','species_name' => 'murrayana','common_name' => 'Murray\'s plum','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5268','genus_name' => 'Prunus','species_name' => 'myrtifolia','common_name' => 'West indies cherry','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5269','genus_name' => 'Prunus','species_name' => 'nigra','common_name' => 'Canada plum','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '5271','genus_name' => 'Prunus','species_name' => 'occidentalis','common_name' => 'Western cherry laurel','growth_rate' => 'Moderate','height_at_maturity' => '80'),
            array('id' => '5272','genus_name' => 'Premna','species_name' => 'odorata','common_name' => 'Fragrant premna','growth_rate' => '','height_at_maturity' => '27'),
            array('id' => '5273','genus_name' => 'Prunus','species_name' => 'orthosepal','common_name' => 'Hybrid plum','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '5274','genus_name' => 'Prunus','species_name' => 'padus','common_name' => 'European bird cherry','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '5275','genus_name' => 'Prosopis','species_name' => 'palmeri','common_name' => 'Palo fierro','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '5277','genus_name' => 'Prosopis','species_name' => 'pallida','common_name' => 'Kiawe','growth_rate' => 'Slow','height_at_maturity' => '67'),
            array('id' => '5278','genus_name' => 'Prunus','species_name' => 'palmer','common_name' => 'Palmer\'s prunus','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5279','genus_name' => 'Prunus','species_name' => 'pensylvanica','common_name' => 'Pin cherry','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5280','genus_name' => 'Prunus','species_name' => 'persica','common_name' => 'Peach','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '5282','genus_name' => 'Pritchardia','species_name' => 'perlmanii','common_name' => 'Wai\'oli Valley pritchardia','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '5283','genus_name' => 'Prunus','species_name' => 'persica v nucipersica','common_name' => 'Nectarine','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '5285','genus_name' => 'Prunus','species_name' => 'pleuradenia','common_name' => 'antilles cherry','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5286','genus_name' => 'Prunus','species_name' => 'pumila','common_name' => 'Sand cherry','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5287','genus_name' => 'Prosopis','species_name' => 'pubescens','common_name' => 'Screwbean mesquite','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '5289','genus_name' => 'Pritchardia','species_name' => 'remota','common_name' => 'Nihoa pritchardia','growth_rate' => 'Slow','height_at_maturity' => '17'),
            array('id' => '5290','genus_name' => 'Premna','species_name' => 'resinosa','common_name' => 'Premna resinosa','growth_rate' => 'Fast','height_at_maturity' => '36'),
            array('id' => '5291','genus_name' => 'Prunus','species_name' => 'rivularis','common_name' => 'Creek plum','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5292','genus_name' => 'Prosopis','species_name' => 'rojasiana','common_name' => 'Prosopis rojasiana','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '5293','genus_name' => 'Prosopis','species_name' => 'ruizlealii','common_name' => 'Prosopis ruizlealii','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '5294','genus_name' => 'Prosopis','species_name' => 'ruscifolia','common_name' => 'Ibope-Moroti','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '5295','genus_name' => 'Prunus','species_name' => 'sargentii','common_name' => 'Sargent cherry','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '5296','genus_name' => 'Prunus','species_name' => 'salicinia \'Santa Rosa\'','common_name' => 'Santa Rosa plum','growth_rate' => '','height_at_maturity' => '33'),
            array('id' => '5297','genus_name' => 'Prunus','species_name' => 'salicina','common_name' => 'Chinese plum','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '5298','genus_name' => 'Pritchardia','species_name' => 'schattaueri','common_name' => 'Lands of papa pritchardia','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '5299','genus_name' => 'Prunus','species_name' => 'serrula','common_name' => 'Tibetan Cherry','growth_rate' => 'Fast','height_at_maturity' => '12'),
            array('id' => '5300','genus_name' => 'Prunus','species_name' => 'serotina','common_name' => 'Black cherry','growth_rate' => 'Fast','height_at_maturity' => '80'),
            array('id' => '5301','genus_name' => 'Prunus','species_name' => 'serrulata','common_name' => 'Japanese flowering cherry','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '5303','genus_name' => 'Prosopis','species_name' => 'sericantha','common_name' => 'Barba de tigre','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '5306','genus_name' => 'Prunus','species_name' => 'serrulata \'Shirofugen\'','common_name' => 'Shirofugen cherry','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '5307','genus_name' => 'Prunus','species_name' => 'serrulata \'Shirotae\'','common_name' => 'Mt. Fuji cherry','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '5308','genus_name' => 'Prunus','species_name' => 'serrulata v spontanea','common_name' => 'Japanese mountain cherry','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '5310','genus_name' => 'Prunus','species_name' => 'shirota','common_name' => 'Mount fuji cherry','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '5311','genus_name' => 'Prunus','species_name' => 'Shirotae','common_name' => 'Prunus shirotae','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '5312','genus_name' => 'Prunus','species_name' => 'slavini','common_name' => 'Slavin\'s prunus','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5313','genus_name' => 'Prunus','species_name' => 'spinosa','common_name' => 'Blackthorn','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '5314','genus_name' => 'Prunus','species_name' => 'spachiana f. ascendens','common_name' => 'Usuzumi cherry','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5315','genus_name' => 'Prosopis','species_name' => 'strombulifera','common_name' => 'Argentine screwbean','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '5316','genus_name' => 'Prunus','species_name' => 'subhirtella','common_name' => 'Higan cherry','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '5317','genus_name' => 'Prunus','species_name' => 'subcordata','common_name' => 'Klamath plum','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5318','genus_name' => 'Prunus','species_name' => 'takesimensis','common_name' => 'Korean cherry','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5319','genus_name' => 'Prunus','species_name' => 'texana','common_name' => 'Peachbush','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5320','genus_name' => 'Prunus','species_name' => 'tomentosa','common_name' => 'Manchu cherry','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '5321','genus_name' => 'Prosopis','species_name' => 'torquata','common_name' => 'Lata','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '5322','genus_name' => 'Prunus','species_name' => 'triloba','common_name' => 'Flowering plum','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5323','genus_name' => 'Prunus','species_name' => 'umbellata','common_name' => 'Flatwods plum','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '5325','genus_name' => 'Prosopis','species_name' => 'velutina','common_name' => 'Velvet mesquite','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '5326','genus_name' => 'Prunus','species_name' => 'virginiana','common_name' => 'Common chokecherry','growth_rate' => 'Fast','height_at_maturity' => '23'),
            array('id' => '5327','genus_name' => 'Pritchardia','species_name' => 'viscosa','common_name' => 'Stickybud pritchardia','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '5329','genus_name' => 'Prunus','species_name' => 'virginiana \'Shubert\'','common_name' => 'Shubert chokecherry','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '5330','genus_name' => 'Prunus','species_name' => 'vulgaris','common_name' => 'Prunus vulgaris','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5331','genus_name' => 'Pritchardia','species_name' => 'waialealeana','common_name' => 'Poleline pritchardia','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '5332','genus_name' => 'Prunus','species_name' => 'blirean','common_name' => 'Blireana plum','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '5333','genus_name' => 'Prunus','species_name' => 'schmitti','common_name' => 'Schmitt\'s Cherry','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '5334','genus_name' => 'Prunus','species_name' => 'yedoensis','common_name' => 'Yoshino flowering cherry','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '5336','genus_name' => 'Pseudolarix','species_name' => 'amabilis','common_name' => 'Golden larch','growth_rate' => 'Slow','height_at_maturity' => '40'),
            array('id' => '5337','genus_name' => 'Psidium','species_name' => 'amplexicaule','common_name' => 'Mountain guava','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '5338','genus_name' => 'Pseudopanax','species_name' => 'arboreus','common_name' => 'Five-Fingers','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '5339','genus_name' => 'Psidium','species_name' => 'araca','common_name' => 'Psidium araca','growth_rate' => 'Slow','height_at_maturity' => '16'),
            array('id' => '5342','genus_name' => 'Psychotria','species_name' => 'brachiata','common_name' => 'Palo de cachimbo','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '5344','genus_name' => 'Psidium','species_name' => 'cattleianum','common_name' => 'Strawberry guava','growth_rate' => 'Moderate','height_at_maturity' => '14'),
            array('id' => '5347','genus_name' => 'Psidium','species_name' => 'calyptranthoides','common_name' => 'Luquillo mountain guava','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '5348','genus_name' => 'Pseudopanax','species_name' => 'colensoi','common_name' => 'Orihou','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '5353','genus_name' => 'Psychotria','species_name' => 'fauriei','common_name' => 'Koolau range wild coffee','growth_rate' => '','height_at_maturity' => '13'),
            array('id' => '5355','genus_name' => 'Psychotria','species_name' => 'grandiflora','common_name' => 'Largeflower wild coffee','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '5358','genus_name' => 'Psychotria','species_name' => 'greenwelliae','common_name' => 'Kauai wild coffee','growth_rate' => '','height_at_maturity' => '16'),
            array('id' => '5359','genus_name' => 'Psidium','species_name' => 'guajava','common_name' => 'Common guava','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '5360','genus_name' => 'Pseudosamanea','species_name' => 'guachapele','common_name' => 'Igua','growth_rate' => 'Fast','height_at_maturity' => '82'),
            array('id' => '5361','genus_name' => 'Psychotria','species_name' => 'hathewayi','common_name' => 'Waianae range wild coffee','growth_rate' => '','height_at_maturity' => '26'),
            array('id' => '5362','genus_name' => 'Psychotria','species_name' => 'hawaiiensis','common_name' => 'Kopiko \'ula','growth_rate' => '','height_at_maturity' => '33'),
            array('id' => '5363','genus_name' => 'Psychotria','species_name' => 'hexandra','common_name' => 'Woodland wild coffee','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '5364','genus_name' => 'Psychotria','species_name' => 'hobdyi','common_name' => 'Milolii kopiwai','growth_rate' => '','height_at_maturity' => '26'),
            array('id' => '5366','genus_name' => 'Psychotria','species_name' => 'insularum','common_name' => 'Island wild coffee','growth_rate' => '','height_at_maturity' => '45'),
            array('id' => '5367','genus_name' => 'Pseudosasa','species_name' => 'japonica','common_name' => 'arrow bamboo','growth_rate' => '','height_at_maturity' => '14'),
            array('id' => '5369','genus_name' => 'Psychotria','species_name' => 'kaduana','common_name' => 'Kopiko kea','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '5373','genus_name' => 'Psidium','species_name' => 'longipes','common_name' => 'Mangroveberry','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '5374','genus_name' => 'Pseudotsuga','species_name' => 'macrocarpa','common_name' => 'Bigcone douglas fir','growth_rate' => 'Moderate','height_at_maturity' => '75'),
            array('id' => '5375','genus_name' => 'Psychotria','species_name' => 'maleolens','common_name' => 'Cachimbo de gato','growth_rate' => '','height_at_maturity' => '33'),
            array('id' => '5377','genus_name' => 'Psychotria','species_name' => 'mariniana','common_name' => 'Forest wild coffee','growth_rate' => '','height_at_maturity' => '65'),
            array('id' => '5378','genus_name' => 'Psychotria','species_name' => 'mauiensis','common_name' => '\'opiko','growth_rate' => '','height_at_maturity' => '26'),
            array('id' => '5379','genus_name' => 'Pseudotsuga','species_name' => 'menziesii','common_name' => 'Douglas fir','growth_rate' => 'Moderate','height_at_maturity' => '200'),
            array('id' => '5381','genus_name' => 'Psychotria','species_name' => 'nervosa','common_name' => 'Seminole balsamo','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '5385','genus_name' => 'Pseudobombax','species_name' => 'palmeri','common_name' => 'Shaving brush tree','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '5386','genus_name' => 'Psoralea','species_name' => 'pinnata','common_name' => 'Fountain bush','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '5392','genus_name' => 'Pseudophoenix','species_name' => 'sargentii','common_name' => 'Buccaneer palm','growth_rate' => 'Slow','height_at_maturity' => '27'),
            array('id' => '5393','genus_name' => 'Psidium','species_name' => 'sartorianum','common_name' => 'Sartre guava','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '5396','genus_name' => 'Pseudobombax','species_name' => 'septenatum','common_name' => 'Barrigon kapoktree','growth_rate' => 'Fast','height_at_maturity' => '66'),
            array('id' => '5397','genus_name' => 'Psidium','species_name' => 'sintenisii','common_name' => 'Sintenis\' guava','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '5398','genus_name' => 'Pseudocydonia','species_name' => 'sinensis','common_name' => 'Chinese-quince','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '5404','genus_name' => 'Psychotria','species_name' => 'wawrae','common_name' => 'Leatherleaf wild coffee','growth_rate' => '','height_at_maturity' => '16'),
            array('id' => '5405','genus_name' => 'Pterocarpus','species_name' => 'acapulcensis','common_name' => 'Sangregao','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '5406','genus_name' => 'Pterostyrax','species_name' => 'corymbosus','common_name' => 'Little Epaulette Tree','growth_rate' => 'Fast','height_at_maturity' => '12'),
            array('id' => '5407','genus_name' => 'Ptelea','species_name' => 'crenulata','common_name' => 'California hoptree','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '5408','genus_name' => 'Ptychosperma','species_name' => 'elegans','common_name' => 'Alexander palm','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '5409','genus_name' => 'Pterocarya','species_name' => 'fraxinifolia','common_name' => 'Caucasian Wingnut','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '5411','genus_name' => 'Pterocarpus','species_name' => 'indicus','common_name' => 'India padauk','growth_rate' => 'Fast','height_at_maturity' => '115'),
            array('id' => '5412','genus_name' => 'Pteralyxia','species_name' => 'kauaiensis','common_name' => 'Kauai pteralyxia','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '5413','genus_name' => 'Pterocarpus','species_name' => 'macrocarpus','common_name' => 'Burma paduak','growth_rate' => 'Moderate','height_at_maturity' => '100'),
            array('id' => '5415','genus_name' => 'Pterocarpus','species_name' => 'marsupium','common_name' => 'Malabar kino','growth_rate' => '','height_at_maturity' => '90'),
            array('id' => '5416','genus_name' => 'Ptychosperma','species_name' => 'macarthurii','common_name' => 'Macarthur palm','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '5417','genus_name' => 'Pterocarpus','species_name' => 'officinalis','common_name' => 'Dragonsblood tree','growth_rate' => 'Fast','height_at_maturity' => '75'),
            array('id' => '5418','genus_name' => 'Pterocarya','species_name' => 'rehderian','common_name' => 'Hybrid Wing-nut','growth_rate' => 'Fast','height_at_maturity' => '22'),
            array('id' => '5420','genus_name' => 'Pterocarya','species_name' => 'stenoptera','common_name' => 'Chinese wingnut','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '5421','genus_name' => 'Pterocymbium','species_name' => 'tinctorium','common_name' => 'Taluto','growth_rate' => 'Fast','height_at_maturity' => '150'),
            array('id' => '5422','genus_name' => 'Ptelea','species_name' => 'trifoliata','common_name' => 'Common hoptree','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '5426','genus_name' => 'Punica','species_name' => 'granatum','common_name' => 'Pomegranate','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '5430','genus_name' => 'Purshia','species_name' => 'stansburiana','common_name' => 'Stansbury cliffrose','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '5433','genus_name' => 'Pyrus','species_name' => 'amygdaliformis','common_name' => 'Almond-leaved Pear','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '5434','genus_name' => 'Malus','species_name' => 'angustifolia','common_name' => 'Southern crabapple','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '5436','genus_name' => 'Pyracantha','species_name' => 'atalantioides','common_name' => 'Giggs Firethorn','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '5437','genus_name' => 'Malus','species_name' => 'baccata','common_name' => 'Siberian crabapple','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '5438','genus_name' => 'Pyrus','species_name' => 'calleryana','common_name' => 'Callery pear','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '5439','genus_name' => 'Pyrus','species_name' => 'calleryana \'Aristocrat\'','common_name' => '\'Aristocrat\' callery pear','growth_rate' => '','height_at_maturity' => '35'),
            array('id' => '5440','genus_name' => 'Pyrus','species_name' => 'calleryana \'Bradford','common_name' => '\'Bradford\' callery pear','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '5441','genus_name' => 'Pyrus','species_name' => 'calleryana \'Capital\'','common_name' => '\'Capital\' callery pear','growth_rate' => '','height_at_maturity' => '35'),
            array('id' => '5442','genus_name' => 'Pyrus','species_name' => 'calleryana \'Chanticleer\'','common_name' => 'Chanticleer callery pear','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '5444','genus_name' => 'Pyrus','species_name' => 'calleryana \'Red Spire\'','common_name' => '\'Redspire\' callery pear','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '5446','genus_name' => 'Pyrus','species_name' => 'calleryana \'Whitehouse\'','common_name' => '\'Whitehouse\' flowering pear','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '5447','genus_name' => 'Pyrus','species_name' => 'communis','common_name' => 'Common pear','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '5448','genus_name' => 'Pyracantha','species_name' => 'coccinea','common_name' => 'Fire thorn','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '5449','genus_name' => 'Malus','species_name' => 'coronaria','common_name' => 'Sweet crabapple','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '5454','genus_name' => 'Malus','species_name' => 'fusca','common_name' => 'Oregon crabapple','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '5455','genus_name' => 'Malus','species_name' => 'ioensis','common_name' => 'Prairie crabapple','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '5456','genus_name' => 'Pyrus','species_name' => 'irregularis','common_name' => 'Shipova','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '5457','genus_name' => 'Pyrus','species_name' => 'kawakamii','common_name' => 'Evergreen pear','growth_rate' => 'Fast','height_at_maturity' => '28'),
            array('id' => '5458','genus_name' => 'Pyracantha','species_name' => 'koidzumii','common_name' => 'Formosa firethorn','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '5459','genus_name' => 'Pyrus','species_name' => 'nivalis','common_name' => 'Snow Pear','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '5460','genus_name' => 'Pyrus','species_name' => 'pashia','common_name' => 'Wild pear','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '5462','genus_name' => 'Pyrus','species_name' => 'pyrifolia','common_name' => 'Asian pear','growth_rate' => 'Moderate','height_at_maturity' => '45'),
            array('id' => '5463','genus_name' => 'Pyrus','species_name' => 'pyraster','common_name' => 'European wild pear','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '5464','genus_name' => 'Pyrus','species_name' => 'salicifolia','common_name' => 'Willow-leaved Pear','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '5465','genus_name' => 'Pyrus','species_name' => 'ussuriensis','common_name' => 'Chinese pear','growth_rate' => 'Slow','height_at_maturity' => '45'),
            array('id' => '5467','genus_name' => 'Quercus','species_name' => 'acutissima','common_name' => 'Sawtooth oak','growth_rate' => 'Fast','height_at_maturity' => '70'),
            array('id' => '5468','genus_name' => 'Quercus','species_name' => 'acutifolia','common_name' => 'Quercus acutifolia','growth_rate' => 'Fast','height_at_maturity' => '35'),
            array('id' => '5469','genus_name' => 'Quercus','species_name' => 'acerifolia','common_name' => 'Mapleleaf oak','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '5470','genus_name' => 'Quercus','species_name' => 'acutiden','common_name' => 'Quercus x acutidens','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5471','genus_name' => 'agrifolia','species_name' => 'agrifolia','common_name' => 'Coastal live oak','growth_rate' => 'Slow','height_at_maturity' => '70'),
            array('id' => '5472','genus_name' => 'Quercus','species_name' => 'ajoensis','common_name' => 'Ajo mountain scrub oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5473','genus_name' => 'Quercus','species_name' => 'alba','common_name' => 'White oak','growth_rate' => 'Slow','height_at_maturity' => '100'),
            array('id' => '5474','genus_name' => 'Quercus','species_name' => 'alvordian','common_name' => 'Alvord oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5475','genus_name' => 'Quercus','species_name' => 'aliena','common_name' => 'Oriental white oak','growth_rate' => '','height_at_maturity' => '65'),
            array('id' => '5476','genus_name' => 'Quassia','species_name' => 'amara','common_name' => 'Quassia wood','growth_rate' => '','height_at_maturity' => '11'),
            array('id' => '5477','genus_name' => 'arizonica','species_name' => 'arizonica','common_name' => 'Arizona white oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5478','genus_name' => 'Quercus','species_name' => 'arkansana','common_name' => 'Arkansas oak','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '5479','genus_name' => 'Quercus','species_name' => 'ashe','common_name' => 'Ash\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5480','genus_name' => 'Quercus','species_name' => 'atlantic','common_name' => 'Atlantic oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5481','genus_name' => 'Quercus','species_name' => 'austrina','common_name' => 'Bluff oak','growth_rate' => 'Moderate','height_at_maturity' => '60'),
            array('id' => '5482','genus_name' => 'Quercus','species_name' => 'berberidifolia','common_name' => 'Scrub oak','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '5483','genus_name' => 'Quercus','species_name' => 'beaumontian','common_name' => 'Beaumont\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5484','genus_name' => 'Quercus','species_name' => 'bebbian','common_name' => 'Bebb\'s oak','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '5485','genus_name' => 'Quercus','species_name' => 'bernardensi','common_name' => 'Bernard\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5486','genus_name' => 'Quercus','species_name' => 'beadle','common_name' => 'Beadle\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5487','genus_name' => 'Quercus','species_name' => 'beckya','common_name' => 'Becky\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5488','genus_name' => 'Quercus','species_name' => 'bender','common_name' => 'Bender oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5489','genus_name' => 'Quercus','species_name' => 'bicolor','common_name' => 'Swamp white oak','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '5490','genus_name' => 'Quercus','species_name' => 'bimundoru','common_name' => 'Bimundor\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '45'),
            array('id' => '5491','genus_name' => 'Quercus','species_name' => 'blufftonensi','common_name' => 'Bluffton\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5492','genus_name' => 'Quercus','species_name' => 'boyntonii','common_name' => 'Boynton sand post oak','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '5493','genus_name' => 'Quercus','species_name' => 'brittoni','common_name' => 'Britton\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5494','genus_name' => 'Quercus','species_name' => 'bushi','common_name' => 'Bush\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5495','genus_name' => 'Quercus','species_name' => 'buckleyi','common_name' => 'Buckley oak','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '5496','genus_name' => 'Quercus','species_name' => 'burnetensi','common_name' => 'Burnet\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5497','genus_name' => 'Quercus','species_name' => 'byarsi','common_name' => 'Byars\' oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5498','genus_name' => 'Quercus','species_name' => 'caduc','common_name' => 'Quercus x caduca','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5499','genus_name' => 'Quercus','species_name' => 'calliprinos','common_name' => 'Palestine Oak','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '5500','genus_name' => 'Quercus','species_name' => 'capesi','common_name' => 'Cape oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5501','genus_name' => 'Quercus','species_name' => 'caesariensi','common_name' => 'Caesar oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5503','genus_name' => 'Quercus','species_name' => 'candicans','common_name' => 'Quercus candicans','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '5504','genus_name' => 'Quercus','species_name' => 'castanea','common_name' => 'Quercus castanea','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '5505','genus_name' => 'Quercus','species_name' => 'carmenensis','common_name' => 'Mexican oak','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '5506','genus_name' => 'Quercus','species_name' => 'canariensis','common_name' => 'Algerian Oak','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '5507','genus_name' => 'Quercus','species_name' => 'castaneifolia','common_name' => 'Chestnut-leaved oak','growth_rate' => 'Moderate','height_at_maturity' => '83'),
            array('id' => '5508','genus_name' => 'Quercus','species_name' => 'cerris','common_name' => 'European turkey oak','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '5509','genus_name' => 'chrysolepis','species_name' => 'chrysolepis','common_name' => 'Canyon live oak','growth_rate' => 'Slow','height_at_maturity' => '90'),
            array('id' => '5510','genus_name' => 'Quercus','species_name' => 'chapmanii','common_name' => 'Chapman oak','growth_rate' => 'Slow','height_at_maturity' => '85'),
            array('id' => '5511','genus_name' => 'Quercus','species_name' => 'chihuahuensis','common_name' => 'Chihuahuan oak','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '5512','genus_name' => 'Quercus','species_name' => 'incana','common_name' => 'Bluejack oak','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '5513','genus_name' => 'Quercus','species_name' => 'coccinea','common_name' => 'Scarlet oak','growth_rate' => 'Fast','height_at_maturity' => '70'),
            array('id' => '5514','genus_name' => 'Quercus','species_name' => 'coccifera','common_name' => 'Kermes oak','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '5515','genus_name' => 'Quercus','species_name' => 'comptonia','common_name' => 'Compton\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5516','genus_name' => 'Quercus','species_name' => 'columnari','common_name' => 'Column oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5517','genus_name' => 'Quercus','species_name' => 'cocksi','common_name' => 'Cock\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5518','genus_name' => 'Quercus','species_name' => 'cornelius-mulleri','common_name' => 'Muller oak','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '5519','genus_name' => 'Quercus','species_name' => 'cravenensi','common_name' => 'Craven oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5520','genus_name' => 'Quercus','species_name' => 'crassifolia','common_name' => 'Leather leaf Mexican oak','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '5521','genus_name' => 'Quercus','species_name' => 'crassipes','common_name' => 'Quercus crassipes','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '5522','genus_name' => 'Quercus','species_name' => 'deami','common_name' => 'Deam\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5523','genus_name' => 'Quercus','species_name' => 'dentata','common_name' => 'Daimio oak','growth_rate' => 'Moderate','height_at_maturity' => '59'),
            array('id' => '5524','genus_name' => 'Quercus','species_name' => 'bemareei','common_name' => 'Quercus bemareei','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5525','genus_name' => 'Quercus','species_name' => 'depressipes','common_name' => 'Davis mountain oak','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '5526','genus_name' => 'Quercus','species_name' => 'discret','common_name' => 'Discreet oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5527','genus_name' => 'Quercus','species_name' => 'diversilob','common_name' => 'Manylobed oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5528','genus_name' => 'Quercus','species_name' => 'douglasii','common_name' => 'Blue oak','growth_rate' => 'Slow','height_at_maturity' => '60'),
            array('id' => '5529','genus_name' => 'Quercus','species_name' => 'dumosa','common_name' => 'Coastal sage scrub oak','growth_rate' => 'Slow','height_at_maturity' => '9'),
            array('id' => '5530','genus_name' => 'Quercus','species_name' => 'dunnii','common_name' => 'Dunn oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5531','genus_name' => 'Quercus','species_name' => 'durata','common_name' => 'Leather oak','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '5532','genus_name' => 'Quercus','species_name' => 'egglestoni','common_name' => 'Eggleston\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5533','genus_name' => 'Quercus','species_name' => 'ellipsoidalis','common_name' => 'Northern pin oak','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '5534','genus_name' => 'emoryi','species_name' => 'emoryi','common_name' => 'Emory oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5535','genus_name' => 'Quercus','species_name' => 'engelmannii','common_name' => 'Engelmann oak','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '5536','genus_name' => 'Quercus','species_name' => 'eplingi','common_name' => 'Epling\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5537','genus_name' => 'Quercus','species_name' => 'exact','common_name' => 'Laurelpin oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5538','genus_name' => 'Quercus','species_name' => 'falcata','common_name' => 'Southern red oak','growth_rate' => 'Moderate','height_at_maturity' => '75'),
            array('id' => '5539','genus_name' => 'Quercus','species_name' => 'faxoni','common_name' => 'Faxon\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5540','genus_name' => 'Quercus','species_name' => 'fernaldi','common_name' => 'Fernald\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5541','genus_name' => 'Quercus','species_name' => 'fernowi','common_name' => 'Fernow\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5542','genus_name' => 'Quercus','species_name' => 'filiali','common_name' => 'Quercus x filialis','growth_rate' => 'Moderate','height_at_maturity' => '85')
        );

        Tree::insert($trees);

        $seeder = new TreeSpeciesSeeder8;
        $seeder->run();
    }
}
