<?php

namespace Database\Seeders\TreeSpecies;

use App\Models\Trees\Tree;
use Illuminate\Database\Seeder;

class TreeSpeciesSeeder1 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $trees = array(
            array('id' => '551','genus_name' => 'Amorpha','species_name' => 'nitens','common_name' => 'Shining false indigo','growth_rate' => '','height_at_maturity' => '9'),
            array('id' => '554','genus_name' => 'Amelanchier','species_name' => 'obovalis','common_name' => 'Coastal serviceberry','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '555','genus_name' => 'Amorpha','species_name' => 'ouachitensis','common_name' => 'Ouachita false indigo','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '556','genus_name' => 'Amelanchier','species_name' => 'pallida','common_name' => 'Pale serviceberry','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '557','genus_name' => 'Amorpha','species_name' => 'paniculata','common_name' => 'Panicled false indigo','growth_rate' => '','height_at_maturity' => '9'),
            array('id' => '558','genus_name' => 'Amelanchier','species_name' => 'pumila','common_name' => 'Dwarf serviceberry','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '559','genus_name' => 'Amelanchier','species_name' => 'x quinti-martii','common_name' => 'Guint mart\'s serviceberry','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '560','genus_name' => 'Amorpha','species_name' => 'roemeriana','common_name' => 'Roemer\'s false indigo','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '561','genus_name' => 'Amelanchier','species_name' => 'sanguinea','common_name' => 'Roundleaf serviceberry','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '563','genus_name' => 'Amyris','species_name' => 'texana','common_name' => 'Texas torchwood','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '564','genus_name' => 'Amelanchier','species_name' => 'utahensis','common_name' => 'Utah serviceberry','growth_rate' => 'Fast','height_at_maturity' => '36'),
            array('id' => '565','genus_name' => 'Antirhea','species_name' => 'acutata','common_name' => 'Placa chiquitu','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '566','genus_name' => 'Angophora','species_name' => 'bakeri','common_name' => 'Narrow-leaved apple','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '567','genus_name' => 'Aniba','species_name' => 'bracteata','common_name' => 'Canelillo','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '568','genus_name' => 'Antidesma','species_name' => 'bunius','common_name' => 'bignay','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '571','genus_name' => 'Anthocephalus','species_name' => 'chinensis','common_name' => 'Anthocephalus Kadam','growth_rate' => 'Fast','height_at_maturity' => '145'),
            array('id' => '572','genus_name' => 'Annona','species_name' => 'cherimola','common_name' => 'Cherimoya','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '573','genus_name' => 'Angophora','species_name' => 'costata','common_name' => 'Smooth-bark angophora','growth_rate' => 'Moderate','height_at_maturity' => '69'),
            array('id' => '575','genus_name' => 'Antirhea','species_name' => 'coriacea','common_name' => 'Pegwood','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '576','genus_name' => 'Anadenanthera','species_name' => 'colubrina v. cebil','common_name' => 'curupay','growth_rate' => '','height_at_maturity' => '80'),
            array('id' => '577','genus_name' => 'Annona','species_name' => 'diversifolia','common_name' => 'ilama','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '578','genus_name' => 'Anacardium','species_name' => 'excelsum','common_name' => 'Caracoli','growth_rate' => 'Moderate','height_at_maturity' => '98'),
            array('id' => '580','genus_name' => 'Angophora','species_name' => 'floribunda','common_name' => 'Rough-bark angophora','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '582','genus_name' => 'Antidesma','species_name' => 'ghaesembilla','common_name' => 'Binayuyo (inyam)','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '583','genus_name' => 'Annona','species_name' => 'glabra','common_name' => 'Pond apple','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '584','genus_name' => 'Anopterus','species_name' => 'glandulosus','common_name' => 'Tasmanian Laurel','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '586','genus_name' => 'Angophora','species_name' => 'hispida','common_name' => 'Dwarf Apple','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '587','genus_name' => 'Andira','species_name' => 'inermis','common_name' => 'Cabbagebark tree','growth_rate' => 'Fast','height_at_maturity' => '90'),
            array('id' => '590','genus_name' => 'Anisacanthus','species_name' => 'linearis','common_name' => 'Narrowleaf honeysuckle','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '591','genus_name' => 'Antirhea','species_name' => 'lucida','common_name' => 'Palo iloron','growth_rate' => '','height_at_maturity' => '22'),
            array('id' => '592','genus_name' => 'Annona','species_name' => 'montana','common_name' => 'Mountain soursop','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '593','genus_name' => 'Annona','species_name' => 'muricata','common_name' => 'Soursop','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '596','genus_name' => 'Antirhea','species_name' => 'obtusifolia','common_name' => 'Quina roja','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '597','genus_name' => 'Anacardium','species_name' => 'occidentale','common_name' => 'Cashew','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '598','genus_name' => 'Anadenanthera','species_name' => 'peregrina','common_name' => 'Cohoba tree','growth_rate' => '','height_at_maturity' => '65'),
            array('id' => '599','genus_name' => 'Antidesma','species_name' => 'platyphyllum','common_name' => 'Ha\'a','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '600','genus_name' => 'Antirhea','species_name' => 'portoricensis','common_name' => 'Puerto rico quina','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '601','genus_name' => 'Antidesma','species_name' => 'pulvinatum','common_name' => 'Hame','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '602','genus_name' => 'Anisacanthus','species_name' => 'puberulus','common_name' => 'Dwarf desert honeysuckle','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '603','genus_name' => 'Anisacanthus','species_name' => 'quadrifidus','common_name' => 'Wright desert honeysuckle','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '604','genus_name' => 'Annona','species_name' => 'reticulata','common_name' => 'Custard apple','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '605','genus_name' => 'Antirhea','species_name' => 'sintenisii','common_name' => 'Sintenis\' quina','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '606','genus_name' => 'Annona','species_name' => 'squamosa','common_name' => 'Sugar apple','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '607','genus_name' => 'Anisacanthus','species_name' => 'thurberi','common_name' => 'Thurber\'s honeysuckle','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '609','genus_name' => 'Apophyllum','species_name' => 'anomalum','common_name' => 'Warrior Bush','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '610','genus_name' => 'Apollonias','species_name' => 'barbujana','common_name' => 'Barbusano','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '614','genus_name' => 'Apeiba','species_name' => 'tibourbou','common_name' => 'pau-jangada','growth_rate' => '','height_at_maturity' => '43'),
            array('id' => '615','genus_name' => 'Aquilaria','species_name' => 'sinensis','common_name' => 'Incense Tree','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '616','genus_name' => 'Argyrodendron','species_name' => 'actinophyllum','common_name' => 'Black booyong','growth_rate' => 'Moderate','height_at_maturity' => '165'),
            array('id' => '617','genus_name' => 'Archontophoenix','species_name' => 'alexandrae','common_name' => 'Alexandra palm','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '618','genus_name' => 'Artocarpus','species_name' => 'altilis','common_name' => 'Breadfruit','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '619','genus_name' => 'Arctostaphylos','species_name' => 'alpina','common_name' => 'Alpine bearberry','growth_rate' => 'Fast','height_at_maturity' => '1'),
            array('id' => '620','genus_name' => 'Arbutus','species_name' => 'andrachne','common_name' => 'Cyprus strawberry tree','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '621','genus_name' => 'Araucaria','species_name' => 'angustifolia','common_name' => 'Parana pine','growth_rate' => 'Moderate','height_at_maturity' => '42'),
            array('id' => '622','genus_name' => 'Arctostaphylos','species_name' => 'andersonii','common_name' => 'Santa cruz manzanita','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '623','genus_name' => 'Araucaria','species_name' => 'araucana','common_name' => 'Monkeypuzzle tree','growth_rate' => 'Moderate','height_at_maturity' => '73'),
            array('id' => '624','genus_name' => 'Arbutus','species_name' => 'arizonica','common_name' => 'Arizona madrone','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '625','genus_name' => 'Arctostaphylos','species_name' => 'auriculata','common_name' => 'Mount diablo manzanita','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '626','genus_name' => 'Arctostaphylos','species_name' => 'bakeri','common_name' => 'Baker\'s manzanita','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '627','genus_name' => 'Archirhodomyrts','species_name' => 'beckleri','common_name' => 'Archirhodomyrtus beckleri','growth_rate' => 'Fast','height_at_maturity' => '5'),
            array('id' => '628','genus_name' => 'Arctostaphylos','species_name' => 'x benitoensis','common_name' => 'Benito\'s mazanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '629','genus_name' => 'Araucaria','species_name' => 'bidwillii','common_name' => 'Bunya bunya','growth_rate' => 'Moderate','height_at_maturity' => '80'),
            array('id' => '630','genus_name' => 'Artocarpus','species_name' => 'blancoi','common_name' => 'Antipolo','growth_rate' => 'Fast','height_at_maturity' => '98'),
            array('id' => '631','genus_name' => 'Araucaria','species_name' => 'brasiliensis','common_name' => 'Brazilian pine','growth_rate' => 'Fast','height_at_maturity' => '150'),
            array('id' => '632','genus_name' => 'Arbutus','species_name' => 'canariensis','common_name' => 'Canary Islands Madrone','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '634','genus_name' => 'Arctostaphylos','species_name' => 'catalinae','common_name' => 'Santa catalina manzanita','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '636','genus_name' => 'Arctostaphylos','species_name' => 'x campbelliae','common_name' => 'Campbell manzanita','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '637','genus_name' => 'Areca','species_name' => 'catechu','common_name' => 'betel palm','growth_rate' => '','height_at_maturity' => '65'),
            array('id' => '638','genus_name' => 'Arctostaphylos','species_name' => 'canescens','common_name' => 'Hoary manzanita','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '639','genus_name' => 'Aristotelia','species_name' => 'chilensis','common_name' => 'Maqui','growth_rate' => 'Slow','height_at_maturity' => '11'),
            array('id' => '640','genus_name' => 'Aralia','species_name' => 'chinensis','common_name' => 'Chinese angelica tree','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '641','genus_name' => 'Arctostaphylos','species_name' => 'x cinerea','common_name' => 'Waldo manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '642','genus_name' => 'Araucaria','species_name' => 'columnaris','common_name' => 'Coral reef araucaria','growth_rate' => 'Moderate','height_at_maturity' => '198'),
            array('id' => '643','genus_name' => 'Arctostaphylos','species_name' => 'confertiflora','common_name' => 'Santa rosa manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '644','genus_name' => 'Arctostaphylos','species_name' => 'x coloradensis','common_name' => 'Colorado manzanita','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '645','genus_name' => 'Arctostaphylos','species_name' => 'columbiana','common_name' => 'Hairy manzanita','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '646','genus_name' => 'Arctostaphylos','species_name' => 'cruzensis','common_name' => 'La cruz manzanita','growth_rate' => 'Slow','height_at_maturity' => '3'),
            array('id' => '647','genus_name' => 'Ardisia','species_name' => 'crenata','common_name' => 'Hen\'s eyes','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '648','genus_name' => 'Archontophoenix','species_name' => 'cunninghamiana','common_name' => 'King palm','growth_rate' => 'Fast','height_at_maturity' => '80'),
            array('id' => '649','genus_name' => 'Araucaria','species_name' => 'cunninghamii','common_name' => 'Hoop pine','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '651','genus_name' => 'Arctostaphylos','species_name' => 'edmundsii','common_name' => 'Little sur manzanita','growth_rate' => 'Slow','height_at_maturity' => '2'),
            array('id' => '652','genus_name' => 'Ardisia','species_name' => 'elliptica','common_name' => 'Shoebutton','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '653','genus_name' => 'Aralia','species_name' => 'elata','common_name' => 'Japanese angelica tree','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '654','genus_name' => 'Ardisia','species_name' => 'escallonioides','common_name' => 'Marlberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '655','genus_name' => 'Araucaria','species_name' => 'excelsa','common_name' => 'Araucaria excelsa','growth_rate' => 'Moderate','height_at_maturity' => '98'),
            array('id' => '656','genus_name' => 'Arctostaphylos','species_name' => 'gabrielensis','common_name' => 'San gabriel manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '657','genus_name' => 'Ardisia','species_name' => 'glauciflora','common_name' => 'Ausubon','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '658','genus_name' => 'Arctostaphylos','species_name' => 'glandulosa','common_name' => 'Eastwood\'s manzanita','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '659','genus_name' => 'Arctostaphylos','species_name' => 'glauca','common_name' => 'Bigberry manzanita','growth_rate' => 'Slow','height_at_maturity' => '18'),
            array('id' => '660','genus_name' => 'Arctostaphylos','species_name' => 'glutinosa','common_name' => 'Schreiber\'s manzanita','growth_rate' => 'Slow','height_at_maturity' => '7'),
            array('id' => '661','genus_name' => 'Argusia','species_name' => 'gnaphalodes','common_name' => 'Sea rosemary','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '663','genus_name' => 'Argyroxiphium','species_name' => 'grayanum','common_name' => 'Hana forest silversword','growth_rate' => '','height_at_maturity' => '7'),
            array('id' => '664','genus_name' => 'Ardisia','species_name' => 'guianensis','common_name' => 'Ardisia guianensis','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '665','genus_name' => 'Araucaria','species_name' => 'heterophylla','common_name' => 'Norfolk island pine','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '666','genus_name' => 'Artocarpus','species_name' => 'heterophyllus','common_name' => 'Jackfruit','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '667','genus_name' => 'Arctostaphylos','species_name' => 'x helleri','common_name' => 'Heller\'s manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '668','genus_name' => 'Arctostaphylos','species_name' => 'hispidula','common_name' => 'Gasquet manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '669','genus_name' => 'Arctostaphylos','species_name' => 'hooveri','common_name' => 'Hoover\'s manzanita','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '671','genus_name' => 'Araucaria','species_name' => 'hunsteinii','common_name' => 'Klinki pine','growth_rate' => 'Moderate','height_at_maturity' => '262'),
            array('id' => '672','genus_name' => 'Arctostaphylos','species_name' => 'imbricata','common_name' => 'San bruno manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '674','genus_name' => 'Arctostaphylos','species_name' => 'insularis','common_name' => 'Island manzanita','growth_rate' => 'Slow','height_at_maturity' => '7'),
            array('id' => '675','genus_name' => 'Ardisia','species_name' => 'japonica','common_name' => 'Japanese ardisia','growth_rate' => 'Moderate','height_at_maturity' => '1'),
            array('id' => '676','genus_name' => 'Arctostaphylos','species_name' => 'x jepsonii','common_name' => 'Jepson\'s manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '680','genus_name' => 'Arctostaphylos','species_name' => 'x laxiflora','common_name' => 'Lazyflower manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '681','genus_name' => 'Ardisia','species_name' => 'luquillensis','common_name' => 'Mountain marlberry','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '682','genus_name' => 'Arctostaphylos','species_name' => 'luciana','common_name' => 'Santa lucia manzanita','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '683','genus_name' => 'Arctostaphylos','species_name' => 'manzanita','common_name' => 'Whiteleaf manzanita','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '684','genus_name' => 'Arbutus','species_name' => 'var. marina','common_name' => 'Marina arbutus','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '685','genus_name' => 'Artocarpus','species_name' => 'mariannensis','common_name' => 'Marianas breadfruit','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '686','genus_name' => 'Arctostaphylos','species_name' => 'malloryi','common_name' => 'Mallory\'s manzanita','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '687','genus_name' => 'Arbutus','species_name' => 'menziesii','common_name' => 'Pacific madrone','growth_rate' => 'Slow','height_at_maturity' => '80'),
            array('id' => '688','genus_name' => 'Arctostaphylos','species_name' => 'mewukka','common_name' => 'Indian manzanita','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '689','genus_name' => 'Arctostaphylos','species_name' => 'x media','common_name' => 'Intermediate manzanita','growth_rate' => 'Slow','height_at_maturity' => '3'),
            array('id' => '690','genus_name' => 'Arctostaphylos','species_name' => 'mendocinoensis','common_name' => 'Pygmy manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '691','genus_name' => 'Arctostaphylos','species_name' => 'moranii','common_name' => 'Moran\'s manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '692','genus_name' => 'Arctostaphylos','species_name' => 'morroensis','common_name' => 'Morro manzanita','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '693','genus_name' => 'Arctostaphylos','species_name' => 'montaraensis','common_name' => 'Montara manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '694','genus_name' => 'Arctostaphylos','species_name' => 'montereyensis','common_name' => 'Monterey manzanita','growth_rate' => 'Slow','height_at_maturity' => '9'),
            array('id' => '695','genus_name' => 'Arctostaphylos','species_name' => 'myrtifolia','common_name' => 'Ione manzanita','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '696','genus_name' => 'Arctostaphylos','species_name' => 'nisseniana','common_name' => 'Nissenan manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '698','genus_name' => 'Arctostaphylos','species_name' => 'nortensis','common_name' => 'Del norte manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '699','genus_name' => 'Arctostaphylos','species_name' => 'obispoensis','common_name' => 'Serpentine manzanita','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '700','genus_name' => 'Ardisia','species_name' => 'obovata','common_name' => 'Guadeloupe marlberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '701','genus_name' => 'Artocarpus','species_name' => 'odoratissimus','common_name' => 'Marang','growth_rate' => '','height_at_maturity' => '82'),
            array('id' => '702','genus_name' => 'Arctostaphylos','species_name' => 'osoensis','common_name' => 'Oso manzanita','growth_rate' => 'Slow','height_at_maturity' => '3'),
            array('id' => '703','genus_name' => 'Arctostaphylos','species_name' => 'otayensis','common_name' => 'Otay manzanita','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '704','genus_name' => 'Arctostaphylos','species_name' => 'pacifica','common_name' => 'Pacific manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '705','genus_name' => 'Arctostaphylos','species_name' => 'pallida','common_name' => 'Alameda manzanita','growth_rate' => 'Slow','height_at_maturity' => '13'),
            array('id' => '706','genus_name' => 'Arctostaphylos','species_name' => 'pajaroensis','common_name' => 'Pajaro manzanita','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '707','genus_name' => 'Arctostaphylos','species_name' => 'parryana','common_name' => 'Parry manzanita','growth_rate' => 'Slow','height_at_maturity' => '3'),
            array('id' => '708','genus_name' => 'Arctostaphylos','species_name' => 'patula','common_name' => 'Greenleaf manzanita','growth_rate' => 'Slow','height_at_maturity' => '7'),
            array('id' => '709','genus_name' => 'Arctostaphylos','species_name' => 'pechoensis','common_name' => 'Pecho manzanita','growth_rate' => 'Fast','height_at_maturity' => '5'),
            array('id' => '710','genus_name' => 'Arctostaphylos','species_name' => 'peninsularis','common_name' => 'Peninsular manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '711','genus_name' => 'Arctostaphylos','species_name' => 'pilosula','common_name' => 'La panza manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '712','genus_name' => 'Arenga','species_name' => 'pinnata','common_name' => 'sugar palm','growth_rate' => 'Slow','height_at_maturity' => '65'),
            array('id' => '713','genus_name' => 'Arctostaphylos','species_name' => 'pringlei','common_name' => 'Pringle manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '714','genus_name' => 'Arctostaphylos','species_name' => 'pugens','common_name' => 'Pointleaf manzanita','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '715','genus_name' => 'Arctostaphylos','species_name' => 'purissima','common_name' => 'La purissima manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '716','genus_name' => 'Arctostaphylos','species_name' => 'rainbowensis','common_name' => 'Rainbow manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '717','genus_name' => 'Arctostaphylos','species_name' => 'refugioensis','common_name' => 'Refugio manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '718','genus_name' => 'Arctostaphylos','species_name' => 'regismontana','common_name' => 'Kings mountain manzanita','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '719','genus_name' => 'Arctostaphylos','species_name' => 'x repens','common_name' => 'Pmc manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '720','genus_name' => 'Arecastrum','species_name' => 'romanzoffianum','common_name' => 'Queen palm','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '721','genus_name' => 'Arctostaphylos','species_name' => 'rubra','common_name' => 'Red fruit bearberry','growth_rate' => 'Slow','height_at_maturity' => '1'),
            array('id' => '722','genus_name' => 'Arctostaphylos','species_name' => 'rudis','common_name' => 'Shagbark manzanita','growth_rate' => 'Slow','height_at_maturity' => '3'),
            array('id' => '724','genus_name' => 'Aristotelia','species_name' => 'serrata','common_name' => 'Makomako','growth_rate' => 'Fast','height_at_maturity' => '5'),
            array('id' => '725','genus_name' => 'Arctostaphylos','species_name' => 'silvicola','common_name' => 'Bonny doon manzanita','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '726','genus_name' => 'Ardisia','species_name' => 'solanacea','common_name' => 'China shrub','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '727','genus_name' => 'Aralia','species_name' => 'spinosa','common_name' => 'Devils walking stick','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '728','genus_name' => 'Arctostaphylos','species_name' => 'stanfordiana','common_name' => 'Stanford\'s manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '729','genus_name' => 'Arbutus','species_name' => 'xalapensis','common_name' => 'Texas madrone','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '730','genus_name' => 'Arctostaphylos','species_name' => 'tomentosa','common_name' => 'Woollyleaf manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '731','genus_name' => 'Artemisia','species_name' => 'tridentata','common_name' => 'Big sagebrush','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '732','genus_name' => 'Artemisia','species_name' => 'tripartita','common_name' => 'Threetip sagebrush','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '733','genus_name' => 'Arbutus','species_name' => 'unedo','common_name' => 'Strawberry tree','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '734','genus_name' => 'Arctostaphylos','species_name' => 'uva-ursi','common_name' => 'Kinnikinnick','growth_rate' => 'Moderate','height_at_maturity' => '1'),
            array('id' => '735','genus_name' => 'Arctostaphylos','species_name' => 'virgata','common_name' => 'Bolinas manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '736','genus_name' => 'Arctostaphylos','species_name' => 'viscida','common_name' => 'Sticky white manzanita','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '737','genus_name' => 'Arctostaphylos','species_name' => 'viridissima','common_name' => 'Whitehair manzanita','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '739','genus_name' => 'Arctostaphylos','species_name' => 'wellsii','common_name' => 'Wells\' manzanita','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '740','genus_name' => 'Arbutus','species_name' => 'x andrachnoides','common_name' => 'Hybrid Strawberry tree','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '742','genus_name' => 'Asimina','species_name' => 'angustifolia','common_name' => 'Slimleaf pawpaw','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '743','genus_name' => 'Acer','species_name' => 'saccharum \'Bailsta\'','common_name' => 'Fall fiesta sugar maple','growth_rate' => '','height_at_maturity' => '70'),
            array('id' => '744','genus_name' => 'Ascarina','species_name' => 'diffusa','common_name' => 'Ascarina','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '746','genus_name' => 'Asimina','species_name' => 'incana','common_name' => 'Woolly pawpaw','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '747','genus_name' => 'Asteromyrtus','species_name' => 'magnifica','common_name' => 'Asteromyrtus magnifica','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '748','genus_name' => 'Asimina','species_name' => 'x nashii','common_name' => 'Nash\'s pawpaw','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '749','genus_name' => 'Asimina','species_name' => 'obovata','common_name' => 'Bigflower pawpaw','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '751','genus_name' => 'Asimina','species_name' => 'parviflora','common_name' => 'Smallflower pawpaw','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '752','genus_name' => 'Astronidium','species_name' => 'pickeringii','common_name' => 'Astronidium Gray','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '753','genus_name' => 'Asimina','species_name' => 'reticulata','common_name' => 'Netted pawpaw','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '754','genus_name' => 'Asteromyrtus','species_name' => 'symphyocarpa','common_name' => 'Liniment Tree','growth_rate' => 'Fast','height_at_maturity' => '5'),
            array('id' => '755','genus_name' => 'Asimina','species_name' => 'tetramera','common_name' => 'Fourpetal pawpaw','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '756','genus_name' => 'Asimina','species_name' => 'triloba','common_name' => 'Pawpaw','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '757','genus_name' => 'Astianthus','species_name' => 'viminalis','common_name' => 'Astianthus viminalis','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '758','genus_name' => 'Atriplex','species_name' => 'canescens','common_name' => 'Four winged saltbrush','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '759','genus_name' => 'Athrotaxis','species_name' => 'cupressoides','common_name' => 'Pencil Pine','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '760','genus_name' => 'Attalea','species_name' => 'dubia','common_name' => 'Bacuau palm','growth_rate' => '','height_at_maturity' => '26'),
            array('id' => '761','genus_name' => 'Atamisquea','species_name' => 'emarginata','common_name' => 'Vomitbush','growth_rate' => '','height_at_maturity' => '26'),
            array('id' => '762','genus_name' => 'Atriplex','species_name' => 'griffithii','common_name' => 'Griffiths\' saltbush','growth_rate' => '','height_at_maturity' => '3'),
            array('id' => '763','genus_name' => 'Atalaya','species_name' => 'hemiglauca','common_name' => 'Cattle Bush','growth_rate' => 'Moderate','height_at_maturity' => '9'),
            array('id' => '765','genus_name' => 'Atriplex','species_name' => 'hymenelytra','common_name' => 'Desertholly','growth_rate' => '','height_at_maturity' => '3'),
            array('id' => '767','genus_name' => 'Athrotaxis','species_name' => 'laxifolia','common_name' => 'Tasmanian Pencil Pine','growth_rate' => 'Slow','height_at_maturity' => '21'),
            array('id' => '769','genus_name' => 'Atherosperma','species_name' => 'moschatum','common_name' => 'Southern Sassafras','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '771','genus_name' => 'Atriplex','species_name' => 'nummularia','common_name' => 'Bluegreen saltbush','growth_rate' => 'Slow','height_at_maturity' => ''),
            array('id' => '772','genus_name' => 'Atriplex','species_name' => 'polycarpa','common_name' => 'Allscale','growth_rate' => 'Slow','height_at_maturity' => '9'),
            array('id' => '773','genus_name' => 'Athrotaxis','species_name' => 'selaginoides','common_name' => 'King Billy Pine','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '774','genus_name' => 'Atriplex','species_name' => 'spinifera','common_name' => 'Spinescale saltbush','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '775','genus_name' => 'Atriplex','species_name' => 'torreyi','common_name' => 'Torrey\'s saltbush','growth_rate' => '','height_at_maturity' => '4'),
            array('id' => '778','genus_name' => 'Austrocedrus','species_name' => 'chilensis','common_name' => 'Chilean cedar','growth_rate' => 'Moderate','height_at_maturity' => '24'),
            array('id' => '780','genus_name' => 'Austroeupatorium','species_name' => 'inulifolium','common_name' => 'Christmas bush','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '781','genus_name' => 'Aucuba','species_name' => 'japonica','common_name' => 'Japanese aucuba','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '783','genus_name' => 'Averrhoa','species_name' => 'bilimbi','common_name' => 'Bilimbi','growth_rate' => '','height_at_maturity' => '42'),
            array('id' => '784','genus_name' => 'Averrhoa','species_name' => 'carambola','common_name' => 'Star fruit','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '785','genus_name' => 'Avicennia','species_name' => 'germinans','common_name' => 'Black mangrove','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '786','genus_name' => 'Avicennia','species_name' => 'marina','common_name' => 'Gray mangrove','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '787','genus_name' => 'Avicennia','species_name' => 'schaueriana','common_name' => 'Avicennia schaueriana','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '792','genus_name' => 'Azolla','species_name' => 'filiculoides','common_name' => 'Pacific mosquito fern','growth_rate' => 'Fast','height_at_maturity' => ''),
            array('id' => '793','genus_name' => 'Azadirachta','species_name' => 'indica','common_name' => 'Neem Tree','growth_rate' => 'Fast','height_at_maturity' => '18'),
            array('id' => '794','genus_name' => 'Azara','species_name' => 'lanceolata','common_name' => 'Aromo','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '797','genus_name' => 'Azara','species_name' => 'microphylla','common_name' => 'Boxleaf azara','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '799','genus_name' => 'Barringtonia','species_name' => 'acutangula','common_name' => 'Freshwater Mangrove','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '800','genus_name' => 'Bauhinia','species_name' => 'aculeata grandiflora','common_name' => 'Bauhinia aculeata grandiflora','growth_rate' => 'Fast','height_at_maturity' => '9'),
            array('id' => '801','genus_name' => 'Banksia','species_name' => 'aemula','common_name' => 'Wallum Banksia','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '802','genus_name' => 'Baccharis','species_name' => 'angustifolia','common_name' => 'Saltwater false willow','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '803','genus_name' => 'Bambusa','species_name' => 'arundinacea','common_name' => 'Thorny bamboo','growth_rate' => '','height_at_maturity' => '98'),
            array('id' => '804','genus_name' => 'Barringtonia','species_name' => 'asiatica','common_name' => 'Sea putat','growth_rate' => '','height_at_maturity' => '80'),
            array('id' => '805','genus_name' => 'Banksia','species_name' => 'ashbyi','common_name' => 'Ashby\'s Banksia','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '806','genus_name' => 'Banksia','species_name' => 'attenuata','common_name' => 'Candle Banksia','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '807','genus_name' => 'Banksia','species_name' => 'baueri','common_name' => 'Possum Banksia','growth_rate' => 'Moderate','height_at_maturity' => '2'),
            array('id' => '808','genus_name' => 'Banksia','species_name' => 'baxteri','common_name' => 'Birds-nest Banksia','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '810','genus_name' => 'Bambusa','species_name' => 'beecheyana','common_name' => 'Beechey\'s bamboo','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '811','genus_name' => 'Bauhinia','species_name' => 'blakeana','common_name' => 'Blake\'s bauhinia','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '812','genus_name' => 'Banksia','species_name' => 'brownii','common_name' => 'Brown\'s Banksia','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '813','genus_name' => 'Banksia','species_name' => 'burdettii','common_name' => 'Burdett\'s Banksia','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '814','genus_name' => 'Bauhinia','species_name' => 'candicans','common_name' => 'Pata de vaca','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '815','genus_name' => 'Banksia','species_name' => 'canei','common_name' => 'Banksia','growth_rate' => 'Moderate','height_at_maturity' => '2'),
            array('id' => '816','genus_name' => 'Backhousia','species_name' => 'citriodora','common_name' => 'Lemon-scented Myrtle','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '817','genus_name' => 'Baccharis','species_name' => 'conferta','common_name' => 'Baccharis conferta','growth_rate' => '','height_at_maturity' => '3'),
            array('id' => '818','genus_name' => 'Banksia','species_name' => 'dentata','common_name' => 'Tropical Banksia','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '819','genus_name' => 'Bauhinia','species_name' => 'divaricata','common_name' => 'Pom pom orchid tree','growth_rate' => '','height_at_maturity' => '8'),
            array('id' => '820','genus_name' => 'Baccharis','species_name' => 'dioica','common_name' => 'Broombush false willow','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '821','genus_name' => 'Baccharis','species_name' => 'emoryi','common_name' => 'Emory\'s baccharis','growth_rate' => 'Fast','height_at_maturity' => '12'),
            array('id' => '822','genus_name' => 'Banksia','species_name' => 'ericifolia','common_name' => 'Heath-leaved Banksia','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '823','genus_name' => 'Bauhinia','species_name' => 'forficata','common_name' => 'Bauhinia','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '824','genus_name' => 'Bauhinia','species_name' => 'galpinii','common_name' => 'Pride of de kaap','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '826','genus_name' => 'Baccharis','species_name' => 'glomeruliflora','common_name' => 'Silverling','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '827','genus_name' => 'Banksia','species_name' => 'grandis','common_name' => 'Bull Banksia','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '828','genus_name' => 'Baccharis','species_name' => 'halimifolia','common_name' => 'Eastern baccharis','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '830','genus_name' => 'Banksia','species_name' => 'integrifolia','common_name' => 'Coast banksia','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '831','genus_name' => 'Bambusa','species_name' => 'longifolia','common_name' => 'Longflower bamboo','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '832','genus_name' => 'Bambusa','species_name' => 'longispiculata','common_name' => 'Mahal bamboo','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '833','genus_name' => 'Bauhinia','species_name' => 'lunarioides','common_name' => 'Texasplume','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '834','genus_name' => 'Barleria','species_name' => 'lupulina','common_name' => 'Hophead philippine violet','growth_rate' => '','height_at_maturity' => '3'),
            array('id' => '836','genus_name' => 'Banksia','species_name' => 'marginata','common_name' => 'Silver banksia','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '837','genus_name' => 'Banksia','species_name' => 'media','common_name' => 'Golden stalk','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '839','genus_name' => 'Bauhinia','species_name' => 'monandra','common_name' => 'Mariposa','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '840','genus_name' => 'Bauhinia','species_name' => 'multinervia','common_name' => 'Petit flamboyant bauhinia','growth_rate' => 'Fast','height_at_maturity' => '52'),
            array('id' => '841','genus_name' => 'Backhousia','species_name' => 'myrtifolia','common_name' => 'Grey Myrtle','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '842','genus_name' => 'Baccharis','species_name' => 'neglecta','common_name' => 'Rooseveltweed','growth_rate' => 'Fast','height_at_maturity' => '9'),
            array('id' => '843','genus_name' => 'Banksia','species_name' => 'oblongifolia','common_name' => 'Fern-leaved Banksia','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '844','genus_name' => 'Banksia','species_name' => 'occidentalis','common_name' => 'Red Swamp Banksia','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '845','genus_name' => 'Banksia','species_name' => 'ornata','common_name' => 'Desert Banksia','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '846','genus_name' => 'Banksia','species_name' => 'paludosa','common_name' => 'Marsh Banksia','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '847','genus_name' => 'Bauhinia','species_name' => 'pauletia','common_name' => 'Railroadfence','growth_rate' => 'Fast','height_at_maturity' => '52'),
            array('id' => '849','genus_name' => 'Baccharis','species_name' => 'pilularis','common_name' => 'Dwarf chaparral broom','growth_rate' => '','height_at_maturity' => '1'),
            array('id' => '850','genus_name' => 'Bauhinia','species_name' => 'picta','common_name' => 'Bauhinia picta','growth_rate' => 'Fast','height_at_maturity' => '59'),
            array('id' => '851','genus_name' => 'Banara','species_name' => 'portoricensis','common_name' => 'Puerto rico palo de ramon','growth_rate' => '','height_at_maturity' => '35'),
            array('id' => '852','genus_name' => 'Bambusa','species_name' => 'polymorpha','common_name' => 'Polymorph bamboo','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '853','genus_name' => 'Barleria','species_name' => 'prionitis','common_name' => 'Porcupine flower','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '854','genus_name' => 'Baccharis','species_name' => 'pteronioides','common_name' => 'Yerba de pasmo','growth_rate' => '','height_at_maturity' => '3'),
            array('id' => '855','genus_name' => 'Bauhinia','species_name' => 'purpurea','common_name' => 'Orchid tree','growth_rate' => 'Fast','height_at_maturity' => '35'),
            array('id' => '856','genus_name' => 'Barringtonia','species_name' => 'racemosa','common_name' => 'powder-puff tree','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '857','genus_name' => 'Banksia','species_name' => 'robur','common_name' => 'Swamp Banksia','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '858','genus_name' => 'Baccharis','species_name' => 'salicina','common_name' => 'Great plains false willow','growth_rate' => '','height_at_maturity' => '9'),
            array('id' => '859','genus_name' => 'Banksia','species_name' => 'saxicola','common_name' => 'Grampians Banksia','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '860','genus_name' => 'Baccharis','species_name' => 'sarothroides','common_name' => 'Desertbroom','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '861','genus_name' => 'Baccharis','species_name' => 'salicifolia','common_name' => 'Mule\'s fat','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '863','genus_name' => 'Baccharis','species_name' => 'sergiloides','common_name' => 'Squaw waterweed baccharis','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '864','genus_name' => 'Banksia','species_name' => 'serrata','common_name' => 'Saw Banksia','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '867','genus_name' => 'Banksia','species_name' => 'speciosa','common_name' => 'Showy Banksia','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '868','genus_name' => 'Banksia','species_name' => 'spinulosa','common_name' => 'Hairpin Banksia','growth_rate' => 'Fast','height_at_maturity' => '3'),
            array('id' => '869','genus_name' => 'Banksia','species_name' => 'spinulosa v. collina','common_name' => 'Hill Banksia','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '871','genus_name' => 'Bambusa','species_name' => 'textilis','common_name' => 'Textile bamboo','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '872','genus_name' => 'Bauhinia','species_name' => 'tomentosa','common_name' => 'St. thomas tree','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '873','genus_name' => 'Bambusa','species_name' => 'tulda','common_name' => 'Bamboo','growth_rate' => 'Fast','height_at_maturity' => '80'),
            array('id' => '875','genus_name' => 'Bauhinia','species_name' => 'variegata','common_name' => 'Mountain ebony','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '876','genus_name' => 'Banara','species_name' => 'vanderbiltii','common_name' => 'Vanderbilt palo de ramon','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '877','genus_name' => 'Baccharis','species_name' => 'vanessae','common_name' => 'Encinitis false willow','growth_rate' => '','height_at_maturity' => '7'),
            array('id' => '878','genus_name' => 'Batesimalva','species_name' => 'violacea','common_name' => 'Purple gaymallow','growth_rate' => '','height_at_maturity' => '7'),
            array('id' => '879','genus_name' => 'Bambusa','species_name' => 'vulgaris','common_name' => 'Common bamboo','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '880','genus_name' => 'Bauhinia','species_name' => 'yunnanensis','common_name' => 'Yunnan bauhinia','growth_rate' => 'Fast','height_at_maturity' => '52'),
            array('id' => '881','genus_name' => 'Bersama','species_name' => 'abyssinica','common_name' => 'Winged bersama','growth_rate' => 'Moderate','height_at_maturity' => '45'),
            array('id' => '882','genus_name' => 'Betula','species_name' => 'alleghaniensis','common_name' => 'Yellow birch','growth_rate' => 'Slow','height_at_maturity' => '75'),
            array('id' => '883','genus_name' => 'Betula','species_name' => 'pubescens','common_name' => 'Downy birch','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '884','genus_name' => 'Betula','species_name' => 'albosinensis','common_name' => 'Chinese birch','growth_rate' => 'Slow','height_at_maturity' => '60'),
            array('id' => '885','genus_name' => 'Bedfordia','species_name' => 'arborescens','common_name' => 'Blanket Leaf','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '886','genus_name' => 'Betula','species_name' => 'borealis','common_name' => 'Northern birch','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '887','genus_name' => 'Berberis','species_name' => 'canadensis','common_name' => 'American barberry','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '888','genus_name' => 'Betula','species_name' => 'x caerulea','common_name' => 'Blue birch','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '889','genus_name' => 'Betula','species_name' => 'costata','common_name' => 'Korean birch','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '890','genus_name' => 'Berberis','species_name' => 'darwinii','common_name' => 'Darwin\'s berberis','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '891','genus_name' => 'Bernardia','species_name' => 'dichotoma','common_name' => 'Caribbean myrtlecroton','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '892','genus_name' => 'Betula','species_name' => 'x dugleana','common_name' => 'Dugle\'s birch','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '893','genus_name' => 'Betula','species_name' => 'x eastwoodiae','common_name' => 'Eastwood\'s birch','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '895','genus_name' => 'Betula','species_name' => 'ermanii','common_name' => 'Ermans birch','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '896','genus_name' => 'Berberis','species_name' => 'fendleri','common_name' => 'Colorado barberry','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '897','genus_name' => 'Berberis','species_name' => 'harrisoniana','common_name' => 'Harrison\'s barberry','growth_rate' => '','height_at_maturity' => '5'),
            array('id' => '898','genus_name' => 'Betula','species_name' => 'x hornei','common_name' => 'Horne\'s birch','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '900','genus_name' => 'Betula','species_name' => 'x jackii','common_name' => 'Jack\'s birch','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '901','genus_name' => 'Berberis','species_name' => 'julianae','common_name' => 'Julian\'s berberis','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '902','genus_name' => 'Betula','species_name' => 'lenta','common_name' => 'Black birch','growth_rate' => 'Moderate','height_at_maturity' => '60'),
            array('id' => '903','genus_name' => 'Betula','species_name' => 'maximowicziana','common_name' => 'Monarch Birch','growth_rate' => 'Fast','height_at_maturity' => '12'),
            array('id' => '904','genus_name' => 'Beilschmiedia','species_name' => 'miersii','common_name' => 'Belloto del norte','growth_rate' => '','height_at_maturity' => '80'),
            array('id' => '905','genus_name' => 'Betula','species_name' => 'murrayana','common_name' => 'Murray\'s birch','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '907','genus_name' => 'Betula','species_name' => 'neoalaskana','common_name' => 'Resin birch','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '908','genus_name' => 'Betula','species_name' => 'nigra','common_name' => 'River birch','growth_rate' => 'Fast','height_at_maturity' => '70'),
            array('id' => '910','genus_name' => 'Betula','species_name' => 'occidentalis','common_name' => 'Water birch','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '912','genus_name' => 'Betula','species_name' => 'papyrifera','common_name' => 'Paper birch','growth_rate' => 'Fast','height_at_maturity' => '70'),
            array('id' => '913','genus_name' => 'Betula','species_name' => 'pendula','common_name' => 'European white birch','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '914','genus_name' => 'Beilschmiedia','species_name' => 'pendula','common_name' => 'Guajon','growth_rate' => '','height_at_maturity' => '90'),
            array('id' => '916','genus_name' => 'Betula','species_name' => 'platyphylla','common_name' => 'Asian white birch','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '917','genus_name' => 'Betula','species_name' => 'populifolia','common_name' => 'Gray birch','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '918','genus_name' => 'Betula','species_name' => 'pumila','common_name' => 'Bog birch','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '919','genus_name' => 'Betula','species_name' => 'x purpusii','common_name' => 'Purpus\'s birch','growth_rate' => 'Moderate','height_at_maturity' => '45'),
            array('id' => '921','genus_name' => 'Beaucarnea','species_name' => 'recurvata','common_name' => 'Ponytail palm','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '922','genus_name' => 'Betula','species_name' => 'x sandbergii','common_name' => 'Sandberg\'s birch','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '923','genus_name' => 'Betula','species_name' => 'schmidtii','common_name' => 'Schmidt\'s birch','growth_rate' => '','height_at_maturity' => '98'),
            array('id' => '924','genus_name' => 'Betula','species_name' => 'dahurica','common_name' => 'Dahurian birch','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '925','genus_name' => 'Berberis','species_name' => 'thunbergii','common_name' => 'Japanese barberry','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '926','genus_name' => 'Betula','species_name' => 'uber','common_name' => 'Virginia roundleaf birch','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '927','genus_name' => 'Betula','species_name' => 'x utahensis','common_name' => 'Northwestern paper birch','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '928','genus_name' => 'Betula','species_name' => 'utilis','common_name' => 'Indian paper birch','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '929','genus_name' => 'Berberis','species_name' => 'vulgaris','common_name' => 'Common barberry','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '931','genus_name' => 'Betula','species_name' => 'x winteri','common_name' => 'Winter\'s birch','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '932','genus_name' => 'Bischofia','species_name' => 'javanica','common_name' => 'Toog','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '934','genus_name' => 'Bismarckia','species_name' => 'nobilis','common_name' => 'Bismarckia palm','growth_rate' => '','height_at_maturity' => '55'),
            array('id' => '935','genus_name' => 'Bixa','species_name' => 'orellana','common_name' => 'Lipsticktree','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '936','genus_name' => 'Bischofia','species_name' => 'polycarpa','common_name' => 'Bischofia polycarpa','growth_rate' => 'Fast','height_at_maturity' => '63'),
            array('id' => '938','genus_name' => 'Blighia','species_name' => 'sapida','common_name' => 'Akee','growth_rate' => '','height_at_maturity' => '82'),
            array('id' => '939','genus_name' => 'Borassus','species_name' => 'aethiopium','common_name' => 'African fan palm','growth_rate' => 'Slow','height_at_maturity' => '27'),
            array('id' => '941','genus_name' => 'Bobea','species_name' => 'brevipes','common_name' => '\'akupa','growth_rate' => '','height_at_maturity' => '32'),
            array('id' => '944','genus_name' => 'Bombax','species_name' => 'ceiba','common_name' => 'Red-silk cotton','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '945','genus_name' => 'Bontia','species_name' => 'daphnoides','common_name' => 'White alling','growth_rate' => 'Moderate','height_at_maturity' => '11'),
            array('id' => '946','genus_name' => 'Bobea','species_name' => 'elatior','common_name' => '\'ahakea lau nui','growth_rate' => '','height_at_maturity' => '33'),
            array('id' => '947','genus_name' => 'Bocconia','species_name' => 'frutescens','common_name' => 'Parrotweed','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '951','genus_name' => 'Bobea','species_name' => 'sandwicensis','common_name' => 'Hawai\'i dogweed','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '956','genus_name' => 'Bobea','species_name' => 'timonioides','common_name' => '\'ahakea','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '957','genus_name' => 'Bourreria','species_name' => 'virgata','common_name' => 'Roble de guayo','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '958','genus_name' => 'Schefflera','species_name' => 'actinophylla','common_name' => 'Schefflera','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '959','genus_name' => 'Brachychiton','species_name' => 'acerifolius','common_name' => 'Illwarra Flame Tree','growth_rate' => 'Fast','height_at_maturity' => '93'),
            array('id' => '960','genus_name' => 'Brosimum','species_name' => 'alicastrum','common_name' => 'Breadnut','growth_rate' => '','height_at_maturity' => '130'),
            array('id' => '961','genus_name' => 'Brunfelsia','species_name' => 'americana','common_name' => 'American brunfelsia','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '962','genus_name' => 'Brucea','species_name' => 'antidysenterica','common_name' => 'Waginos','growth_rate' => 'Fast','height_at_maturity' => '45'),
            array('id' => '963','genus_name' => 'Brahea','species_name' => 'armata','common_name' => 'Mexican blue palm','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '964','genus_name' => 'Broussaisia','species_name' => 'arguta','common_name' => 'Kanawao','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '965','genus_name' => 'Brachychiton','species_name' => 'bidwillii','common_name' => 'Little Kurrajong','growth_rate' => 'Moderate','height_at_maturity' => '16'),
            array('id' => '966','genus_name' => 'Brahea','species_name' => 'brandegeei','common_name' => 'San jose hesper palm','growth_rate' => 'Moderate','height_at_maturity' => '45'),
            array('id' => '967','genus_name' => 'Brugmansia','species_name' => 'candida','common_name' => 'Angel\'s-trumpet','growth_rate' => 'Moderate','height_at_maturity' => '16'),
            array('id' => '968','genus_name' => 'Brunellia','species_name' => 'comocladiifolia','common_name' => 'West indian sumac','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '969','genus_name' => 'Brunfelsia','species_name' => 'densifolia','common_name' => 'Serpentine hill raintree','growth_rate' => '','height_at_maturity' => '22'),
            array('id' => '970','genus_name' => 'Brachychiton','species_name' => 'discolor','common_name' => 'Lacebark','growth_rate' => 'Moderate','height_at_maturity' => '82'),
            array('id' => '971','genus_name' => 'Brachychiton','species_name' => 'diversifolius','common_name' => 'Northern Kurrajong','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '974','genus_name' => 'Brahea','species_name' => 'edulis','common_name' => 'Guadalupe palm','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '975','genus_name' => 'Brachychiton','species_name' => 'gregorii','common_name' => 'Desert Kurrajong','growth_rate' => 'Fast','height_at_maturity' => '8'),
            array('id' => '976','genus_name' => 'Brownea','species_name' => 'grandiceps','common_name' => 'Rose of Venezuela','growth_rate' => '','height_at_maturity' => '66'),
            array('id' => '980','genus_name' => 'Brunfelsia','species_name' => 'lactea','common_name' => 'Vega blanca','growth_rate' => 'Slow','height_at_maturity' => '23'),
            array('id' => '983','genus_name' => 'Brachychiton','species_name' => 'occulneuem','common_name' => 'Bottle tree','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '984','genus_name' => 'Broussonetia','species_name' => 'papyrifera','common_name' => 'Paper mulberry','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '985','genus_name' => 'Brunfelsia','species_name' => 'pauciflora','common_name' => 'Brunfelsia pauciflora','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '987','genus_name' => 'Brachychiton','species_name' => 'populneus','common_name' => 'Kurrajong','growth_rate' => 'Fast','height_at_maturity' => '93'),
            array('id' => '988','genus_name' => 'Brunfelsia','species_name' => 'portoricensis','common_name' => 'Puerto rico raintree','growth_rate' => '','height_at_maturity' => '7'),
            array('id' => '990','genus_name' => 'Brachychiton','species_name' => 'rupestris','common_name' => 'Brachichiton rupestris','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '991','genus_name' => 'Brugmansia','species_name' => 'sanguinea','common_name' => 'Floripondio','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '992','genus_name' => 'Brugmansia','species_name' => 'suaveolens','common_name' => 'Angel\'s-tears','growth_rate' => 'Moderate','height_at_maturity' => '16'),
            array('id' => '994','genus_name' => 'Buddleja','species_name' => 'alternifolia','common_name' => 'Fountain butterflybush','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '995','genus_name' => 'Buchanania','species_name' => 'arborescens','common_name' => 'Little Gooseberry Tree','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '996','genus_name' => 'Bunchosia','species_name' => 'armeniaca','common_name' => 'Cereza','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '997','genus_name' => 'Buddleja','species_name' => 'asiatica','common_name' => 'Dogtail','growth_rate' => 'Fast','height_at_maturity' => '9'),
            array('id' => '998','genus_name' => 'Bursera','species_name' => 'bipinnata','common_name' => 'Bursera bipinnata','growth_rate' => '','height_at_maturity' => '5'),
            array('id' => '999','genus_name' => 'Bucida','species_name' => 'buceras','common_name' => 'Black olive','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '1000','genus_name' => 'Butia','species_name' => 'capitata','common_name' => 'Jelly palm','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '1001','genus_name' => 'Buchenavia','species_name' => 'capitata','common_name' => 'Buchenavia capitata','growth_rate' => 'Slow','height_at_maturity' => '59'),
            array('id' => '1002','genus_name' => 'Buckinghamia','species_name' => 'celsissima','common_name' => 'Ivory Curl Flower','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '1003','genus_name' => 'Buddleja','species_name' => 'cordata','common_name' => 'Buddleja cordata','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '1004','genus_name' => 'Bursera','species_name' => 'cuneata','common_name' => 'Bursera cuneata','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '1005','genus_name' => 'Buddleja','species_name' => 'davidii','common_name' => 'Orange eye butterflybush','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '1007','genus_name' => 'Bursera','species_name' => 'fagaroides','common_name' => 'Fragrant bursera','growth_rate' => 'Moderate','height_at_maturity' => '44'),
            array('id' => '1008','genus_name' => 'Bursera','species_name' => 'fagaroides elongata','common_name' => 'Torchwood copal','growth_rate' => '','height_at_maturity' => '8'),
            array('id' => '1009','genus_name' => 'Bunchosia','species_name' => 'glandulosa','common_name' => 'Cafe forastero','growth_rate' => 'Moderate','height_at_maturity' => '31'),
            array('id' => '1010','genus_name' => 'Bunchosia','species_name' => 'glandulifera','common_name' => 'Cafe falso','growth_rate' => 'Moderate','height_at_maturity' => '31'),
            array('id' => '1011','genus_name' => 'Bursera','species_name' => 'graveolens','common_name' => 'Bijo','growth_rate' => 'Fast','height_at_maturity' => '12'),
            array('id' => '1012','genus_name' => 'Bursaria','species_name' => 'incana','common_name' => 'Prickly pine','growth_rate' => 'Fast','height_at_maturity' => '7'),
            array('id' => '1013','genus_name' => 'Bumelia','species_name' => 'lanuginosum','common_name' => 'Chittamwood','growth_rate' => 'Slow','height_at_maturity' => '43'),
            array('id' => '1018','genus_name' => 'Buddleja','species_name' => 'megalocephala','common_name' => 'Buddleja megalocephala','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '1019','genus_name' => 'Bursera','species_name' => 'microphylla','common_name' => 'Elephant tree','growth_rate' => 'Moderate','height_at_maturity' => '44'),
            array('id' => '1020','genus_name' => 'Buxus','species_name' => 'microphylla','common_name' => 'Littleleaf box','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '1021','genus_name' => 'Buxus','species_name' => 'microphylla koreana','common_name' => 'Korean box tree','growth_rate' => '','height_at_maturity' => '4'),
            array('id' => '1022','genus_name' => 'Bucida','species_name' => 'molinetii','common_name' => 'Spiny bucida','growth_rate' => 'Moderate','height_at_maturity' => '49'),
            array('id' => '1024','genus_name' => 'Bursera','species_name' => 'palmeri','common_name' => 'Copal','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '1025','genus_name' => 'Buddleja','species_name' => 'parviflora','common_name' => 'Buddleja parviflora','growth_rate' => '','height_at_maturity' => '7'),
            array('id' => '1027','genus_name' => 'Bunchosia','species_name' => 'polystachia','common_name' => 'Woodland coffee','growth_rate' => 'Moderate','height_at_maturity' => '31'),
            array('id' => '1029','genus_name' => 'Buddleja','species_name' => 'saligna','common_name' => 'Squarestem butterflybush','growth_rate' => 'Fast','height_at_maturity' => '9'),
            array('id' => '1031','genus_name' => 'Bursera','species_name' => 'schlechtendalii','common_name' => 'Bursera schlechtendalii','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '1033','genus_name' => 'Buxus','species_name' => 'sempervirens','common_name' => 'Common box','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '1034','genus_name' => 'Bursera','species_name' => 'simaruba','common_name' => 'Gumbo limbo','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '1035','genus_name' => 'Bursaria','species_name' => 'spinosa','common_name' => 'Sweet bursaria','growth_rate' => 'Slow','height_at_maturity' => '13'),
            array('id' => '1036','genus_name' => 'Buchenavia','species_name' => 'tetraphylla','common_name' => 'Fourleaf buchenavia','growth_rate' => 'Fast','height_at_maturity' => '75'),
            array('id' => '1037','genus_name' => 'Buxus','species_name' => 'vahlii','common_name' => 'Vahl\'s box','growth_rate' => '','height_at_maturity' => '16'),
            array('id' => '1038','genus_name' => 'Butia','species_name' => 'yatay','common_name' => 'Yatay Palm','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '1039','genus_name' => 'Byrsonima','species_name' => 'crassifolia','common_name' => 'Maricao cimun','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '1043','genus_name' => 'Byrsonima','species_name' => 'lucida','common_name' => 'Long key locustberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1045','genus_name' => 'Byrsonima','species_name' => 'spicata','common_name' => 'Doncella','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '1046','genus_name' => 'Byrsonima','species_name' => 'wadsworthii','common_name' => 'Almendrillo','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '1047','genus_name' => 'Camptotheca','species_name' => 'acuminata','common_name' => 'Happy tree','growth_rate' => 'Fast','height_at_maturity' => '66'),
            array('id' => '1048','genus_name' => 'Carpenteria','species_name' => 'acuminata','common_name' => 'Carpentaria Palm','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '1049','genus_name' => 'Casearia','species_name' => 'aculeata','common_name' => 'Rabo de raton','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '1050','genus_name' => 'Calyptranthes','species_name' => 'acevedoi','common_name' => 'Puerto rico mountainbay','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1051','genus_name' => 'Cassia','species_name' => 'afrofistula','common_name' => 'Kenyan shower','growth_rate' => 'Fast','height_at_maturity' => '51'),
            array('id' => '1052','genus_name' => 'Capparis','species_name' => 'amplissima','common_name' => 'Burro blanco','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '1053','genus_name' => 'Callicarpa','species_name' => 'ampla','common_name' => 'Caparosa','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '1054','genus_name' => 'Callicarpa','species_name' => 'americana','common_name' => 'American beautyberry','growth_rate' => '','height_at_maturity' => '8'),
            array('id' => '1055','genus_name' => 'Carya','species_name' => 'aquatica','common_name' => 'Water hickory','growth_rate' => 'Slow','height_at_maturity' => '85'),
            array('id' => '1056','genus_name' => 'Caragana','species_name' => 'arborescens','common_name' => 'Siberian pea tree','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '1057','genus_name' => 'Senna','species_name' => 'artemisioides','common_name' => 'Wormwood senna','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '1058','genus_name' => 'Casearia','species_name' => 'arborea','common_name' => 'Gia verde','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '1059','genus_name' => 'Castanospermum','species_name' => 'australe','common_name' => 'Black Bean','growth_rate' => 'Moderate','height_at_maturity' => '116'),
            array('id' => '1060','genus_name' => 'Calpurnia','species_name' => 'aurea','common_name' => 'African Laburnum','growth_rate' => 'Fast','height_at_maturity' => '4'),
            array('id' => '1061','genus_name' => 'Caragana','species_name' => 'aurantiaca','common_name' => 'Dwarf peashrub','growth_rate' => 'Slow','height_at_maturity' => '26'),
            array('id' => '1062','genus_name' => 'Canarium','species_name' => 'australianum','common_name' => 'Melville Island Wht Beech','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '1063','genus_name' => 'Callitris','species_name' => 'baileyi','common_name' => 'Bailey\'s Cypress-pine','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '1064','genus_name' => 'Capparis','species_name' => 'baducca','common_name' => 'Caper','growth_rate' => 'Slow','height_at_maturity' => '7'),
            array('id' => '1065','genus_name' => 'Carpinus','species_name' => 'betulus','common_name' => 'European hornbeam','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '1066','genus_name' => 'Carpinus','species_name' => 'betulus \'Fastigiata\'','common_name' => 'Fastigate hornbeam','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '1067','genus_name' => 'Catalpa','species_name' => 'bignonioides','common_name' => 'Southern catalpa','growth_rate' => 'Fast','height_at_maturity' => '66'),
            array('id' => '1068','genus_name' => 'Callicarpa','species_name' => 'bodinieri','common_name' => 'Profusion beautyberry','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '1069','genus_name' => 'Calytrix','species_name' => 'brownii','common_name' => 'White Turkey Bush','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '1070','genus_name' => 'Carallia','species_name' => 'brachiata','common_name' => 'Bush Currant','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '1071','genus_name' => 'Carya','species_name' => 'x brownii','common_name' => 'Brown\'s hickory','growth_rate' => 'Slow','height_at_maturity' => '105'),
            array('id' => '1073','genus_name' => 'Calophyllum','species_name' => 'brasiliense','common_name' => 'Palo de Maria','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1075','genus_name' => 'Catalpa','species_name' => 'bungei','common_name' => 'Umbrella catalpa','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '1076','genus_name' => 'Carpinus','species_name' => 'caroliniana','common_name' => 'American hornbeam','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '1079','genus_name' => 'Calophyllum','species_name' => 'antillanum','common_name' => 'Maria','growth_rate' => 'Slow','height_at_maturity' => '65'),
            array('id' => '1080','genus_name' => 'Caesalpinia','species_name' => 'caudata','common_name' => 'Tailed nicker','growth_rate' => 'Fast','height_at_maturity' => '37'),
            array('id' => '1081','genus_name' => 'Calodendrum','species_name' => 'capense','common_name' => 'Cape chesnut','growth_rate' => '','height_at_maturity' => '45'),
            array('id' => '1082','genus_name' => 'Carya','species_name' => 'carolinae','common_name' => 'Southern shagbark hickory','growth_rate' => '','height_at_maturity' => '105'),
            array('id' => '1083','genus_name' => 'Caesalpinia','species_name' => 'cacalaco','common_name' => 'Cascalote','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '1084','genus_name' => 'Calycophyllum','species_name' => 'candidissimum','common_name' => 'Degame','growth_rate' => '','height_at_maturity' => '45'),
            array('id' => '1085','genus_name' => 'Carpenteria','species_name' => 'decidua','common_name' => 'Karira','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '1086','genus_name' => 'Chrysolepis','species_name' => 'chrysophylla','common_name' => 'Giant chinkapin','growth_rate' => 'Moderate','height_at_maturity' => '100'),
            array('id' => '1087','genus_name' => 'Callistemon','species_name' => 'citrinus','common_name' => 'Crimson bottlebrush','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '1088','genus_name' => 'Caesalpinia','species_name' => 'ciliata','common_name' => 'Mato','growth_rate' => 'Fast','height_at_maturity' => '37'),
            array('id' => '1089','genus_name' => 'Casasia','species_name' => 'clusiifolia','common_name' => 'Sevenyear apple','growth_rate' => 'Slow','height_at_maturity' => '13'),
            array('id' => '1090','genus_name' => 'Caryopteris','species_name' => 'x clandonensis','common_name' => 'Caryopteris','growth_rate' => '','height_at_maturity' => '2'),
            array('id' => '1091','genus_name' => 'Carya','species_name' => 'cordiformis','common_name' => 'Bitternut hickory','growth_rate' => 'Slow','height_at_maturity' => '75'),
            array('id' => '1092','genus_name' => 'Callitris','species_name' => 'columellaris','common_name' => 'White cypress-pine','growth_rate' => 'Moderate','height_at_maturity' => '53'),
            array('id' => '1094','genus_name' => 'Carya','species_name' => 'x collina','common_name' => 'Collin hickory','growth_rate' => 'Slow','height_at_maturity' => '105'),
            array('id' => '1095','genus_name' => 'Caesalpinia','species_name' => 'coriaria','common_name' => 'Divi divi','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '1096','genus_name' => 'Casearia','species_name' => 'commersoniana','common_name' => 'yerce','growth_rate' => '','height_at_maturity' => '26'),
            array('id' => '1097','genus_name' => 'Carpinus','species_name' => 'cordata','common_name' => 'Heartleaf hornbeam','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '1098','genus_name' => 'Castanea','species_name' => 'crenata','common_name' => 'Japanese chestnut','growth_rate' => 'Moderate','height_at_maturity' => '49'),
            array('id' => '1099','genus_name' => 'Casuarina','species_name' => 'cunninghamiana','common_name' => 'River she-oak','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '1100','genus_name' => 'Capparis','species_name' => 'cynophallophora','common_name' => 'Jamacia caper','growth_rate' => 'Slow','height_at_maturity' => '23'),
            array('id' => '1101','genus_name' => 'Castanea','species_name' => 'dentata','common_name' => 'American chestnut','growth_rate' => 'Fast','height_at_maturity' => '115'),
            array('id' => '1102','genus_name' => 'Carya','species_name' => 'x demareei','common_name' => 'Demaree hickory','growth_rate' => 'Slow','height_at_maturity' => '105'),
            array('id' => '1103','genus_name' => 'Casearia','species_name' => 'decandra','common_name' => 'Wild honeytree','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '1104','genus_name' => 'Caesalpinia','species_name' => 'decapetala','common_name' => 'Shoofly','growth_rate' => 'Fast','height_at_maturity' => '37'),
            array('id' => '1105','genus_name' => 'Calocedrus','species_name' => 'decurrens','common_name' => 'Incense cedar','growth_rate' => 'Slow','height_at_maturity' => '100'),
            array('id' => '1106','genus_name' => 'Callicarpa','species_name' => 'dichotoma','common_name' => 'Purple beautyberry','growth_rate' => '','height_at_maturity' => '4'),
            array('id' => '1107','genus_name' => 'Caesalpinia','species_name' => 'divergens','common_name' => 'Small yellow nicker','growth_rate' => 'Fast','height_at_maturity' => '37'),
            array('id' => '1108','genus_name' => 'Callitris','species_name' => 'drummondii','common_name' => 'Drummond\'s Cypress-pine','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '1109','genus_name' => 'Carya','species_name' => 'x dunbarii','common_name' => 'Dunbar\'s hickory','growth_rate' => 'Slow','height_at_maturity' => '105'),
            array('id' => '1110','genus_name' => 'Caesalpinia','species_name' => 'echinata','common_name' => 'Brazilwood','growth_rate' => '','height_at_maturity' => '39'),
            array('id' => '1111','genus_name' => 'Caloncoba','species_name' => 'echinata','common_name' => 'gorli','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '1112','genus_name' => 'Casimiroa','species_name' => 'edulis','common_name' => 'White sapote','growth_rate' => 'Fast','height_at_maturity' => '32'),
            array('id' => '1114','genus_name' => 'Castilla','species_name' => 'elastica','common_name' => 'Panama rubbertree','growth_rate' => '','height_at_maturity' => '26'),
            array('id' => '1115','genus_name' => 'Castela','species_name' => 'emoryi','common_name' => 'Crucifixion thorn','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '1116','genus_name' => 'Callitris','species_name' => 'endlicheri','common_name' => 'Black Cypress Pine','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '1117','genus_name' => 'Casuarina','species_name' => 'equisetifolia','common_name' => 'Australian pine','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '1118','genus_name' => 'Catalpa','species_name' => 'x erubescens','common_name' => 'Purple toned catalpa','growth_rate' => 'Fast','height_at_maturity' => '55'),
            array('id' => '1119','genus_name' => 'Calliandra','species_name' => 'eriophylla','common_name' => 'Fairy duster','growth_rate' => '','height_at_maturity' => '1'),
            array('id' => '1120','genus_name' => 'Castela','species_name' => 'erecta','common_name' => 'Goatbush','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '1121','genus_name' => 'Calyptranthes','species_name' => 'estremenae','common_name' => 'Las cuevas mountainbay','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1122','genus_name' => 'Cariniana','species_name' => 'estrellensis','common_name' => 'jequitiba-branco','growth_rate' => '','height_at_maturity' => '196'),
            array('id' => '1123','genus_name' => 'Cassia','species_name' => 'excelsa','common_name' => 'Crown of gold tree','growth_rate' => 'Fast','height_at_maturity' => ''),
            array('id' => '1124','genus_name' => 'Calytrix','species_name' => 'exstipulata','common_name' => 'Turkey Bush','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '1125','genus_name' => 'Caesalpinia','species_name' => 'ferrea','common_name' => 'Leopard tree(pau-ferro)','growth_rate' => 'Fast','height_at_maturity' => '37'),
            array('id' => '1127','genus_name' => 'Cassia','species_name' => 'fistula','common_name' => 'Canafistula','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '1128','genus_name' => 'Carya','species_name' => 'floridana','common_name' => 'Scrub hickory','growth_rate' => 'Slow','height_at_maturity' => '105'),
            array('id' => '1129','genus_name' => 'Calycanthus','species_name' => 'floridus','common_name' => 'Carolina allspice','growth_rate' => 'Slow','height_at_maturity' => '16'),
            array('id' => '1130','genus_name' => 'Capparis','species_name' => 'flexuosa','common_name' => 'Falseteeth','growth_rate' => 'Slow','height_at_maturity' => '16'),
            array('id' => '1131','genus_name' => 'Calocedrus','species_name' => 'formosana','common_name' => 'Taiwan incense-cedar','growth_rate' => 'Moderate','height_at_maturity' => ''),
            array('id' => '1132','genus_name' => 'Caragana','species_name' => 'frutex','common_name' => 'Russian peashrub','growth_rate' => 'Slow','height_at_maturity' => '26'),
            array('id' => '1133','genus_name' => 'Caesalpinia','species_name' => 'gilliesii','common_name' => 'Bird or paradise bush','growth_rate' => 'Slow','height_at_maturity' => '37'),
            array('id' => '1135','genus_name' => 'Carya','species_name' => 'glabra','common_name' => 'Pignut hickory','growth_rate' => 'Slow','height_at_maturity' => '80'),
            array('id' => '1136','genus_name' => 'Callistemon','species_name' => 'glaucus','common_name' => 'Albany Bottlebrush','growth_rate' => 'Fast','height_at_maturity' => '3'),
            array('id' => '1137','genus_name' => 'Casuarina','species_name' => 'glauca','common_name' => 'Gray sheoak','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '1138','genus_name' => 'Callitris','species_name' => 'glaucophylla','common_name' => 'White cyprus pine','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1139','genus_name' => 'Callitris','species_name' => 'glaucaphylla','common_name' => 'White Cypress','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '1140','genus_name' => 'Callitris','species_name' => 'gracilis','common_name' => 'Southern Cypress-Pine','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1141','genus_name' => 'Calliandra','species_name' => 'grandiflora','common_name' => 'Calliandra grandiflora','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '1142','genus_name' => 'Cassia','species_name' => 'grandis','common_name' => 'Pink shower','growth_rate' => 'Fast','height_at_maturity' => '51'),
            array('id' => '1144','genus_name' => 'Carapa','species_name' => 'guianensis','common_name' => 'Crabwood','growth_rate' => 'Slow','height_at_maturity' => '49'),
            array('id' => '1145','genus_name' => 'Casearia','species_name' => 'guianensis','common_name' => 'Guyanese wild coffee','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '1146','genus_name' => 'Cassipourea','species_name' => 'guianensis','common_name' => 'Goatwood','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '1147','genus_name' => 'Callistemon','species_name' => '\'Harkness\'','common_name' => 'Gawler hybrid','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1148','genus_name' => 'Calliandra','species_name' => 'haematocephala','common_name' => 'Tassel flower','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '1149','genus_name' => 'Calliandra','species_name' => 'haematomma','common_name' => 'Red powderpuff','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '1150','genus_name' => 'Capparis','species_name' => 'hastata','common_name' => 'Broadleaf caper','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1153','genus_name' => 'Carya','species_name' => 'illinoinensis','common_name' => 'Pecan','growth_rate' => 'Slow','height_at_maturity' => '120'),
            array('id' => '1154','genus_name' => 'Callitris','species_name' => 'intratropica','common_name' => 'Northern Cypress-pine','growth_rate' => 'Slow','height_at_maturity' => '18'),
            array('id' => '1155','genus_name' => 'Capparis','species_name' => 'incana','common_name' => 'Hoary caper','growth_rate' => 'Slow','height_at_maturity' => '23'),
            array('id' => '1156','genus_name' => 'Calophyllum','species_name' => 'inophyllum','common_name' => 'Alexandrian laurel','growth_rate' => 'Slow','height_at_maturity' => '40'),
            array('id' => '1157','genus_name' => 'Canarium','species_name' => 'indicum','common_name' => 'java almond','growth_rate' => '','height_at_maturity' => '100'),
            array('id' => '1158','genus_name' => 'Capparis','species_name' => 'indica','common_name' => 'Linguam','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '1159','genus_name' => 'Carpinus','species_name' => 'japonica','common_name' => 'Japanese hornbeam','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '1161','genus_name' => 'Callicarpa','species_name' => 'japonica','common_name' => 'Japanese callicarpa','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '1162','genus_name' => 'Camellia','species_name' => 'japonica','common_name' => 'Camellia','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1163','genus_name' => 'Caesalpinia','species_name' => 'kavuaiensis','common_name' => 'Uhiuhi','growth_rate' => 'Fast','height_at_maturity' => '37'),
            array('id' => '1164','genus_name' => 'Calyptranthes','species_name' => 'kiaerskovii','common_name' => 'Kiaerskov\'s lidflower','growth_rate' => 'Moderate','height_at_maturity' => '20')
        );

        Tree::insert($trees);

        $seeder = new TreeSpeciesSeeder2;
        $seeder->run();

    }
}