<?php

namespace Database\Seeders\TreeSpecies;

use App\Models\Tree\Tree;
use Illuminate\Database\Seeder;

class TreeSpeciesSeeder8 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $trees = array(
            array('id' => '5544','genus_name' => 'Quercus','species_name' => 'frainetto','common_name' => 'Hungarian Oak','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '5545','genus_name' => 'fusiformis','species_name' => 'fusiformis','common_name' => 'Plateau oak','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '5546','genus_name' => 'Quercus','species_name' => 'gambelii','common_name' => 'Gambel oak','growth_rate' => 'Slow','height_at_maturity' => '35'),
            array('id' => '5547','genus_name' => 'Quercus','species_name' => 'garryana','common_name' => 'Oregon white oak','growth_rate' => 'Slow','height_at_maturity' => '80'),
            array('id' => '5548','genus_name' => 'Quercus','species_name' => 'garlandensi','common_name' => 'Garland oak','growth_rate' => 'Slow','height_at_maturity' => '85'),
            array('id' => '5549','genus_name' => 'Quercus','species_name' => 'gander','common_name' => 'Gander oak','growth_rate' => 'Slow','height_at_maturity' => '17'),
            array('id' => '5550','genus_name' => 'Quercus','species_name' => 'georgiana','common_name' => 'Georgia oak','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '5551','genus_name' => 'Quercus','species_name' => 'germana','common_name' => 'Royal oak','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '5552','genus_name' => 'geminata','species_name' => 'geminata','common_name' => 'Sand live oak','growth_rate' => 'Moderate','height_at_maturity' => '83'),
            array('id' => '5553','genus_name' => 'Quercus','species_name' => 'giffordi','common_name' => 'Gifford\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5554','genus_name' => 'Quercus','species_name' => 'grisea','common_name' => 'Arizona grey oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5555','genus_name' => 'Quercus','species_name' => 'gravesii','common_name' => 'Chisos red oak','growth_rate' => 'Fast','height_at_maturity' => '35'),
            array('id' => '5556','genus_name' => 'Quercus','species_name' => 'graciliformis','common_name' => 'Chisos oak','growth_rate' => 'Moderate','height_at_maturity' => '27'),
            array('id' => '5557','genus_name' => 'Quercus','species_name' => 'grandidentat','common_name' => 'Largeleaf oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5558','genus_name' => 'Quercus','species_name' => 'guadalupensi','common_name' => 'Guadalupe oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5559','genus_name' => 'Quercus','species_name' => 'harbisoni','common_name' => 'Harbison\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5560','genus_name' => 'Quercus','species_name' => 'hastingsi','common_name' => 'Hasting\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5561','genus_name' => 'Quercus','species_name' => 'havardii','common_name' => 'Havard oak','growth_rate' => 'Slow','height_at_maturity' => '7'),
            array('id' => '5562','genus_name' => 'Quercus','species_name' => 'hawkinsia','common_name' => 'Hawkins\' oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5563','genus_name' => 'Quercus','species_name' => 'hemisphaerica','common_name' => 'Darlington oak','growth_rate' => 'Fast','height_at_maturity' => '131'),
            array('id' => '5564','genus_name' => 'Quercus','species_name' => 'heterophyll','common_name' => 'Oddleaf oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5565','genus_name' => 'Quercus','species_name' => 'hinckleyi','common_name' => 'Hinckley oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5566','genus_name' => 'Quercus','species_name' => 'hispanica','common_name' => 'Lucombe Oak','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '5567','genus_name' => 'Quercus','species_name' => 'howelli','common_name' => 'Howell\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5568','genus_name' => 'Quercus','species_name' => 'humidicol','common_name' => 'Quercus x humidicola','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5569','genus_name' => 'hypoleucoides','species_name' => 'hypoleucoides','common_name' => 'Silver leaf oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5570','genus_name' => 'Quercus','species_name' => 'ilicifolia','common_name' => 'Bear oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5571','genus_name' => 'ilex','species_name' => 'ilex','common_name' => 'Holly oak','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '5572','genus_name' => 'Quercus','species_name' => 'ilex ballota','common_name' => 'Evergreen oak','growth_rate' => 'Slow','height_at_maturity' => '82'),
            array('id' => '5573','genus_name' => 'Quercus','species_name' => 'imbricaria','common_name' => 'Shingle oak','growth_rate' => 'Moderate','height_at_maturity' => '45'),
            array('id' => '5574','genus_name' => 'Quassia','species_name' => 'indica','common_name' => 'bitter wood','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '5575','genus_name' => 'Quercus','species_name' => 'inconstan','common_name' => 'Quercus x inconstans','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5576','genus_name' => 'Quercus','species_name' => 'intricata','common_name' => 'Dwarf oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5577','genus_name' => 'Quercus','species_name' => 'introgress','common_name' => 'Quercus x introgressa','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5578','genus_name' => 'Quercus','species_name' => 'incomit','common_name' => 'Quercus x incomita','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5579','genus_name' => 'Quercus','species_name' => 'inopina','common_name' => 'Sandhill oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5580','genus_name' => 'Quercus','species_name' => 'ithaburensis','common_name' => 'Valonia Oak','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '5581','genus_name' => 'Quercus','species_name' => 'jackian','common_name' => 'Jack\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5582','genus_name' => 'Quercus','species_name' => 'jolonensi','common_name' => 'Jolon\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5583','genus_name' => 'Quercus','species_name' => 'john-tuckeri','common_name' => 'Tucker oak','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '5584','genus_name' => 'Quercus','species_name' => 'joori','common_name' => 'Jorr\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5585','genus_name' => 'Quercus','species_name' => 'kelloggii','common_name' => 'California black oak','growth_rate' => 'Slow','height_at_maturity' => '85'),
            array('id' => '5586','genus_name' => 'Quercus','species_name' => 'laceyi','common_name' => 'Lacey oak','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '5587','genus_name' => 'Quercus','species_name' => 'laevis','common_name' => 'Turkey oak','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '5588','genus_name' => 'Quercus','species_name' => 'laurifolia','common_name' => 'Laurel oak','growth_rate' => 'Fast','height_at_maturity' => '70'),
            array('id' => '5589','genus_name' => 'Quercus','species_name' => 'laurina','common_name' => 'Quercus laurina','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '5590','genus_name' => 'Quercus','species_name' => 'laeta','common_name' => 'Quercus laeta','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '5591','genus_name' => 'Quercus','species_name' => 'lean','common_name' => 'Lea oak','growth_rate' => 'Moderate','height_at_maturity' => '67'),
            array('id' => '5592','genus_name' => 'Quercus','species_name' => 'libani','common_name' => 'Lebanon Oak','growth_rate' => 'Slow','height_at_maturity' => '21'),
            array('id' => '5593','genus_name' => 'Quercus','species_name' => 'lobata','common_name' => 'California white oak','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '5594','genus_name' => 'Quercus','species_name' => 'ludovician','common_name' => 'Louisiana oak','growth_rate' => 'Moderate','height_at_maturity' => '67'),
            array('id' => '5595','genus_name' => 'Quercus','species_name' => 'ludoviciana','common_name' => 'Ludwig\'s Oak','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '5596','genus_name' => 'Quercus','species_name' => 'lyrata','common_name' => 'Overcup oak','growth_rate' => 'Moderate','height_at_maturity' => '80'),
            array('id' => '5597','genus_name' => 'Quercus','species_name' => 'macnabian','common_name' => 'Macnab\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5598','genus_name' => 'Quercus','species_name' => 'macrocarpa','common_name' => 'Bur oak','growth_rate' => 'Slow','height_at_maturity' => '100'),
            array('id' => '5599','genus_name' => 'Quercus','species_name' => 'marilandica','common_name' => 'Blackjack oak','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '5600','genus_name' => 'Quercus','species_name' => 'margarettae','common_name' => 'Sand post oak','growth_rate' => 'Slow','height_at_maturity' => '85'),
            array('id' => '5601','genus_name' => 'Quercus','species_name' => 'macdonaldi','common_name' => 'Macdonald oak','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '5602','genus_name' => 'Quercus','species_name' => 'macranthera','common_name' => 'Caucasian Oak','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '5603','genus_name' => 'Quercus','species_name' => 'margarettiae','common_name' => 'Runner oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5604','genus_name' => 'Quercus','species_name' => 'magnoliifolia','common_name' => 'Quercus magnoliifolia','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '5605','genus_name' => 'Quercus','species_name' => 'mellichampi','common_name' => 'Mellichamp\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5606','genus_name' => 'Quercus','species_name' => 'megalei','common_name' => 'Quercus x megaleia','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5607','genus_name' => 'Quercus','species_name' => 'michauxii','common_name' => 'Swamp chestnut oak','growth_rate' => 'Moderate','height_at_maturity' => '80'),
            array('id' => '5608','genus_name' => 'Quercus','species_name' => 'minima','common_name' => 'Dwarf live oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5609','genus_name' => 'Quercus','species_name' => 'mohriana','common_name' => 'Mohr oak','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '5611','genus_name' => 'Quercus','species_name' => 'moreh','common_name' => 'Oracle oak','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '5612','genus_name' => 'Quercus','species_name' => 'moultonensi','common_name' => 'Moulton\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5613','genus_name' => 'Quercus','species_name' => 'muehlenbergii','common_name' => 'Chinkapin oak','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '5614','genus_name' => 'Quercus','species_name' => 'mutabili','common_name' => 'Quercus x mutabilis','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5615','genus_name' => 'Quercus','species_name' => 'munzi','common_name' => 'Munz\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5616','genus_name' => 'Quercus','species_name' => 'myrtifolia','common_name' => 'Myrtle oak','growth_rate' => 'Slow','height_at_maturity' => '13'),
            array('id' => '5617','genus_name' => 'Quercus','species_name' => 'myrsinifolia','common_name' => 'Bamboo-leaved Oak','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '5618','genus_name' => 'Quercus','species_name' => 'neopalmer','common_name' => 'Quercus x neopalmeri','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5619','genus_name' => 'Quercus','species_name' => 'neotharpi','common_name' => 'Quercus x neotharpii','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5620','genus_name' => 'Quercus','species_name' => 'nessian','common_name' => 'Ness\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5621','genus_name' => 'Quercus','species_name' => 'nigra','common_name' => 'Water oak','growth_rate' => 'Fast','height_at_maturity' => '90'),
            array('id' => '5622','genus_name' => 'Quercus','species_name' => 'texana','common_name' => 'Texas red oak','growth_rate' => 'Fast','height_at_maturity' => '110'),
            array('id' => '5623','genus_name' => 'oblongifolia','species_name' => 'oblongifolia','common_name' => 'Mexican blue oak','growth_rate' => 'Slow','height_at_maturity' => '26'),
            array('id' => '5624','genus_name' => 'Quercus','species_name' => 'obtusata','common_name' => 'Quercus obtusata','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '5625','genus_name' => 'Quercus','species_name' => 'oglethorpensis','common_name' => 'Oglethorpe oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5626','genus_name' => 'Quercus','species_name' => 'organensi','common_name' => 'Organ oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5627','genus_name' => 'Quercus','species_name' => 'oviedoensi','common_name' => 'Quercus x oviedoensis','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5628','genus_name' => 'Quercus','species_name' => 'oxyodon','common_name' => 'Man Qing Gang','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '5629','genus_name' => 'Quercus','species_name' => 'palustris','common_name' => 'Pin oak','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '5630','genus_name' => 'Quercus','species_name' => 'pagoda','common_name' => 'Cherrybark oak','growth_rate' => 'Moderate','height_at_maturity' => '120'),
            array('id' => '5631','genus_name' => 'Quercus','species_name' => 'palmerian','common_name' => 'Palmer\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5632','genus_name' => 'Quercus','species_name' => 'paucilob','common_name' => 'Wavyleaf oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5633','genus_name' => 'Quercus','species_name' => 'palaeolithicol','common_name' => 'Quercus x palaeolithicola','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5634','genus_name' => 'Quercus','species_name' => 'pacifica','common_name' => 'Channel island scrub oak','growth_rate' => 'Moderate','height_at_maturity' => '17'),
            array('id' => '5635','genus_name' => 'Quercus','species_name' => 'parvula','common_name' => 'Coast oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5638','genus_name' => 'Quercus','species_name' => 'petraea','common_name' => 'Durmast oak','growth_rate' => 'Slow','height_at_maturity' => '133'),
            array('id' => '5639','genus_name' => 'Quercus','species_name' => 'phellos','common_name' => 'Willow oak','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '5640','genus_name' => 'Quercus','species_name' => 'podophyll','common_name' => 'Quercus x podophylla','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5641','genus_name' => 'Quercus','species_name' => 'pontica','common_name' => 'Armenian Oak','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '5642','genus_name' => 'polymorpha','species_name' => 'polymorpha','common_name' => 'Netleaf white oak','growth_rate' => 'Moderate','height_at_maturity' => '68'),
            array('id' => '5643','genus_name' => 'Quercus','species_name' => 'polymorpha','common_name' => 'Monterrey oak','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '5644','genus_name' => 'Quercus','species_name' => 'prinus','common_name' => 'Chestnut oak','growth_rate' => 'Slow','height_at_maturity' => '73'),
            array('id' => '5645','genus_name' => 'Quercus','species_name' => 'prinoides','common_name' => 'Dwarf chinkapin oak','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '5646','genus_name' => 'Quercus','species_name' => 'pseudomargarettia','common_name' => 'False sand post oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5647','genus_name' => 'pungens','species_name' => 'pungens','common_name' => 'Pungent oak','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '5648','genus_name' => 'Quercus','species_name' => 'pubescens','common_name' => 'Downy Oak','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '5649','genus_name' => 'Quercus','species_name' => 'pumila','common_name' => 'Running oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5650','genus_name' => 'Quercus','species_name' => 'pyrenaica','common_name' => 'Pyrenean Oak','growth_rate' => 'Moderate','height_at_maturity' => '59'),
            array('id' => '5651','genus_name' => 'Quercus','species_name' => 'rehder','common_name' => 'Rehder\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5652','genus_name' => 'Quercus','species_name' => 'resinosa','common_name' => 'Quercus resinosa','growth_rate' => 'Slow','height_at_maturity' => '7'),
            array('id' => '5653','genus_name' => 'Quercus','species_name' => 'ripari','common_name' => 'Riparian oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5654','genus_name' => 'Quercus','species_name' => 'robur','common_name' => 'English oak','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '5655','genus_name' => 'Quercus','species_name' => 'robbinsi','common_name' => 'Robinn\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5656','genus_name' => 'Quercus','species_name' => 'robust','common_name' => 'Robust oak','growth_rate' => 'Moderate','height_at_maturity' => '43'),
            array('id' => '5657','genus_name' => 'Quercus','species_name' => 'rolfsi','common_name' => 'Rolf\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5658','genus_name' => 'Quercus','species_name' => 'robur \'Fastigiata\'','common_name' => 'Columnar english oak','growth_rate' => 'Moderate','height_at_maturity' => '83'),
            array('id' => '5659','genus_name' => 'Quercus','species_name' => 'rubra','common_name' => 'Northern red oak','growth_rate' => 'Moderate','height_at_maturity' => '81'),
            array('id' => '5660','genus_name' => 'Quercus','species_name' => 'rudkini','common_name' => 'Rudkin\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5661','genus_name' => 'Quercus','species_name' => 'runcinat','common_name' => 'Quercus x runcinata','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5662','genus_name' => 'Quercus','species_name' => 'rugosa','common_name' => 'Netleaf oak','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '5663','genus_name' => 'Quercus','species_name' => 'sauli','common_name' => 'Saul\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5664','genus_name' => 'Quillaja','species_name' => 'saponaria','common_name' => 'Quillay','growth_rate' => 'Slow','height_at_maturity' => '60'),
            array('id' => '5665','genus_name' => 'Quercus','species_name' => 'sargenti','common_name' => 'Sargent oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5666','genus_name' => 'Quercus','species_name' => 'sadleriana','common_name' => 'Deer oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5667','genus_name' => 'Quercus','species_name' => 'schochian','common_name' => 'Schoch oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5668','genus_name' => 'Quercus','species_name' => 'schuette','common_name' => 'Schuettes oak','growth_rate' => 'Moderate','height_at_maturity' => '63'),
            array('id' => '5669','genus_name' => 'Quercus','species_name' => 'glandulifera','common_name' => 'Konara oak','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '5670','genus_name' => 'Quercus','species_name' => 'serrata','common_name' => 'Bao li','growth_rate' => '','height_at_maturity' => '82'),
            array('id' => '5671','genus_name' => 'Quercus','species_name' => 'shumardii','common_name' => 'Shumard oak','growth_rate' => 'Moderate','height_at_maturity' => '100'),
            array('id' => '5672','genus_name' => 'Quercus','species_name' => 'sinuata','common_name' => 'Bastard oak','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '5673','genus_name' => 'Quercus','species_name' => 'similis','common_name' => 'Bottomland post oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5674','genus_name' => 'Quercus','species_name' => 'smalli','common_name' => 'Small\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5675','genus_name' => 'Quercus','species_name' => 'stellata','common_name' => 'Post oak','growth_rate' => 'Slow','height_at_maturity' => '60'),
            array('id' => '5676','genus_name' => 'Quercus','species_name' => 'stelloide','common_name' => 'Stelloides oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5677','genus_name' => 'Quercus','species_name' => 'sterili','common_name' => 'Barren oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5678','genus_name' => 'Quercus','species_name' => 'sterreti','common_name' => 'Sterret\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5679','genus_name' => 'suber','species_name' => 'suber','common_name' => 'Cork oak','growth_rate' => 'Slow','height_at_maturity' => '66'),
            array('id' => '5680','genus_name' => 'Quercus','species_name' => 'subintegr','common_name' => 'Quercus x subintegra','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5681','genus_name' => 'Quercus','species_name' => 'substellat','common_name' => 'Quercus x substellata','growth_rate' => 'Slow','height_at_maturity' => '60'),
            array('id' => '5682','genus_name' => 'Quercus','species_name' => 'subconvex','common_name' => 'Quercus x subconvexa','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5683','genus_name' => 'Quercus','species_name' => 'subfalcat','common_name' => 'Subfalcate oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5684','genus_name' => 'Quercus','species_name' => 'tardifolia','common_name' => 'Lateleaf oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5685','genus_name' => 'Quercus','species_name' => 'tharpi','common_name' => 'Tharp\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5686','genus_name' => 'tomentella','species_name' => 'tomentella','common_name' => 'Island live oak','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '5687','genus_name' => 'Quercus','species_name' => 'toumeyi','common_name' => 'Toumey oak','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '5688','genus_name' => 'Quercus','species_name' => 'towne','common_name' => 'Towne\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5689','genus_name' => 'Quercus','species_name' => 'totteni','common_name' => 'Totten\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5690','genus_name' => 'Quercus','species_name' => 'tridentat','common_name' => 'Tridentata oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5691','genus_name' => 'Quercus','species_name' => 'trojana','common_name' => 'Macedonian Oak','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '5693','genus_name' => 'turbinella','species_name' => 'turbinella','common_name' => 'Sonoran scrub oak','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '5694','genus_name' => 'vacciniifolia','species_name' => 'vacciniifolia','common_name' => 'Huckleberry oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5695','genus_name' => 'Quercus','species_name' => 'variabilis','common_name' => 'Chinese cork oak','growth_rate' => '','height_at_maturity' => '98'),
            array('id' => '5696','genus_name' => 'Quercus','species_name' => 'vag','common_name' => 'Quercus x vaga','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5697','genus_name' => 'Quercus','species_name' => 'vaseyana','common_name' => 'Sandpaper oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5698','genus_name' => 'Quercus','species_name' => 'velutina','common_name' => 'Black oak','growth_rate' => 'Moderate','height_at_maturity' => '80'),
            array('id' => '5699','genus_name' => 'Quercus','species_name' => 'venulos','common_name' => 'Quercus x venulosa','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5700','genus_name' => 'virginiana','species_name' => 'virginiana','common_name' => 'Live oak','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '5701','genus_name' => 'Quercus','species_name' => 'viminea','common_name' => 'Sonoran oak','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '5702','genus_name' => 'Quercus','species_name' => 'walterian','common_name' => 'Walter\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5703','genus_name' => 'Quercus','species_name' => 'wagner','common_name' => 'Wagner\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5704','genus_name' => 'wislizeni','species_name' => 'wislizeni','common_name' => 'Interior live oak','growth_rate' => 'Slow','height_at_maturity' => '75'),
            array('id' => '5705','genus_name' => 'Quercus','species_name' => 'willdenowian','common_name' => 'Willdenow\'s oak','growth_rate' => 'Moderate','height_at_maturity' => '85'),
            array('id' => '5706','genus_name' => 'Quercus','species_name' => 'xalapensis','common_name' => 'Xalapa oak','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '5707','genus_name' => 'Quercus','species_name' => 'rosace','common_name' => 'Hybrid oak','growth_rate' => 'Slow','height_at_maturity' => '125'),
            array('id' => '5708','genus_name' => 'Randia','species_name' => 'aculeata','common_name' => 'White indigoberry','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '5712','genus_name' => 'Myrsine','species_name' => 'floridana','common_name' => 'Myrsine','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '5713','genus_name' => 'Rapanea','species_name' => 'howittiana','common_name' => 'Turnipwood','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '5715','genus_name' => 'Ravenala','species_name' => 'madagascariensis','common_name' => 'Traveler\'s tree','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '5721','genus_name' => 'Ravenea','species_name' => 'rivularis','common_name' => 'Majesty palm','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '5722','genus_name' => 'Rauvolfia','species_name' => 'sandwicensis','common_name' => 'Devil\'s-pepper','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '5724','genus_name' => 'Radermachera','species_name' => 'sinica','common_name' => 'Serpent Tree','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '5725','genus_name' => 'Rauvolfia','species_name' => 'tetraphylla','common_name' => 'Be still tree','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '5726','genus_name' => 'Randia','species_name' => 'thurberi','common_name' => 'Randia thurberi','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '5732','genus_name' => 'Reynosia','species_name' => 'guama','common_name' => 'Guama','growth_rate' => '','height_at_maturity' => '38'),
            array('id' => '5734','genus_name' => 'Reynosia','species_name' => 'krugii','common_name' => 'Krug\'s darlingplum','growth_rate' => '','height_at_maturity' => '38'),
            array('id' => '5738','genus_name' => 'Reynoldsia','species_name' => 'sandwicensis','common_name' => '\'ohe makai','growth_rate' => '','height_at_maturity' => '70'),
            array('id' => '5739','genus_name' => 'Reynosia','species_name' => 'septentrionalis','common_name' => 'Darling plum','growth_rate' => '','height_at_maturity' => '38'),
            array('id' => '5740','genus_name' => 'Reynosia','species_name' => 'uncinata','common_name' => 'Sloe','growth_rate' => '','height_at_maturity' => '38'),
            array('id' => '5741','genus_name' => 'Rhamnus','species_name' => 'alnifolia','common_name' => 'Alderleaf buckthorn','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '5742','genus_name' => 'Rhamnus','species_name' => 'alaternus','common_name' => 'Italian Buckthorn','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '5743','genus_name' => 'Rhododendron','species_name' => 'albiflorum','common_name' => 'Cascade azalea','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5744','genus_name' => 'Rhododendron','species_name' => 'alabamense','common_name' => 'Alabama azalea','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5746','genus_name' => 'Rhododendron','species_name' => 'arboreum','common_name' => 'Tree Rhododendron','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '5747','genus_name' => 'Rhododendron','species_name' => 'arborescens','common_name' => 'Smooth azalea','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5748','genus_name' => 'Rhus','species_name' => 'aromatica','common_name' => 'Fragrant sumac','growth_rate' => 'Moderate','height_at_maturity' => '31'),
            array('id' => '5749','genus_name' => 'Rhamnus','species_name' => 'arguta','common_name' => 'Sharp tooth buckthorn','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '5750','genus_name' => 'Rhus','species_name' => 'ashe','common_name' => 'Ashe\'s sumac','growth_rate' => 'Moderate','height_at_maturity' => '31'),
            array('id' => '5751','genus_name' => 'Rhododendron','species_name' => 'atlanticum','common_name' => 'Dwarf azalea','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5752','genus_name' => 'Rhododendron','species_name' => 'austrinum','common_name' => 'Orange azalea','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5754','genus_name' => 'Rhododendron','species_name' => 'azalea','common_name' => 'Azalea','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5755','genus_name' => 'Rhododendron','species_name' => 'baker','common_name' => 'Baker\'s rhododendron','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5757','genus_name' => 'Rhamnus','species_name' => 'cathartica','common_name' => 'European buckthorn','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '5758','genus_name' => 'Rhododendron','species_name' => 'carolinianum','common_name' => 'Carolina azalea','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5760','genus_name' => 'Rhododendron','species_name' => 'calendulaceum','common_name' => 'Flame azalea','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5761','genus_name' => 'Rhododendron','species_name' => 'camtschaticum','common_name' => 'Kamchatka rhododendron','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5762','genus_name' => 'Rhododendron','species_name' => 'canadense','common_name' => 'Rhodora','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5763','genus_name' => 'Rhododendron','species_name' => 'canescens','common_name' => 'Mountain azalea','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5764','genus_name' => 'Rhododendron','species_name' => 'catawbiense','common_name' => 'Catawba rosebay','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '5765','genus_name' => 'Rhus','species_name' => 'chinensis','common_name' => 'Chinese sumac','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '5767','genus_name' => 'Rhododendron','species_name' => 'minus v. chapmanii','common_name' => 'Chapman\'s rhododendron','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5768','genus_name' => 'Rhus','species_name' => 'copallina','common_name' => 'Shining sumac','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '5769','genus_name' => 'Rhamnus','species_name' => 'crocea','common_name' => 'Spiny redberry','growth_rate' => 'Slow','height_at_maturity' => '23'),
            array('id' => '5770','genus_name' => 'Rhododendron','species_name' => 'cumberlandense','common_name' => 'Cumberland rhododendron','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5771','genus_name' => 'Rhamnus','species_name' => 'davurica','common_name' => 'Dahurian buckthorn','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '5772','genus_name' => 'Rhapis','species_name' => 'excelsa','common_name' => 'Bamboo palm','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '5773','genus_name' => 'Rhododendron','species_name' => 'flammeum','common_name' => 'Piedmont azalea','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5774','genus_name' => 'Frangula','species_name' => 'alnus','common_name' => 'Glossy buckthorn','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '5775','genus_name' => 'Rhus','species_name' => 'glabra','common_name' => 'Smooth sumac','growth_rate' => 'Moderate','height_at_maturity' => '31'),
            array('id' => '5776','genus_name' => 'Rhapidophyllum','species_name' => 'hystrix','common_name' => 'Needle palm','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '5777','genus_name' => 'Rhamnus','species_name' => 'ilicifolia','common_name' => 'Hollyleaf redberry','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '5778','genus_name' => 'Rhus','species_name' => 'integrifolia','common_name' => 'Lemonade berry','growth_rate' => 'Moderate','height_at_maturity' => ''),
            array('id' => '5779','genus_name' => 'Rhododendron','species_name' => 'indicum','common_name' => 'Rhododendron indicum','growth_rate' => '','height_at_maturity' => '3'),
            array('id' => '5781','genus_name' => 'Rhododendron','species_name' => 'japonicum','common_name' => 'Japanese azalea','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5782','genus_name' => 'Rhamnus','species_name' => 'japonica','common_name' => 'Japanese buckthorn','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '5783','genus_name' => 'Rhus','species_name' => 'kearneyi','common_name' => 'Kearney\'s sumac','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '5784','genus_name' => 'Rhus','species_name' => 'lancea','common_name' => 'African sumac','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '5785','genus_name' => 'Rhododendron','species_name' => 'lapponicum','common_name' => 'Lapland rosebay','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5786','genus_name' => 'Rhus','species_name' => 'lanceolata','common_name' => 'Prairie sumac','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '5787','genus_name' => 'Rhamnus','species_name' => 'lanceolata','common_name' => 'Lanceleaf buckthorn','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '5788','genus_name' => 'Rhododendron','species_name' => 'maximum','common_name' => 'Rosebay rhododendron','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5789','genus_name' => 'Rhizophora','species_name' => 'mangle','common_name' => 'Mangrove','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '5790','genus_name' => 'Rhododendron','species_name' => 'macrophyllum','common_name' => 'Pacific rhododendron','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '5791','genus_name' => 'Rhododendron','species_name' => 'minus','common_name' => 'Piedmont rhododendron','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5792','genus_name' => 'Rhus','species_name' => 'microphylla','common_name' => 'Littleleaf sumac','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '5793','genus_name' => 'Rhizophora','species_name' => 'mucronata','common_name' => 'Red mangrove','growth_rate' => 'Slow','height_at_maturity' => '83'),
            array('id' => '5795','genus_name' => 'Rhus','species_name' => 'natalensis','common_name' => 'Rhus natalensis','growth_rate' => 'Fast','height_at_maturity' => '66'),
            array('id' => '5796','genus_name' => 'Rhododendron','species_name' => 'oblongifolium','common_name' => 'Texas azalea','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5797','genus_name' => 'Rhododendron','species_name' => 'obtusum','common_name' => 'Kurume azalea','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '5798','genus_name' => 'Rhododendron','species_name' => 'occidentale','common_name' => 'Western azalea','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5799','genus_name' => 'Rhus','species_name' => 'ovata','common_name' => 'Sugar sumac','growth_rate' => 'Moderate','height_at_maturity' => '31'),
            array('id' => '5800','genus_name' => 'Rhus','species_name' => 'pachyrhachis','common_name' => 'Rhus pachyrhachis','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '5801','genus_name' => 'Rhododendron','species_name' => 'pennsylvanicu','common_name' => 'Pennsylvania rhododendron','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5802','genus_name' => 'Rhododendron','species_name' => 'periclymenoides','common_name' => 'Pink azalea','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5803','genus_name' => 'Rhamnus','species_name' => 'pirifolia','common_name' => 'Island redberry','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '5804','genus_name' => 'Rhododendron','species_name' => 'prinophyllum','common_name' => 'Early azalea','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5805','genus_name' => 'Rhamnus','species_name' => 'prinoides','common_name' => 'Blinkblaar','growth_rate' => 'Fast','height_at_maturity' => '18'),
            array('id' => '5806','genus_name' => 'Rhododendron','species_name' => 'prunifolium','common_name' => 'Plumleaf azalea','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5808','genus_name' => 'Rhus','species_name' => 'pulvinat','common_name' => 'Pulvinate sumac','growth_rate' => 'Moderate','height_at_maturity' => '31'),
            array('id' => '5809','genus_name' => 'Rhus','species_name' => 'retinorrhoea','common_name' => 'Daabeluuca','growth_rate' => 'Fast','height_at_maturity' => '64'),
            array('id' => '5810','genus_name' => 'Rhodamnia','species_name' => 'rubescens','common_name' => 'Scrub turpentine','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '5811','genus_name' => 'Rhus','species_name' => 'sandwicensis','common_name' => 'Neneleau','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '5812','genus_name' => 'Rhododendron','species_name' => 'schlippenbachii','common_name' => 'Royal azalea','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '5813','genus_name' => 'Rhodotypos','species_name' => 'scandens','common_name' => 'Jetbead','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '5814','genus_name' => 'Rhamnus','species_name' => 'serrata','common_name' => 'Sawleaf buckthorn','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '5815','genus_name' => 'Rhamnus','species_name' => 'smithii','common_name' => 'Smith\'s buckthorn','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '5817','genus_name' => 'Rhodomyrtus','species_name' => 'tomentosa','common_name' => 'Rose myrtle','growth_rate' => '','height_at_maturity' => '8'),
            array('id' => '5818','genus_name' => 'Rhus','species_name' => 'trilobata','common_name' => 'Skunkbush sumac','growth_rate' => 'Moderate','height_at_maturity' => '31'),
            array('id' => '5819','genus_name' => 'Rhus','species_name' => 'trichocarpa','common_name' => 'Japanese sumac','growth_rate' => '','height_at_maturity' => '19'),
            array('id' => '5820','genus_name' => 'Rhus','species_name' => 'hirta','common_name' => 'Staghorn sumac','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '5821','genus_name' => 'Rhamnus','species_name' => 'utilis','common_name' => 'Chinese buckthorn','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '5822','genus_name' => 'Rhododendron','species_name' => 'vaseyi','common_name' => 'Pinkshell azalea','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5823','genus_name' => 'Rhododendron','species_name' => 'viscosum','common_name' => 'Swamp azalea','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5824','genus_name' => 'Rhus','species_name' => 'virens','common_name' => 'Evergreen sumac','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '5825','genus_name' => 'Rhododendron','species_name' => 'welleslyanu','common_name' => 'Wellesly rhododendron','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '5827','genus_name' => 'Rhododendron','species_name' => 'yedoense v. poukhanense','common_name' => 'Korean azalea','growth_rate' => '','height_at_maturity' => '4'),
            array('id' => '5829','genus_name' => 'Ribes','species_name' => 'alpinum','common_name' => 'Alpine currant','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '5839','genus_name' => 'Ricinus','species_name' => 'communis','common_name' => 'Castorbean','growth_rate' => 'Fast','height_at_maturity' => '5'),
            array('id' => '5871','genus_name' => 'Ribes','species_name' => 'sanguineum','common_name' => 'Redflower currant','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '5884','genus_name' => 'Euphorbia','species_name' => 'abyssinica','common_name' => 'Desert candle','growth_rate' => 'Fast','height_at_maturity' => '31'),
            array('id' => '5885','genus_name' => 'Rosa','species_name' => 'abyssinica','common_name' => 'Ethiopian rose','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '5889','genus_name' => 'Robinia','species_name' => 'ambigu','common_name' => 'Pink locust','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '5891','genus_name' => 'Rosa','species_name' => 'banksiae','common_name' => 'Banksian rose','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '5892','genus_name' => 'Rosa','species_name' => 'blanda','common_name' => 'Smooth rose','growth_rate' => '','height_at_maturity' => '5'),
            array('id' => '5893','genus_name' => 'Roystonea','species_name' => 'borinquena','common_name' => 'Puerto rico royal palm','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '5903','genus_name' => 'Rollinia','species_name' => 'deliciosa','common_name' => 'biriba','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '5907','genus_name' => 'Roystonea','species_name' => 'elata','common_name' => 'Florida royalpalm','growth_rate' => 'Moderate','height_at_maturity' => '80'),
            array('id' => '5910','genus_name' => 'Rothmannia','species_name' => 'globosa','common_name' => 'September Bells','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '5912','genus_name' => 'Robinia','species_name' => 'hispida','common_name' => 'Bristly locust','growth_rate' => 'Fast','height_at_maturity' => '68'),
            array('id' => '5913','genus_name' => 'Robinia','species_name' => 'holdti','common_name' => 'Holdt\'s locust','growth_rate' => 'Fast','height_at_maturity' => '68'),
            array('id' => '5918','genus_name' => 'Robinia','species_name' => 'longilob','common_name' => 'Locust','growth_rate' => 'Fast','height_at_maturity' => '68'),
            array('id' => '5919','genus_name' => 'Robinia','species_name' => 'margarett','common_name' => 'Margarett\'s locust','growth_rate' => 'Fast','height_at_maturity' => '68'),
            array('id' => '5926','genus_name' => 'Rosa','species_name' => 'multiflora','common_name' => 'Multiflora rose','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '5927','genus_name' => 'Rollinia','species_name' => 'mucosa','common_name' => 'Wild sugar apple','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '5929','genus_name' => 'Robinia','species_name' => 'neomexicana','common_name' => 'New mexico locust','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '5934','genus_name' => 'Rosmarinus','species_name' => 'officinalis','common_name' => 'Rosemary','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '5938','genus_name' => 'Rondeletia','species_name' => 'pilosa','common_name' => 'Cordobancillo peludo','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '5939','genus_name' => 'Rondeletia','species_name' => 'portoricensis','common_name' => 'Juan tomas','growth_rate' => '','height_at_maturity' => '67'),
            array('id' => '5940','genus_name' => 'Robinia','species_name' => 'pseudoacacia','common_name' => 'Black locust','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '5941','genus_name' => 'Robinia','species_name' => 'pseudoacacia \'Frisia\'','common_name' => 'Golden Black Locust','growth_rate' => 'Moderate','height_at_maturity' => '9'),
            array('id' => '5942','genus_name' => 'Robinia','species_name' => 'pseudoacacia \'Purple Robe\'','common_name' => 'Black locust Purple Robe','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '5943','genus_name' => 'Robinia','species_name' => 'pseudoacacia \'Umbraculifera\'','common_name' => 'Robinia Mop Top','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '5944','genus_name' => 'Roystonea','species_name' => 'regia','common_name' => 'Florida royal palm','growth_rate' => 'Fast','height_at_maturity' => '82'),
            array('id' => '5946','genus_name' => 'Rosa','species_name' => 'rugosa','common_name' => 'Rugosa rose','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '5947','genus_name' => 'Rosa','species_name' => 'rubrifolia','common_name' => 'Redleaf rose','growth_rate' => '','height_at_maturity' => '7'),
            array('id' => '5949','genus_name' => 'Rosa','species_name' => 'setigera','common_name' => 'Climbing prarie rose','growth_rate' => '','height_at_maturity' => '4'),
            array('id' => '5952','genus_name' => 'Robinia','species_name' => 'slavinii \'Hillieri','common_name' => 'Rose Acacia','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '5954','genus_name' => 'Rosa','species_name' => 'spinosissima','common_name' => 'Scotch rose','growth_rate' => '','height_at_maturity' => '4'),
            array('id' => '5957','genus_name' => 'Rosa','species_name' => 'suffulta','common_name' => 'Prarie rose','growth_rate' => '','height_at_maturity' => '2'),
            array('id' => '5961','genus_name' => 'Robinia','species_name' => 'viscosa','common_name' => 'Clammy locust','growth_rate' => 'Fast','height_at_maturity' => '68'),
            array('id' => '5962','genus_name' => 'Rosa','species_name' => 'virginiana','common_name' => 'Virginia rose','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '5964','genus_name' => 'Rosa','species_name' => 'wichuraiana','common_name' => 'Memorial rose','growth_rate' => '','height_at_maturity' => '16'),
            array('id' => '6003','genus_name' => 'Rubus','species_name' => 'crataegifolius','common_name' => 'Korean raspberry','growth_rate' => '','height_at_maturity' => '8'),
            array('id' => '6025','genus_name' => 'Rubus','species_name' => 'fruticosus x idaeus','common_name' => 'Tayberry','growth_rate' => 'Fast','height_at_maturity' => '7'),
            array('id' => '6190','genus_name' => 'Santalum','species_name' => 'acuminatum','common_name' => 'Quandong','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '6191','genus_name' => 'Sassafras','species_name' => 'albidum','common_name' => 'Sassafras','growth_rate' => 'Moderate','height_at_maturity' => '75'),
            array('id' => '6192','genus_name' => 'Salix','species_name' => 'alaxensis','common_name' => 'Feltleaf willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6193','genus_name' => 'Salix','species_name' => 'alba','common_name' => 'White willow','growth_rate' => 'Fast','height_at_maturity' => '70'),
            array('id' => '6194','genus_name' => 'Salix','species_name' => 'alba \'Tristis\'','common_name' => 'Weeping white willow','growth_rate' => '','height_at_maturity' => '62'),
            array('id' => '6195','genus_name' => 'Salix','species_name' => 'amygdaloides','common_name' => 'Peachleaf willow','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '6196','genus_name' => 'Salix','species_name' => 'arizonica','common_name' => 'Arizona willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6197','genus_name' => 'Salix','species_name' => 'arbusculoides','common_name' => 'Littletree willow','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '6198','genus_name' => 'Salix','species_name' => 'argyrocarpa','common_name' => 'Labrador willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6199','genus_name' => 'Salix','species_name' => 'athabascensis','common_name' => 'Athabasca willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6200','genus_name' => 'Salix','species_name' => 'atrocinerea','common_name' => 'Rusty sallow','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '6201','genus_name' => 'Sambucus','species_name' => 'australasica','common_name' => 'Yellow Elderberry','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '6202','genus_name' => 'Salix','species_name' => 'aurita','common_name' => 'Eared willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6203','genus_name' => 'Salix','species_name' => 'sepulcrali','common_name' => 'Weeping willow','growth_rate' => 'Fast','height_at_maturity' => '70'),
            array('id' => '6204','genus_name' => 'Salix','species_name' => 'babylonica','common_name' => 'Babylon weeping willow','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '6205','genus_name' => 'Salix','species_name' => 'babylonica pekinensis','common_name' => 'Peking Willow','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '6206','genus_name' => 'Salix','species_name' => 'barclayi','common_name' => 'Barclay\'s willow','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '6207','genus_name' => 'Salix','species_name' => 'barrattiana','common_name' => 'Barratt\'s willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6208','genus_name' => 'Savia','species_name' => 'bahamensis','common_name' => 'Bahama maidenbush','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '6209','genus_name' => 'Salix','species_name' => 'bebbiana','common_name' => 'Bebb willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6210','genus_name' => 'Salix','species_name' => 'bebbi','common_name' => 'Bebb\'s hybrid willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6211','genus_name' => 'Salix','species_name' => 'bescheli','common_name' => 'Beschel\'s willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6212','genus_name' => 'Salix','species_name' => 'bonplandiana','common_name' => 'Bonpland willow','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '6213','genus_name' => 'Salix','species_name' => 'boothii','common_name' => 'Booth\'s willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6214','genus_name' => 'Salix','species_name' => 'brachycarpa','common_name' => 'Shortfruit willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6215','genus_name' => 'Salix','species_name' => 'breweri','common_name' => 'Brewer\'s willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6216','genus_name' => 'Sambucus','species_name' => 'canadensis','common_name' => 'Common elderberry','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '6217','genus_name' => 'Salix','species_name' => 'candida','common_name' => 'Sageleaf willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6218','genus_name' => 'Sapium','species_name' => 'caribaeum','common_name' => 'Gumtree','growth_rate' => 'Fast','height_at_maturity' => '58'),
            array('id' => '6219','genus_name' => 'Salix','species_name' => 'caroliniana','common_name' => 'Coastal plain willow','growth_rate' => 'Fast','height_at_maturity' => '28'),
            array('id' => '6220','genus_name' => 'Salix','species_name' => 'calcicola','common_name' => 'Woolly willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6221','genus_name' => 'Salix','species_name' => 'caprea','common_name' => 'Goat willow','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '6222','genus_name' => 'Sabal','species_name' => 'causiarum','common_name' => 'Puerto rico palmetto','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '6223','genus_name' => 'Salix','species_name' => 'cascadensis','common_name' => 'Cascade willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6225','genus_name' => 'Salix','species_name' => 'chrysocom','common_name' => 'Golden weeping Willow','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '6226','genus_name' => 'Salix','species_name' => 'cinerea','common_name' => 'Large gray willow','growth_rate' => 'Fast','height_at_maturity' => '23'),
            array('id' => '6228','genus_name' => 'Salix','species_name' => 'cordata','common_name' => 'Heartleaf willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6229','genus_name' => 'Saxegothaea','species_name' => 'conspicua','common_name' => 'Prince Albert\'s Yew','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '6230','genus_name' => 'Salix','species_name' => 'conifer','common_name' => 'Conifer willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6231','genus_name' => 'Salix','species_name' => 'commutata','common_name' => 'Undergreen willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6232','genus_name' => 'Salix','species_name' => 'cryptodont','common_name' => 'Smalltoothed willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6234','genus_name' => 'Salix','species_name' => 'delnortensis','common_name' => 'Del norte willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6235','genus_name' => 'Salix','species_name' => 'discolor','common_name' => 'Pussy willow','growth_rate' => 'Fast','height_at_maturity' => '19'),
            array('id' => '6237','genus_name' => 'Salix','species_name' => 'dieckian','common_name' => 'Dieck\'s willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6240','genus_name' => 'Sapindus','species_name' => 'saponaria ssp. Drummondii','common_name' => 'Western soapberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6241','genus_name' => 'Salix','species_name' => 'drummondiana','common_name' => 'Drummond\'s willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6242','genus_name' => 'Salix','species_name' => 'eastwoodiae','common_name' => 'Mountain willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6243','genus_name' => 'Salix','species_name' => 'ehrhartian','common_name' => 'Ehrhart\'s willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6244','genus_name' => 'Salix','species_name' => 'elaeagnos','common_name' => 'Elaeagnus willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6245','genus_name' => 'Santalum','species_name' => 'ellipticum','common_name' => 'Coastal sandalwood','growth_rate' => 'Slow','height_at_maturity' => '16'),
            array('id' => '6246','genus_name' => 'Salix','species_name' => 'eriocephala','common_name' => 'Diamond willow','growth_rate' => 'Fast','height_at_maturity' => '52'),
            array('id' => '6247','genus_name' => 'Sabal','species_name' => 'etonia','common_name' => 'Scrub palmetto','growth_rate' => 'Slow','height_at_maturity' => '9'),
            array('id' => '6248','genus_name' => 'Salix','species_name' => 'exigua','common_name' => 'Narrowleaf willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6249','genus_name' => 'Salix','species_name' => 'farrae','common_name' => 'Farr\'s willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6250','genus_name' => 'Salix','species_name' => 'floridana','common_name' => 'Florida willow','growth_rate' => 'Fast','height_at_maturity' => '12'),
            array('id' => '6251','genus_name' => 'Salix','species_name' => 'fluviatilis','common_name' => 'River willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6252','genus_name' => 'Salix','species_name' => 'fragilis','common_name' => 'Crack willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6253','genus_name' => 'Santalum','species_name' => 'freycinetianum','common_name' => 'Forest sandalwood','growth_rate' => 'Slow','height_at_maturity' => '35'),
            array('id' => '6254','genus_name' => 'Salix','species_name' => 'geyeriana','common_name' => 'Geyer\'s willow','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '6255','genus_name' => 'Salix','species_name' => 'glauca','common_name' => 'Grayleaf willow','growth_rate' => 'Fast','height_at_maturity' => '4'),
            array('id' => '6257','genus_name' => 'Salix','species_name' => 'glatfelter','common_name' => 'Glatfelter\'s willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6258','genus_name' => 'Salix','species_name' => 'gooddingii','common_name' => 'Goodding\'s willow','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '6260','genus_name' => 'Salix','species_name' => 'gray','common_name' => 'Gray\'s willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6261','genus_name' => 'Salix','species_name' => 'hastata','common_name' => 'Halberd willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6262','genus_name' => 'Santalum','species_name' => 'haleakalae','common_name' => 'Haleakala sandalwood','growth_rate' => 'Slow','height_at_maturity' => '13'),
            array('id' => '6263','genus_name' => 'Salix','species_name' => 'herbacea','common_name' => 'Snowbed willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6264','genus_name' => 'Salix','species_name' => 'hookeriana','common_name' => 'Hooker willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6265','genus_name' => 'Salix','species_name' => 'humboldtiana','common_name' => 'Humboldt\'s willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6266','genus_name' => 'Salix','species_name' => 'humilis','common_name' => 'Prairie willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6267','genus_name' => 'Salix','species_name' => 'interior','common_name' => 'Sandbar willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6268','genus_name' => 'Salix','species_name' => 'irrorata','common_name' => 'Dewystem willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6269','genus_name' => 'Salix','species_name' => 'jepsonii','common_name' => 'Jepson\'s willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6270','genus_name' => 'Salix','species_name' => 'koreensis','common_name' => 'Salix koreensis','growth_rate' => '','height_at_maturity' => '65'),
            array('id' => '6271','genus_name' => 'Salix','species_name' => 'koriyanagi','common_name' => 'Kori-yanagi','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6272','genus_name' => 'Sandoricum','species_name' => 'koetjape','common_name' => 'cottonfruit','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '6273','genus_name' => 'Santalum','species_name' => 'lanceolatum','common_name' => 'Plum Bush','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '6274','genus_name' => 'Salix','species_name' => 'lasiolepis','common_name' => 'Arroyo willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6275','genus_name' => 'Salix','species_name' => 'lucida ssp. lasiandra','common_name' => 'Pacific willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6276','genus_name' => 'Sapium','species_name' => 'laurifolium','common_name' => 'Hinchahuevos','growth_rate' => 'Fast','height_at_maturity' => '58'),
            array('id' => '6277','genus_name' => 'Salix','species_name' => 'laevigata','common_name' => 'Red willow','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '6278','genus_name' => 'Sapium','species_name' => 'laurocerasus','common_name' => 'Milktree','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '6280','genus_name' => 'Salix','species_name' => 'lemmonii','common_name' => 'Lemmon\'s willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6281','genus_name' => 'Salvia','species_name' => 'leucantha','common_name' => 'Mexican bush sage','growth_rate' => 'Fast','height_at_maturity' => '2'),
            array('id' => '6282','genus_name' => 'Salix','species_name' => 'ligulifolia','common_name' => 'Strapleaf willow','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '6283','genus_name' => 'Salix','species_name' => 'lucida','common_name' => 'Shining willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6284','genus_name' => 'Salix','species_name' => 'lutea','common_name' => 'Yellow willow','growth_rate' => 'Fast','height_at_maturity' => '16'),
            array('id' => '6285','genus_name' => 'Salix','species_name' => 'matsudana','common_name' => 'Corkscrew willow','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '6286','genus_name' => 'Salix','species_name' => 'matsudana \'Tortuosa\'','common_name' => 'Tortured willow','growth_rate' => 'Moderate','height_at_maturity' => '48'),
            array('id' => '6287','genus_name' => 'Salix','species_name' => 'maccalliana','common_name' => 'Mccalla\'s willow','growth_rate' => 'Fast','height_at_maturity' => '13'),
            array('id' => '6288','genus_name' => 'Salix','species_name' => 'prolixa','common_name' => 'MacKenzie\'s willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6289','genus_name' => 'Sabal','species_name' => 'mauritiiformis','common_name' => 'Tinidad palm','growth_rate' => 'Slow','height_at_maturity' => '65'),
            array('id' => '6291','genus_name' => 'Salix','species_name' => 'melanopsis','common_name' => 'Dusky willow','growth_rate' => 'Fast','height_at_maturity' => '23'),
            array('id' => '6292','genus_name' => 'Sabal','species_name' => 'mexicana','common_name' => 'Rio grande palmetto','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '6294','genus_name' => 'Sabal','species_name' => 'minor','common_name' => 'Dwarf palmetto','growth_rate' => 'Slow','height_at_maturity' => '9'),
            array('id' => '6295','genus_name' => 'Salix','species_name' => 'monticola','common_name' => 'Park willow','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '6296','genus_name' => 'Salix','species_name' => 'monochroma','common_name' => 'Onecolor willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6297','genus_name' => 'Sapindus','species_name' => 'mukorossi','common_name' => 'Chinese soapberry','growth_rate' => 'Moderate','height_at_maturity' => '58'),
            array('id' => '6298','genus_name' => 'Santalum','species_name' => 'murrayanum','common_name' => 'Bitter Quandong','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '6299','genus_name' => 'Salix','species_name' => 'myrtillifolia','common_name' => 'Blueberry willow','growth_rate' => 'Fast','height_at_maturity' => '8'),
            array('id' => '6300','genus_name' => 'Salix','species_name' => 'myricoides','common_name' => 'Bayberry willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6301','genus_name' => 'Salix','species_name' => 'nigra','common_name' => 'Black willow','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '6302','genus_name' => 'Salix','species_name' => 'niphoclada','common_name' => 'Barrenground willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6303','genus_name' => 'Sambucus','species_name' => 'nigra','common_name' => 'European black elderberry','growth_rate' => 'Slow','height_at_maturity' => '7'),
            array('id' => '6304','genus_name' => 'Sapindus','species_name' => 'oahuensis','common_name' => 'Lonomea','growth_rate' => 'Moderate','height_at_maturity' => '58'),
            array('id' => '6305','genus_name' => 'Salvadora','species_name' => 'oleoides','common_name' => 'Vann','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '6306','genus_name' => 'Salix','species_name' => 'orestera','common_name' => 'Sierra willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6307','genus_name' => 'Sabal','species_name' => 'palmetto','common_name' => 'Cabbage palmetto','growth_rate' => 'Slow','height_at_maturity' => '90'),
            array('id' => '6308','genus_name' => 'Salix','species_name' => 'paradoxa','common_name' => 'Salix paradoxa','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '6309','genus_name' => 'Sarcopygme','species_name' => 'pacifica','common_name' => 'uunu','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '6310','genus_name' => 'Santalum','species_name' => 'paniculatum','common_name' => 'Mountain sandalwood','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '6311','genus_name' => 'Salix','species_name' => 'pentandra','common_name' => 'Laurel willow','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '6312','genus_name' => 'Salix','species_name' => 'pendulin','common_name' => 'Wisconsin weeping willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6313','genus_name' => 'Salix','species_name' => 'petrophila','common_name' => 'Alpine willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6314','genus_name' => 'Salix','species_name' => 'pedicellaris','common_name' => 'Bog willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6315','genus_name' => 'Salix','species_name' => 'pellita','common_name' => 'Satiny willow','growth_rate' => 'Fast','height_at_maturity' => '16'),
            array('id' => '6316','genus_name' => 'Salix','species_name' => 'petiolaris','common_name' => 'Meadow willow','growth_rate' => 'Fast','height_at_maturity' => '23'),
            array('id' => '6317','genus_name' => 'Salix','species_name' => 'pease','common_name' => 'Salix x peasei','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6318','genus_name' => 'Salix','species_name' => 'planifolia','common_name' => 'Diamondleaf willow','growth_rate' => 'Fast','height_at_maturity' => '8'),
            array('id' => '6319','genus_name' => 'Salix','species_name' => 'princeps-ouray','common_name' => 'Ouray willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6320','genus_name' => 'Salix','species_name' => 'pseudomonticola','common_name' => 'False mountain willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6321','genus_name' => 'Salix','species_name' => 'pseudomyrsinites','common_name' => 'Firmleaf willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6322','genus_name' => 'Salix','species_name' => 'pulchra','common_name' => 'Tealeaf willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6323','genus_name' => 'Salix','species_name' => 'purpurea','common_name' => 'Purpleosier willow','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '6324','genus_name' => 'Salix','species_name' => 'pyrifolia','common_name' => 'Balsam willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6325','genus_name' => 'Sambucus','species_name' => 'racemosa','common_name' => 'Red elderberry','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '6326','genus_name' => 'Salix','species_name' => 'richardsonii','common_name' => 'Richardson\'s willow','growth_rate' => 'Slow','height_at_maturity' => '53'),
            array('id' => '6327','genus_name' => 'Salix','species_name' => 'rubell','common_name' => 'Rubella willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6328','genus_name' => 'Salix','species_name' => 'ruben','common_name' => 'Hybrid crack willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6329','genus_name' => 'Sapindus','species_name' => 'saponaria','common_name' => 'Wingleaf soapberry','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '6330','genus_name' => 'Sapium','species_name' => 'sabiferum','common_name' => 'Chinese Popcorn Tree','growth_rate' => 'Moderate','height_at_maturity' => '9'),
            array('id' => '6332','genus_name' => 'Salix','species_name' => 'scouleriana','common_name' => 'Scouler willow','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '6336','genus_name' => 'Salix','species_name' => 'sericea','common_name' => 'Silky willow','growth_rate' => 'Fast','height_at_maturity' => '12'),
            array('id' => '6337','genus_name' => 'Salix','species_name' => 'serissima','common_name' => 'Autumn willow','growth_rate' => 'Fast','height_at_maturity' => '17'),
            array('id' => '6338','genus_name' => 'Salix','species_name' => 'sessilifolia','common_name' => 'Northwest sandbar willow','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '6339','genus_name' => 'Savia','species_name' => 'sessiliflora','common_name' => 'Amansa guapo','growth_rate' => '','height_at_maturity' => '27'),
            array('id' => '6340','genus_name' => 'Sarcomelicope','species_name' => 'simplicifolia','common_name' => 'Big yellowwood','growth_rate' => 'Moderate','height_at_maturity' => '59'),
            array('id' => '6341','genus_name' => 'Salix','species_name' => 'sitchensis','common_name' => 'Sitka willow','growth_rate' => 'Fast','height_at_maturity' => '23'),
            array('id' => '6342','genus_name' => 'Salix','species_name' => 'smithian','common_name' => 'Silky-leaf osier','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6343','genus_name' => 'Salix','species_name' => 'solheimi','common_name' => 'Solheim\'s willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6346','genus_name' => 'Salix','species_name' => 'taxifolia','common_name' => 'Yewleaf willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6348','genus_name' => 'Salix','species_name' => 'triandra','common_name' => 'Almond-leaved Willow','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '6349','genus_name' => 'Samanea','species_name' => 'tubulosa','common_name' => 'Rain tree','growth_rate' => '','height_at_maturity' => '196'),
            array('id' => '6350','genus_name' => 'Salix','species_name' => 'tweedyi','common_name' => 'Tweedy\'s willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6352','genus_name' => 'Salix','species_name' => 'uva-ursi','common_name' => 'Bearberry willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6353','genus_name' => 'Salix','species_name' => 'vestita','common_name' => 'Rock willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6355','genus_name' => 'Salix','species_name' => 'viminalis','common_name' => 'Basket willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6356','genus_name' => 'Salix','species_name' => 'waghorne','common_name' => 'Waghorn\'s willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6357','genus_name' => 'Salix','species_name' => 'wolfii','common_name' => 'Wolf\'s willow','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '6361','genus_name' => 'Schefflera','species_name' => 'arboricola','common_name' => 'Dwarf Umbrella Tree','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '6362','genus_name' => 'Schoepfia','species_name' => 'arenaria','common_name' => 'Arana','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '6364','genus_name' => 'Schotia','species_name' => 'brachypetala','common_name' => 'African Walnut','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6368','genus_name' => 'Scaevola','species_name' => 'chamissoniana','common_name' => 'Naupaka kuahiwi','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '6369','genus_name' => 'Schaefferia','species_name' => 'cuneifolia','common_name' => 'Desert yaupon','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '6370','genus_name' => 'Schefflera','species_name' => 'elegantissima','common_name' => 'Falsa aralia','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '6372','genus_name' => 'Schaefferia','species_name' => 'frutescens','common_name' => 'Florida boxwood','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '6373','genus_name' => 'Scaevola','species_name' => 'gaudichaudiana','common_name' => 'Mountain naupaka','growth_rate' => '','height_at_maturity' => '16'),
            array('id' => '6376','genus_name' => 'Schefflera','species_name' => 'gleasonii','common_name' => 'Yuquilla','growth_rate' => 'Fast','height_at_maturity' => '49'),
            array('id' => '6381','genus_name' => 'Scyphiphora','species_name' => 'hydrophylacea','common_name' => 'kuat','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '6383','genus_name' => 'Schinus','species_name' => 'lentiscifolia','common_name' => 'Paraguay Peppercorn','growth_rate' => 'Slow','height_at_maturity' => '9'),
            array('id' => '6385','genus_name' => 'Schinus','species_name' => 'longifolia','common_name' => 'Longleaf peppertree','growth_rate' => 'Fast','height_at_maturity' => '55'),
            array('id' => '6387','genus_name' => 'Schinus','species_name' => 'molle','common_name' => 'California peppertree','growth_rate' => 'Fast','height_at_maturity' => '35'),
            array('id' => '6388','genus_name' => 'Schefflera','species_name' => 'morototoni','common_name' => 'Matchwood','growth_rate' => 'Fast','height_at_maturity' => '56'),
            array('id' => '6390','genus_name' => 'Schoepfia','species_name' => 'obovata','common_name' => 'White beefwood','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '6391','genus_name' => 'Schleichera','species_name' => 'oleosa','common_name' => 'Ceylon Oak','growth_rate' => 'Moderate','height_at_maturity' => '17'),
            array('id' => '6392','genus_name' => 'Schizomeria','species_name' => 'ovata','common_name' => 'Cherry Birch','growth_rate' => 'Moderate','height_at_maturity' => '116'),
            array('id' => '6394','genus_name' => 'Schizolobium','species_name' => 'parahybum','common_name' => 'Brazilian firetree','growth_rate' => '','height_at_maturity' => '98'),
            array('id' => '6395','genus_name' => 'Schinus','species_name' => 'polygama','common_name' => 'Hardee peppertree','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '6397','genus_name' => 'Scaevola','species_name' => 'procera','common_name' => 'Forest naupaka','growth_rate' => '','height_at_maturity' => '14'),
            array('id' => '6398','genus_name' => 'Scolopia','species_name' => 'saeva','common_name' => 'Kwangtung Scolopia','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '6401','genus_name' => 'Schima','species_name' => 'superba','common_name' => 'Mu he','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '6402','genus_name' => 'Schinus','species_name' => 'terebinthifolia','common_name' => 'Brazilian peppertree','growth_rate' => 'Moderate','height_at_maturity' => '55'),
            array('id' => '6403','genus_name' => 'Sciadopitys','species_name' => 'verticillata','common_name' => 'Umbrella pine','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '6405','genus_name' => 'Senna','species_name' => 'alata','common_name' => 'Emperor\'s candlesticks','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6406','genus_name' => 'Senna','species_name' => 'armata','common_name' => 'Desertsenna','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '6407','genus_name' => 'Senna','species_name' => 'atomaria','common_name' => 'Flor de san jose','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '6408','genus_name' => 'Senna','species_name' => 'bacillaris','common_name' => 'Whitebark senna','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '6409','genus_name' => 'Senna','species_name' => 'bicapsularis','common_name' => 'Christmasbush','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '6412','genus_name' => 'Senna','species_name' => 'corymbosa','common_name' => 'Argentine senna','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '6414','genus_name' => 'Senna','species_name' => 'didymobotrya','common_name' => 'African senna','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '6416','genus_name' => 'Senna','species_name' => 'floribund','common_name' => 'Floribunda senna','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '6417','genus_name' => 'Serissa','species_name' => 'foetida','common_name' => 'Snowrose','growth_rate' => '','height_at_maturity' => '4'),
            array('id' => '6419','genus_name' => 'Senna','species_name' => 'gaudichaudii','common_name' => 'Gaudichaud\'s senna','growth_rate' => 'Fast','height_at_maturity' => '2'),
            array('id' => '6420','genus_name' => 'Sequoiadendron','species_name' => 'giganteum','common_name' => 'Giant sequoia','growth_rate' => 'Slow','height_at_maturity' => '200'),
            array('id' => '6421','genus_name' => 'Searsia','species_name' => 'glutinosa','common_name' => 'Searsia glutinosa','growth_rate' => 'Fast','height_at_maturity' => '88'),
            array('id' => '6422','genus_name' => 'Sesbania','species_name' => 'grandiflora','common_name' => 'Vegetable hummingbird','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '6424','genus_name' => 'Senna','species_name' => 'macranthera','common_name' => 'Manduirana','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '6425','genus_name' => 'Senna','species_name' => 'mexicana','common_name' => 'Mexican senna','growth_rate' => 'Fast','height_at_maturity' => '4'),
            array('id' => '6426','genus_name' => 'Senna','species_name' => 'monozyx','common_name' => 'Andean senna','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '6429','genus_name' => 'Senna','species_name' => 'multiglandulosa','common_name' => 'Glandular senna','growth_rate' => 'Fast','height_at_maturity' => '4'),
            array('id' => '6430','genus_name' => 'Senna','species_name' => 'multijuga','common_name' => 'False sicklepod','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '6432','genus_name' => 'Senna','species_name' => 'nitida','common_name' => 'Hediondilla','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '6433','genus_name' => 'Senna','species_name' => 'pendula','common_name' => 'Valamuerto','growth_rate' => 'Fast','height_at_maturity' => '13'),
            array('id' => '6434','genus_name' => 'Senna','species_name' => 'pistaccifolia','common_name' => 'Alcaparro','growth_rate' => 'Moderate','height_at_maturity' => '39'),
            array('id' => '6436','genus_name' => 'Senna','species_name' => 'polyantha','common_name' => 'Senna polyantha','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '6437','genus_name' => 'Senna','species_name' => 'polyphylla','common_name' => 'Retama prieta','growth_rate' => 'Slow','height_at_maturity' => '17'),
            array('id' => '6438','genus_name' => 'Senna','species_name' => 'racemosa','common_name' => 'Limestone senna','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '6439','genus_name' => 'Serenoa','species_name' => 'repens','common_name' => 'Saw palmetto','growth_rate' => 'Slow','height_at_maturity' => '7'),
            array('id' => '6440','genus_name' => 'Senecio','species_name' => 'salignus','common_name' => 'Willow ragwort','growth_rate' => 'Fast','height_at_maturity' => '2'),
            array('id' => '6442','genus_name' => 'Sequoia','species_name' => 'sempervirens','common_name' => 'Coast redwood','growth_rate' => 'Fast','height_at_maturity' => '250'),
            array('id' => '6443','genus_name' => 'Sesbania','species_name' => 'sesban','common_name' => 'Egyptian riverhemp','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '6444','genus_name' => 'Senna','species_name' => 'septemtrionalis','common_name' => 'Arsenic bush','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '6445','genus_name' => 'Senna','species_name' => 'sulfurea','common_name' => 'Smooth senna','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '6446','genus_name' => 'Senna','species_name' => 'surattensis','common_name' => 'Glossy shower','growth_rate' => 'Fast','height_at_maturity' => '14'),
            array('id' => '6451','genus_name' => 'Senna','species_name' => 'wislizeni','common_name' => 'Wislizenus\' senna','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '6452','genus_name' => 'Shepherdia','species_name' => 'argentea','common_name' => 'Silver buffaloberry','growth_rate' => 'Fast','height_at_maturity' => '18'),
            array('id' => '6453','genus_name' => 'Shepherdia','species_name' => 'canadensis','common_name' => 'Russet buffaloberry','growth_rate' => 'Slow','height_at_maturity' => '9'),
            array('id' => '6461','genus_name' => 'Sideroxylon','species_name' => 'cubense','common_name' => 'Espejuelo','growth_rate' => '','height_at_maturity' => '83'),
            array('id' => '6464','genus_name' => 'Sida','species_name' => 'fallax','common_name' => 'Yellow llima','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '6465','genus_name' => 'Sideroxylon','species_name' => 'foetidissimum','common_name' => 'Sideroxylon foetidissimum','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '6466','genus_name' => 'Simarouba','species_name' => 'glauca','common_name' => 'Paradise tree','growth_rate' => 'Moderate','height_at_maturity' => '50')
        );

        Tree::insert($trees);

        $seeder = new TreeSpeciesSeeder9;
        $seeder->run();
    }
}
