<?php

namespace Database\Seeders\TreeSpecies;

use App\Models\Trees\Tree;
use Illuminate\Database\Seeder;

class TreeSpeciesSeeder2 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $trees = array(
            array('id' => '1166','genus_name' => 'Calyptranthes','species_name' => 'krugii','common_name' => 'Limoncillo','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1167','genus_name' => 'Carya','species_name' => 'laciniosa','common_name' => 'Shellbark hickory','growth_rate' => 'Slow','height_at_maturity' => '100'),
            array('id' => '1169','genus_name' => 'Carpinus','species_name' => 'laxiflora','common_name' => 'Carpinus laxiflora','growth_rate' => '','height_at_maturity' => '49'),
            array('id' => '1170','genus_name' => 'Carya','species_name' => 'x laneyi','common_name' => 'Laney\'s hickory','growth_rate' => '','height_at_maturity' => '105'),
            array('id' => '1171','genus_name' => 'Cassia','species_name' => 'leptophylla','common_name' => 'Gold medallion tree','growth_rate' => '','height_at_maturity' => '35'),
            array('id' => '1173','genus_name' => 'Carya','species_name' => 'x lecontei','common_name' => 'Leconte\'s hickory','growth_rate' => 'Slow','height_at_maturity' => '105'),
            array('id' => '1174','genus_name' => 'Casuarina','species_name' => 'lepidophloia','common_name' => 'Belah','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '1175','genus_name' => 'Callistemon','species_name' => 'linearifolius','common_name' => 'Netted Bottle Brush','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '1176','genus_name' => 'Callistemon','species_name' => 'linearis','common_name' => 'Narrow-leaved Bottlebrush','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '1177','genus_name' => 'Catalpa','species_name' => 'longissima','common_name' => 'Haitian catalpa','growth_rate' => 'Fast','height_at_maturity' => '56'),
            array('id' => '1178','genus_name' => 'Calliandra','species_name' => 'locoensis','common_name' => 'Rio Loc stickpea','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '1179','genus_name' => 'Calophyllum','species_name' => 'longifolium','common_name' => 'Santa maria','growth_rate' => 'Moderate','height_at_maturity' => '63'),
            array('id' => '1181','genus_name' => 'Calyptranthes','species_name' => 'luquillensis','common_name' => 'Luquillo forest lidflower','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1182','genus_name' => 'Canarium','species_name' => 'luzonicum','common_name' => 'Manila elemi','growth_rate' => 'Fast','height_at_maturity' => '98'),
            array('id' => '1183','genus_name' => 'Carya','species_name' => 'x ludoviciana','common_name' => 'Hickory','growth_rate' => 'Slow','height_at_maturity' => '105'),
            array('id' => '1184','genus_name' => 'Callistemon','species_name' => 'macropunctatus','common_name' => 'Scarlet Bottlebrush','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '1185','genus_name' => 'Callitris','species_name' => 'macleayana','common_name' => 'Brush Cypress-pine','growth_rate' => 'Slow','height_at_maturity' => '40'),
            array('id' => '1186','genus_name' => 'Calliandra','species_name' => 'magdalenae','common_name' => 'Calliandra magdalenae','growth_rate' => 'Fast','height_at_maturity' => '26'),
            array('id' => '1187','genus_name' => 'Calyptranthes','species_name' => 'martorellii','common_name' => 'Martorell\'s lidflower','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1190','genus_name' => 'Caesalpinia','species_name' => 'mexicana','common_name' => 'Mexican holdback','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '1191','genus_name' => 'Calliandra','species_name' => 'medellinensis','common_name' => 'Calliandra medellinensis','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '1193','genus_name' => 'Capparis','species_name' => 'mitchellii','common_name' => 'Wild Orange','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '1194','genus_name' => 'Caryota','species_name' => 'mitis','common_name' => 'Burmese fishtail palm','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1195','genus_name' => 'Castanea','species_name' => 'mollissima','common_name' => 'Chinese chestnut','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '1196','genus_name' => 'Callitris','species_name' => 'monticola','common_name' => 'Dwarf Cypress-pine','growth_rate' => 'Moderate','height_at_maturity' => '2'),
            array('id' => '1197','genus_name' => 'Caesalpinia','species_name' => 'monensis','common_name' => 'Black nicker','growth_rate' => 'Fast','height_at_maturity' => '37'),
            array('id' => '1198','genus_name' => 'Carya','species_name' => 'myristiciformis','common_name' => 'Nutmeg hickory','growth_rate' => 'Slow','height_at_maturity' => '105'),
            array('id' => '1199','genus_name' => 'Cassia','species_name' => 'nemophila','common_name' => 'Australian senna','growth_rate' => 'Fast','height_at_maturity' => '51'),
            array('id' => '1202','genus_name' => 'Castanea','species_name' => 'x neglecta','common_name' => 'Neglected chesnut','growth_rate' => 'Moderate','height_at_maturity' => '49'),
            array('id' => '1204','genus_name' => 'Cassia','species_name' => 'nodosa','common_name' => 'Balayong','growth_rate' => 'Fast','height_at_maturity' => '80'),
            array('id' => '1205','genus_name' => 'Carya','species_name' => 'x nussbaumeri','common_name' => 'Nussbaumer\'s hickory','growth_rate' => 'Slow','height_at_maturity' => '105'),
            array('id' => '1206','genus_name' => 'Casuarina','species_name' => 'obesa','common_name' => 'Swamp Sheoak','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '1207','genus_name' => 'Callitris','species_name' => 'oblonga','common_name' => 'South Esk Pine','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '1210','genus_name' => 'Cananga','species_name' => 'odorata','common_name' => 'Ilang-Ilang','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '1211','genus_name' => 'Capparis','species_name' => 'odoratissima','common_name' => 'Olivo santo','growth_rate' => 'Moderate','height_at_maturity' => '47'),
            array('id' => '1212','genus_name' => 'Canthium','species_name' => 'odoratum','common_name' => 'Alahe\'e','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '1213','genus_name' => 'Carya','species_name' => 'ovata','common_name' => 'Shagbark hickory','growth_rate' => 'Slow','height_at_maturity' => '75'),
            array('id' => '1214','genus_name' => 'Carya','species_name' => 'ovalis','common_name' => 'Red hickory','growth_rate' => 'Slow','height_at_maturity' => '105'),
            array('id' => '1215','genus_name' => 'Catalpa','species_name' => 'ovata','common_name' => 'Chinese catalpa','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '1216','genus_name' => 'Canarium','species_name' => 'ovatum','common_name' => 'Pili Nut','growth_rate' => '','height_at_maturity' => '66'),
            array('id' => '1217','genus_name' => 'Carya','species_name' => 'pallida','common_name' => 'Sand hickory','growth_rate' => 'Slow','height_at_maturity' => '105'),
            array('id' => '1218','genus_name' => 'Callistemon','species_name' => 'pallidus','common_name' => 'Lemon bottlebrush','growth_rate' => 'Fast','height_at_maturity' => '7'),
            array('id' => '1219','genus_name' => 'Calyptranthes','species_name' => 'pallens','common_name' => 'Pale lidflower','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '1220','genus_name' => 'Carica','species_name' => 'papaya','common_name' => 'Papaya','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '1221','genus_name' => 'Caesalpinia','species_name' => 'parryi','common_name' => 'Parry\'s holdback','growth_rate' => 'Fast','height_at_maturity' => '37'),
            array('id' => '1222','genus_name' => 'Caesalpinia','species_name' => 'pauciflora','common_name' => 'Fewflower holdback','growth_rate' => 'Fast','height_at_maturity' => '37'),
            array('id' => '1223','genus_name' => 'Callistemon','species_name' => 'pauciflorus','common_name' => 'Desert Bottlebrush','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '1225','genus_name' => 'Casuarina','species_name' => 'pauper','common_name' => 'Black Sheoak','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '1226','genus_name' => 'Callistemon','species_name' => 'pendula','common_name' => 'Bottlebrush','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '1227','genus_name' => 'Calyptranthes','species_name' => 'peduncularis','common_name' => 'Maricao lidflower','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1228','genus_name' => 'Caesalpinia','species_name' => 'peltophoroides','common_name' => 'Sibipiruna','growth_rate' => 'Fast','height_at_maturity' => '37'),
            array('id' => '1229','genus_name' => 'Caesalpinia','species_name' => 'phyllanthoides','common_name' => 'Wait-a-bit vine','growth_rate' => 'Fast','height_at_maturity' => '37'),
            array('id' => '1230','genus_name' => 'Callistemon','species_name' => 'phoeniceus','common_name' => 'Lesser Bottlebrush','growth_rate' => 'Fast','height_at_maturity' => '3'),
            array('id' => '1231','genus_name' => 'Callistemon','species_name' => 'pinifolius','common_name' => 'Pine-leaved Bottlebrush','growth_rate' => 'Moderate','height_at_maturity' => '2'),
            array('id' => '1232','genus_name' => 'Callistemon','species_name' => 'polandii','common_name' => 'Gold-tipped Bottlebrush','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '1233','genus_name' => 'Caesalpinia','species_name' => 'portoricensis','common_name' => 'Brown nicker','growth_rate' => 'Fast','height_at_maturity' => '37'),
            array('id' => '1234','genus_name' => 'Calyptranthes','species_name' => 'portoricensis','common_name' => 'Puerto rico lidflower','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1236','genus_name' => 'Callitris','species_name' => 'preissii','common_name' => 'Rottnest Island Pine','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '1237','genus_name' => 'Castanea','species_name' => 'pumila','common_name' => 'Alleghany chinkapin','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '1238','genus_name' => 'Caesalpinia','species_name' => 'pulcherrima','common_name' => 'Pride-of-barbados','growth_rate' => 'Fast','height_at_maturity' => '37'),
            array('id' => '1239','genus_name' => 'Carya','species_name' => 'pumilia','common_name' => 'Carya','growth_rate' => 'Slow','height_at_maturity' => '105'),
            array('id' => '1240','genus_name' => 'Calliandra','species_name' => 'purpurea','common_name' => 'Purple stickpea','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '1241','genus_name' => 'Caragana','species_name' => 'pygmaea','common_name' => 'Dwarf pea tree','growth_rate' => '','height_at_maturity' => '4'),
            array('id' => '1242','genus_name' => 'Cariniana','species_name' => 'pyriformis','common_name' => 'Cariniana pyriformis','growth_rate' => 'Slow','height_at_maturity' => '66'),
            array('id' => '1243','genus_name' => 'Camellia','species_name' => 'reticulata','common_name' => 'Chinese Camellia','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '1244','genus_name' => 'Carmona','species_name' => 'retusa','common_name' => 'Scorpionbush','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '1246','genus_name' => 'Callitris','species_name' => 'rhomboidea','common_name' => 'Oyster Bay Pine','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1247','genus_name' => 'Calyptronoma','species_name' => 'rivalis','common_name' => 'Puerto rico manac','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '1248','genus_name' => 'Callistemon','species_name' => 'rigidus','common_name' => 'Stiff bottlebrush','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '1249','genus_name' => 'Cassia','species_name' => 'javanica','common_name' => 'Apple blossom','growth_rate' => 'Fast','height_at_maturity' => '35'),
            array('id' => '1250','genus_name' => 'Camellia','species_name' => 'sasanqua','common_name' => 'Sasanqua camellia','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1251','genus_name' => 'Castanea','species_name' => 'sativa','common_name' => 'Sweet chestnut','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '1253','genus_name' => 'Capparis','species_name' => 'sandwichiana','common_name' => 'Native caper','growth_rate' => 'Slow','height_at_maturity' => '23'),
            array('id' => '1254','genus_name' => 'Callistemon','species_name' => 'salignus','common_name' => 'White bottlebrush','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '1256','genus_name' => 'Carya','species_name' => 'x schneckii','common_name' => 'Schneck\'s hickory','growth_rate' => 'Slow','height_at_maturity' => '105'),
            array('id' => '1258','genus_name' => 'Callicoma','species_name' => 'serratifolia','common_name' => 'Butterwood','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '1260','genus_name' => 'Senna','species_name' => 'siamea','common_name' => 'Siamese cassia','growth_rate' => 'Fast','height_at_maturity' => '67'),
            array('id' => '1261','genus_name' => 'Calophyllum','species_name' => 'sil','common_name' => 'Touriga','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1262','genus_name' => 'Camellia','species_name' => 'sinensis','common_name' => 'Tea','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1263','genus_name' => 'Calyptranthes','species_name' => 'sintenisii','common_name' => 'Limoncillo del monte','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1264','genus_name' => 'Catalpa','species_name' => 'speciosa','common_name' => 'Northern catalpa','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '1265','genus_name' => 'Callistemon','species_name' => 'speciosus','common_name' => 'Callistemon speciosus','growth_rate' => 'Moderate','height_at_maturity' => '49'),
            array('id' => '1266','genus_name' => 'Caesalpinia','species_name' => 'spinosa','common_name' => 'Spiny holdback','growth_rate' => 'Fast','height_at_maturity' => '37'),
            array('id' => '1267','genus_name' => 'Senna','species_name' => 'spectabilis','common_name' => 'Casia amarilla','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '1268','genus_name' => 'Cassia','species_name' => 'spectabilis','common_name' => 'Cassia spectabilis','growth_rate' => 'Fast','height_at_maturity' => '49'),
            array('id' => '1269','genus_name' => 'Carissa','species_name' => 'spinarum','common_name' => 'Conkerberry','growth_rate' => 'Fast','height_at_maturity' => '21'),
            array('id' => '1270','genus_name' => 'Casuarina','species_name' => 'stricta','common_name' => 'Coast beefwood','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '1272','genus_name' => 'Calliandra','species_name' => 'surinamensis','common_name' => 'Surinamese stickpea','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '1274','genus_name' => 'Casearia','species_name' => 'sylvestris','common_name' => 'Crackopen','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '1275','genus_name' => 'Carya','species_name' => 'texana','common_name' => 'Black hickory','growth_rate' => 'Slow','height_at_maturity' => '105'),
            array('id' => '1276','genus_name' => 'Calyptranthes','species_name' => 'thomasiana','common_name' => 'Thomas\' lidflower','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1277','genus_name' => 'Carya','species_name' => 'alba','common_name' => 'Mockernut hickory','growth_rate' => 'Slow','height_at_maturity' => '85'),
            array('id' => '1278','genus_name' => 'Calyptranthes','species_name' => 'triflora','common_name' => 'Threeblossom lidflower','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1279','genus_name' => 'Carpinus','species_name' => 'tschonoskii','common_name' => 'Asian hornbeam','growth_rate' => '','height_at_maturity' => '35'),
            array('id' => '1281','genus_name' => 'Caryota','species_name' => 'urens','common_name' => 'Wine palm','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '1282','genus_name' => 'Callitris','species_name' => 'verrucosa','common_name' => 'Scrub Cypress-pine','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '1283','genus_name' => 'Callistemon','species_name' => 'viminalis','common_name' => 'Weeping bottlebrush','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '1284','genus_name' => 'Callistemon','species_name' => 'viridiflorus','common_name' => 'Green Bottlebrush','growth_rate' => 'Fast','height_at_maturity' => '2'),
            array('id' => '1285','genus_name' => 'Caesalpinia','species_name' => 'virgata','common_name' => 'Wand holdback','growth_rate' => 'Fast','height_at_maturity' => '37'),
            array('id' => '1286','genus_name' => 'Calluna','species_name' => 'vulgaris','common_name' => 'Heather','growth_rate' => 'Slow','height_at_maturity' => '2'),
            array('id' => '1287','genus_name' => 'Canella','species_name' => 'winterana','common_name' => 'Cinnamon bark','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1288','genus_name' => 'Calyptranthes','species_name' => 'woodburyi','common_name' => 'Woodbury\'s lidflower','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1290','genus_name' => 'Cassine','species_name' => 'xylocarpa','common_name' => 'Marbletree','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '1291','genus_name' => 'Calyptranthes','species_name' => 'zuzygium','common_name' => 'Myrtle of the river','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1292','genus_name' => 'Ceiba','species_name' => 'acuminata','common_name' => 'Kapok trees','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '1295','genus_name' => 'Ceratopetalum','species_name' => 'apetalum','common_name' => 'Coachwood','growth_rate' => 'Moderate','height_at_maturity' => '82'),
            array('id' => '1296','genus_name' => 'Ceanothus','species_name' => 'arboreus','common_name' => 'Feltleaf ceanthous','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1297','genus_name' => 'Ceanothus','species_name' => 'x arcuatus','common_name' => 'Arching ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1298','genus_name' => 'Cedrus','species_name' => 'atlantica','common_name' => 'Atlas cedar','growth_rate' => 'Moderate','height_at_maturity' => '93'),
            array('id' => '1299','genus_name' => 'Cedrus','species_name' => 'atlantica v. glauca','common_name' => 'Blue atlas cedar','growth_rate' => 'Moderate','height_at_maturity' => '119'),
            array('id' => '1300','genus_name' => 'Celtis','species_name' => 'australis','common_name' => 'European hackberry','growth_rate' => 'Fast','height_at_maturity' => '58'),
            array('id' => '1301','genus_name' => 'Cestrum','species_name' => 'aurantiacum','common_name' => 'Orange jessamine','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '1302','genus_name' => 'Ceanothus','species_name' => 'x bakeri','common_name' => 'Baker\'s ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1303','genus_name' => 'Cercocarpus','species_name' => 'montanus v glaber','common_name' => 'Birchleaf mountain mahogany','growth_rate' => 'Moderate','height_at_maturity' => '21'),
            array('id' => '1304','genus_name' => 'Cercis','species_name' => 'canadensis','common_name' => 'Eastern redbud','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1306','genus_name' => 'Celtis','species_name' => 'caudata','common_name' => 'Celtis caudata','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '1309','genus_name' => 'Ceanothus','species_name' => 'cordulatus','common_name' => 'Whitethorn ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1310','genus_name' => 'Ceanothus','species_name' => 'connivens','common_name' => 'Trailing buckbrush','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1311','genus_name' => 'Ceanothus','species_name' => 'crassifolius','common_name' => 'Hoaryleaf ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1312','genus_name' => 'Ceanothus','species_name' => 'cuneatus','common_name' => 'Buckbrush','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1313','genus_name' => 'Ceanothus','species_name' => 'cyaneus','common_name' => 'San diego buckbrush','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1314','genus_name' => 'Cedrus','species_name' => 'deodara','common_name' => 'Deodar cedar','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '1315','genus_name' => 'Ceanothus','species_name' => 'dentatus','common_name' => 'Sandscrub ceanothus','growth_rate' => 'Fast','height_at_maturity' => '22'),
            array('id' => '1316','genus_name' => 'Ceanothus','species_name' => 'divergens','common_name' => 'Calistoga ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1318','genus_name' => 'Cestrum','species_name' => 'diurnum','common_name' => 'Day jessamine','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '1319','genus_name' => 'Cedrela','species_name' => 'dugesii','common_name' => 'Cedrela dugesii','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '1322','genus_name' => 'Ceanothus','species_name' => 'fendleri','common_name' => 'Fendler\'s ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1323','genus_name' => 'Ceanothus','species_name' => 'ferrisiae','common_name' => 'Coyote ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1325','genus_name' => 'Parkinsonia','species_name' => 'florida','common_name' => 'Blue paloverde','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '1326','genus_name' => 'Ceanothus','species_name' => 'x flexilis','common_name' => 'Flexible ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1327','genus_name' => 'Cephalotaxus','species_name' => 'fortunei','common_name' => 'Chinese Plum Yew','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '1330','genus_name' => 'Ceanothus','species_name' => 'greggii','common_name' => 'Desert ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1331','genus_name' => 'Ceanothus','species_name' => 'griseus','common_name' => 'Carmel ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1332','genus_name' => 'Ceratopetalum','species_name' => 'gummiferum','common_name' => 'NS Wales Christmas Bush','growth_rate' => 'Moderate','height_at_maturity' => '16'),
            array('id' => '1333','genus_name' => 'Cephalotaxus','species_name' => 'harringtonii','common_name' => 'Cowtail Pine','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '1334','genus_name' => 'Ceanothus','species_name' => 'herbaceus','common_name' => 'Jersey tea','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1338','genus_name' => 'Celtis','species_name' => 'iguanaea','common_name' => 'Iguana hackberry','growth_rate' => 'Fast','height_at_maturity' => '83'),
            array('id' => '1339','genus_name' => 'Ceanothus','species_name' => 'impressus','common_name' => 'Santa barbara ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1340','genus_name' => 'Ceanothus','species_name' => 'integerrimus','common_name' => 'Deer brush','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1341','genus_name' => 'Cercocarpus','species_name' => 'intricatus','common_name' => 'Littleleaf mahogany','growth_rate' => 'Moderate','height_at_maturity' => '21'),
            array('id' => '1342','genus_name' => 'Ceanothus','species_name' => 'incanus','common_name' => 'Coast whitethorn','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1343','genus_name' => 'Cercidiphyllum','species_name' => 'japonicum','common_name' => 'Katsura tree','growth_rate' => 'Moderate','height_at_maturity' => '43'),
            array('id' => '1344','genus_name' => 'Ceanothus','species_name' => 'jepsonii','common_name' => 'Jepson\'s ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1345','genus_name' => 'Celtis','species_name' => 'jessoensis','common_name' => 'Japanese hackberry','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '1346','genus_name' => 'Celtis','species_name' => 'laevigata','common_name' => 'Sugarberry','growth_rate' => 'Moderate','height_at_maturity' => '80'),
            array('id' => '1348','genus_name' => 'Cestrum','species_name' => 'laurifolium','common_name' => 'Galan del monte','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '1349','genus_name' => 'Cercocarpus','species_name' => 'ledifolius','common_name' => 'Curlleaf mahogany','growth_rate' => 'Moderate','height_at_maturity' => '21'),
            array('id' => '1350','genus_name' => 'Ceanothus','species_name' => 'leucodermis','common_name' => 'Chaparral whitethorn','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1351','genus_name' => 'Ceanothus','species_name' => 'lemmonii','common_name' => 'Lemmon\'s ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1352','genus_name' => 'Cedrus','species_name' => 'libani','common_name' => 'Cedar of lebanon','growth_rate' => 'Moderate','height_at_maturity' => '45'),
            array('id' => '1353','genus_name' => 'Celtis','species_name' => 'lindheimeri','common_name' => 'Lindheimer\'s hackberry','growth_rate' => 'Fast','height_at_maturity' => '83'),
            array('id' => '1354','genus_name' => 'Ceanothus','species_name' => 'x lobbianus','common_name' => 'Lobbian ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1355','genus_name' => 'Ceanothus','species_name' => 'x lorenzenii','common_name' => 'Lorenzen\'s ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1356','genus_name' => 'Ceanothus','species_name' => 'maritimus','common_name' => 'Maritime ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1357','genus_name' => 'Cereus','species_name' => 'marginatus','common_name' => 'Central Mexico organ pipe','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '1358','genus_name' => 'Ceanothus','species_name' => 'martinii','common_name' => 'Martin\'s ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1360','genus_name' => 'Ceanothus','species_name' => 'megacarpus','common_name' => 'Bigpod ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1361','genus_name' => 'Ceanothus','species_name' => 'x mendocinensis','common_name' => 'Mendocino ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1362','genus_name' => 'Parkinsonia','species_name' => 'microphylla','common_name' => 'Yellow paloverde','growth_rate' => 'Fast','height_at_maturity' => '27'),
            array('id' => '1363','genus_name' => 'Ceanothus','species_name' => 'microphyllus','common_name' => 'Littleleaf buckbrush','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1364','genus_name' => 'Cercocarpus','species_name' => 'montanus','common_name' => 'Alderleaf mahogany','growth_rate' => 'Moderate','height_at_maturity' => '21'),
            array('id' => '1365','genus_name' => 'Cedrela','species_name' => 'montana','common_name' => 'Cedrela montana','growth_rate' => 'Moderate','height_at_maturity' => '98'),
            array('id' => '1366','genus_name' => 'Cestrum','species_name' => 'nocturnum','common_name' => 'Night jessamine','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '1367','genus_name' => 'Cecropia','species_name' => 'obtusifolia','common_name' => 'Trumpet tree','growth_rate' => 'Fast','height_at_maturity' => '26'),
            array('id' => '1368','genus_name' => 'Celtis','species_name' => 'occidentalis','common_name' => 'Northern hackberry','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '1369','genus_name' => 'Cephalanthus','species_name' => 'occidentalis','common_name' => 'Button bush','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '1370','genus_name' => 'Cercis','species_name' => 'canadensis v texensis','common_name' => 'Western redbud','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '1371','genus_name' => 'Cedrela','species_name' => 'odorata','common_name' => 'Spanish cedar','growth_rate' => 'Fast','height_at_maturity' => '90'),
            array('id' => '1372','genus_name' => 'Ceanothus','species_name' => 'oliganthus','common_name' => 'Hairy ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '1373','genus_name' => 'Ceanothus','species_name' => 'ophiochilus','common_name' => 'Vail lake ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1375','genus_name' => 'Cercis','species_name' => 'orbiculata','common_name' => 'California redbud','growth_rate' => 'Fast','height_at_maturity' => '34'),
            array('id' => '1376','genus_name' => 'Ceanothus','species_name' => 'x otayensis','common_name' => 'Otay ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1378','genus_name' => 'Celtis','species_name' => 'paniculata','common_name' => 'Native Hackberry','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '1379','genus_name' => 'Ceanothus','species_name' => 'papillosus','common_name' => 'Wartleaf ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1380','genus_name' => 'Ceanothus','species_name' => 'parryi','common_name' => 'Parry ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1381','genus_name' => 'Ceanothus','species_name' => 'parvifolius','common_name' => 'Littleleaf ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1383','genus_name' => 'Ceanothus','species_name' => 'palmeri','common_name' => 'Palmer ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1385','genus_name' => 'Celtis','species_name' => 'pallida','common_name' => 'Spiny hackberry','growth_rate' => 'Fast','height_at_maturity' => '18'),
            array('id' => '1386','genus_name' => 'Ceiba','species_name' => 'pentandra','common_name' => 'Kapok','growth_rate' => 'Fast','height_at_maturity' => '150'),
            array('id' => '1387','genus_name' => 'Cecropia','species_name' => 'schreberiana','common_name' => 'Pumpwood','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '1388','genus_name' => 'Ceanothus','species_name' => 'purpureus','common_name' => 'Hollyleaf ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1389','genus_name' => 'Cestrum','species_name' => 'racemosum','common_name' => 'Cestrum racemosum','growth_rate' => 'Fast','height_at_maturity' => '59'),
            array('id' => '1390','genus_name' => 'Celtis','species_name' => 'reticulata','common_name' => 'Western hackberry','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '1392','genus_name' => 'Ceanothus','species_name' => 'roderickii','common_name' => 'Pine hill buckbrush','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1393','genus_name' => 'Ceanothus','species_name' => 'x rugosus','common_name' => 'Rugose ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1394','genus_name' => 'Ceanothus','species_name' => 'sanguineus','common_name' => 'Redstem ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1395','genus_name' => 'Cephalanthus','species_name' => 'salicifolius','common_name' => 'Mexican buttonbush','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '1397','genus_name' => 'Celastrus','species_name' => 'scandens','common_name' => 'American bittersweet','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '1398','genus_name' => 'Ceanothus','species_name' => 'serpyllifolius','common_name' => 'Coastal plain buckbrush','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1399','genus_name' => 'Cedrela','species_name' => 'sinensis','common_name' => 'Chinese toon','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '1401','genus_name' => 'Cercis','species_name' => 'siliquastrum','common_name' => 'Arbol de judea','growth_rate' => 'Fast','height_at_maturity' => '23'),
            array('id' => '1402','genus_name' => 'Ceratonia','species_name' => 'siliqua','common_name' => 'Carob','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '1403','genus_name' => 'Celtis','species_name' => 'sinensis','common_name' => 'Chinese hackberry','growth_rate' => 'Fast','height_at_maturity' => ''),
            array('id' => '1404','genus_name' => 'Ceanothus','species_name' => 'sonomensis','common_name' => 'Sonoma ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1405','genus_name' => 'Ceanothus','species_name' => 'sorediatus','common_name' => 'Jimbrush','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1406','genus_name' => 'Ceanothus','species_name' => 'spinosus','common_name' => 'Green bark ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '1407','genus_name' => 'Ceiba','species_name' => 'speciosa','common_name' => 'silk floss tree','growth_rate' => '','height_at_maturity' => '45'),
            array('id' => '1408','genus_name' => 'Cespedesia','species_name' => 'spathulata','common_name' => 'Cespedesia spathulata','growth_rate' => 'Moderate','height_at_maturity' => '49'),
            array('id' => '1409','genus_name' => 'Ceriops','species_name' => 'tagal','common_name' => 'indian mangrove','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '1410','genus_name' => 'Celtis','species_name' => 'tenuifolia','common_name' => 'Dwarf hackberry','growth_rate' => 'Fast','height_at_maturity' => '83'),
            array('id' => '1411','genus_name' => 'Celtis','species_name' => 'tetrandra','common_name' => 'Eastern nettle tree','growth_rate' => 'Fast','height_at_maturity' => '83'),
            array('id' => '1412','genus_name' => 'Ceanothus','species_name' => 'thyrsiflorus','common_name' => 'Blue blossom','growth_rate' => '','height_at_maturity' => '17'),
            array('id' => '1413','genus_name' => 'Ceanothus','species_name' => 'tomentosus','common_name' => 'Woolyleaf ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1414','genus_name' => 'Celtis','species_name' => 'tournefortii','common_name' => 'Oriental hackberry','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '1416','genus_name' => 'Cestrum','species_name' => 'tomentosum','common_name' => 'Cestrum tomentosum','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '1417','genus_name' => 'Celtis','species_name' => 'trinervia','common_name' => 'Almez','growth_rate' => 'Fast','height_at_maturity' => '83'),
            array('id' => '1418','genus_name' => 'Cercocarpus','species_name' => 'traskiae','common_name' => 'Catalina island mahogany','growth_rate' => 'Moderate','height_at_maturity' => '21'),
            array('id' => '1419','genus_name' => 'Ceanothus','species_name' => 'x vanrensselaeri','common_name' => 'Vanrensselaer ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1420','genus_name' => 'Ceanothus','species_name' => 'velutinus','common_name' => 'Snowbrush ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '1421','genus_name' => 'Ceanothus','species_name' => 'verrucosus','common_name' => 'Barranca brush','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1422','genus_name' => 'Ceanothus','species_name' => 'x veitchianus','common_name' => 'Veitch ceanothus','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '1423','genus_name' => 'Chiococca','species_name' => 'alba','common_name' => 'West indian milkberry','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '1426','genus_name' => 'Chrysophyllum','species_name' => 'argenteum','common_name' => 'Bastard redwood','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '1428','genus_name' => 'Chamaesyce','species_name' => 'atrococca','common_name' => 'Koko','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '1430','genus_name' => 'Chionanthus','species_name' => 'axilliflorus','common_name' => 'Hueso','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1431','genus_name' => 'Chrysophyllum','species_name' => 'bicolor','common_name' => 'Chrysophyllum bicolor','growth_rate' => 'Slow','height_at_maturity' => '56'),
            array('id' => '1434','genus_name' => 'Chrysophyllum','species_name' => 'cainito','common_name' => 'Star apple','growth_rate' => 'Slow','height_at_maturity' => '38'),
            array('id' => '1435','genus_name' => 'Chamaesyce','species_name' => 'celastroides','common_name' => '\'ekoko','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '1437','genus_name' => 'Chionanthus','species_name' => 'compactus','common_name' => 'Bridgotree','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1438','genus_name' => 'Charpentiera','species_name' => 'densiflora','common_name' => 'Napali coast papala','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '1440','genus_name' => 'Chionanthus','species_name' => 'domingensis','common_name' => 'White rosewood','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1442','genus_name' => 'Charpentiera','species_name' => 'elliptica','common_name' => 'Ellipticleaf papala','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '1444','genus_name' => 'Chlorophora','species_name' => 'excelsa','common_name' => 'african teak','growth_rate' => '','height_at_maturity' => '160'),
            array('id' => '1452','genus_name' => 'Chamaesyce','species_name' => 'herbstii','common_name' => 'Herbst\'s sandmat','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '1453','genus_name' => 'Chionanthus','species_name' => 'holdridgii','common_name' => 'Hueso prieto','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1454','genus_name' => 'Chamaerops','species_name' => 'humilis','common_name' => 'Mediterranean fan palm','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '1456','genus_name' => 'Chrysobalanus','species_name' => 'icaco','common_name' => 'Coco plum','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '1457','genus_name' => 'Chaenomeles','species_name' => 'japonica','common_name' => 'Maule\'s quince','growth_rate' => '','height_at_maturity' => '5'),
            array('id' => '1458','genus_name' => 'Chamaesyce','species_name' => 'kuwaleana','common_name' => 'Kokomalei','growth_rate' => '','height_at_maturity' => '3'),
            array('id' => '1459','genus_name' => 'Chaenomeles','species_name' => 'speciosa','common_name' => 'Flowering quince','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '1460','genus_name' => 'Chamaecyparis','species_name' => 'lawsoniana','common_name' => 'Port orford cedar','growth_rate' => 'Moderate','height_at_maturity' => '200'),
            array('id' => '1461','genus_name' => 'Choricarpia','species_name' => 'leptopetala','common_name' => 'Brush Turpentine','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '1462','genus_name' => 'Chilopsis','species_name' => 'linearis','common_name' => 'Desertwillow','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1464','genus_name' => 'Chionanthus','species_name' => 'ligustrinus','common_name' => 'Cabra blanca','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1465','genus_name' => 'Dypsis','species_name' => 'lutescens','common_name' => 'Areca palm','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '1469','genus_name' => 'Chamaesyce','species_name' => 'multiformis','common_name' => 'Variable sandmat','growth_rate' => '','height_at_maturity' => '7'),
            array('id' => '1471','genus_name' => 'Chamaecyparis','species_name' => 'nootkatensis','common_name' => 'Alaska cedar','growth_rate' => 'Slow','height_at_maturity' => '53'),
            array('id' => '1472','genus_name' => 'Chenopodium','species_name' => 'oahuense','common_name' => 'Alaweo','growth_rate' => 'Fast','height_at_maturity' => '4'),
            array('id' => '1473','genus_name' => 'Chamaecyparis','species_name' => 'obtusa','common_name' => 'Hinoki cypress','growth_rate' => 'Slow','height_at_maturity' => '63'),
            array('id' => '1474','genus_name' => 'Charpentiera','species_name' => 'obovata','common_name' => 'Broadleaf papala','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '1475','genus_name' => 'Chrysophyllum','species_name' => 'oliviforme','common_name' => 'Satinleaf','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1476','genus_name' => 'Chamaesyce','species_name' => 'olowaluana','common_name' => 'Alpine sandmat','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '1477','genus_name' => 'Charpentiera','species_name' => 'ovata','common_name' => 'Koolau range papala','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '1480','genus_name' => 'Chrysophyllum','species_name' => 'pauciflorum','common_name' => 'Camito de perro','growth_rate' => 'Slow','height_at_maturity' => '56'),
            array('id' => '1481','genus_name' => 'Chiranthodendron','species_name' => 'pentadactylon','common_name' => 'Mexican hand tree','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '1482','genus_name' => 'Chamaecyparis','species_name' => 'pisifera','common_name' => 'Sawara cypress','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '1484','genus_name' => 'Cheirodendron','species_name' => 'platyphyllum','common_name' => 'Lapalapa','growth_rate' => '','height_at_maturity' => '26'),
            array('id' => '1488','genus_name' => 'Chimonanthus','species_name' => 'praecox','common_name' => 'Japanese allspice','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '1489','genus_name' => 'Chrysothamnus','species_name' => 'pulchellus','common_name' => 'Southwestern Rabbitbrush','growth_rate' => '','height_at_maturity' => '3'),
            array('id' => '1490','genus_name' => 'Chionanthus','species_name' => 'retusus','common_name' => 'Chinese fringe tree','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1491','genus_name' => 'Chionanthus','species_name' => 'retusa','common_name' => 'Chinese Fringetree','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '1493','genus_name' => 'Chamaesyce','species_name' => 'rockii','common_name' => 'Koolau range sandmat','growth_rate' => '','height_at_maturity' => '4'),
            array('id' => '1495','genus_name' => 'Chamaedorea','species_name' => 'seifrizii','common_name' => 'Seifriz\'s chamaedorea','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '1498','genus_name' => 'Chorisia','species_name' => 'speciosa','common_name' => 'Palo borracho','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '1500','genus_name' => 'Chitalpa','species_name' => 'tashkentensis','common_name' => 'Chitalpa','growth_rate' => '','height_at_maturity' => ''),
            array('id' => '1502','genus_name' => 'Chamaecyparis','species_name' => 'thyoides','common_name' => 'Atlantic white cedar','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '1503','genus_name' => 'Charpentiera','species_name' => 'tomentosa','common_name' => 'Waianae range papala','growth_rate' => '','height_at_maturity' => '39'),
            array('id' => '1504','genus_name' => 'Cheirodendron','species_name' => 'trigynum','common_name' => 'Olapalapa','growth_rate' => '','height_at_maturity' => '49'),
            array('id' => '1506','genus_name' => 'Chionanthus','species_name' => 'virginicus','common_name' => 'Fringe tree','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '1508','genus_name' => 'Cinnamomum','species_name' => 'aromaticum','common_name' => 'Chinese cassia','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '1509','genus_name' => 'Citrus','species_name' => 'aurantifolia','common_name' => 'Key Lime','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '1510','genus_name' => 'Citrus','species_name' => 'australasica','common_name' => 'Finger Lime','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '1511','genus_name' => 'Citrus','species_name' => 'aurantium','common_name' => 'Sour orange','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '1512','genus_name' => 'Citharexylum','species_name' => 'berlandieri','common_name' => 'Berlandier\'s fiddlewood','growth_rate' => 'Slow','height_at_maturity' => '40'),
            array('id' => '1513','genus_name' => 'Citharexylum','species_name' => 'brachyanthum','common_name' => 'Boxthorn fiddlewood','growth_rate' => 'Slow','height_at_maturity' => '40'),
            array('id' => '1514','genus_name' => 'Cinnamomum','species_name' => 'burmannii','common_name' => 'Padang cassia','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '1515','genus_name' => 'Cinnamomum','species_name' => 'camphora','common_name' => 'Camphor tree','growth_rate' => 'Fast','height_at_maturity' => '55'),
            array('id' => '1516','genus_name' => 'Citharexylum','species_name' => 'caudatum','common_name' => 'Juniper berry','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '1517','genus_name' => 'Cibotium','species_name' => 'chamissoi','common_name' => 'Chamisso\'s manfern','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '1518','genus_name' => 'Cinnamomum','species_name' => 'elongatum','common_name' => 'Laurel avispillo','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '1519','genus_name' => 'Citharexylum','species_name' => 'fruticosum','common_name' => 'Florida fuddlewood','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '1520','genus_name' => 'Cibotium','species_name' => 'glaucum','common_name' => 'Hapu\'u','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '1521','genus_name' => 'Citrus','species_name' => 'glauca','common_name' => 'Desert Lime','growth_rate' => 'Slow','height_at_maturity' => '7'),
            array('id' => '1523','genus_name' => 'Citrus','species_name' => 'maxima','common_name' => 'Shaddock','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '1524','genus_name' => 'Citrus','species_name' => 'hystrix','common_name' => 'kaffir lime','growth_rate' => '','height_at_maturity' => '17'),
            array('id' => '1525','genus_name' => 'Citrus','species_name' => 'x jambhiri','common_name' => 'Citrus x jambhiri','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '1526','genus_name' => 'Cinnamomum','species_name' => 'kanehirai','common_name' => 'Cinnamomum kanehirai','growth_rate' => 'Moderate','height_at_maturity' => ''),
            array('id' => '1528','genus_name' => 'Citrus','species_name' => 'limon','common_name' => 'Lemon','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '1529','genus_name' => 'Citrus','species_name' => 'limetta','common_name' => 'Bitter orange','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '1530','genus_name' => 'Citrus','species_name' => 'x limonia','common_name' => 'Mandarin lime','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '1531','genus_name' => 'Citrus','species_name' => 'macroptera','common_name' => 'melanesian papeda','growth_rate' => '','height_at_maturity' => '17'),
            array('id' => '1532','genus_name' => 'Citrus','species_name' => 'medica','common_name' => 'Citron','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '1533','genus_name' => 'Cibotium','species_name' => 'menziesii','common_name' => 'Hapu\'u li','growth_rate' => '','height_at_maturity' => '33'),
            array('id' => '1534','genus_name' => 'Citrus','species_name' => 'mitis','common_name' => 'musk lime','growth_rate' => '','height_at_maturity' => '17'),
            array('id' => '1536','genus_name' => 'Cinnamomum','species_name' => 'montanum','common_name' => 'Avispillo','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '1538','genus_name' => 'Cinnamomum','species_name' => 'osmophloeum','common_name' => 'Cinnamomum osmophloeum','growth_rate' => 'Moderate','height_at_maturity' => ''),
            array('id' => '1539','genus_name' => 'Citrus','species_name' => 'x paradisi','common_name' => 'Grapefruit','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1542','genus_name' => 'Citharexylum','species_name' => 'x perkinsii','common_name' => 'Perkins\' fiddlewood','growth_rate' => 'Slow','height_at_maturity' => '40'),
            array('id' => '1543','genus_name' => 'Cinchona','species_name' => 'pubescens','common_name' => 'Quinine','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '1544','genus_name' => 'Citrus','species_name' => 'reticulata','common_name' => 'Tangerine','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1546','genus_name' => 'Citrus','species_name' => 'sinensis','common_name' => 'Orange','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1547','genus_name' => 'Citharexylum','species_name' => 'spinosum','common_name' => 'Fiddlewood','growth_rate' => 'Slow','height_at_maturity' => '40'),
            array('id' => '1548','genus_name' => 'Citharexylum','species_name' => 'tristachyum','common_name' => 'Threespike fiddlewood','growth_rate' => 'Slow','height_at_maturity' => '40'),
            array('id' => '1549','genus_name' => 'Cinnamomum','species_name' => 'verum','common_name' => 'Cinnamon','growth_rate' => 'Moderate','height_at_maturity' => '43'),
            array('id' => '1550','genus_name' => 'Clerodendrum','species_name' => 'aculeatum','common_name' => 'Haggarbush','growth_rate' => 'Fast','height_at_maturity' => '14'),
            array('id' => '1551','genus_name' => 'Clethra','species_name' => 'acuminata','common_name' => 'Mountain sweetpepperbush','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '1552','genus_name' => 'Clethra','species_name' => 'alnifolia','common_name' => 'Sweet pepperbush','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '1553','genus_name' => 'Cleyera','species_name' => 'albopunctata','common_name' => 'Teta prieta','growth_rate' => '','height_at_maturity' => '32'),
            array('id' => '1555','genus_name' => 'Clethra','species_name' => 'arborea','common_name' => 'Lily of the Valley Tree','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '1556','genus_name' => 'Clermontia','species_name' => 'arborescens','common_name' => '\'oha wai nui','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '1558','genus_name' => 'Clerodendrum','species_name' => 'bungei','common_name' => 'Rose glorybower','growth_rate' => 'Fast','height_at_maturity' => '14'),
            array('id' => '1561','genus_name' => 'Clerodendrum','species_name' => 'chinense','common_name' => 'Stickbush','growth_rate' => 'Fast','height_at_maturity' => '14'),
            array('id' => '1562','genus_name' => 'Clermontia','species_name' => 'clermontioides','common_name' => 'Kauai clermontia','growth_rate' => '','height_at_maturity' => '13'),
            array('id' => '1563','genus_name' => 'Clusia','species_name' => 'clusioides','common_name' => 'Cupeillo','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '1567','genus_name' => 'Clermontia','species_name' => 'drepanomorpha','common_name' => 'Kohala mountain clermontia','growth_rate' => '','height_at_maturity' => '16'),
            array('id' => '1569','genus_name' => 'Clermontia','species_name' => 'fauriei','common_name' => 'Haha\'aiakamanu','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '1570','genus_name' => 'Clitoria','species_name' => 'fairchildiana','common_name' => 'Philippine pigeonwings','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '1571','genus_name' => 'Clerodendrum','species_name' => 'floribundum','common_name' => 'Thurkoo','growth_rate' => 'Fast','height_at_maturity' => '5'),
            array('id' => '1575','genus_name' => 'Clerodendrum','species_name' => 'glabrum','common_name' => 'Natal glorybower','growth_rate' => 'Fast','height_at_maturity' => '14'),
            array('id' => '1576','genus_name' => 'Clermontia','species_name' => 'grandiflora','common_name' => 'Bog clermontia','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '1577','genus_name' => 'Clusia','species_name' => 'gundlachii','common_name' => 'Grundlach\'s attorney','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '1578','genus_name' => 'Clermontia','species_name' => 'hawaiiensis','common_name' => '\'oha kepau','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '1580','genus_name' => 'Clerodendrum','species_name' => 'indicum','common_name' => 'turks turbin','growth_rate' => '','height_at_maturity' => '7'),
            array('id' => '1581','genus_name' => 'Clerodendrum','species_name' => 'inerme','common_name' => 'Embrert','growth_rate' => 'Fast','height_at_maturity' => '14'),
            array('id' => '1582','genus_name' => 'Clerodendrum','species_name' => 'japonicum','common_name' => 'Japanese glorybower','growth_rate' => 'Fast','height_at_maturity' => '14'),
            array('id' => '1584','genus_name' => 'Clermontia','species_name' => 'kakeana','common_name' => 'Forest clermontia','growth_rate' => '','height_at_maturity' => '11'),
            array('id' => '1585','genus_name' => 'Clerodendrum','species_name' => 'kaempferi','common_name' => 'Kaempfer\'s glorybower','growth_rate' => 'Fast','height_at_maturity' => '14'),
            array('id' => '1586','genus_name' => 'Clermontia','species_name' => 'kohalae','common_name' => 'Waipio valley clermontia','growth_rate' => '','height_at_maturity' => '17'),
            array('id' => '1589','genus_name' => 'Clermontia','species_name' => 'lindseyana','common_name' => 'Hillside clermontia','growth_rate' => '','height_at_maturity' => '14'),
            array('id' => '1590','genus_name' => 'Cladrastis','species_name' => 'kentukea','common_name' => 'American yellowwood','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '1591','genus_name' => 'Clerodendrum','species_name' => 'macrostegium','common_name' => 'Velvetleaf glorybower','growth_rate' => 'Fast','height_at_maturity' => '14'),
            array('id' => '1592','genus_name' => 'Claoxylon','species_name' => 'marianum','common_name' => 'katteknau','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '1593','genus_name' => 'Clethra','species_name' => 'mexicana','common_name' => 'Clethra mexicana','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '1594','genus_name' => 'Clusia','species_name' => 'minor','common_name' => 'Cupey de monte','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '1595','genus_name' => 'Clermontia','species_name' => 'micrantha','common_name' => 'Maui clermontia','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '1597','genus_name' => 'Clermontia','species_name' => 'montis-loa','common_name' => 'Mauna loa clermontia','growth_rate' => '','height_at_maturity' => '11'),
            array('id' => '1600','genus_name' => 'Clermontia','species_name' => 'oblongifolia','common_name' => 'Oahu clermontia','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '1601','genus_name' => 'Clusia','species_name' => 'orthoneura','common_name' => 'Clusia orthoneura','growth_rate' => 'Fast','height_at_maturity' => '16'),
            array('id' => '1602','genus_name' => 'Clermontia','species_name' => 'pallida','common_name' => 'Wailai pali clermontia','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '1603','genus_name' => 'Clermontia','species_name' => 'parviflora','common_name' => 'Smallflower clermontia','growth_rate' => '','height_at_maturity' => '8'),
            array('id' => '1604','genus_name' => 'Clermontia','species_name' => 'peleana','common_name' => 'Pele clermontia','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '1605','genus_name' => 'Clermontia','species_name' => 'persicifolia','common_name' => 'Waioiani clermontia','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '1606','genus_name' => 'Clermontia','species_name' => 'pyrularia','common_name' => 'Hamakua clermontia','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '1609','genus_name' => 'Clusia','species_name' => 'rosea','common_name' => 'Autograph tree','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '1610','genus_name' => 'Claoxylon','species_name' => 'sandwicense','common_name' => 'Po\'ola','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '1613','genus_name' => 'Cladrastis','species_name' => 'sinensis','common_name' => 'Yellowwood','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1614','genus_name' => 'Clerodendrum','species_name' => 'x speciosum','common_name' => 'Glory bean','growth_rate' => 'Fast','height_at_maturity' => '14'),
            array('id' => '1615','genus_name' => 'Clerodendrum','species_name' => 'speciosissimum','common_name' => 'Javanese glorybower','growth_rate' => 'Fast','height_at_maturity' => '14'),
            array('id' => '1617','genus_name' => 'Clerodendrum','species_name' => 'thompsoniae','common_name' => 'Bagflower','growth_rate' => 'Fast','height_at_maturity' => '14'),
            array('id' => '1618','genus_name' => 'Clerodendrum','species_name' => 'trichotomum','common_name' => 'Harlequin glorybower','growth_rate' => 'Fast','height_at_maturity' => '14'),
            array('id' => '1619','genus_name' => 'Clermontia','species_name' => 'tuberculata','common_name' => 'Haleakala clermontia','growth_rate' => '','height_at_maturity' => '14'),
            array('id' => '1620','genus_name' => 'Clerodendrum','species_name' => 'umbellatum','common_name' => 'Umbel clerodendrum','growth_rate' => 'Fast','height_at_maturity' => '14'),
            array('id' => '1621','genus_name' => 'Clermontia','species_name' => 'waimeae','common_name' => 'Swampforest clermontia','growth_rate' => '','height_at_maturity' => '13'),
            array('id' => '1622','genus_name' => 'Clerodendrum','species_name' => 'wallichii','common_name' => 'Wallich\'s glorybower','growth_rate' => 'Fast','height_at_maturity' => '14'),
            array('id' => '1623','genus_name' => 'Cnidoscolus','species_name' => 'aconitifolius','common_name' => 'Treadsoftly','growth_rate' => '','height_at_maturity' => '13'),
            array('id' => '1626','genus_name' => 'Coccoloba','species_name' => 'acuminata','common_name' => 'Maiz tostado','growth_rate' => 'Fast','height_at_maturity' => '26'),
            array('id' => '1627','genus_name' => 'Cotoneaster','species_name' => 'acutifolius','common_name' => 'Peking cotoneaster','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '1628','genus_name' => 'Cola','species_name' => 'acuminata','common_name' => 'abata cola','growth_rate' => '','height_at_maturity' => '76'),
            array('id' => '1629','genus_name' => 'Cotoneaster','species_name' => 'adpressus','common_name' => 'Creeping cotoneaster','growth_rate' => '','height_at_maturity' => '2'),
            array('id' => '1630','genus_name' => 'Cordia','species_name' => 'africana','common_name' => 'Large-leaved cordial','growth_rate' => 'Fast','height_at_maturity' => '89'),
            array('id' => '1631','genus_name' => 'Cornus','species_name' => 'alternifolia','common_name' => 'Alternateleaf dogwood','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '1633','genus_name' => 'Cordia','species_name' => 'alliodora','common_name' => 'Capa prieto','growth_rate' => 'Slow','height_at_maturity' => '70'),
            array('id' => '1634','genus_name' => 'Coccothrinax','species_name' => 'barbadensis','common_name' => 'Puerto rican thatch palm','growth_rate' => 'Slow','height_at_maturity' => '32'),
            array('id' => '1635','genus_name' => 'Trema','species_name' => 'micranthum','common_name' => 'Rainforest laurel','growth_rate' => '','height_at_maturity' => '32'),
            array('id' => '1636','genus_name' => 'Corylus','species_name' => 'americana','common_name' => 'American hazlenut','growth_rate' => 'Moderate','height_at_maturity' => '9'),
            array('id' => '1637','genus_name' => 'Cornus','species_name' => 'amomum','common_name' => 'Knob-styled dogwood','growth_rate' => 'Moderate','height_at_maturity' => '31'),
            array('id' => '1638','genus_name' => 'Cordia','species_name' => 'angustifolia','common_name' => 'Basora','growth_rate' => 'Slow','height_at_maturity' => '34'),
            array('id' => '1639','genus_name' => 'Coccothrinax','species_name' => 'argentata','common_name' => 'Florida silverpalm','growth_rate' => 'Slow','height_at_maturity' => '13'),
            array('id' => '1640','genus_name' => 'Corymbia','species_name' => 'arnhemensis','common_name' => 'Katherine Gorge Bloodwood','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '1641','genus_name' => 'Coffea','species_name' => 'arabica','common_name' => 'Arabian coffee','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '1642','genus_name' => 'Colubrina','species_name' => 'arborescens','common_name' => 'Greenheart','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '1643','genus_name' => 'Colutea','species_name' => 'arborescens','common_name' => 'Bladder senna','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '1644','genus_name' => 'Cornus','species_name' => 'x arnoldiana','common_name' => 'Arnold dogwood','growth_rate' => 'Moderate','height_at_maturity' => '31'),
            array('id' => '1646','genus_name' => 'Cornus','species_name' => 'asperifolia','common_name' => 'Toughleaf dogwood','growth_rate' => 'Moderate','height_at_maturity' => '31'),
            array('id' => '1647','genus_name' => 'Colubrina','species_name' => 'asiatica','common_name' => 'Asian nakedwood','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1649','genus_name' => 'Corylus','species_name' => 'avellana','common_name' => 'European filbert','growth_rate' => 'Slow','height_at_maturity' => '58'),
            array('id' => '1651','genus_name' => 'Commersonia','species_name' => 'bartramia','common_name' => 'Brown Kurrajong','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '1652','genus_name' => 'Cordia','species_name' => 'bahamensis','common_name' => 'Bahama manjack','growth_rate' => 'Slow','height_at_maturity' => '34'),
            array('id' => '1653','genus_name' => 'Corymbia','species_name' => 'bella','common_name' => 'Weeping Ghost Gum','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1654','genus_name' => 'Cordia','species_name' => 'bellonis','common_name' => 'Serpentine manjack','growth_rate' => 'Slow','height_at_maturity' => '34'),
            array('id' => '1655','genus_name' => 'Cordia','species_name' => 'boissieri','common_name' => 'Anacahuita','growth_rate' => 'Slow','height_at_maturity' => '18'),
            array('id' => '1656','genus_name' => 'Cordia','species_name' => 'borinquensis','common_name' => 'Muneco','growth_rate' => 'Slow','height_at_maturity' => '34'),
            array('id' => '1658','genus_name' => 'Cornus','species_name' => 'capitata','common_name' => 'Himalayan Strawberry Tree','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '1659','genus_name' => 'Corymbia','species_name' => 'calophylla','common_name' => 'Marri','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '1660','genus_name' => 'Colubrina','species_name' => 'californica','common_name' => 'Las animas nakedwood','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1663','genus_name' => 'Corymbia','species_name' => 'citriodora','common_name' => 'Lemonscented gum','growth_rate' => 'Fast','height_at_maturity' => '88'),
            array('id' => '1664','genus_name' => 'Corymbia','species_name' => 'confertiflora','common_name' => 'Broad Leaved Carbeen','growth_rate' => 'Slow','height_at_maturity' => '18'),
            array('id' => '1665','genus_name' => 'Cotinus','species_name' => 'coggygria','common_name' => 'Smoke tree','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '1666','genus_name' => 'Condalia','species_name' => 'correllii','common_name' => 'Correll\'s snakewood','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '1667','genus_name' => 'Corylus','species_name' => 'colurna','common_name' => 'Turkish hazelnut','growth_rate' => 'Moderate','height_at_maturity' => '63'),
            array('id' => '1668','genus_name' => 'Corylus','species_name' => 'cornuta','common_name' => 'Beaked hazlenut','growth_rate' => 'Slow','height_at_maturity' => '58'),
            array('id' => '1669','genus_name' => 'Cornus','species_name' => 'controversa','common_name' => 'Giant Dogwood','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '1670','genus_name' => 'Cordia','species_name' => 'collococca','common_name' => 'Red manjack','growth_rate' => 'Slow','height_at_maturity' => '34'),
            array('id' => '1671','genus_name' => 'Codonocarpus','species_name' => 'cotinifolius','common_name' => 'Desert Poplar','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '1672','genus_name' => 'Coccoloba','species_name' => 'costata','common_name' => 'Uvilla','growth_rate' => 'Moderate','height_at_maturity' => '54'),
            array('id' => '1673','genus_name' => 'Colubrina','species_name' => 'cubensis','common_name' => 'Cuban nakedwood','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1675','genus_name' => 'Cordia','species_name' => 'dentata','common_name' => 'Uvito comun','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '1676','genus_name' => 'Coccoloba','species_name' => 'diversifolia','common_name' => 'Doveplum','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '1677','genus_name' => 'Cordia','species_name' => 'dichotoma','common_name' => 'Fragrant manjack','growth_rate' => 'Slow','height_at_maturity' => '34'),
            array('id' => '1678','genus_name' => 'Cotoneaster','species_name' => 'divaricatus','common_name' => 'Spreading cotoneaster','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '1681','genus_name' => 'Cordia','species_name' => 'dodecandra','common_name' => 'Ziricote','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '1682','genus_name' => 'Cornus','species_name' => 'drummondii','common_name' => 'Roughleaf dogwood','growth_rate' => 'Moderate','height_at_maturity' => '31'),
            array('id' => '1683','genus_name' => 'Colubrina','species_name' => 'elliptica','common_name' => 'Soldierwood','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1684','genus_name' => 'Cordia','species_name' => 'elaeagnoides','common_name' => 'Cordia elaeagnoides','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '1686','genus_name' => 'Conocarpus','species_name' => 'erectus','common_name' => 'Button mangrove','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '1688','genus_name' => 'Condalia','species_name' => 'ericoides','common_name' => 'Javelin bush','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '1690','genus_name' => 'Corymbia','species_name' => 'eximia','common_name' => 'Yellow bloodwood','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '1691','genus_name' => 'Cornus','species_name' => 'florida','common_name' => 'Flowering dogwood','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '1692','genus_name' => 'Cornus','species_name' => 'foemina','common_name' => 'Stiff dogwood','growth_rate' => 'Moderate','height_at_maturity' => '16'),
            array('id' => '1693','genus_name' => 'Coprosma','species_name' => 'foliosa','common_name' => 'Forest mirrorplant','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '1694','genus_name' => 'Cotoneaster','species_name' => 'frigidus','common_name' => 'Tree cotoneaster','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '1695','genus_name' => 'Cordyline','species_name' => 'fruticosa','common_name' => 'Tiplant','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '1697','genus_name' => 'Cornus','species_name' => 'x friedlanderi','common_name' => 'Friedlander\'s dogwood','growth_rate' => 'Moderate','height_at_maturity' => '31'),
            array('id' => '1698','genus_name' => 'Cordia','species_name' => 'gerascanthus','common_name' => 'Yauco','growth_rate' => 'Slow','height_at_maturity' => '34'),
            array('id' => '1699','genus_name' => 'Condalia','species_name' => 'globosa','common_name' => 'Bitter snakewood','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1700','genus_name' => 'Cotoneaster','species_name' => 'glaucophyllus','common_name' => 'Large Leaf Cotoneaster','growth_rate' => 'Fast','height_at_maturity' => '3'),
            array('id' => '1702','genus_name' => 'Cornus','species_name' => 'glabrata','common_name' => 'Brown dogwood','growth_rate' => 'Moderate','height_at_maturity' => '31'),
            array('id' => '1703','genus_name' => 'Comocladia','species_name' => 'glabra','common_name' => 'Carrasco','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '1704','genus_name' => 'Colubrina','species_name' => 'glandulosa','common_name' => 'Glandular nakedwood','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1705','genus_name' => 'Cordia','species_name' => 'globosa','common_name' => 'Curaciao bush','growth_rate' => 'Slow','height_at_maturity' => '34'),
            array('id' => '1708','genus_name' => 'Colubrina','species_name' => 'greggii','common_name' => 'Sierra nakedwood','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1710','genus_name' => 'Couroupita','species_name' => 'guianensis','common_name' => 'Cannonball tree','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '1713','genus_name' => 'Corymbia','species_name' => 'henryi','common_name' => 'Large-leaved Spotted Gum','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '1715','genus_name' => 'Corylus','species_name' => 'heterophylla','common_name' => 'Siberian hazelnut','growth_rate' => 'Slow','height_at_maturity' => '58'),
            array('id' => '1717','genus_name' => 'Condalia','species_name' => 'hookeri','common_name' => 'Brazilian bluewood','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '1718','genus_name' => 'Cotoneaster','species_name' => 'horizontalis','common_name' => 'Rockspray cotoneaster','growth_rate' => 'Slow','height_at_maturity' => '3'),
            array('id' => '1720','genus_name' => 'Corymbia','species_name' => 'intermedia','common_name' => 'Pink Bloodwood','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '1721','genus_name' => 'Corymbia','species_name' => 'jacobsiana','common_name' => 'Stringybarked Bloodwood','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '1722','genus_name' => 'Coprosma','species_name' => 'kauensis','common_name' => 'Koi','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '1723','genus_name' => 'Cornus','species_name' => 'kousa','common_name' => 'Kousa dogwood','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '1724','genus_name' => 'Coccoloba','species_name' => 'krugii','common_name' => 'Whitewood','growth_rate' => 'Moderate','height_at_maturity' => '54'),
            array('id' => '1725','genus_name' => 'Cocculus','species_name' => 'laurifolius','common_name' => 'Laurel-leafed snailseed','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '1726','genus_name' => 'Cordia','species_name' => 'laevigata','common_name' => 'Smooth manjack','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '1727','genus_name' => 'Cotoneaster','species_name' => 'lacteus','common_name' => 'Milkflower cotoneaster','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '1728','genus_name' => 'Corynocarpus','species_name' => 'laevigatus','common_name' => 'Karaka nut','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '1729','genus_name' => 'Cordia','species_name' => 'lima','common_name' => 'Lija','growth_rate' => 'Slow','height_at_maturity' => '34'),
            array('id' => '1730','genus_name' => 'Coffea','species_name' => 'liberica','common_name' => 'Liberian coffee','growth_rate' => '','height_at_maturity' => '65'),
            array('id' => '1731','genus_name' => 'Coprosma','species_name' => 'longifolia','common_name' => 'Oahu mirrorplant','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '1733','genus_name' => 'Cotoneaster','species_name' => 'lucidus','common_name' => 'Shiny cotoneaster','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '1734','genus_name' => 'Cornus','species_name' => 'mas','common_name' => 'Cornelian cherry','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '1735','genus_name' => 'Corymbia','species_name' => 'maculata','common_name' => 'Spotted gum','growth_rate' => 'Moderate','height_at_maturity' => '116'),
            array('id' => '1736','genus_name' => 'Corylus','species_name' => 'maxima','common_name' => 'Filbert','growth_rate' => 'Slow','height_at_maturity' => '58'),
            array('id' => '1738','genus_name' => 'Corokia','species_name' => 'macrocarpa','common_name' => 'Whakataka','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '1741','genus_name' => 'Condalia','species_name' => 'mexicana','common_name' => 'Condalia mexicana','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '1744','genus_name' => 'Coccoloba','species_name' => 'microstachya','common_name' => 'Pockhout','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '1746','genus_name' => 'Coprosma','species_name' => 'montana','common_name' => 'Alpine mirrorplant','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '1747','genus_name' => 'Conzattia','species_name' => 'multiflora','common_name' => 'Conzattia multiflora','growth_rate' => '','height_at_maturity' => '9'),
            array('id' => '1748','genus_name' => 'Cordia','species_name' => 'myxa','common_name' => 'Assyrian plum','growth_rate' => 'Slow','height_at_maturity' => '34'),
            array('id' => '1749','genus_name' => 'Corymbia','species_name' => 'nesophila','common_name' => 'Melville Island Bloodwood','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '1750','genus_name' => 'Cocos','species_name' => 'nucifera','common_name' => 'Coconut palm','growth_rate' => 'Moderate','height_at_maturity' => '60'),
            array('id' => '1751','genus_name' => 'Cornus','species_name' => 'nuttallii','common_name' => 'Pacific dogwood','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '1752','genus_name' => 'Cotinus','species_name' => 'obovatus','common_name' => 'American smoketree','growth_rate' => 'Slow','height_at_maturity' => '23'),
            array('id' => '1753','genus_name' => 'Cordia','species_name' => 'obliqua','common_name' => 'Clammy cherry','growth_rate' => 'Slow','height_at_maturity' => '34'),
            array('id' => '1754','genus_name' => 'Cornutia','species_name' => 'obovata','common_name' => 'Nigua','growth_rate' => '','height_at_maturity' => '100'),
            array('id' => '1755','genus_name' => 'Cornus','species_name' => 'obliqua','common_name' => 'Silky dogwood','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '1756','genus_name' => 'Coprosma','species_name' => 'ochracea','common_name' => 'Maui mirrorplant','growth_rate' => '','height_at_maturity' => '13'),
            array('id' => '1757','genus_name' => 'Cornus','species_name' => 'officinalis','common_name' => 'Japanese cornelia dogwood','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '1759','genus_name' => 'Colubrina','species_name' => 'oppositifolia','common_name' => 'Kauila','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1762','genus_name' => 'Corymbia','species_name' => 'papuana','common_name' => 'Ghost Gum','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '1763','genus_name' => 'Cordia','species_name' => 'parvifolia','common_name' => 'Small-leaf geigertree','growth_rate' => 'Slow','height_at_maturity' => '34'),
            array('id' => '1764','genus_name' => 'Coccoloba','species_name' => 'pallida','common_name' => 'Pale seagrape','growth_rate' => 'Moderate','height_at_maturity' => '54'),
            array('id' => '1765','genus_name' => 'Corymbia','species_name' => 'polycarpa','common_name' => 'Long-fruited Bloodwood','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1766','genus_name' => 'Corymbia','species_name' => 'polysciada','common_name' => 'Corymbia polysciada','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '1768','genus_name' => 'Corymbia','species_name' => 'ptychocarpa','common_name' => 'Swamp Bloodwood','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1769','genus_name' => 'Coccoloba','species_name' => 'pubescens','common_name' => 'Moralon','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '1770','genus_name' => 'Coprosma','species_name' => 'pubens','common_name' => 'Pubescent mirrorplant','growth_rate' => '','height_at_maturity' => '17'),
            array('id' => '1771','genus_name' => 'Coccoloba','species_name' => 'pyrifolia','common_name' => 'Uvera','growth_rate' => 'Moderate','height_at_maturity' => '54'),
            array('id' => '1772','genus_name' => 'Cornutia','species_name' => 'pyramidata','common_name' => 'Azulejo','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '1773','genus_name' => 'Cornus','species_name' => 'racemosa','common_name' => 'Gray dogwood','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '1777','genus_name' => 'Coprosma','species_name' => 'rhynchocarpa','common_name' => 'Woodland mirrorplant','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '1778','genus_name' => 'Cordia','species_name' => 'rickseckeri','common_name' => 'San bartolome','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '1779','genus_name' => 'Cornus','species_name' => 'rugosa','common_name' => 'Roundleaf dogwood','growth_rate' => 'Moderate','height_at_maturity' => '31'),
            array('id' => '1780','genus_name' => 'Cordyline','species_name' => 'rubra','common_name' => 'Cordyline rubra','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '1782','genus_name' => 'Coccoloba','species_name' => 'rugosa','common_name' => 'Ortegon','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1783','genus_name' => 'Cordia','species_name' => 'rupicola','common_name' => 'Puerto rico manjack','growth_rate' => 'Slow','height_at_maturity' => '34'),
            array('id' => '1784','genus_name' => 'Cotoneaster','species_name' => 'salicifolius','common_name' => 'Willow-leaved Cotoneaster','growth_rate' => 'Fast','height_at_maturity' => '5'),
            array('id' => '1785','genus_name' => 'Cornus','species_name' => 'sanguinea','common_name' => 'Bloodtwig dogwood','growth_rate' => 'Moderate','height_at_maturity' => '31'),
            array('id' => '1787','genus_name' => 'Cortaderia','species_name' => 'selloana','common_name' => 'Uruguayan pampas grass','growth_rate' => 'Fast','height_at_maturity' => '3'),
            array('id' => '1788','genus_name' => 'Cotoneaster','species_name' => 'serotinus','common_name' => 'Cotoneaster serotinus','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '1789','genus_name' => 'Cordia','species_name' => 'sebestena','common_name' => 'Geiger tree','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '1790','genus_name' => 'Cornus','species_name' => 'sessilis','common_name' => 'Blackfruit dogwood','growth_rate' => 'Moderate','height_at_maturity' => '31'),
            array('id' => '1792','genus_name' => 'Cordia','species_name' => 'sinensis','common_name' => 'Long leaved saucer-berry','growth_rate' => 'Slow','height_at_maturity' => '34'),
            array('id' => '1793','genus_name' => 'Corylus','species_name' => 'sieboldiana','common_name' => 'Japanese hazel','growth_rate' => '','height_at_maturity' => '16'),
            array('id' => '1794','genus_name' => 'Coccoloba','species_name' => 'sintenisii','common_name' => 'Uvero de monte','growth_rate' => 'Moderate','height_at_maturity' => '54'),
            array('id' => '1796','genus_name' => 'Cornus','species_name' => 'x slavinii','common_name' => 'Slavin\'s dogwood','growth_rate' => 'Moderate','height_at_maturity' => '31'),
            array('id' => '1797','genus_name' => 'Corylopsis','species_name' => 'spicata','common_name' => 'Spike Winter Hazel','growth_rate' => 'Fast','height_at_maturity' => '2'),
            array('id' => '1798','genus_name' => 'Condalia','species_name' => 'spathulata','common_name' => 'Squawbush','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '1799','genus_name' => 'Cornus','species_name' => 'sericea','common_name' => 'Red osier dogwood','growth_rate' => 'Fast','height_at_maturity' => '31'),
            array('id' => '1800','genus_name' => 'Cordyline','species_name' => 'stricta','common_name' => 'Narrow Leaved Palm Lily','growth_rate' => 'Fast','height_at_maturity' => '5'),
            array('id' => '1801','genus_name' => 'Colubrina','species_name' => 'stricta','common_name' => 'Comal nakedwood','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1802','genus_name' => 'Cordia','species_name' => 'sulcata','common_name' => 'Moral','growth_rate' => 'Slow','height_at_maturity' => '34'),
            array('id' => '1804','genus_name' => 'Cordia','species_name' => 'subcordata','common_name' => 'Kou','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '1805','genus_name' => 'Coccoloba','species_name' => 'swartzii','common_name' => 'Swartz\'s pigeonplum','growth_rate' => 'Moderate','height_at_maturity' => '39'),
            array('id' => '1806','genus_name' => 'Corymbia','species_name' => 'terminalis','common_name' => 'Desert Bloodwood','growth_rate' => 'Slow','height_at_maturity' => '18'),
            array('id' => '1807','genus_name' => 'Corymbia','species_name' => 'tessellaris','common_name' => 'Carbeen','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '1808','genus_name' => 'Combretum','species_name' => 'tetralophum','common_name' => 'ochaol','growth_rate' => '','height_at_maturity' => '17'),
            array('id' => '1809','genus_name' => 'Cordyline','species_name' => 'terminalis','common_name' => 'Cordyline terminalis','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '1810','genus_name' => 'Colubrina','species_name' => 'texensis','common_name' => 'Texan hogplum','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1812','genus_name' => 'Coccoloba','species_name' => 'tenuifolia','common_name' => 'Bahama pigeonplum','growth_rate' => 'Moderate','height_at_maturity' => '54'),
            array('id' => '1813','genus_name' => 'Corymbia','species_name' => 'torelliana','common_name' => 'Cadaghi','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '1814','genus_name' => 'Corymbia','species_name' => 'trachyphloia','common_name' => 'Corymbia trachyphloia','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '1818','genus_name' => 'Corypha','species_name' => 'utan','common_name' => 'Buri palm','growth_rate' => '','height_at_maturity' => '65'),
            array('id' => '1819','genus_name' => 'Coccoloba','species_name' => 'uvifera','common_name' => 'Sea grape','growth_rate' => 'Slow','height_at_maturity' => '38'),
            array('id' => '1820','genus_name' => 'Codiaeum','species_name' => 'variegatum','common_name' => 'Garden croton','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '1822','genus_name' => 'Coccoloba','species_name' => 'venosa','common_name' => 'False chiggergrape','growth_rate' => 'Moderate','height_at_maturity' => '54'),
            array('id' => '1823','genus_name' => 'Condalia','species_name' => 'velutina','common_name' => 'Condalia velutina','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '1825','genus_name' => 'Colubrina','species_name' => 'verrucosa','common_name' => 'Urban\'s nakedwood','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1826','genus_name' => 'Cochlospermum','species_name' => 'vitifolium','common_name' => 'Silk cottontree','growth_rate' => '','height_at_maturity' => '26')
        );

        Tree::insert($trees);

        $seeder = new TreeSpeciesSeeder3;
        $seeder->run();
    }
}