<?php

namespace Database\Seeders\TreeSpecies;

use App\Models\Tree\Tree;
use Illuminate\Database\Seeder;

class TreeSpeciesSeeder9 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $trees = array(
            array('id' => '6469','genus_name' => 'Sideroxylon','species_name' => 'lycioides','common_name' => 'Buckthorn bully','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '6474','genus_name' => 'Sideroxylon','species_name' => 'tenax','common_name' => 'Tough bully','growth_rate' => '','height_at_maturity' => '27'),
            array('id' => '6476','genus_name' => 'Simarouba','species_name' => 'tulae','common_name' => 'Aceitillo falso','growth_rate' => 'Moderate','height_at_maturity' => '63'),
            array('id' => '6477','genus_name' => 'Sloanea','species_name' => 'amygdalina','common_name' => 'Motillo','growth_rate' => '','height_at_maturity' => '100'),
            array('id' => '6478','genus_name' => 'Sloanea','species_name' => 'berteriana','common_name' => 'Bullwood','growth_rate' => 'Moderate','height_at_maturity' => '100'),
            array('id' => '6481','genus_name' => 'Smilax','species_name' => 'bona-nox','common_name' => 'Greenbrier','growth_rate' => 'Fast','height_at_maturity' => '4'),
            array('id' => '6482','genus_name' => 'Smilax','species_name' => 'hispida','common_name' => 'Bristly greenbrier','growth_rate' => '','height_at_maturity' => '2'),
            array('id' => '6484','genus_name' => 'Sophora','species_name' => 'affinis','common_name' => 'Texas sophora','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '6485','genus_name' => 'Sorbus','species_name' => 'alnifolia','common_name' => 'Korean mountain ash','growth_rate' => '','height_at_maturity' => '35'),
            array('id' => '6486','genus_name' => 'Sonneratia','species_name' => 'alba','common_name' => 'Mangrove apple','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '6487','genus_name' => 'Sorbus','species_name' => 'americana','common_name' => 'American mountain ash','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '6488','genus_name' => 'Solanum','species_name' => 'americanum','common_name' => 'American black nightshade','growth_rate' => '','height_at_maturity' => '4'),
            array('id' => '6489','genus_name' => 'Solanum','species_name' => 'aphyodendron','common_name' => 'Zopilote yerba','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '6490','genus_name' => 'Sorbus','species_name' => 'aria','common_name' => 'Whitebeam','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '6492','genus_name' => 'Sophora','species_name' => 'arizonica','common_name' => 'Arizona necklacepod','growth_rate' => 'Moderate','height_at_maturity' => '55'),
            array('id' => '6494','genus_name' => 'Sorbus','species_name' => 'aucuparia','common_name' => 'European mountain ash','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '6497','genus_name' => 'Sorbus','species_name' => 'californica','common_name' => 'California mountain ash','growth_rate' => 'Moderate','height_at_maturity' => '47'),
            array('id' => '6498','genus_name' => 'Sophora','species_name' => 'chrysophylla','common_name' => 'Mamani','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '6499','genus_name' => 'Sorbus','species_name' => 'commixta','common_name' => 'Japanese Rowan','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '6500','genus_name' => 'Sorbus','species_name' => 'commixta \'Embley\'','common_name' => 'Chinese Scarlet Rowan','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '6501','genus_name' => 'Sorbus','species_name' => 'decora','common_name' => 'Showy mountain ash','growth_rate' => 'Moderate','height_at_maturity' => '47'),
            array('id' => '6502','genus_name' => 'Sorbus','species_name' => 'domestica','common_name' => 'Service Tree','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '6503','genus_name' => 'Solanum','species_name' => 'donianum','common_name' => 'Mullein nightshade','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '6504','genus_name' => 'Solanum','species_name' => 'drymophilum','common_name' => 'Bahama nightshade','growth_rate' => 'Moderate','height_at_maturity' => '19'),
            array('id' => '6505','genus_name' => 'Sorbus','species_name' => 'dumosa','common_name' => 'Arizona mountain ash','growth_rate' => 'Moderate','height_at_maturity' => '47'),
            array('id' => '6506','genus_name' => 'Solanum','species_name' => 'erianthum','common_name' => 'Potatotree','growth_rate' => '','height_at_maturity' => '33'),
            array('id' => '6507','genus_name' => 'Sorbus','species_name' => 'groenlandica','common_name' => 'Greenland mountain ash','growth_rate' => 'Moderate','height_at_maturity' => '47'),
            array('id' => '6508','genus_name' => 'Sophora','species_name' => 'gypsophila','common_name' => 'Guadalupe Mountain necklacepos','growth_rate' => 'Moderate','height_at_maturity' => '55'),
            array('id' => '6510','genus_name' => 'Sorbus','species_name' => 'hupehensis','common_name' => 'Hupeh Rowan','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '6511','genus_name' => 'Sorbus','species_name' => 'hupehensis v coral fire','common_name' => 'Mountain ash \'Coral Fire\'','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '6512','genus_name' => 'Sorbus','species_name' => 'hupehensis v columbia','common_name' => 'Mountain ash \'Columbia Queen\'','growth_rate' => 'Fast','height_at_maturity' => ''),
            array('id' => '6513','genus_name' => 'Sorbus','species_name' => 'hybrida','common_name' => 'Oakleaf mountain ash','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '6514','genus_name' => 'Sorbus','species_name' => 'intermedia','common_name' => 'Swedish Whitebeam','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '6515','genus_name' => 'Sophora','species_name' => 'japonica','common_name' => 'Japanese pagoda tree','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '6516','genus_name' => 'Sorbus','species_name' => 'latifolia','common_name' => 'Broadleaf Whitebeam','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6517','genus_name' => 'Solanum','species_name' => 'laxum','common_name' => 'Potato vine','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '6518','genus_name' => 'Sophora','species_name' => 'leachiana','common_name' => 'Western necklacepod','growth_rate' => 'Moderate','height_at_maturity' => '55'),
            array('id' => '6520','genus_name' => 'Solanum','species_name' => 'mauritianum','common_name' => 'Earleaf nightshade','growth_rate' => '','height_at_maturity' => '13'),
            array('id' => '6521','genus_name' => 'Sophora','species_name' => 'microphylla','common_name' => 'Kowhai','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '6522','genus_name' => 'Sorbus','species_name' => 'mougeotii','common_name' => 'Pyrenean Whitebeam','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '6526','genus_name' => 'Solanum','species_name' => 'rugosum','common_name' => 'Tabacon aspero','growth_rate' => '','height_at_maturity' => '16'),
            array('id' => '6527','genus_name' => 'Sorbus','species_name' => 'sargentiana','common_name' => 'Sargent\'s Rowan','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '6528','genus_name' => 'Sorbus','species_name' => 'sambucifolia','common_name' => 'Siberian mountain ash','growth_rate' => 'Moderate','height_at_maturity' => '47'),
            array('id' => '6529','genus_name' => 'Sorbus','species_name' => 'scopulina','common_name' => 'Greene\'s mountain ash','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '6530','genus_name' => 'Sophora','species_name' => 'secundiflora','common_name' => 'Mescalbean','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '6531','genus_name' => 'Sorbus','species_name' => 'sitchensis','common_name' => 'Western mountain ash','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '6532','genus_name' => 'Sorbaria','species_name' => 'sorbifolia','common_name' => 'False spiraea','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '6533','genus_name' => 'Sophora','species_name' => 'tetraptera','common_name' => 'Large-leaved Kowhai','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '6534','genus_name' => 'Sorbus','species_name' => 'thuringiac','common_name' => 'Bastard service-tree','growth_rate' => 'Moderate','height_at_maturity' => '47'),
            array('id' => '6535','genus_name' => 'Sorbus','species_name' => 'thuringiaca','common_name' => 'Bastard Service Tree','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '6536','genus_name' => 'Sorbus','species_name' => 'thibetica \'John Mitchell\'','common_name' => 'Mitchell\'s Whitebeam','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '6537','genus_name' => 'Sorbus','species_name' => 'torminalis','common_name' => 'Wild Service Tree','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '6538','genus_name' => 'Sophora','species_name' => 'tomentosa','common_name' => 'Yellow necklacepod','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '6539','genus_name' => 'Solanum','species_name' => 'torvum','common_name' => 'Turkey berry','growth_rate' => '','height_at_maturity' => '16'),
            array('id' => '6540','genus_name' => 'Sorbus','species_name' => 'vilmorinii','common_name' => 'Chinese Mountain Ash','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '6543','genus_name' => 'Spiraea','species_name' => 'betulifolia','common_name' => 'White spirea','growth_rate' => '','height_at_maturity' => '3'),
            array('id' => '6544','genus_name' => 'Spiraea','species_name' => 'billiardi','common_name' => 'Billard\'s spirea','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '6545','genus_name' => 'Spiraea','species_name' => 'bumald','common_name' => 'Bumald spiraea','growth_rate' => 'Fast','height_at_maturity' => '3'),
            array('id' => '6546','genus_name' => 'Spathodea','species_name' => 'campanulata','common_name' => 'African tulip tree','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '6547','genus_name' => 'Spiraea','species_name' => 'cantoniensis','common_name' => 'Reeves\' meadowsweet','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '6550','genus_name' => 'Spondias','species_name' => 'dulcis','common_name' => 'Ambarella','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '6552','genus_name' => 'Spiraea','species_name' => 'japonica','common_name' => 'Japanese meadowsweet','growth_rate' => '','height_at_maturity' => '5'),
            array('id' => '6554','genus_name' => 'Sparattosperma','species_name' => 'leucanthum','common_name' => 'Tarumacillo','growth_rate' => '','height_at_maturity' => '82'),
            array('id' => '6555','genus_name' => 'Spondias','species_name' => 'mombin','common_name' => 'Yellow mombim','growth_rate' => 'Moderate','height_at_maturity' => '45'),
            array('id' => '6556','genus_name' => 'Spondias','species_name' => 'pinnata','common_name' => 'wild mango','growth_rate' => '','height_at_maturity' => '35'),
            array('id' => '6557','genus_name' => 'Spiraea','species_name' => 'prunifolia','common_name' => 'Bridalwreath spirea','growth_rate' => '','height_at_maturity' => '9'),
            array('id' => '6558','genus_name' => 'Spondias','species_name' => 'purpurea','common_name' => 'Purple mombin','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '6565','genus_name' => 'Spiraea','species_name' => 'thunbergii','common_name' => 'Thunberg\'s meadowsweet','growth_rate' => '','height_at_maturity' => '5'),
            array('id' => '6567','genus_name' => 'Spiraea','species_name' => 'trilobata','common_name' => 'Asian meadowsweet','growth_rate' => '','height_at_maturity' => '5'),
            array('id' => '6571','genus_name' => 'Styrax','species_name' => 'americanus','common_name' => 'American snowbell','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '6572','genus_name' => 'Streblus','species_name' => 'anthropophagorum','common_name' => 'streblus','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '6573','genus_name' => 'Sterculia','species_name' => 'apetala','common_name' => 'Panama tree','growth_rate' => 'Moderate','height_at_maturity' => '131'),
            array('id' => '6574','genus_name' => 'Streblus','species_name' => 'asper','common_name' => 'Kalios','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '6575','genus_name' => 'Staphylea','species_name' => 'bolanderi','common_name' => 'Sierra bladdernut','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6578','genus_name' => 'Sterculia','species_name' => 'discolor','common_name' => 'Sterculia rosada','growth_rate' => 'Moderate','height_at_maturity' => '100'),
            array('id' => '6579','genus_name' => 'Stenocereus','species_name' => 'dumortieri','common_name' => 'Stenocereus dumortieri','growth_rate' => 'Slow','height_at_maturity' => '13'),
            array('id' => '6581','genus_name' => 'Sterculia','species_name' => 'foetida','common_name' => 'australian flame tree','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '6582','genus_name' => 'Styrax','species_name' => 'grandifolium','common_name' => 'Bigleaf snowbell','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '6584','genus_name' => 'Styrax','species_name' => 'japonicus','common_name' => 'Japanese snowbell','growth_rate' => 'Slow','height_at_maturity' => '38'),
            array('id' => '6586','genus_name' => 'Stewartia','species_name' => 'koreana','common_name' => 'Stewartia','growth_rate' => 'Slow','height_at_maturity' => '37'),
            array('id' => '6587','genus_name' => 'Stereospermum','species_name' => 'kunthianum','common_name' => 'Pink jacaranda','growth_rate' => 'Moderate','height_at_maturity' => '51'),
            array('id' => '6590','genus_name' => 'Stewartia','species_name' => 'malacodendron','common_name' => 'Silky camellia','growth_rate' => 'Slow','height_at_maturity' => '13'),
            array('id' => '6592','genus_name' => 'Stahlia','species_name' => 'monosperma','common_name' => 'Cobana negra','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '6593','genus_name' => 'Strelitzia','species_name' => 'nicolai','common_name' => 'Bird of paradise tree','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '6594','genus_name' => 'Styrax','species_name' => 'obassia','common_name' => 'Fragrant snowbell','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '6596','genus_name' => 'Stewartia','species_name' => 'ovata','common_name' => 'Mountain stewartia','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '6599','genus_name' => 'Streblus','species_name' => 'pendulinus','common_name' => 'Hawai\'i roughbush','growth_rate' => '','height_at_maturity' => '38'),
            array('id' => '6600','genus_name' => 'Staphylea','species_name' => 'pinnata','common_name' => 'European Bladder-Nut','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '6601','genus_name' => 'Styrax','species_name' => 'platanifolius','common_name' => 'Sycamoreleaf snowbell','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '6602','genus_name' => 'Styrax','species_name' => 'portoricensis','common_name' => 'Palo de jazmin','growth_rate' => 'Slow','height_at_maturity' => '38'),
            array('id' => '6603','genus_name' => 'Stewartia','species_name' => 'pseudocamellia','common_name' => 'Deciduous Stewartia','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '6604','genus_name' => 'Sterculia','species_name' => 'quadrifida','common_name' => 'Peanut Tree','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '6605','genus_name' => 'Styrax','species_name' => 'redivivus','common_name' => 'Drug snowbell','growth_rate' => 'Slow','height_at_maturity' => '38'),
            array('id' => '6606','genus_name' => 'Stenocarpus','species_name' => 'salignus','common_name' => 'Killarney Beefwood','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '6607','genus_name' => 'Stenocarpus','species_name' => 'sinuatus','common_name' => 'Firewheel tree','growth_rate' => 'Slow','height_at_maturity' => '35'),
            array('id' => '6608','genus_name' => 'Stewartia','species_name' => 'sinensis','common_name' => 'Chinese Stewartia','growth_rate' => 'Moderate','height_at_maturity' => '11'),
            array('id' => '6610','genus_name' => 'Styphelia','species_name' => 'tameiameiae','common_name' => 'Pukiawe','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '6612','genus_name' => 'Staphylea','species_name' => 'trifolia','common_name' => 'American bladdernut','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '6614','genus_name' => 'Suriana','species_name' => 'maritima','common_name' => 'Bay cedar','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6616','genus_name' => 'Swinglea','species_name' => 'glutinosa','common_name' => 'Lemon swinglea','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '6617','genus_name' => 'Swietenia','species_name' => 'humilis','common_name' => 'Pacific coast mahogany','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '6619','genus_name' => 'Swietenia','species_name' => 'mahogani','common_name' => 'West indian mahogany','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '6620','genus_name' => 'Swietenia','species_name' => 'macrophylla','common_name' => 'Honduras mahogany','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '6624','genus_name' => 'Symphoricarpos','species_name' => 'albus','common_name' => 'Common snowberry','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '6625','genus_name' => 'Syzygium','species_name' => 'angophoroides','common_name' => 'Watergum','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '6626','genus_name' => 'Syzygium','species_name' => 'armstrongii','common_name' => 'White Bush Apple','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '6627','genus_name' => 'Syzygium','species_name' => 'australe','common_name' => 'Scrub Cherry','growth_rate' => 'Moderate','height_at_maturity' => '82'),
            array('id' => '6628','genus_name' => 'Syringa','species_name' => 'chinensi','common_name' => 'Chinese lilac','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '6629','genus_name' => 'Symplocos','species_name' => 'paniculata','common_name' => 'Asiatic sweetleaf','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '6631','genus_name' => 'Syzygium','species_name' => 'crebrinerve','common_name' => 'Purple Cherry','growth_rate' => 'Fast','height_at_maturity' => '45'),
            array('id' => '6632','genus_name' => 'Syzygium','species_name' => 'cumini','common_name' => 'Jambolan plum','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '6633','genus_name' => 'Synsepalum','species_name' => 'dulcificum','common_name' => 'Miracle Berry','growth_rate' => '','height_at_maturity' => '19'),
            array('id' => '6634','genus_name' => 'Syzygium','species_name' => 'fibrosum','common_name' => 'Red Bush Apple','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '6635','genus_name' => 'Syzygium','species_name' => 'forte','common_name' => 'White Apple','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '6636','genus_name' => 'Syzygium','species_name' => 'francisii','common_name' => 'Giant Water Gum','growth_rate' => 'Moderate','height_at_maturity' => '148'),
            array('id' => '6637','genus_name' => 'Syncarpia','species_name' => 'glomerulifera','common_name' => 'Turpentine tree','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '6638','genus_name' => 'Syzygium','species_name' => 'grande','common_name' => 'Sea apple','growth_rate' => 'Fast','height_at_maturity' => '150'),
            array('id' => '6641','genus_name' => 'Syzygium','species_name' => 'jambos','common_name' => 'Malabar plum','growth_rate' => 'Slow','height_at_maturity' => '35'),
            array('id' => '6642','genus_name' => 'Syringa','species_name' => 'josikaea','common_name' => 'Hungarian lilac','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '6646','genus_name' => 'Syzygium','species_name' => 'luehmannii','common_name' => 'Small Leaved Lilly Pilly','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '6648','genus_name' => 'Syzygium','species_name' => 'malaccense','common_name' => 'Malaysian apple','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '6649','genus_name' => 'Syzygium','species_name' => 'minutuliflorum','common_name' => 'Gove Satinash','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '6652','genus_name' => 'Syzygium','species_name' => 'moorei','common_name' => 'Coolamon','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '6653','genus_name' => 'Syzygium','species_name' => 'nervosum','common_name' => 'Forest Apple','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '6655','genus_name' => 'Syringa','species_name' => 'oblata dilatata','common_name' => 'Korean early lilac','growth_rate' => '','height_at_maturity' => '11'),
            array('id' => '6657','genus_name' => 'Syzygium','species_name' => 'oleosum','common_name' => 'Satinash','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6658','genus_name' => 'Symphoricarpos','species_name' => 'orbiculatus','common_name' => 'Coralberry','growth_rate' => '','height_at_maturity' => '5'),
            array('id' => '6661','genus_name' => 'Syzygium','species_name' => 'paniculatum','common_name' => 'Syzygium paniculatum','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '6662','genus_name' => 'Syringa','species_name' => 'patula','common_name' => 'Manchurian lilac','growth_rate' => '','height_at_maturity' => '9'),
            array('id' => '6663','genus_name' => 'Syringa','species_name' => 'persic','common_name' => 'Persian lilac','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '6665','genus_name' => 'Syringa','species_name' => 'reticulata','common_name' => 'Japanese tree lilac','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6667','genus_name' => 'Syagrus','species_name' => 'romanzoffiana','common_name' => 'Syagrus romanzoffiana','growth_rate' => 'Slow','height_at_maturity' => '82'),
            array('id' => '6669','genus_name' => 'Syzygium','species_name' => 'sandwicense','common_name' => '\'ohi\'a ha','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '6670','genus_name' => 'Symplocos','species_name' => 'tinctoria','common_name' => 'Common sweetleaf','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6672','genus_name' => 'Syringa','species_name' => 'villosa','common_name' => 'Villous lilac','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '6673','genus_name' => 'Syringa','species_name' => 'vulgaris','common_name' => 'Common lilac','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '6674','genus_name' => 'Syzygium','species_name' => 'wilsonii','common_name' => 'Powder-puff lilliy pilly','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '6675','genus_name' => 'Tamarix','species_name' => 'africana','common_name' => 'African tamarisk','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '6677','genus_name' => 'Tamarix','species_name' => 'aphylla','common_name' => 'Athel tamarisk','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '6678','genus_name' => 'Tabebuia','species_name' => 'aurea','common_name' => 'Caribbean trumpet-tree','growth_rate' => 'Moderate','height_at_maturity' => '45'),
            array('id' => '6680','genus_name' => 'Taxodium','species_name' => 'ascendens','common_name' => 'Pond cypress','growth_rate' => 'Slow','height_at_maturity' => '100'),
            array('id' => '6681','genus_name' => 'Tabebuia','species_name' => 'avellanedae','common_name' => 'Ipe-roxo','growth_rate' => 'Fast','height_at_maturity' => '35'),
            array('id' => '6682','genus_name' => 'Taxus','species_name' => 'baccata','common_name' => 'English yew','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '6684','genus_name' => 'Taxus','species_name' => 'baccata \'fastigiata\'','common_name' => 'European yew','growth_rate' => '','height_at_maturity' => '8'),
            array('id' => '6685','genus_name' => 'Tabebuia','species_name' => 'billbergii','common_name' => 'Puy','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '6687','genus_name' => 'Taxus','species_name' => 'brevifolia','common_name' => 'Pacific yew','growth_rate' => 'Slow','height_at_maturity' => '35'),
            array('id' => '6688','genus_name' => 'Taxus','species_name' => 'canadensis','common_name' => 'Canada yew','growth_rate' => 'Slow','height_at_maturity' => '35'),
            array('id' => '6691','genus_name' => 'Tabebuia','species_name' => 'chrysantha','common_name' => 'Roble amarillo','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '6692','genus_name' => 'Tabebuia','species_name' => 'chrysea','common_name' => 'Canahuate','growth_rate' => 'Slow','height_at_maturity' => '98'),
            array('id' => '6693','genus_name' => 'Tamarix','species_name' => 'chinensis','common_name' => 'Fivestamen tamarisk','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '6694','genus_name' => 'Tabebuia','species_name' => 'chrysotricha','common_name' => 'Ipe-amarelo','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '6696','genus_name' => 'Tabernaemontana','species_name' => 'citrifolia','common_name' => 'Milkwood','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '6697','genus_name' => 'Taiwania','species_name' => 'cryptomerioides','common_name' => 'Taiwania','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '6698','genus_name' => 'Taxus','species_name' => 'cuspidata','common_name' => 'Japanese yew','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '6699','genus_name' => 'Taxodium','species_name' => 'distichum','common_name' => 'Baldcypress','growth_rate' => 'Fast','height_at_maturity' => '130'),
            array('id' => '6700','genus_name' => 'Tabernaemontana','species_name' => 'divaricata','common_name' => 'Pinwheelflower','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '6702','genus_name' => 'Tabebuia','species_name' => 'donnell-smithii','common_name' => 'Primavera','growth_rate' => 'Fast','height_at_maturity' => '117'),
            array('id' => '6703','genus_name' => 'Taxus','species_name' => 'floridana','common_name' => 'Florida yew','growth_rate' => 'Slow','height_at_maturity' => '35'),
            array('id' => '6706','genus_name' => 'Tabebuia','species_name' => 'glomerata','common_name' => 'Arawnig','growth_rate' => 'Moderate','height_at_maturity' => '45'),
            array('id' => '6708','genus_name' => 'Tabebuia','species_name' => 'haemantha','common_name' => 'Roble cimarron','growth_rate' => 'Moderate','height_at_maturity' => '17'),
            array('id' => '6709','genus_name' => 'Tabebuia','species_name' => 'heptaphylla','common_name' => 'Robie blanco','growth_rate' => '','height_at_maturity' => '45'),
            array('id' => '6710','genus_name' => 'Tabebuia','species_name' => 'impetiginosa','common_name' => 'Pink trumpet tree','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '6711','genus_name' => 'Tamarindus','species_name' => 'indica','common_name' => 'India tamarind','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '6712','genus_name' => 'Tasmannia','species_name' => 'lanceolata','common_name' => 'Mountain Pepper','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '6714','genus_name' => 'Talauma','species_name' => 'mexicana','common_name' => 'Talauma mexicana','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '6715','genus_name' => 'Taxodium','species_name' => 'mucronatum','common_name' => 'Montezuma cypress','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '6718','genus_name' => 'Tabebuia','species_name' => 'heterophylla','common_name' => 'White cedar','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '6720','genus_name' => 'Tamarix','species_name' => 'parviflora','common_name' => 'Small flower tamerisk','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '6723','genus_name' => 'Tamarix','species_name' => 'ramosissima','common_name' => 'Saltcedar','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '6724','genus_name' => 'Tabebuia','species_name' => 'rigida','common_name' => 'Roble de sierra','growth_rate' => 'Moderate','height_at_maturity' => '45'),
            array('id' => '6725','genus_name' => 'Tabebuia','species_name' => 'rosea','common_name' => 'Apamate','growth_rate' => 'Moderate','height_at_maturity' => '83'),
            array('id' => '6727','genus_name' => 'Tabernaemontana','species_name' => 'rotensis','common_name' => 'Tabernaemontana rotensis','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '6728','genus_name' => 'Tarenna','species_name' => 'sambucina','common_name' => 'manunu','growth_rate' => '','height_at_maturity' => '45'),
            array('id' => '6729','genus_name' => 'Tabebuia','species_name' => 'schumanniana','common_name' => 'Roble colorado','growth_rate' => 'Moderate','height_at_maturity' => '45'),
            array('id' => '6730','genus_name' => 'Tabebuia','species_name' => 'serratifolia','common_name' => 'Yellow poui','growth_rate' => 'Moderate','height_at_maturity' => '123'),
            array('id' => '6733','genus_name' => 'Tasmannia','species_name' => 'xerophila','common_name' => 'Alpine Pepper','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '6734','genus_name' => 'Tetrazygia','species_name' => 'angustifolia','common_name' => 'Stinkingfish','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '6735','genus_name' => 'Terminalia','species_name' => 'arostrata','common_name' => 'Nutwood','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '6737','genus_name' => 'Tetragastris','species_name' => 'balsamifera','common_name' => 'Masa','growth_rate' => '','height_at_maturity' => '80'),
            array('id' => '6738','genus_name' => 'Tetrazygia','species_name' => 'bicolor','common_name' => 'Florida clover ash','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '6739','genus_name' => 'Tetrazygia','species_name' => 'biflora','common_name' => 'Puerto rico clover ash','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '6740','genus_name' => 'Terminalia','species_name' => 'catappa','common_name' => 'Tropical almond','growth_rate' => 'Moderate','height_at_maturity' => '45'),
            array('id' => '6741','genus_name' => 'Terminalia','species_name' => 'carolinensis','common_name' => 'Kaima tree','growth_rate' => '','height_at_maturity' => '80'),
            array('id' => '6744','genus_name' => 'Tecoma','species_name' => 'capensis','common_name' => 'Cape honeysuckle','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '6745','genus_name' => 'Tecoma','species_name' => 'castanifolia','common_name' => 'Chestnutleaf trumpetbush','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '6748','genus_name' => 'Tetrazygia','species_name' => 'crotonifolia','common_name' => 'Hillside clover ash','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '6749','genus_name' => 'Tetradium','species_name' => 'daniellii','common_name' => 'Korean Evodia','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '6751','genus_name' => 'Templetonia','species_name' => 'egena','common_name' => 'Desert Broombush','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '6752','genus_name' => 'Tetrazygia','species_name' => 'elaeagnoides','common_name' => 'Krekre','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '6753','genus_name' => 'Terminalia','species_name' => 'ferdinandiana','common_name' => 'Billy Goat Plum','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '6755','genus_name' => 'Tetraplasandra','species_name' => 'flynnii','common_name' => 'Flynn\'s \'ohe','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '6757','genus_name' => 'Tectona','species_name' => 'grandis','common_name' => 'Teak','growth_rate' => '','height_at_maturity' => '114'),
            array('id' => '6758','genus_name' => 'Tetraplasandra','species_name' => 'gymnocarpa','common_name' => 'Koolau range \'ohe','growth_rate' => '','height_at_maturity' => '33'),
            array('id' => '6759','genus_name' => 'Tetraplasandra','species_name' => 'hawaiensis','common_name' => 'Hawai\'i \'ohe','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '6760','genus_name' => 'Ternstroemia','species_name' => 'heptasepala','common_name' => 'Saintedwood','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '6764','genus_name' => 'Terminalia','species_name' => 'ivorensis','common_name' => 'Ivory coast almond','growth_rate' => '','height_at_maturity' => '150'),
            array('id' => '6765','genus_name' => 'Gardenia','species_name' => 'jasminoides','common_name' => 'Bower of beauty','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '6766','genus_name' => 'Tetraplasandra','species_name' => 'kavaiensis','common_name' => '\'ohe\'ohe','growth_rate' => '','height_at_maturity' => '52'),
            array('id' => '6769','genus_name' => 'Ternstroemia','species_name' => 'luquillensis','common_name' => 'Palo colorado','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '6770','genus_name' => 'Terminalia','species_name' => 'mantaly','common_name' => 'Madagascar almond','growth_rate' => 'Fast','height_at_maturity' => '37'),
            array('id' => '6772','genus_name' => 'Terminalia','species_name' => 'microcarpa','common_name' => 'Damson','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '6773','genus_name' => 'Telopea','species_name' => 'mongaensis','common_name' => 'Monga Waratah','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '6774','genus_name' => 'Terminalia','species_name' => 'muelleri','common_name' => 'Australian almond','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '6775','genus_name' => 'Terminalia','species_name' => 'muellerii','common_name' => 'Terminalia muellerii','growth_rate' => 'Moderate','height_at_maturity' => ''),
            array('id' => '6776','genus_name' => 'Terminalia','species_name' => 'myriocarpa','common_name' => 'East indian almond','growth_rate' => 'Fast','height_at_maturity' => '83'),
            array('id' => '6777','genus_name' => 'Tetraplasandra','species_name' => 'oahuensis','common_name' => '\'ohe mauka','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '6778','genus_name' => 'Terminalia','species_name' => 'oblonga','common_name' => 'Peruvian almond','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '6780','genus_name' => 'Telopea','species_name' => 'oreades','common_name' => 'Gippsland Waratah','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '6781','genus_name' => 'Tetrapanax','species_name' => 'papyrifer','common_name' => 'Ricepaper plant','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '6782','genus_name' => 'Ternstroemia','species_name' => 'peduncularis','common_name' => 'Copey vera','growth_rate' => '','height_at_maturity' => '33'),
            array('id' => '6783','genus_name' => 'Terminalia','species_name' => 'platyphylla','common_name' => 'Durin','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '6787','genus_name' => 'Terminalia','species_name' => 'samoensis','common_name' => 'talie','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '6788','genus_name' => 'Tecoma','species_name' => 'stans','common_name' => 'Ginger-thomas','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '6789','genus_name' => 'Ternstroemia','species_name' => 'stahlii','common_name' => 'Mamey de cura','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '6790','genus_name' => 'Ternstroemia','species_name' => 'subsessilis','common_name' => 'El yunque colorado','growth_rate' => '','height_at_maturity' => '59'),
            array('id' => '6791','genus_name' => 'Terminalia','species_name' => 'superba','common_name' => 'superb terminalia','growth_rate' => '','height_at_maturity' => '180'),
            array('id' => '6793','genus_name' => 'Ternstroemia','species_name' => 'sylvatica','common_name' => 'Ternstroemia sylvatica','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '6795','genus_name' => 'Tetrazygia','species_name' => 'urbani','common_name' => 'Cenizo','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '6796','genus_name' => 'Tetraplasandra','species_name' => 'waialealae','common_name' => 'Mt. waialeale \'ohe','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '6797','genus_name' => 'Tetraplasandra','species_name' => 'waimeae','common_name' => '\'ohe kiko \'ola','growth_rate' => '','height_at_maturity' => '35'),
            array('id' => '6798','genus_name' => 'Theobroma','species_name' => 'cacao','common_name' => 'Cacao','growth_rate' => '','height_at_maturity' => '26'),
            array('id' => '6799','genus_name' => 'Thujopsis','species_name' => 'dolabrata','common_name' => 'False arborvitae','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '6801','genus_name' => 'Theobroma','species_name' => 'grandiflorum','common_name' => 'Cupuassu','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '6803','genus_name' => 'Thrinax','species_name' => 'morrisii','common_name' => 'Key thatch palm','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '6804','genus_name' => 'Thuja','species_name' => 'occidentalis','common_name' => 'Northern white cedar','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '6805','genus_name' => 'Platycladus','species_name' => 'orientalis','common_name' => 'Oriental arborvitae','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '6806','genus_name' => 'Thevetia','species_name' => 'ovata','common_name' => 'Thevetia ovata','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '6807','genus_name' => 'Thrinax','species_name' => 'radiata','common_name' => 'Florida thatchpalm','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '6808','genus_name' => 'Thevetia','species_name' => 'peruviana','common_name' => 'Luckynut','growth_rate' => 'Fast','height_at_maturity' => '23'),
            array('id' => '6809','genus_name' => 'Thuja','species_name' => 'plicata','common_name' => 'Western redcedar','growth_rate' => 'Slow','height_at_maturity' => '150'),
            array('id' => '6810','genus_name' => 'Thespesia','species_name' => 'populnea','common_name' => 'Portia tree','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '6811','genus_name' => 'Thouinia','species_name' => 'striata','common_name' => 'Ceboruquillo','growth_rate' => '','height_at_maturity' => '65'),
            array('id' => '6812','genus_name' => 'Thevetia','species_name' => 'thevetioides','common_name' => 'Giant thevetia','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '6813','genus_name' => 'Tilia','species_name' => 'americana','common_name' => 'American basswood','growth_rate' => 'Moderate','height_at_maturity' => '100'),
            array('id' => '6814','genus_name' => 'Tilia','species_name' => 'amurensis','common_name' => 'Amur linden','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '6815','genus_name' => 'Tilia','species_name' => 'americana \'Redmond\'','common_name' => 'Redmond American Linden','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '6816','genus_name' => 'Tilia','species_name' => 'americana v caroliniana','common_name' => 'Carolina basswood','growth_rate' => 'Moderate','height_at_maturity' => '88'),
            array('id' => '6817','genus_name' => 'Tilia','species_name' => 'cordata','common_name' => 'Littleleaf linden','growth_rate' => 'Moderate','height_at_maturity' => '100'),
            array('id' => '6818','genus_name' => 'Tilia','species_name' => 'cordata \'Greenspire\'','common_name' => '\'Greenspire\' littleleaf linden','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '6819','genus_name' => 'Tilia','species_name' => 'vulgari','common_name' => 'Common linden','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '6820','genus_name' => 'Tilia','species_name' => 'europae','common_name' => 'Common lime','growth_rate' => 'Moderate','height_at_maturity' => '129'),
            array('id' => '6821','genus_name' => 'Tilia','species_name' => 'euchlora','common_name' => 'Crimean linden','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '6822','genus_name' => 'Tilia','species_name' => 'flaccid','common_name' => 'Tilia x flaccida','growth_rate' => 'Slow','height_at_maturity' => '26'),
            array('id' => '6823','genus_name' => 'Tibouchina','species_name' => 'granulosa','common_name' => 'Brazilian glorytree','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '6824','genus_name' => 'Tilia','species_name' => 'americana v heterophylla','common_name' => 'White basswood','growth_rate' => 'Moderate','height_at_maturity' => '90'),
            array('id' => '6826','genus_name' => 'Tibouchina','species_name' => 'mutabilis','common_name' => 'Quaresmeira ou tibuchina','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '6827','genus_name' => 'Tilia','species_name' => 'petiolaris','common_name' => 'Pendent silver linden','growth_rate' => 'Moderate','height_at_maturity' => '80'),
            array('id' => '6828','genus_name' => 'Tilia','species_name' => 'platyphyllos','common_name' => 'Bigleaf linden','growth_rate' => 'Moderate','height_at_maturity' => '80'),
            array('id' => '6830','genus_name' => 'Tipuana','species_name' => 'tipu','common_name' => 'Pride of bolivia','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '6831','genus_name' => 'Timonius','species_name' => 'timon','common_name' => 'Tim-Tim','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '6832','genus_name' => 'Tilia','species_name' => 'tomentosa','common_name' => 'Silver linden','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '6835','genus_name' => 'Tibouchina','species_name' => 'urvilleana','common_name' => 'Princess-flower','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '6836','genus_name' => 'Tournefortia','species_name' => 'argentea','common_name' => 'Velvetleaf soldierbush','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '6838','genus_name' => 'Torreya','species_name' => 'californica','common_name' => 'California torreya','growth_rate' => 'Slow','height_at_maturity' => '100'),
            array('id' => '6839','genus_name' => 'Toona','species_name' => 'ciliata','common_name' => 'Australian redcedar','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '6840','genus_name' => 'Torralbasia','species_name' => 'cuneifolia','common_name' => 'Boje','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '6842','genus_name' => 'Torreya','species_name' => 'grandis','common_name' => 'Chinese nutmeg tree','growth_rate' => 'Slow','height_at_maturity' => '80'),
            array('id' => '6844','genus_name' => 'Touchardia','species_name' => 'latifolia','common_name' => 'Olona','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '6848','genus_name' => 'Torreya','species_name' => 'nucifera','common_name' => 'Japanese torreya','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '6849','genus_name' => 'Toxicodendron','species_name' => 'radicans','common_name' => 'Poison ivy','growth_rate' => 'Moderate','height_at_maturity' => '55'),
            array('id' => '6850','genus_name' => 'Toxicodendron','species_name' => 'rydbergii','common_name' => 'Western poison ivy','growth_rate' => 'Moderate','height_at_maturity' => '55'),
            array('id' => '6852','genus_name' => 'Toxicocendron','species_name' => 'succedaneum','common_name' => 'Rhus Tree','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '6853','genus_name' => 'Torreya','species_name' => 'taxifolia','common_name' => 'Florida torreya','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '6854','genus_name' => 'Toxicodendron','species_name' => 'vernix','common_name' => 'Poison sumac','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '6855','genus_name' => 'Toxicodendron','species_name' => 'vernicifluum','common_name' => 'Varnish Tree','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '6856','genus_name' => 'Trithrinax','species_name' => 'acanthocoma','common_name' => 'Brizilian needle palm','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '6857','genus_name' => 'Triplaris','species_name' => 'americana','common_name' => 'Palo diablo','growth_rate' => 'Fast','height_at_maturity' => '82'),
            array('id' => '6862','genus_name' => 'Tristaniopsis','species_name' => 'conferta','common_name' => 'Brisbane box','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '6863','genus_name' => 'Triplaris','species_name' => 'cumingiana','common_name' => 'ant tree','growth_rate' => '','height_at_maturity' => '70'),
            array('id' => '6865','genus_name' => 'Trachycarpus','species_name' => 'fortunei','common_name' => 'Windmill palm','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '6866','genus_name' => 'Trichanthera','species_name' => 'gigantea','common_name' => 'Aro blanco','growth_rate' => 'Fast','height_at_maturity' => '39'),
            array('id' => '6867','genus_name' => 'Trichilia','species_name' => 'glabra','common_name' => 'Trichilia glabra','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '6869','genus_name' => 'Trichilia','species_name' => 'hirta','common_name' => 'Broomstick','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '6872','genus_name' => 'Tristaniopsis','species_name' => 'laurina','common_name' => 'Water gum','growth_rate' => 'Slow','height_at_maturity' => '45'),
            array('id' => '6873','genus_name' => 'Trattinnickia','species_name' => 'lawrancei','common_name' => 'Trattinnickia lawrancei','growth_rate' => 'Slow','height_at_maturity' => '49'),
            array('id' => '6874','genus_name' => 'Trema','species_name' => 'lamarckiana','common_name' => 'Lamarck\'s trema','growth_rate' => 'Slow','height_at_maturity' => '26'),
            array('id' => '6880','genus_name' => 'Tristiropsis','species_name' => 'obtusangula','common_name' => 'faia','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '6881','genus_name' => 'Trema','species_name' => 'orientalis','common_name' => 'Oriental trema','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '6882','genus_name' => 'Trichilia','species_name' => 'pallida','common_name' => 'Gaita','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '6883','genus_name' => 'Trophis','species_name' => 'racemosa','common_name' => 'White ramoon','growth_rate' => '','height_at_maturity' => '82'),
            array('id' => '6884','genus_name' => 'Trichospermum','species_name' => 'richii','common_name' => 'mako','growth_rate' => '','height_at_maturity' => '75'),
            array('id' => '6885','genus_name' => 'Triadica','species_name' => 'sebifera','common_name' => 'Chinese tallowtree','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '6887','genus_name' => 'Triphasia','species_name' => 'trifolia','common_name' => 'Limeberry','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '6888','genus_name' => 'Trichilia','species_name' => 'triacantha','common_name' => 'Bariaco','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '6889','genus_name' => 'Tsuga','species_name' => 'canadensis','common_name' => 'Eastern hemlock','growth_rate' => 'Slow','height_at_maturity' => '105'),
            array('id' => '6890','genus_name' => 'Tsuga','species_name' => 'caroliniana','common_name' => 'Carolina hemlock','growth_rate' => 'Slow','height_at_maturity' => '65'),
            array('id' => '6891','genus_name' => 'Tsuga','species_name' => 'heterophylla','common_name' => 'Western hemlock','growth_rate' => 'Slow','height_at_maturity' => '170'),
            array('id' => '6892','genus_name' => 'Tsuga','species_name' => 'jeffrey','common_name' => 'Jeffrey hemlock','growth_rate' => 'Slow','height_at_maturity' => '93'),
            array('id' => '6893','genus_name' => 'Tsuga','species_name' => 'mertensiana','common_name' => 'Mountain hemlock','growth_rate' => 'Slow','height_at_maturity' => '125'),
            array('id' => '6894','genus_name' => 'Tupidanthus','species_name' => 'calyptratus','common_name' => 'Mallet flower','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '6895','genus_name' => 'Turpinia','species_name' => 'insignis','common_name' => 'Turpinia insignis','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '6896','genus_name' => 'Turpinia','species_name' => 'occidentalis','common_name' => 'Muttonwood','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '6897','genus_name' => 'Ulmus','species_name' => 'alata','common_name' => 'Winged elm','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '6898','genus_name' => 'Ulmus','species_name' => 'americana','common_name' => 'American elm','growth_rate' => 'Fast','height_at_maturity' => '120'),
            array('id' => '6901','genus_name' => 'Ulmus','species_name' => 'cornubiensis fastigiata','common_name' => 'Cornish elm','growth_rate' => 'Moderate','height_at_maturity' => '88'),
            array('id' => '6902','genus_name' => 'Ulmus','species_name' => 'crassifolia','common_name' => 'Cedar elm','growth_rate' => 'Fast','height_at_maturity' => '90'),
            array('id' => '6903','genus_name' => 'Ulmus','species_name' => 'davidiana','common_name' => 'The David Elm','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '6904','genus_name' => 'Ulmus','species_name' => '\'Dodoens\'','common_name' => 'Dodoens elm','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '6906','genus_name' => 'Ulmus','species_name' => '\'Frontier\'','common_name' => 'Frontier elm','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '6907','genus_name' => 'Ulmus','species_name' => 'glabra','common_name' => 'Wych elm','growth_rate' => 'Fast','height_at_maturity' => '90'),
            array('id' => '6908','genus_name' => 'Ulmus','species_name' => 'glabra \'Lutescens\'','common_name' => 'Golden wych elm','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '6909','genus_name' => 'Ulmus','species_name' => 'hollandic','common_name' => 'Dutch elm','growth_rate' => 'Fast','height_at_maturity' => '85'),
            array('id' => '6910','genus_name' => 'Ulmus','species_name' => 'japonica','common_name' => 'Japanese elm','growth_rate' => '','height_at_maturity' => '115'),
            array('id' => '6911','genus_name' => 'Ulmus','species_name' => 'laciniata','common_name' => 'Manchurian elm','growth_rate' => '','height_at_maturity' => '32'),
            array('id' => '6912','genus_name' => 'Ulmus','species_name' => 'laevis','common_name' => 'European white elm','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '6913','genus_name' => 'Ulmus','species_name' => '\'Lobel\'','common_name' => 'Lobel elm','growth_rate' => 'Moderate','height_at_maturity' => ''),
            array('id' => '6914','genus_name' => 'Ulmus','species_name' => 'mexicana','common_name' => 'Mexican elm','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '6915','genus_name' => 'Ulmus','species_name' => 'minor','common_name' => 'Field elm','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '6916','genus_name' => 'Ulmus','species_name' => 'minor angustifolia','common_name' => 'Ulmus minor angustifolia','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6917','genus_name' => 'Ulmus','species_name' => '\'New Horizon\'','common_name' => 'New horizon elm','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '6918','genus_name' => 'Ulmus','species_name' => 'noth','common_name' => 'Ulmus x notha','growth_rate' => 'Fast','height_at_maturity' => '85'),
            array('id' => '6919','genus_name' => 'Ulmus','species_name' => 'parvifolia','common_name' => 'Chinese elm','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '6921','genus_name' => 'Ulmus','species_name' => 'parvifolia \'Drake\'','common_name' => 'Drake chinese elm','growth_rate' => 'Fast','height_at_maturity' => '35'),
            array('id' => '6922','genus_name' => 'Ulmus','species_name' => 'parvifolia \'Emer II\'','common_name' => 'Emerald vase chinese elm','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '6924','genus_name' => 'Ulmus','species_name' => '\'Plantijn\'','common_name' => 'Ulmus \'Plantijn\'','growth_rate' => 'Moderate','height_at_maturity' => ''),
            array('id' => '6925','genus_name' => 'Ulmus','species_name' => 'procera','common_name' => 'English elm','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '6926','genus_name' => 'Ulmus','species_name' => 'pumila','common_name' => 'Siberian elm','growth_rate' => 'Fast','height_at_maturity' => '70'),
            array('id' => '6928','genus_name' => 'Ulmus','species_name' => 'rubra','common_name' => 'Slippery elm','growth_rate' => 'Fast','height_at_maturity' => '85'),
            array('id' => '6929','genus_name' => 'Ulmus','species_name' => '\'Sapporo Autunm Gold\'','common_name' => 'Autumn gold elm','growth_rate' => 'Fast','height_at_maturity' => '35'),
            array('id' => '6930','genus_name' => 'Ulmus','species_name' => 'serotina','common_name' => 'September elm','growth_rate' => 'Fast','height_at_maturity' => '70'),
            array('id' => '6931','genus_name' => 'Ulmus','species_name' => 'thomasii','common_name' => 'Rock elm','growth_rate' => 'Moderate','height_at_maturity' => '90'),
            array('id' => '6932','genus_name' => 'Ulmus','species_name' => 'villosa','common_name' => 'Cherry bark elm','growth_rate' => '','height_at_maturity' => '82'),
            array('id' => '6933','genus_name' => 'Ulmus','species_name' => 'wilsoniana','common_name' => 'Wilson elm','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '6934','genus_name' => 'Umbellularia','species_name' => 'californica','common_name' => 'California laurel','growth_rate' => 'Moderate','height_at_maturity' => '80'),
            array('id' => '6935','genus_name' => 'Ungnadia','species_name' => 'speciosa','common_name' => 'Mexican buckeye','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '6936','genus_name' => 'Urera','species_name' => 'baccifera','common_name' => 'Scratchbush','growth_rate' => '','height_at_maturity' => '16'),
            array('id' => '6938','genus_name' => 'Urera','species_name' => 'chlorocarpa','common_name' => 'Stinging nettle','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '6939','genus_name' => 'Urera','species_name' => 'glabra','common_name' => 'Hopue','growth_rate' => '','height_at_maturity' => '35'),
            array('id' => '6940','genus_name' => 'Urera','species_name' => 'kaalae','common_name' => 'Opuhe','growth_rate' => '','height_at_maturity' => '23'),
            array('id' => '6942','genus_name' => 'Vallesia','species_name' => 'antillana','common_name' => 'Tearshrub','growth_rate' => '','height_at_maturity' => '8'),
            array('id' => '6943','genus_name' => 'Vaccinium','species_name' => 'arboreum','common_name' => 'Sparkleberry','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '6944','genus_name' => 'Vaccinium','species_name' => 'atlanticu','common_name' => 'Atlantic huckleberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6946','genus_name' => 'Vaccinium','species_name' => 'carolinianu','common_name' => 'Carolina huckleberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6947','genus_name' => 'Vaccinium','species_name' => 'caesariense','common_name' => 'New jersey blueberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6948','genus_name' => 'Vaccinium','species_name' => 'calycinum','common_name' => 'Ohelo kau la\'au','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6949','genus_name' => 'Vaccinium','species_name' => 'corymbosum','common_name' => 'Highbush blueberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6950','genus_name' => 'Vauquelinia','species_name' => 'corymbosa','common_name' => 'Slimleaf rosewood','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '6951','genus_name' => 'Vaccinium','species_name' => 'dentatum','common_name' => 'Ohelo','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6952','genus_name' => 'Vaccinium','species_name' => 'dobbini','common_name' => 'Dobbin\'s huckleberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6953','genus_name' => 'Vaccinium','species_name' => 'elliottii','common_name' => 'Elliott\'s blueberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6954','genus_name' => 'Vaccinium','species_name' => 'erythrocarpum','common_name' => 'Southern mountain blueberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6955','genus_name' => 'Vaccinium','species_name' => 'formosum','common_name' => 'Southern blueberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6956','genus_name' => 'Vaccinium','species_name' => 'fuscatum','common_name' => 'Black highbush blueberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6958','genus_name' => 'Vaccinium','species_name' => 'hirsutum','common_name' => 'Hairy blueberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6959','genus_name' => 'Vaccinium','species_name' => 'marianu','common_name' => 'Vaccinium','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6960','genus_name' => 'Vaccinium','species_name' => 'margarettae','common_name' => 'Margarett\'s huckleberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6961','genus_name' => 'Vangueria','species_name' => 'madagascariensis','common_name' => 'Voa vanga','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '6962','genus_name' => 'Vaccinium','species_name' => 'membranaceum','common_name' => 'Thinleaf huckleberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6963','genus_name' => 'Vaccinium','species_name' => 'myrsinites','common_name' => 'Shiny blueberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6964','genus_name' => 'Vaccinium','species_name' => 'oldhamii','common_name' => 'xian chi yue ju','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '6965','genus_name' => 'Vaccinium','species_name' => 'ovalifolium','common_name' => 'Oval-leaf blueberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6966','genus_name' => 'Vaccinium','species_name' => 'ovatum','common_name' => 'California huckleberry','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '6967','genus_name' => 'Vaccinium','species_name' => 'parvifolium','common_name' => 'Red huckleberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6968','genus_name' => 'Vaccinium','species_name' => 'reticulatum','common_name' => 'Ohelo \'ai','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6969','genus_name' => 'Vaccinium','species_name' => 'simulatum','common_name' => 'Upland highbush blueberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6970','genus_name' => 'Vaccinium','species_name' => 'stamineum','common_name' => 'Deerberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6973','genus_name' => 'Vaccinium','species_name' => 'vacillians','common_name' => 'Lowbush blueberry','growth_rate' => '','height_at_maturity' => '2'),
            array('id' => '6975','genus_name' => 'Vaccinium','species_name' => 'virgatum','common_name' => 'Smallflower blueberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6976','genus_name' => 'Vernonia','species_name' => 'amygdalina','common_name' => 'Bitter leaf','growth_rate' => 'Fast','height_at_maturity' => '43'),
            array('id' => '6977','genus_name' => 'Verticordia','species_name' => 'cunninghamii','common_name' => 'Cunningham feather flower','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '6978','genus_name' => 'Verbesina','species_name' => 'fastigiata','common_name' => 'Verbesina fastigiata','growth_rate' => '','height_at_maturity' => '4'),
            array('id' => '6979','genus_name' => 'Vernicia','species_name' => 'fordii','common_name' => 'Tungoil tree','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '6980','genus_name' => 'Veitchia','species_name' => 'merrillii','common_name' => 'Christmas palm','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '6982','genus_name' => 'Ventilago','species_name' => 'viminalis','common_name' => 'Supplejack','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '6983','genus_name' => 'Viburnum','species_name' => 'acerifolium','common_name' => 'Mapleleaf viburnum','growth_rate' => 'Slow','height_at_maturity' => '29'),
            array('id' => '6984','genus_name' => 'Vitex','species_name' => 'agnus-castus','common_name' => 'Chaste tree','growth_rate' => 'Fast','height_at_maturity' => '13'),
            array('id' => '6986','genus_name' => 'Viburnum','species_name' => 'bracteatum','common_name' => 'Bracted arrowwood','growth_rate' => 'Slow','height_at_maturity' => '29'),
            array('id' => '6987','genus_name' => 'Viburnum','species_name' => 'buddleifolium','common_name' => 'Buddlejaleaf viburnum','growth_rate' => 'Slow','height_at_maturity' => '29'),
            array('id' => '6988','genus_name' => 'Vitex','species_name' => 'cymosa','common_name' => 'Taruma guazu','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '6989','genus_name' => 'Viburnum','species_name' => 'dentatum','common_name' => 'Southern arrowwood','growth_rate' => 'Slow','height_at_maturity' => '29'),
            array('id' => '6990','genus_name' => 'Virgilia','species_name' => 'divaricata','common_name' => 'Cape Lilac','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '6991','genus_name' => 'Vitex','species_name' => 'divaricata','common_name' => 'Higuerillo','growth_rate' => 'Slow','height_at_maturity' => '45'),
            array('id' => '6992','genus_name' => 'Viburnum','species_name' => 'dilatatum','common_name' => 'Linden arrowwood','growth_rate' => 'Slow','height_at_maturity' => '29'),
            array('id' => '6993','genus_name' => 'Viburnum','species_name' => 'edule','common_name' => 'Squashberry','growth_rate' => 'Slow','height_at_maturity' => '29'),
            array('id' => '6994','genus_name' => 'Viburnum','species_name' => 'ellipticum','common_name' => 'Oval leafed vibrunum','growth_rate' => 'Slow','height_at_maturity' => '29'),
            array('id' => '6995','genus_name' => 'Viburnum','species_name' => 'erosum','common_name' => 'Japanese arrowood','growth_rate' => '','height_at_maturity' => '9'),
            array('id' => '6996','genus_name' => 'Vitex','species_name' => 'glabrata','common_name' => 'Smooth chastetree','growth_rate' => 'Fast','height_at_maturity' => '24'),
            array('id' => '6997','genus_name' => 'Viburnum','species_name' => 'japonicum','common_name' => 'Japanese viburnum','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '6998','genus_name' => 'Viminaria','species_name' => 'juncea','common_name' => 'Golden spray','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '6999','genus_name' => 'Viburnum','species_name' => 'lantana','common_name' => 'Wayfaring tree','growth_rate' => 'Slow','height_at_maturity' => '29'),
            array('id' => '7000','genus_name' => 'Viburnum','species_name' => 'lantanoides','common_name' => 'Hobblebush','growth_rate' => 'Slow','height_at_maturity' => '29'),
            array('id' => '7001','genus_name' => 'Viburnum','species_name' => 'lentago','common_name' => 'Nannyberry','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '7003','genus_name' => 'Viburnum','species_name' => 'molle','common_name' => 'Softleaf arrowwood','growth_rate' => 'Slow','height_at_maturity' => '29'),
            array('id' => '7004','genus_name' => 'Viscum','species_name' => 'nervosum','common_name' => 'European mistletoe','growth_rate' => 'Moderate','height_at_maturity' => '19'),
            array('id' => '7005','genus_name' => 'Vitex','species_name' => 'negundo','common_name' => 'Chinese chastetree','growth_rate' => 'Fast','height_at_maturity' => '18'),
            array('id' => '7006','genus_name' => 'Viburnum','species_name' => 'nudum','common_name' => 'Possumhaw','growth_rate' => 'Slow','height_at_maturity' => '29'),
            array('id' => '7007','genus_name' => 'Viburnum','species_name' => 'obovatum','common_name' => 'Small-leaf arrowwood','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '7008','genus_name' => 'Viburnum','species_name' => 'odoratissimum','common_name' => 'Sweet viburnum','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '7010','genus_name' => 'Viburnum','species_name' => 'opulus','common_name' => 'European cranberry bush','growth_rate' => 'Slow','height_at_maturity' => '29'),
            array('id' => '7012','genus_name' => 'Virgilia','species_name' => 'oroboides','common_name' => 'Keurboom','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '7014','genus_name' => 'Vitex','species_name' => 'parviflora','common_name' => 'Smallflower chastetree','growth_rate' => 'Slow','height_at_maturity' => '90'),
            array('id' => '7016','genus_name' => 'Viburnum','species_name' => 'prunifolium','common_name' => 'Black haw','growth_rate' => 'Slow','height_at_maturity' => '14'),
            array('id' => '7017','genus_name' => 'Viburnum','species_name' => 'rafinesquianum','common_name' => 'Downy arrowwood','growth_rate' => 'Slow','height_at_maturity' => '29'),
            array('id' => '7018','genus_name' => 'Viburnum','species_name' => 'rhytidophyllum','common_name' => 'Leather leaf viburnum','growth_rate' => 'Slow','height_at_maturity' => '29'),
            array('id' => '7019','genus_name' => 'Viburnum','species_name' => 'rhytidophylloide','common_name' => 'Lantanaphyllum viburnum','growth_rate' => 'Slow','height_at_maturity' => '29'),
            array('id' => '7021','genus_name' => 'Vitex','species_name' => 'rotundifolia','common_name' => 'Roundleaf chastetree','growth_rate' => 'Fast','height_at_maturity' => '24'),
            array('id' => '7022','genus_name' => 'Viburnum','species_name' => 'rufidulum','common_name' => 'Rusty blackhaw','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '7024','genus_name' => 'Viburnum','species_name' => 'setigerum','common_name' => 'Tea viburnum','growth_rate' => 'Slow','height_at_maturity' => '29'),
            array('id' => '7025','genus_name' => 'Viburnum','species_name' => 'sieboldii','common_name' => 'Siebold\'s arrowwood','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '7026','genus_name' => 'Viburnum','species_name' => 'tinus','common_name' => 'Laurustinus','growth_rate' => 'Slow','height_at_maturity' => '29'),
            array('id' => '7027','genus_name' => 'Viburnum','species_name' => 'plicatum','common_name' => 'Japanese snowball','growth_rate' => 'Slow','height_at_maturity' => '29'),
            array('id' => '7028','genus_name' => 'Viburnum','species_name' => 'opulus v americanum','common_name' => 'American cranberrybush','growth_rate' => 'Slow','height_at_maturity' => '29'),
            array('id' => '7029','genus_name' => 'Vitex','species_name' => 'trifolia','common_name' => 'Simpleleaf chastetree','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '7034','genus_name' => 'Washingtonia','species_name' => 'filifera','common_name' => 'California palm','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '7035','genus_name' => 'Syzygium','species_name' => 'floribundum','common_name' => 'Weeping lilly pilly','growth_rate' => 'Moderate','height_at_maturity' => '98'),
            array('id' => '7037','genus_name' => 'Washingtonia','species_name' => 'robusta','common_name' => 'Mexican fan palm','growth_rate' => 'Fast','height_at_maturity' => '63'),
            array('id' => '7045','genus_name' => 'Weinmannia','species_name' => 'pinnata','common_name' => 'Bastard briziletto','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '7047','genus_name' => 'Weigela','species_name' => 'subsessilis','common_name' => 'weigela','growth_rate' => '','height_at_maturity' => '5'),
            array('id' => '7048','genus_name' => 'Wikstroemia','species_name' => 'bicornuta','common_name' => 'Alpine false ohelo','growth_rate' => '','height_at_maturity' => '23'),
            array('id' => '7049','genus_name' => 'Wisteria','species_name' => 'floribunda','common_name' => 'Japanese wisteria','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '7051','genus_name' => 'Wisteria','species_name' => 'formos','common_name' => 'Wisteria x formosa','growth_rate' => 'Fast','height_at_maturity' => '32'),
            array('id' => '7052','genus_name' => 'Wikstroemia','species_name' => 'furcata','common_name' => 'Forest false ohelo','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '7055','genus_name' => 'Wikstroemia','species_name' => 'monticola','common_name' => 'Montane false ohelo','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '7056','genus_name' => 'Wikstroemia','species_name' => 'oahuensis','common_name' => 'Oahu false ohelo','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '7058','genus_name' => 'Wikstroemia','species_name' => 'pulcherrima','common_name' => 'Kohala false ohelo','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '7059','genus_name' => 'Wikstroemia','species_name' => 'sandwicensis','common_name' => 'Variableleaf false ohelo','growth_rate' => '','height_at_maturity' => '11'),
            array('id' => '7063','genus_name' => 'Wikstroemia','species_name' => 'villosa','common_name' => 'Hairy false ohelo','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '7064','genus_name' => 'Wodyetia','species_name' => 'bifurcata','common_name' => 'Foxtail palm','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '7065','genus_name' => 'Wollemia','species_name' => 'nobilis','common_name' => 'Wollemi Pine','growth_rate' => 'Slow','height_at_maturity' => '132'),
            array('id' => '7066','genus_name' => 'Wrightia','species_name' => 'pubescens','common_name' => 'Wrightia','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '7067','genus_name' => 'Xanthostemon','species_name' => 'chrysanthus','common_name' => 'Golden Penda','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '7068','genus_name' => 'Xanthoceras','species_name' => 'sorbifolia','common_name' => 'Yellow-horn','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '7070','genus_name' => 'Xylococcus','species_name' => 'bicolor','common_name' => 'Mission manzanita','growth_rate' => 'Slow','height_at_maturity' => '14'),
            array('id' => '7072','genus_name' => 'Xylosma','species_name' => 'buxifolium','common_name' => 'Mucha-gente','growth_rate' => '','height_at_maturity' => '26'),
            array('id' => '7074','genus_name' => 'Xylosma','species_name' => 'congestum','common_name' => 'Shiny xylosma','growth_rate' => '','height_at_maturity' => '26'),
            array('id' => '7075','genus_name' => 'Xylosma','species_name' => 'crenatum','common_name' => 'Sawtooth logwood','growth_rate' => '','height_at_maturity' => '46'),
            array('id' => '7076','genus_name' => 'Xylosma','species_name' => 'flexuosum','common_name' => 'Brushholly','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '7078','genus_name' => 'Xylosma','species_name' => 'hawaiiensis','common_name' => 'Hawai\'i brushholly','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '7079','genus_name' => 'Xylocarpus','species_name' => 'moluccensis','common_name' => 'cedar mangrove','growth_rate' => '','height_at_maturity' => '100'),
            array('id' => '7081','genus_name' => 'Xylosma','species_name' => 'pachyphyllum','common_name' => 'Spiny logwood','growth_rate' => '','height_at_maturity' => '26'),
            array('id' => '7083','genus_name' => 'Xylomelum','species_name' => 'pyriforme','common_name' => 'Woody Pear','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '7084','genus_name' => 'Xylosma','species_name' => 'schaefferioides','common_name' => 'White logwood','growth_rate' => '','height_at_maturity' => '26'),
            array('id' => '7085','genus_name' => 'Xylosma','species_name' => 'schwaneckeanum','common_name' => 'Schwaneck\'s logwood','growth_rate' => '','height_at_maturity' => '26'),
            array('id' => '7088','genus_name' => 'Yucca','species_name' => 'brevifolia','common_name' => 'Joshua tree','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '7091','genus_name' => 'Yucca','species_name' => 'filifera','common_name' => 'St. Peter\'s palm','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '7097','genus_name' => 'Yucca','species_name' => 'rostrata','common_name' => 'Beaked yucca','growth_rate' => '','height_at_maturity' => '5'),
            array('id' => '7098','genus_name' => 'Yucca','species_name' => 'torreyi','common_name' => 'Torrey yucca','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '7099','genus_name' => 'Zanthoxylum','species_name' => 'americanum','common_name' => 'Common prickly ash','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '7100','genus_name' => 'Zaluzania','species_name' => 'augusta','common_name' => 'Zaluzania augusta','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '7101','genus_name' => 'Zanthoxylum','species_name' => 'bifoliolatum','common_name' => 'Maricao pricklyash','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '7103','genus_name' => 'Zanthoxylum','species_name' => 'caribaeum','common_name' => 'Prickly yellow','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '7105','genus_name' => 'Zanthoxylum','species_name' => 'clava-herculis','common_name' => 'Hercules club','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '7106','genus_name' => 'Zanthoxylum','species_name' => 'coriaceum','common_name' => 'Biscayne pricklyash','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '7107','genus_name' => 'Zanthoxylum','species_name' => 'dipetalum','common_name' => 'Kawa\'u','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '7108','genus_name' => 'Zanthoxylum','species_name' => 'fagara','common_name' => 'Lime prickly ash','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '7109','genus_name' => 'Zanthoxylum','species_name' => 'flavum','common_name' => 'West Indian satinwood','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '7110','genus_name' => 'Zanthoxylum','species_name' => 'hawaiiense','common_name' => 'Hawai\'i pricklyash','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '7111','genus_name' => 'Zanthoxylum','species_name' => 'hirsutum','common_name' => 'Texas hercules\' club','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '7112','genus_name' => 'Zanthoxylum','species_name' => 'kauaense','common_name' => 'Kauai pricklyash','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '7113','genus_name' => 'Zanthoxylum','species_name' => 'martinicense','common_name' => 'White pricklyash','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '7114','genus_name' => 'Zanthoxylum','species_name' => 'monophyllum','common_name' => 'Yellow prickle','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '7115','genus_name' => 'Zanthoxylum','species_name' => 'oahuense','common_name' => 'O\'ahu prickly-ash','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '7116','genus_name' => 'Zanthoxylum','species_name' => 'parvum','common_name' => 'Tickletongue','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '7117','genus_name' => 'Zapoteca','species_name' => 'portoricensis','common_name' => 'White stickpea','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '7118','genus_name' => 'Zanthoxylum','species_name' => 'punctatum','common_name' => 'Dotted pricklyash','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '7120','genus_name' => 'Zanthoxylum','species_name' => 'schinifolium','common_name' => 'Sichuan-pepper','growth_rate' => '','height_at_maturity' => '13'),
            array('id' => '7121','genus_name' => 'Zanthoxylum','species_name' => 'spinifex','common_name' => 'Niaragato','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '7122','genus_name' => 'Zanthoxylum','species_name' => 'thomasianum','common_name' => 'St. thomas pricklyash','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '7123','genus_name' => 'Zelkova','species_name' => 'carpinifolia','common_name' => 'Caucacian zelkova','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '7124','genus_name' => 'Zelkova','species_name' => 'formosana','common_name' => 'Taiwan zelkova','growth_rate' => 'Moderate','height_at_maturity' => '100'),
            array('id' => '7126','genus_name' => 'Zenobia','species_name' => 'pulverulenta','common_name' => 'Honeycup','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '7127','genus_name' => 'Zelkova','species_name' => 'schneideriana','common_name' => 'Schneider zelkova','growth_rate' => 'Moderate','height_at_maturity' => '100'),
            array('id' => '7128','genus_name' => 'Zelkova','species_name' => 'serrata','common_name' => 'Japanese zelkova','growth_rate' => 'Slow','height_at_maturity' => '89'),
            array('id' => '7130','genus_name' => 'Zelkova','species_name' => 'serrata \'Village Green\'','common_name' => '\'Village Green\' Japanese zelkova','growth_rate' => '','height_at_maturity' => '55'),
            array('id' => '7131','genus_name' => 'Zelkova','species_name' => 'sinica','common_name' => 'Chinese zelkova','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '7133','genus_name' => 'Zieria','species_name' => 'arborescens','common_name' => 'Tree Zieria','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '7134','genus_name' => 'Ziziphus','species_name' => 'celata','common_name' => 'Florida jujube','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '7135','genus_name' => 'Ziziphus','species_name' => 'mauritiana','common_name' => 'Indian jujube','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '7136','genus_name' => 'Ziziphus','species_name' => 'obtusifolia','common_name' => 'Lotebush','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '7137','genus_name' => 'Ziziphus','species_name' => 'parryi','common_name' => 'Parry\'s jujube','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '7138','genus_name' => 'Ziziphus','species_name' => 'reticulata','common_name' => 'Cacao rojo','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '7139','genus_name' => 'Ziziphus','species_name' => 'rignonii','common_name' => 'Soane','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '7140','genus_name' => 'Ziziphus','species_name' => 'taylorii','common_name' => 'Taylor\'s jujube','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '7141','genus_name' => 'Ziziphus','species_name' => 'zizyphus','common_name' => 'Common jujube','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '7144','genus_name' => 'Zygia','species_name' => 'longifolia','common_name' => 'Buscilla','growth_rate' => 'Moderate','height_at_maturity' => '49')
        );

        Tree::insert($trees);
    }
}
