<?php

namespace Database\Seeders\TreeSpecies;

use App\Models\Trees\Tree;
use Illuminate\Database\Seeder;

class TreeSpeciesSeeder3 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $trees = array(
            array('id' => '1828','genus_name' => 'Condalia','species_name' => 'warnockii','common_name' => 'Warnock\'s snakewood','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '1829','genus_name' => 'Cotoneaster','species_name' => 'watereri','common_name' => 'Waterer\'s Cotoneaster','growth_rate' => 'Fast','height_at_maturity' => '4'),
            array('id' => '1830','genus_name' => 'Cordia','species_name' => 'wagneriorum','common_name' => 'Luquillo mountain manjack','growth_rate' => 'Slow','height_at_maturity' => '34'),
            array('id' => '1831','genus_name' => 'Coprosma','species_name' => 'waimeae','common_name' => '\'olena','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '1832','genus_name' => 'Critoniella','species_name' => 'acuminata','common_name' => 'Critoniella acuminata','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '1833','genus_name' => 'Crataegus','species_name' => 'aestivalis','common_name' => 'May hawthorn','growth_rate' => 'Slow','height_at_maturity' => '26'),
            array('id' => '1834','genus_name' => 'Crataegus','species_name' => 'aemula','common_name' => 'Rome hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1835','genus_name' => 'Crescentia','species_name' => 'alata','common_name' => 'Morrito','growth_rate' => 'Moderate','height_at_maturity' => '63'),
            array('id' => '1836','genus_name' => 'Crataegus','species_name' => 'alma','common_name' => 'Bountiful hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1837','genus_name' => 'Cryptocarya','species_name' => 'alba','common_name' => 'Peumo','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '1838','genus_name' => 'Crataegus','species_name' => 'ambitiosa','common_name' => 'Grand rapids hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1839','genus_name' => 'Crataegus','species_name' => 'annosa','common_name' => 'Phoenix city hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1840','genus_name' => 'Crataegus','species_name' => 'anamesa','common_name' => 'Fort bend hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1841','genus_name' => 'Crataegus','species_name' => 'x anomala','common_name' => 'Anomalous hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '1842','genus_name' => 'Crataegus','species_name' => 'ancisa','common_name' => 'Mississippi hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1843','genus_name' => 'Crataegus','species_name' => 'apiomorpha','common_name' => 'Fort sheridan hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1844','genus_name' => 'Crataegus','species_name' => 'arborea','common_name' => 'Montgomery hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1845','genus_name' => 'Crataegus','species_name' => 'arcana','common_name' => 'Carolina hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1846','genus_name' => 'Crataegus','species_name' => 'arrogans','common_name' => 'Dixie hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1849','genus_name' => 'Crataegus','species_name' => 'ater','common_name' => 'Nashville hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1850','genus_name' => 'Crataegus','species_name' => 'austromontana','common_name' => 'Valley head hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1851','genus_name' => 'Crataegus','species_name' => 'azarolus','common_name' => 'Mediterranean Medlar','growth_rate' => 'Fast','height_at_maturity' => '9'),
            array('id' => '1852','genus_name' => 'Crataegus','species_name' => 'berberifolia','common_name' => 'Barberry','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1854','genus_name' => 'Crataegus','species_name' => 'beadlei','common_name' => 'Beadle\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1855','genus_name' => 'Crataegus','species_name' => 'beata','common_name' => 'Dunbar\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1857','genus_name' => 'Crataegus','species_name' => 'bona','common_name' => 'Berks county hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1858','genus_name' => 'Crataegus','species_name' => 'brachyacantha','common_name' => 'Blueberry hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1859','genus_name' => 'Crataegus','species_name' => 'x brevipes','common_name' => 'Crataegus x brevipes','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1860','genus_name' => 'Crataegus','species_name' => 'brainerdii','common_name' => 'Brainerd\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1861','genus_name' => 'Crataegus','species_name' => 'brazoria','common_name' => 'Brazos hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1862','genus_name' => 'Crataegus','species_name' => 'calpodendron','common_name' => 'Pear hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1863','genus_name' => 'Crataegus','species_name' => 'carrollensis','common_name' => 'Eureka springs hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1865','genus_name' => 'Crataegus','species_name' => 'chrysocarpa','common_name' => 'Fireberry hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1867','genus_name' => 'Crataegus','species_name' => 'pedicellata','common_name' => 'Scarlet hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1868','genus_name' => 'Crataegus','species_name' => 'coccineoides','common_name' => 'Red Kansas Hawthorn','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '1869','genus_name' => 'Crataegus','species_name' => 'contrita','common_name' => 'Southern hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1870','genus_name' => 'Crataegus','species_name' => 'coccinioides','common_name' => 'Kansas hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1871','genus_name' => 'Crataegus','species_name' => 'compacta','common_name' => 'Clustered hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1872','genus_name' => 'Crataegus','species_name' => 'corusca','common_name' => 'Shiningbranch hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1874','genus_name' => 'Crataegus','species_name' => 'condigna','common_name' => 'River junction hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1875','genus_name' => 'Crataegus','species_name' => 'coleae','common_name' => 'Cole\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1876','genus_name' => 'Crataegus','species_name' => 'compta','common_name' => 'Adorned hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1877','genus_name' => 'Crataegus','species_name' => 'consanguinea','common_name' => 'Tallahassee hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1879','genus_name' => 'Crataegus','species_name' => 'crus-galli','common_name' => 'Cockspur hawthorn','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '1880','genus_name' => 'Crataegus','species_name' => 'crus-galli v. inermis','common_name' => 'Thornless cockspur hawthorn','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '1881','genus_name' => 'Crescentia','species_name' => 'cujete','common_name' => 'Calabash tree','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '1882','genus_name' => 'Cryptocarya','species_name' => 'cunninghamii','common_name' => 'Cunningham\'s Laurel','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '1883','genus_name' => 'Crataegus','species_name' => 'dallasiana','common_name' => 'Dallas hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1884','genus_name' => 'Crataegus','species_name' => 'desueta','common_name' => 'New york hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1885','genus_name' => 'Crataegus','species_name' => 'dilatata','common_name' => 'Broadleaf hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1886','genus_name' => 'Crataegus','species_name' => 'dissona','common_name' => 'Northern hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1887','genus_name' => 'Crataegus','species_name' => 'distincta','common_name' => 'Distinct hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1888','genus_name' => 'Crataegus','species_name' => 'dispar','common_name' => 'Aiken hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1889','genus_name' => 'Crataegus','species_name' => 'disperma','common_name' => 'Spreading hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1891','genus_name' => 'Crataegus','species_name' => 'dispessa','common_name' => 'Mink hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1892','genus_name' => 'Crataegus','species_name' => 'douglasii','common_name' => 'Black hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1893','genus_name' => 'Crataegus','species_name' => 'dodgei','common_name' => 'Dodge\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1895','genus_name' => 'Crataegus','species_name' => 'engelmannii','common_name' => 'Engelmann\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1896','genus_name' => 'Crataegus','species_name' => 'erythropoda','common_name' => 'Cerro hawthorn','growth_rate' => 'Slow','height_at_maturity' => '16'),
            array('id' => '1897','genus_name' => 'Crataegus','species_name' => 'erythrocarpa','common_name' => 'Red hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1898','genus_name' => 'Crataegus','species_name' => 'exilis','common_name' => 'Slender hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1899','genus_name' => 'Crataegus','species_name' => 'extraria','common_name' => 'Marietta hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1900','genus_name' => 'Crataegus','species_name' => 'flabellata','common_name' => 'Fanleaf hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1902','genus_name' => 'Crataegus','species_name' => 'flava','common_name' => 'Yellowleaf hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1904','genus_name' => 'Crataegus','species_name' => 'fragilis','common_name' => 'Fragile hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1905','genus_name' => 'Crataegus','species_name' => 'fulleriana','common_name' => 'Fuller\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1906','genus_name' => 'Crataegus','species_name' => 'furtiva','common_name' => 'Albany hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1907','genus_name' => 'Cryptocarya','species_name' => 'glaucescens','common_name' => 'Jackwood','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '1908','genus_name' => 'Crataegus','species_name' => 'glareosa','common_name' => 'Port huron hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1909','genus_name' => 'Croton','species_name' => 'gossypiifolius','common_name' => 'Croton gossypiifolius','growth_rate' => 'Fast','height_at_maturity' => '18'),
            array('id' => '1910','genus_name' => 'Crataegus','species_name' => 'x grignonensis','common_name' => 'Grignon hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '1911','genus_name' => 'Crataegus','species_name' => 'grandis','common_name' => 'Grand hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1912','genus_name' => 'Crataegus','species_name' => 'greggiana','common_name' => 'Gregg\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1913','genus_name' => 'Crataegus','species_name' => 'harbisonii','common_name' => 'Harbison\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1914','genus_name' => 'Crataegus','species_name' => 'x haemacarpa','common_name' => 'Crataegus x haemacarpa','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1915','genus_name' => 'Crataegus','species_name' => 'harveyana','common_name' => 'Harvey\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1916','genus_name' => 'Crataegus','species_name' => 'helvina','common_name' => 'Clarkton hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1917','genus_name' => 'Crinodendron','species_name' => 'hookerianum','common_name' => 'Red Lantern Tree','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '1918','genus_name' => 'Crataegus','species_name' => 'holmesiana','common_name' => 'Holmes\' hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1920','genus_name' => 'Crataegus','species_name' => 'x hudsonica','common_name' => 'Hudson hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1921','genus_name' => 'Crataegus','species_name' => 'ideae','common_name' => 'Concord hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1922','genus_name' => 'Crataegus','species_name' => 'ignava','common_name' => 'Bedford springs hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1924','genus_name' => 'Crataegus','species_name' => 'x immanis','common_name' => 'Crataegus x immanis','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1926','genus_name' => 'Crataegus','species_name' => 'impar','common_name' => 'Redclay hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1927','genus_name' => 'Crataegus','species_name' => 'intricata','common_name' => 'Biltmore hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1928','genus_name' => 'Crataegus','species_name' => 'x incaedua','common_name' => 'Crataegus x incaedua','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1930','genus_name' => 'Crataegus','species_name' => 'indicens','common_name' => 'Mansfield hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1931','genus_name' => 'Crataegus','species_name' => 'insidiosa','common_name' => 'Ozark hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1932','genus_name' => 'Crataegus','species_name' => 'integra','common_name' => 'Lake ella hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1933','genus_name' => 'Crataegus','species_name' => 'invicta','common_name' => 'Fulton hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1934','genus_name' => 'Crataegus','species_name' => 'inanis','common_name' => 'Oldmaid hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1935','genus_name' => 'Crataegus','species_name' => 'iracunda','common_name' => 'Stolonbearing hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1936','genus_name' => 'Crataegus','species_name' => 'irrasa','common_name' => 'Blanchard\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1937','genus_name' => 'Cryptomeria','species_name' => 'japonica','common_name' => 'Japanese red cedar','growth_rate' => 'Fast','height_at_maturity' => '55'),
            array('id' => '1938','genus_name' => 'Crataegus','species_name' => 'jesupii','common_name' => 'Jesup\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1939','genus_name' => 'Crataegus','species_name' => 'jonesae','common_name' => 'Miss jones\' hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1940','genus_name' => 'Crataegus','species_name' => 'kelloggii','common_name' => 'Kellogg\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1941','genus_name' => 'Crataegus','species_name' => 'x kennedyi','common_name' => 'Kennedy\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1942','genus_name' => 'Crataegus','species_name' => 'knieskerniana','common_name' => 'Knieskern\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1943','genus_name' => 'Crataegus','species_name' => 'x lavallei','common_name' => 'Carriere hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1944','genus_name' => 'Cryptocarya','species_name' => 'laevigata','common_name' => 'Glossy Laurel','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '1945','genus_name' => 'Crataegus','species_name' => 'latebrosa','common_name' => 'Densewoods hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1946','genus_name' => 'Crataegus','species_name' => 'lacrimata','common_name' => 'Pensacola hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1947','genus_name' => 'Crataegus','species_name' => 'lanuginosa','common_name' => 'Woolly hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1948','genus_name' => 'Crataegus','species_name' => 'x laneyi','common_name' => 'Laney\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1949','genus_name' => 'Crataegus','species_name' => 'laciniata','common_name' => 'Oriental Thorn','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '1950','genus_name' => 'Crataegus','species_name' => 'laevigata','common_name' => 'Smooth hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1951','genus_name' => 'Crataegus','species_name' => 'lanata','common_name' => 'Hoary hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1952','genus_name' => 'Crataegus','species_name' => 'x lettermanii','common_name' => 'Letterman\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1953','genus_name' => 'Crataegus','species_name' => 'lemingtonensis','common_name' => 'Lemington hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1954','genus_name' => 'Crataegus','species_name' => 'limnophila','common_name' => 'Waterloving hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1956','genus_name' => 'Crescentia','species_name' => 'linearifolia','common_name' => 'Higuerito','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '1957','genus_name' => 'Crataegus','species_name' => 'limata','common_name' => 'Warm springs hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1959','genus_name' => 'Crataegus','species_name' => 'lucorum','common_name' => 'Grove hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1961','genus_name' => 'Crataegus','species_name' => 'lumaria','common_name' => 'Roundleaf hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1962','genus_name' => 'Crataegus','species_name' => 'marshallii','common_name' => 'Parsley hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '1963','genus_name' => 'Crataegus','species_name' => 'x maligna','common_name' => 'Crataegus x maligna','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1964','genus_name' => 'Crataegus','species_name' => 'macrosperma','common_name' => 'Bigfruit hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1965','genus_name' => 'Crataegus','species_name' => 'margarettae','common_name' => 'Margarett\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1966','genus_name' => 'Cryptocarya','species_name' => 'mannii','common_name' => 'Holio','growth_rate' => '','height_at_maturity' => '24'),
            array('id' => '1967','genus_name' => 'Crataegus','species_name' => 'mendosa','common_name' => 'Albertville hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1968','genus_name' => 'Crataegus','species_name' => 'mexicana','common_name' => 'Mexican hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '1969','genus_name' => 'Crataegus','species_name' => 'membranacea','common_name' => 'Tissueleaf hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1970','genus_name' => 'Croton','species_name' => 'megalocarpus','common_name' => 'Croton tree','growth_rate' => 'Fast','height_at_maturity' => '123'),
            array('id' => '1971','genus_name' => 'Crataegus','species_name' => 'meridionalis','common_name' => 'Gallion hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1972','genus_name' => 'Crataegus','species_name' => 'menandiana','common_name' => 'Menand\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1974','genus_name' => 'Crataegus','species_name' => 'mira','common_name' => 'Confederate hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1975','genus_name' => 'Crataegus','species_name' => 'x mordenensis','common_name' => 'Morden hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '1976','genus_name' => 'Crataegus','species_name' => 'mollis','common_name' => 'Downy hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '1977','genus_name' => 'Cryptocarya','species_name' => 'moschata','common_name' => 'Brazilian muskeg nut','growth_rate' => '','height_at_maturity' => '92'),
            array('id' => '1978','genus_name' => 'Crataegus','species_name' => 'multiflora','common_name' => 'Inkberry hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1979','genus_name' => 'Crataegus','species_name' => 'munda','common_name' => 'Batesburg hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1980','genus_name' => 'Crataegus','species_name' => 'nananixonii','common_name' => 'Nixon\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1981','genus_name' => 'Crataegus','species_name' => 'nitida','common_name' => 'Glossy hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1982','genus_name' => 'Crataegus','species_name' => 'nitidula','common_name' => 'Ontario hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1983','genus_name' => 'Crataegus','species_name' => 'x notha','common_name' => 'Crataegus x notha','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1984','genus_name' => 'Crataegus','species_name' => 'nuda','common_name' => 'Nude hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1985','genus_name' => 'Crataegus','species_name' => 'opaca','common_name' => 'Riverflat hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1986','genus_name' => 'Crataegus','species_name' => 'opulens','common_name' => 'Rochester hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1987','genus_name' => 'Crataegus','species_name' => 'orientalis','common_name' => 'Silver Hawthorn','growth_rate' => 'Fast','height_at_maturity' => '9'),
            array('id' => '1988','genus_name' => 'Crassula','species_name' => 'ovata','common_name' => 'Jade Plant','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '1989','genus_name' => 'Crataegus','species_name' => 'ovata','common_name' => 'Ovateleaf hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1990','genus_name' => 'Crataegus','species_name' => 'monogyna','common_name' => 'Oneseed hawthorn','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '1991','genus_name' => 'Crinodendron','species_name' => 'patagua','common_name' => 'Patagua','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '1992','genus_name' => 'Crataegus','species_name' => 'panda','common_name' => 'Florida hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1993','genus_name' => 'Crataegus','species_name' => 'pearsonii','common_name' => 'Pearson\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1994','genus_name' => 'Crataegus','species_name' => 'x peckietta','common_name' => 'Peck\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1995','genus_name' => 'Crataegus','species_name' => 'pequotorum','common_name' => 'Connecticut hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1996','genus_name' => 'Crataegus','species_name' => 'penita','common_name' => 'Great smoky mountain hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1997','genus_name' => 'Crataegus','species_name' => 'pennsylvanica','common_name' => 'Pennsylvania hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1998','genus_name' => 'Crataegus','species_name' => 'persimilis','common_name' => 'Plumleaf hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '1999','genus_name' => 'Crataegus','species_name' => 'perjucunda','common_name' => 'Pearthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2000','genus_name' => 'Crataegus','species_name' => 'phaenopyrum','common_name' => 'Washington hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '2001','genus_name' => 'Crataegus','species_name' => 'x pilosa','common_name' => 'Pilose hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2002','genus_name' => 'Crataegus','species_name' => 'pinnatifida','common_name' => 'Chinese hawthorn','growth_rate' => '','height_at_maturity' => '23'),
            array('id' => '2003','genus_name' => 'Crataegus','species_name' => 'pinnatifida major','common_name' => 'Chinese Haw','growth_rate' => 'Fast','height_at_maturity' => '7'),
            array('id' => '2004','genus_name' => 'Crataegus','species_name' => 'pinetorum','common_name' => 'Pineland hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2005','genus_name' => 'Crataegus','species_name' => 'piperi','common_name' => 'Piper\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2006','genus_name' => 'Crataegus','species_name' => 'poliophylla','common_name' => 'Elegant hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2007','genus_name' => 'Crataegus','species_name' => 'porrecta','common_name' => 'Pittsburgh hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2009','genus_name' => 'Crescentia','species_name' => 'portoricensis','common_name' => 'Higuero de sierra','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '2011','genus_name' => 'Crataegus','species_name' => 'pruinosa','common_name' => 'Frosted hawthorne','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2012','genus_name' => 'Crataegus','species_name' => 'prunifolia','common_name' => 'Broad-leaf Cockspur Thorn','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '2013','genus_name' => 'Crataegus','species_name' => 'pringlei','common_name' => 'Pringle\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2014','genus_name' => 'Crataegus','species_name' => 'pratensis','common_name' => 'Prairie hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2015','genus_name' => 'Crataegus','species_name' => 'prona','common_name' => 'Illinois hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2016','genus_name' => 'Crataegus','species_name' => 'punctata','common_name' => 'Dotted hawthorn','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '2017','genus_name' => 'Crataegus','species_name' => 'putata','common_name' => 'Scranton hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2018','genus_name' => 'Crataegus','species_name' => 'x puberis','common_name' => 'Crataegus x puberis','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2019','genus_name' => 'Crataegus','species_name' => 'pulcherrima','common_name' => 'Beautiful hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2020','genus_name' => 'Crataegus','species_name' => 'ravida','common_name' => 'Jeweled hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2021','genus_name' => 'Crataegus','species_name' => 'resima','common_name' => 'Gulf hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2022','genus_name' => 'Crateva','species_name' => 'religiosa','common_name' => 'sacred garlic pear','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '2023','genus_name' => 'Crataegus','species_name' => 'reverchonii','common_name' => 'Reverchon\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2024','genus_name' => 'Crossopetalum','species_name' => 'rhacoma','common_name' => 'Maidenberry','growth_rate' => 'Slow','height_at_maturity' => '9'),
            array('id' => '2025','genus_name' => 'Crataegus','species_name' => 'rhodella','common_name' => 'Franklin\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2026','genus_name' => 'Crataegus','species_name' => 'rivularis','common_name' => 'River hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2027','genus_name' => 'Croton','species_name' => 'rigidus','common_name' => 'Yellow balsam','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '2028','genus_name' => 'Crataegus','species_name' => 'rigens','common_name' => 'Gadsden hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2029','genus_name' => 'Crataegus','species_name' => 'rosei','common_name' => 'Crataegus rosei','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '2031','genus_name' => 'Crataegus','species_name' => 'x rubrocarnea','common_name' => 'Crataegus x rubrocarnea','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2032','genus_name' => 'Crataegus','species_name' => 'rufula','common_name' => 'Rusty hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2033','genus_name' => 'Crataegus','species_name' => 'saligna','common_name' => 'Willow hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2034','genus_name' => 'Crataegus','species_name' => 'sargentii','common_name' => 'Sargent\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2036','genus_name' => 'Crataegus','species_name' => 'schuettei','common_name' => 'Schuette\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2037','genus_name' => 'Crataegus','species_name' => 'scabrida','common_name' => 'Rough hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2038','genus_name' => 'Crataegus','species_name' => 'shaferi','common_name' => 'Shafer\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2039','genus_name' => 'Crataegus','species_name' => 'x simulata','common_name' => 'Crataegus x simulata','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2042','genus_name' => 'Crataegus','species_name' => 'spathulata','common_name' => 'Littlehip hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2043','genus_name' => 'Crataegus','species_name' => 'spatiosa','common_name' => 'New london hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2044','genus_name' => 'Crataegus','species_name' => 'spissa','common_name' => 'Essex hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2045','genus_name' => 'Crataegus','species_name' => 'stenosepala','common_name' => 'Duke hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2048','genus_name' => 'Crataegus','species_name' => 'succulenta','common_name' => 'Fleshy hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2049','genus_name' => 'Crataegus','species_name' => 'suksdorfii','common_name' => 'Suksdorf\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2050','genus_name' => 'Crataegus','species_name' => 'submollis','common_name' => 'Quebec hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2051','genus_name' => 'Crataegus','species_name' => 'suborbiculata','common_name' => 'Caughuawaga hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2052','genus_name' => 'Crataegus','species_name' => 'sutherlandensis','common_name' => 'Sutherland hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2053','genus_name' => 'Crateva','species_name' => 'tapia','common_name' => 'Toco','growth_rate' => 'Moderate','height_at_maturity' => '82'),
            array('id' => '2054','genus_name' => 'Crataegus','species_name' => 'tanuphylla','common_name' => 'Keystone hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2055','genus_name' => 'Crataegus','species_name' => 'texana','common_name' => 'Texas hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2056','genus_name' => 'Crataegus','species_name' => 'thermopegaea','common_name' => 'Graceful hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2057','genus_name' => 'Crataegus','species_name' => 'tinctoria','common_name' => 'Dyed hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2058','genus_name' => 'Crataegus','species_name' => 'tracyi','common_name' => 'Tracy\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2060','genus_name' => 'Crataegus','species_name' => 'triflora','common_name' => 'Threeflower hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2061','genus_name' => 'Crataegus','species_name' => 'tristis','common_name' => 'Minute hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2062','genus_name' => 'Crataegus','species_name' => 'turnerorum','common_name' => 'Turner\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2063','genus_name' => 'Crataegus','species_name' => 'uniflora','common_name' => 'Dwarf hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2065','genus_name' => 'Crataegus','species_name' => 'uvaldensis','common_name' => 'Lonestar hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2066','genus_name' => 'Crataegus','species_name' => 'vailiae','common_name' => 'Miss vail\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2067','genus_name' => 'Crataegus','species_name' => 'valida','common_name' => 'Rockmart hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2068','genus_name' => 'Crataegus','species_name' => 'versuta','common_name' => 'Johnny reb hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2069','genus_name' => 'Crataegus','species_name' => 'viridis','common_name' => 'Green hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '2070','genus_name' => 'Crataegus','species_name' => 'viburnifolia','common_name' => 'Sawtooth hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2071','genus_name' => 'Crataegus','species_name' => 'vulsa','common_name' => 'Alabama hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2072','genus_name' => 'Crataegus','species_name' => 'warneri','common_name' => 'Warner\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2073','genus_name' => 'Crataegus','species_name' => 'x websteri','common_name' => 'Webster\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2074','genus_name' => 'Crataegus','species_name' => 'x whittakeri','common_name' => 'Whittaker\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2076','genus_name' => 'Crataegus','species_name' => 'wootoniana','common_name' => 'Wooton\'s hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2077','genus_name' => 'Crataegus','species_name' => 'x smithiana','common_name' => 'Red Mexican Hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '2078','genus_name' => 'Crataegus','species_name' => 'xanthophylla','common_name' => 'Buffalo hawthorn','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '2079','genus_name' => 'Crataegus','species_name' => 'x media','common_name' => 'Crataegus x media','growth_rate' => 'Slow','height_at_maturity' => '26'),
            array('id' => '2080','genus_name' => 'Cupressus','species_name' => 'abramsiana','common_name' => 'Santa cruz island cypress','growth_rate' => 'Moderate','height_at_maturity' => '69'),
            array('id' => '2081','genus_name' => 'Cupania','species_name' => 'americana','common_name' => 'Guara','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '2082','genus_name' => 'Cupaniopsis','species_name' => 'anacardioides','common_name' => 'Carrotwood','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '2083','genus_name' => 'Cupressus','species_name' => 'arizonica','common_name' => 'Arizona cypress','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '2084','genus_name' => 'Cupressus','species_name' => 'bakeri','common_name' => 'Baker cypress','growth_rate' => 'Moderate','height_at_maturity' => '69'),
            array('id' => '2085','genus_name' => 'Cupressus','species_name' => 'benthamii','common_name' => 'Mexican cypress','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '2086','genus_name' => 'Cupressus','species_name' => 'cashmeriana','common_name' => 'Kashmir Cypress','growth_rate' => 'Moderate','height_at_maturity' => '45'),
            array('id' => '2088','genus_name' => 'Cupressus','species_name' => 'forbesii','common_name' => 'Tecate cypress','growth_rate' => 'Moderate','height_at_maturity' => '69'),
            array('id' => '2089','genus_name' => 'Cupressus','species_name' => 'funebris','common_name' => 'Chinese weeping cypress','growth_rate' => 'Moderate','height_at_maturity' => '43'),
            array('id' => '2092','genus_name' => 'Cupressus','species_name' => 'goveniana','common_name' => 'Gowen cypress','growth_rate' => 'Moderate','height_at_maturity' => '69'),
            array('id' => '2093','genus_name' => 'Cupressus','species_name' => 'guadalupensis','common_name' => 'Guadalupe cypress','growth_rate' => 'Fast','height_at_maturity' => '45'),
            array('id' => '2094','genus_name' => 'Cuphea','species_name' => 'hyssopifolia','common_name' => 'Stardust heather','growth_rate' => 'Fast','height_at_maturity' => '2'),
            array('id' => '2095','genus_name' => 'Cunninghamia','species_name' => 'lanceolata','common_name' => 'Blue chinese fir','growth_rate' => 'Moderate','height_at_maturity' => '60'),
            array('id' => '2096','genus_name' => 'Cupressocyparis','species_name' => 'leylandii','common_name' => 'Leyland cypress','growth_rate' => 'Fast','height_at_maturity' => '42'),
            array('id' => '2097','genus_name' => 'Cupressus','species_name' => 'lusitanica','common_name' => 'Cedar-of-Goa','growth_rate' => 'Moderate','height_at_maturity' => '69'),
            array('id' => '2098','genus_name' => 'Cupressus','species_name' => 'lusitanica v. benthamii','common_name' => 'Bentham\'s Cypress','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '2099','genus_name' => 'Cupressus','species_name' => 'macrocarpa','common_name' => 'Monterey cypress','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '2100','genus_name' => 'Cupressus','species_name' => 'macnabiana','common_name' => 'MacNab cypress','growth_rate' => 'Moderate','height_at_maturity' => '69'),
            array('id' => '2101','genus_name' => 'Cupressus','species_name' => 'macrocarpa \'Aurea\'','common_name' => 'Golde Monterey cypress','growth_rate' => 'Moderate','height_at_maturity' => '59'),
            array('id' => '2102','genus_name' => 'Cuphea','species_name' => 'mexicana','common_name' => 'False heather','growth_rate' => 'Fast','height_at_maturity' => '2'),
            array('id' => '2105','genus_name' => 'Cupressus','species_name' => 'sargentii','common_name' => 'Sargent cypress','growth_rate' => 'Moderate','height_at_maturity' => '69'),
            array('id' => '2107','genus_name' => 'Cupressus','species_name' => 'sempervirens','common_name' => 'Italian cypress','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '2108','genus_name' => 'Cupressus','species_name' => 'sempervirens \'Glauca\'','common_name' => 'Blue Pencil Pine','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '2109','genus_name' => 'Cupressus','species_name' => 'sempervirens \'Stricta\'','common_name' => 'Mediterranean cypress','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '2110','genus_name' => 'Cussonia','species_name' => 'spicata','common_name' => 'Cabbage Tree','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '2111','genus_name' => 'Cupressus','species_name' => 'torulosa','common_name' => 'Bhutan cypress','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '2112','genus_name' => 'Cupania','species_name' => 'triquetra','common_name' => 'Guara blanca','growth_rate' => '','height_at_maturity' => '65'),
            array('id' => '2113','genus_name' => 'Cudrania','species_name' => 'tricuspidata','common_name' => 'Storehousebush','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2115','genus_name' => 'Cuttsia','species_name' => 'viburnea','common_name' => 'Native Elderberry','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '2116','genus_name' => 'Cyanea','species_name' => 'aculeatiflora','common_name' => 'Haleakala cyanea','growth_rate' => '','height_at_maturity' => '16'),
            array('id' => '2123','genus_name' => 'Cyathea','species_name' => 'arborea','common_name' => 'Tree-fern','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '2124','genus_name' => 'Cyanea','species_name' => 'arborea','common_name' => 'Palmtree cyanea','growth_rate' => '','height_at_maturity' => '19'),
            array('id' => '2125','genus_name' => 'Cyathea','species_name' => 'armata','common_name' => 'Creeping treefern','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '2130','genus_name' => 'Cytisus','species_name' => 'battandieri','common_name' => 'Pineapple Broom','growth_rate' => 'Fast','height_at_maturity' => '3'),
            array('id' => '2132','genus_name' => 'Cyphomandra','species_name' => 'betacea','common_name' => 'Tamarillo','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '2141','genus_name' => 'Cycas','species_name' => 'circinalis','common_name' => 'Queen sago','growth_rate' => 'Slow','height_at_maturity' => '11'),
            array('id' => '2147','genus_name' => 'Cyathea','species_name' => 'cooperi','common_name' => 'Cooper\'s cyathea','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '2167','genus_name' => 'Cyanea','species_name' => 'fissa','common_name' => 'Kauai cyanea','growth_rate' => '','height_at_maturity' => '11'),
            array('id' => '2169','genus_name' => 'Cyathea','species_name' => 'furfuracea','common_name' => 'Jamaican treefern','growth_rate' => '','height_at_maturity' => '13'),
            array('id' => '2172','genus_name' => 'Cyrtandra','species_name' => 'giffardii','common_name' => 'Forest cyrtandra','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '2173','genus_name' => 'Cyanea','species_name' => 'giffardii','common_name' => 'Kilauea mauna cyanea','growth_rate' => '','height_at_maturity' => '26'),
            array('id' => '2174','genus_name' => 'Cyclobalanopsis','species_name' => 'glauca','common_name' => 'Cyclobalanopsis glauca','growth_rate' => '','height_at_maturity' => '65'),
            array('id' => '2185','genus_name' => 'Cyanea','species_name' => 'hamatiflora','common_name' => 'Wetforest cyanea','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '2186','genus_name' => 'Cyanea','species_name' => 'hardyi','common_name' => 'Oahu cyanea','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '2192','genus_name' => 'Cyanea','species_name' => 'horrida','common_name' => 'Prickly cyanea','growth_rate' => '','height_at_maturity' => '8'),
            array('id' => '2207','genus_name' => 'Cyanea','species_name' => 'kunthiana','common_name' => 'Kunth\'s cyanea','growth_rate' => '','height_at_maturity' => '3'),
            array('id' => '2213','genus_name' => 'Cyanea','species_name' => 'leptostegia','common_name' => 'Giant kokee cyanea','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '2223','genus_name' => 'Cyanea','species_name' => 'macrostegia','common_name' => 'Purple cyanea','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '2225','genus_name' => 'Cyanea','species_name' => 'marksii','common_name' => 'Marks\' cyanea','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '2237','genus_name' => 'Cytisus','species_name' => 'multiflorus','common_name' => 'White spanishbroom','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '2240','genus_name' => 'Cydonia','species_name' => 'oblonga','common_name' => 'Quince','growth_rate' => 'Moderate','height_at_maturity' => '16'),
            array('id' => '2247','genus_name' => 'Cyrilla','species_name' => 'parvifolia','common_name' => 'Littleleaf titi','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '2250','genus_name' => 'Cyanea','species_name' => 'pilosa','common_name' => 'Hairy cyanea','growth_rate' => '','height_at_maturity' => '3'),
            array('id' => '2254','genus_name' => 'Cyathea','species_name' => 'ponapeana','common_name' => 'kattar','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '2257','genus_name' => 'Cyanea','species_name' => 'pohaku','common_name' => 'Pohaku cyanea','growth_rate' => '','height_at_maturity' => '21'),
            array('id' => '2261','genus_name' => 'Cyanea','species_name' => 'procera','common_name' => 'Molokai cyanea','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '2267','genus_name' => 'Cyrilla','species_name' => 'racemiflora','common_name' => 'Swamp cypress','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '2269','genus_name' => 'Cynometra','species_name' => 'ramiflora','common_name' => 'cynometra','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '2271','genus_name' => 'Cycas','species_name' => 'revoluta','common_name' => 'Sago palm','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '2275','genus_name' => 'Cycas','species_name' => 'rumphii','common_name' => 'Cycas rumphii','growth_rate' => 'Slow','height_at_maturity' => '16'),
            array('id' => '2285','genus_name' => 'Cyanea','species_name' => 'solenocalyx','common_name' => 'Pua kala','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '2288','genus_name' => 'Cyanea','species_name' => 'stictophylla','common_name' => 'Kaiholena cyanea','growth_rate' => '','height_at_maturity' => '11'),
            array('id' => '2293','genus_name' => 'Cyanea','species_name' => 'superba','common_name' => 'Mt. kaala cyanea','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '2297','genus_name' => 'Cyanea','species_name' => 'tritomantha','common_name' => '\'aku \'aku','growth_rate' => '','height_at_maturity' => '7'),
            array('id' => '2309','genus_name' => 'Dasylirion','species_name' => 'acrotrichum','common_name' => 'Great desert spoon','growth_rate' => 'Slow','height_at_maturity' => '2'),
            array('id' => '2312','genus_name' => 'Dalbergia','species_name' => 'brownei','common_name' => 'Brown\'s indian rosewood','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '2313','genus_name' => 'Dalea','species_name' => 'carthagenensis','common_name' => 'Cartagena prairie clover','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2314','genus_name' => 'Dais','species_name' => 'cotinifolia','common_name' => 'Pompon Tree','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '2315','genus_name' => 'Dalbergia','species_name' => 'ecastaphyllum','common_name' => 'Coinvine','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '2316','genus_name' => 'Dacryodes','species_name' => 'excelsa','common_name' => 'Gommier','growth_rate' => 'Slow','height_at_maturity' => '115'),
            array('id' => '2320','genus_name' => 'Davidia','species_name' => 'involucrata','common_name' => 'Dove Tree','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '2321','genus_name' => 'Davidsonia','species_name' => 'jerseyana','common_name' => 'Mullumbimby Plum','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '2322','genus_name' => 'Daphne','species_name' => 'laureola','common_name' => 'Spurgelaurel','growth_rate' => '','height_at_maturity' => '3'),
            array('id' => '2323','genus_name' => 'Daphniphyllum','species_name' => 'macropodum','common_name' => 'Daphniphyllum','growth_rate' => '','height_at_maturity' => '5'),
            array('id' => '2324','genus_name' => 'Dalbergia','species_name' => 'monetaria','common_name' => 'Moneybush','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '2329','genus_name' => 'Dalbergia','species_name' => 'sissoo','common_name' => 'Indian rosewood','growth_rate' => 'Fast','height_at_maturity' => '63'),
            array('id' => '2332','genus_name' => 'Dasylirion','species_name' => 'wheeleri','common_name' => 'Spoon flower','growth_rate' => 'Slow','height_at_maturity' => '2'),
            array('id' => '2342','genus_name' => 'Deutzia','species_name' => 'gracilis','common_name' => 'Slender pride-of-rochester','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '2344','genus_name' => 'Dendrocnide','species_name' => 'latifolia','common_name' => 'kahtat','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '2349','genus_name' => 'Denhamia','species_name' => 'obscura','common_name' => 'Denhamia','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '2354','genus_name' => 'Delonix','species_name' => 'regia','common_name' => 'Royal poinciana','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '2357','genus_name' => 'Delissea','species_name' => 'rivularis','common_name' => 'Plateau delissea','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '2359','genus_name' => 'Deutzia','species_name' => 'scabra','common_name' => 'Fuzzy pride-of-rochester','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '2361','genus_name' => 'Dendrocalamus','species_name' => 'strictus','common_name' => 'Iron Bamboo','growth_rate' => 'Fast','height_at_maturity' => '12'),
            array('id' => '2365','genus_name' => 'Dillenia','species_name' => 'alata','common_name' => 'Red Beech','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '2366','genus_name' => 'Dicksonia','species_name' => 'antarctica','common_name' => 'Soft Tree-Fern','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '2367','genus_name' => 'Diospyros','species_name' => 'blancoi','common_name' => 'Mabolo','growth_rate' => 'Moderate','height_at_maturity' => '54'),
            array('id' => '2370','genus_name' => 'Diphysa','species_name' => 'carthagenensis','common_name' => 'Diphysa carthagenensis','growth_rate' => '','height_at_maturity' => '9'),
            array('id' => '2373','genus_name' => 'Diospyros','species_name' => 'compacta','common_name' => 'Australian Ebony','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '2374','genus_name' => 'Diospyros','species_name' => 'digyna','common_name' => 'Diospyros digyna','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '2375','genus_name' => 'Diospyros','species_name' => 'ebenum','common_name' => 'Ebony','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '2378','genus_name' => 'Diospyros','species_name' => 'hillebrandii','common_name' => 'Elama','growth_rate' => 'Moderate','height_at_maturity' => '54'),
            array('id' => '2379','genus_name' => 'Diospyros','species_name' => 'inconstans','common_name' => 'Antillean ebony','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '2381','genus_name' => 'Diospyros','species_name' => 'kaki','common_name' => 'Japanese persimmon','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2384','genus_name' => 'Diospyros','species_name' => 'lotus','common_name' => 'Date Plum','growth_rate' => 'Moderate','height_at_maturity' => '9'),
            array('id' => '2387','genus_name' => 'Dimocarpus','species_name' => 'longan','common_name' => 'longan','growth_rate' => '','height_at_maturity' => '22'),
            array('id' => '2388','genus_name' => 'Diospyros','species_name' => 'maritima','common_name' => 'Malaysian persimmon','growth_rate' => 'Moderate','height_at_maturity' => '54'),
            array('id' => '2391','genus_name' => 'Dirca','species_name' => 'palustris','common_name' => 'Eastern leatherwood','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '2393','genus_name' => 'Diospyros','species_name' => 'revoluta','common_name' => 'Black apple','growth_rate' => 'Moderate','height_at_maturity' => '54'),
            array('id' => '2396','genus_name' => 'Sideroxylon','species_name' => 'salicifolium','common_name' => 'Willow bustic','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '2397','genus_name' => 'Diospyros','species_name' => 'sandwicensis','common_name' => 'Lama','growth_rate' => 'Moderate','height_at_maturity' => '54'),
            array('id' => '2398','genus_name' => 'Diervilla','species_name' => 'sessilifolia','common_name' => 'Southern bush honeysuckle','growth_rate' => '','height_at_maturity' => '5'),
            array('id' => '2399','genus_name' => 'Dipteronia','species_name' => 'sinensis','common_name' => 'Dipteronia','growth_rate' => 'Fast','height_at_maturity' => '16'),
            array('id' => '2400','genus_name' => 'Diospyros','species_name' => 'sintenisii','common_name' => 'Chinese persimmon','growth_rate' => 'Moderate','height_at_maturity' => '54'),
            array('id' => '2402','genus_name' => 'Diphysa','species_name' => 'suberosa','common_name' => 'Diphysa suberosa','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2403','genus_name' => 'Dillenia','species_name' => 'suffruticosa','common_name' => 'Shrubby dillenia','growth_rate' => '','height_at_maturity' => '32'),
            array('id' => '2404','genus_name' => 'Diospyros','species_name' => 'texana','common_name' => 'Texas persimmon','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '2407','genus_name' => 'Diospyros','species_name' => 'virginiana','common_name' => 'Common persimmon','growth_rate' => 'Slow','height_at_maturity' => '55'),
            array('id' => '2409','genus_name' => 'Doryphora','species_name' => 'sassafras','common_name' => 'New South Wales Sassafras','growth_rate' => 'Moderate','height_at_maturity' => '82'),
            array('id' => '2410','genus_name' => 'Dolichandrone','species_name' => 'spathacea','common_name' => 'mangrove trumpet','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '2411','genus_name' => 'Dombeya','species_name' => 'tiliacea','common_name' => 'Cape Wedding Bells','growth_rate' => 'Fast','height_at_maturity' => '7'),
            array('id' => '2412','genus_name' => 'Dodonaea','species_name' => 'viscosa','common_name' => 'Florida hopbush','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '2413','genus_name' => 'Dombeya','species_name' => 'wallichii','common_name' => 'Dombeya','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2415','genus_name' => 'Dracaena','species_name' => 'compacta','common_name' => 'Dracaena compacta','growth_rate' => 'Slow','height_at_maturity' => '7'),
            array('id' => '2418','genus_name' => 'Dracontomelon','species_name' => 'duperreanum','common_name' => 'Cay Sau','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '2419','genus_name' => 'Banksia','species_name' => 'formosa','common_name' => 'Showy Dryandra','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '2420','genus_name' => 'Dracaena','species_name' => 'fragrans','common_name' => 'Fragrant dracaena','growth_rate' => 'Slow','height_at_maturity' => '17'),
            array('id' => '2424','genus_name' => 'Dracaena','species_name' => 'marginata','common_name' => 'Madagascar dragon tree','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '2425','genus_name' => 'Dracaena','species_name' => 'reflexa','common_name' => 'Song of India','growth_rate' => 'Slow','height_at_maturity' => '16'),
            array('id' => '2426','genus_name' => 'Drimys','species_name' => 'winteri','common_name' => 'Canelo','growth_rate' => 'Moderate','height_at_maturity' => '16'),
            array('id' => '2427','genus_name' => 'Dubautia','species_name' => 'arborea','common_name' => 'Mauna kea dubautia','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '2431','genus_name' => 'Duranta','species_name' => 'erecta','common_name' => 'Golden dewdrops','growth_rate' => 'Moderate','height_at_maturity' => '9'),
            array('id' => '2440','genus_name' => 'Dubautia','species_name' => 'microcephala','common_name' => 'Kauai dubautia','growth_rate' => '','height_at_maturity' => '13'),
            array('id' => '2448','genus_name' => 'Dubautia','species_name' => 'reticulata','common_name' => 'Netvein dubautia','growth_rate' => '','height_at_maturity' => '26'),
            array('id' => '2451','genus_name' => 'Durio','species_name' => 'zibethinus','common_name' => 'Durian','growth_rate' => '','height_at_maturity' => '150'),
            array('id' => '2452','genus_name' => 'Dypsis','species_name' => 'decaryi','common_name' => 'Triangle palm','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '2453','genus_name' => 'Dysoxylum','species_name' => 'fraserianum','common_name' => 'Rose Mahogany','growth_rate' => 'Moderate','height_at_maturity' => '57'),
            array('id' => '2454','genus_name' => 'Dysoxylum','species_name' => 'huntii','common_name' => 'maota mea','growth_rate' => '','height_at_maturity' => '27'),
            array('id' => '2455','genus_name' => 'Dypsis','species_name' => 'leptocheilos','common_name' => 'Teddy Bear Palm','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '2456','genus_name' => 'Dypsis','species_name' => 'madagascariensis','common_name' => 'Malagasy Palm','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '2461','genus_name' => 'Ehretia','species_name' => 'acuminata','common_name' => 'Koda Tree','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '2462','genus_name' => 'Ehretia','species_name' => 'anacua','common_name' => 'Knockaway','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '2463','genus_name' => 'Ehretia','species_name' => 'cymosa','common_name' => 'Ehretia cymosa','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '2464','genus_name' => 'Ehretia','species_name' => 'latifolia','common_name' => 'Ehretia latifolia','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '2466','genus_name' => 'Ehretia','species_name' => 'tinifolia','common_name' => 'Cherry ehretia','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2467','genus_name' => 'Elaeagnus','species_name' => 'angustifolia','common_name' => 'Russian olive','growth_rate' => 'Fast','height_at_maturity' => '23'),
            array('id' => '2468','genus_name' => 'Elaeodendron','species_name' => 'australe','common_name' => 'Red Olive Plum','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '2470','genus_name' => 'Elaeocarpus','species_name' => 'bifidus','common_name' => 'Kalia','growth_rate' => 'Fast','height_at_maturity' => '73'),
            array('id' => '2471','genus_name' => 'Elaeocarpus','species_name' => 'carolinensis','common_name' => 'sadak','growth_rate' => '','height_at_maturity' => '48'),
            array('id' => '2472','genus_name' => 'Elaeagnus','species_name' => 'commutata','common_name' => 'Silverberry','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '2473','genus_name' => 'Elaeodendron','species_name' => 'croceum','common_name' => 'Common Saffron','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '2475','genus_name' => 'Elaeocarpus','species_name' => 'eumundi','common_name' => 'Smooth-leaved Quandong','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '2476','genus_name' => 'Elaeocarpus','species_name' => 'glabripetalus','common_name' => 'Elaeocarpus glabripetalus','growth_rate' => 'Fast','height_at_maturity' => '73'),
            array('id' => '2477','genus_name' => 'Elaeocarpus','species_name' => 'grandis','common_name' => 'Blue Quandong','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '2478','genus_name' => 'Elaeis','species_name' => 'guineensis','common_name' => 'African oil palm','growth_rate' => '','height_at_maturity' => '65'),
            array('id' => '2480','genus_name' => 'Elaeocarpus','species_name' => 'joga','common_name' => 'joga','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '2481','genus_name' => 'Elaeagnus','species_name' => 'multiflora','common_name' => 'Cherry silverberry','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '2482','genus_name' => 'Elaeocarpus','species_name' => 'obovatus','common_name' => 'Hard Quandong','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '2485','genus_name' => 'Elaeagnus','species_name' => 'pungens','common_name' => 'Thorny olive','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '2487','genus_name' => 'Elliottia','species_name' => 'racemosa','common_name' => 'Georgia plume','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '2488','genus_name' => 'Elaeocarpus','species_name' => 'reticulatus','common_name' => 'Blueberry ash','growth_rate' => 'Moderate','height_at_maturity' => '21'),
            array('id' => '2490','genus_name' => 'Eleutherococcus','species_name' => 'sessiliflorus','common_name' => 'Stalkless flower','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '2491','genus_name' => 'Elaeagnus','species_name' => 'umbellata','common_name' => 'Autumn olive','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '2495','genus_name' => 'Entelea','species_name' => 'arborescens','common_name' => 'Whau','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '2496','genus_name' => 'Endospermum','species_name' => 'chinense','common_name' => 'Endospermum chinense','growth_rate' => 'Slow','height_at_maturity' => ''),
            array('id' => '2497','genus_name' => 'Enterolobium','species_name' => 'contortisiliquum','common_name' => 'Pacara earpod tree','growth_rate' => '','height_at_maturity' => '130'),
            array('id' => '2498','genus_name' => 'Enterolobium','species_name' => 'cyclocarpum','common_name' => 'Earpod tree','growth_rate' => '','height_at_maturity' => '130'),
            array('id' => '2504','genus_name' => 'Endiandra','species_name' => 'sieberi','common_name' => 'Hard Corkwood','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '2507','genus_name' => 'Eremophila','species_name' => 'alternifolia','common_name' => 'Native Honeysuckle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '2511','genus_name' => 'Erica','species_name' => 'arborea','common_name' => 'Tree Heath','growth_rate' => 'Fast','height_at_maturity' => '7'),
            array('id' => '2512','genus_name' => 'Erythroxylum','species_name' => 'areolatum','common_name' => 'Swamp-redwood','growth_rate' => 'Slow','height_at_maturity' => ''),
            array('id' => '2514','genus_name' => 'Erythrina','species_name' => 'berteroana','common_name' => 'Machete','growth_rate' => 'Fast','height_at_maturity' => '55'),
            array('id' => '2516','genus_name' => 'Eremophila','species_name' => 'bignoniiflora','common_name' => 'Creek Wilga','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '2518','genus_name' => 'Erythroxylum','species_name' => 'brevipes','common_name' => 'Brisselet','growth_rate' => 'Slow','height_at_maturity' => ''),
            array('id' => '2523','genus_name' => 'Erythrophleum','species_name' => 'chlorostachys','common_name' => 'Cooktown ironwood','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '2525','genus_name' => 'Erythrina','species_name' => 'corallodendron','common_name' => 'Coral erythrina','growth_rate' => 'Fast','height_at_maturity' => '55'),
            array('id' => '2526','genus_name' => 'Erythrina','species_name' => 'crista-galli','common_name' => 'Cockspur coral tree','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2530','genus_name' => 'Eriobotrya','species_name' => 'deflexa','common_name' => 'Bronze loquat','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '2531','genus_name' => 'Erythrina','species_name' => 'edulis','common_name' => 'Sacha poroto','growth_rate' => 'Fast','height_at_maturity' => '26'),
            array('id' => '2532','genus_name' => 'Erythrina','species_name' => 'eggersii','common_name' => 'Cock\'s spur','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '2534','genus_name' => 'Erythrina','species_name' => 'falcata','common_name' => 'Corticeira-da-serra','growth_rate' => 'Fast','height_at_maturity' => '55'),
            array('id' => '2535','genus_name' => 'Erythrina','species_name' => 'flabelliformis','common_name' => 'Coralbean','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '2536','genus_name' => 'Erithalis','species_name' => 'fruticosa','common_name' => 'Blacktorch','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '2537','genus_name' => 'Erythrina','species_name' => 'fusca','common_name' => 'Bucayo','growth_rate' => 'Fast','height_at_maturity' => '55'),
            array('id' => '2539','genus_name' => 'Erythrina','species_name' => 'herbacea','common_name' => 'Eastern coralbean','growth_rate' => 'Fast','height_at_maturity' => '55'),
            array('id' => '2540','genus_name' => 'Erythrina','species_name' => 'humeana','common_name' => 'Natal coral tree','growth_rate' => '','height_at_maturity' => '13'),
            array('id' => '2541','genus_name' => 'Eriobotrya','species_name' => 'japonica','common_name' => 'Loquat tree','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2547','genus_name' => 'Eremophila','species_name' => 'oppositifolia','common_name' => 'Twin Leaf Emu Bush','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '2549','genus_name' => 'Tabernaemontana','species_name' => 'orientalis','common_name' => 'Banana Bush','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '2557','genus_name' => 'Erythrina','species_name' => 'poeppigiana','common_name' => 'Mountain immortelle','growth_rate' => 'Fast','height_at_maturity' => '55'),
            array('id' => '2563','genus_name' => 'Erythrina','species_name' => 'sandwicensis','common_name' => 'Wili wili','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '2564','genus_name' => 'Erythrina','species_name' => 'senegalensis','common_name' => 'Senegal Coral Tree','growth_rate' => 'Fast','height_at_maturity' => '7'),
            array('id' => '2565','genus_name' => 'Erythrina','species_name' => 'speciosa','common_name' => 'Coral tree','growth_rate' => 'Fast','height_at_maturity' => '55'),
            array('id' => '2566','genus_name' => 'Erythrina','species_name' => 'subumbrans','common_name' => 'december tree','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '2572','genus_name' => 'Erythrina','species_name' => 'umbrosa','common_name' => 'Ceibo','growth_rate' => 'Fast','height_at_maturity' => '55'),
            array('id' => '2574','genus_name' => 'Erythrina','species_name' => 'variegata','common_name' => 'Tiger\'s claw','growth_rate' => 'Fast','height_at_maturity' => '55'),
            array('id' => '2575','genus_name' => 'Erythrina','species_name' => 'variegata v orientalis','common_name' => 'Indian coral tree','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '2576','genus_name' => 'Erythrina','species_name' => 'vespertilio','common_name' => 'Bat\'s-wing coral tree','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '2577','genus_name' => 'Erythrina','species_name' => 'x sykesii','common_name' => 'Thorny coral tree','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '2579','genus_name' => 'Escallonia','species_name' => 'bifida','common_name' => 'Escallonia','growth_rate' => 'Fast','height_at_maturity' => '4'),
            array('id' => '2580','genus_name' => 'Escallonia','species_name' => 'macrantha','common_name' => 'Pink Escallonia','growth_rate' => 'Fast','height_at_maturity' => '3'),
            array('id' => '2582','genus_name' => 'Eucalyptus','species_name' => 'acaciformis','common_name' => 'Wattle-leaved peppermint','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '2583','genus_name' => 'Eucalyptus','species_name' => 'acmenoides','common_name' => 'White mahogany','growth_rate' => 'Moderate','height_at_maturity' => '148'),
            array('id' => '2584','genus_name' => 'Eucalyptus','species_name' => 'acaciiformis','common_name' => 'Wattle Leaf Peppermint','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2585','genus_name' => 'Eucalyptus','species_name' => 'accedens','common_name' => 'Powder-bark Wandoo','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2586','genus_name' => 'Eucalyptus','species_name' => 'agglomerata','common_name' => 'Blue-leaved stringybark','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '2587','genus_name' => 'Eucalyptus','species_name' => 'aggregata','common_name' => 'Black gum','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '2588','genus_name' => 'Euonymus','species_name' => 'alatus','common_name' => 'Winged burningbush','growth_rate' => 'Slow','height_at_maturity' => '16'),
            array('id' => '2589','genus_name' => 'Eucalyptus','species_name' => 'alba australasica','common_name' => 'White Gum','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '2590','genus_name' => 'Euonymus','species_name' => 'alata','common_name' => 'Winged burning bush','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2591','genus_name' => 'Eucalyptus','species_name' => 'albens','common_name' => 'Whitebox','growth_rate' => 'Fast','height_at_maturity' => '75'),
            array('id' => '2592','genus_name' => 'Eucalyptus','species_name' => 'amplifolia','common_name' => 'Cabbage gum','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '2594','genus_name' => 'Euonymus','species_name' => 'americanus','common_name' => 'Bursting-heart','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2595','genus_name' => 'Eucalyptus','species_name' => 'amygdalina','common_name' => 'Blackpeppermint','growth_rate' => 'Fast','height_at_maturity' => '75'),
            array('id' => '2596','genus_name' => 'Eucalyptus','species_name' => 'andrewsii','common_name' => 'New england blackbutt','growth_rate' => 'Moderate','height_at_maturity' => '148'),
            array('id' => '2597','genus_name' => 'Eucalyptus','species_name' => 'angophoroides','common_name' => 'Apple-topped box','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '2598','genus_name' => 'Eucalyptus','species_name' => 'angulosa','common_name' => 'Ridge-fruited Mallee','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '2599','genus_name' => 'Eucalyptus','species_name' => 'aromaphloia','common_name' => 'Scent bark','growth_rate' => 'Moderate','height_at_maturity' => '59'),
            array('id' => '2600','genus_name' => 'Eucalyptus','species_name' => 'apiculata','common_name' => 'Narrow-leaved malle ash','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '2601','genus_name' => 'Eucalyptus','species_name' => 'approximans','common_name' => 'Barren Mountain Mallee','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '2602','genus_name' => 'Euonymus','species_name' => 'aptera','common_name' => 'Corky spindletree','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2603','genus_name' => 'Eugenia','species_name' => 'aquea','common_name' => 'water apple','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '2604','genus_name' => 'Eucalyptus','species_name' => 'archeri','common_name' => 'Alpine Cider Gum','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '2605','genus_name' => 'Eucalyptus','species_name' => 'arenacea','common_name' => 'Desert Stringybark','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '2606','genus_name' => 'Eucalyptus','species_name' => 'astringens','common_name' => 'Brown mallet','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '2607','genus_name' => 'Euonymus','species_name' => 'atropurpureus','common_name' => 'Eastern wahoo','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2608','genus_name' => 'Eugenia','species_name' => 'axillaris','common_name' => 'White stopper','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2609','genus_name' => 'Eucalyptus','species_name' => 'baileyana','common_name' => 'Bailey\'s Stringybark','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '2610','genus_name' => 'Eucalyptus','species_name' => 'badjensis','common_name' => 'Big Badja gum','growth_rate' => 'Moderate','height_at_maturity' => '148'),
            array('id' => '2612','genus_name' => 'Eucalyptus','species_name' => 'baeuerlenii','common_name' => 'Baeuerlen\'s gum','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '2613','genus_name' => 'Eucalyptus','species_name' => 'bakeri','common_name' => 'Baker\'s mallee','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '2614','genus_name' => 'Eucalyptus','species_name' => 'bancroftii','common_name' => 'Bancroft\'s redgum','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '2615','genus_name' => 'Eucalyptus','species_name' => 'baueriana','common_name' => 'Blue box','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '2616','genus_name' => 'Eucalyptus','species_name' => 'baxteri','common_name' => 'Brown stringy bark','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '2617','genus_name' => 'Eucalyptus','species_name' => 'banksii','common_name' => 'Tenterfield Woollybutt','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2618','genus_name' => 'Eucalyptus','species_name' => 'barberi','common_name' => 'Barber\'s Gum','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '2620','genus_name' => 'Eucalyptus','species_name' => 'benthamii','common_name' => 'Camden white gum','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '2621','genus_name' => 'Eucalyptus','species_name' => 'beyeri','common_name' => 'Beyer\'s ironbark','growth_rate' => 'Slow','height_at_maturity' => '66'),
            array('id' => '2622','genus_name' => 'Eucalyptus','species_name' => 'behriana','common_name' => 'Bull Mallee','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '2623','genus_name' => 'Eugenia','species_name' => 'bellonis','common_name' => 'Puerto rico stopper','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2624','genus_name' => 'Eugenia','species_name' => 'biflora','common_name' => 'Blackrodwood','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2625','genus_name' => 'Eucalyptus','species_name' => 'bigalerita','common_name' => 'Northern Salmon Gum','growth_rate' => 'Moderate','height_at_maturity' => '17'),
            array('id' => '2626','genus_name' => 'Eucalyptus','species_name' => 'biturbinata','common_name' => 'New South Wales Grey Gum','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '2627','genus_name' => 'Eucalyptus','species_name' => 'blakelyi','common_name' => 'Blakely\'s redgum','growth_rate' => 'Moderate','height_at_maturity' => '82'),
            array('id' => '2628','genus_name' => 'Eucalyptus','species_name' => 'blaxlandii','common_name' => 'Blaxland\'s strigybark','growth_rate' => 'Moderate','height_at_maturity' => '116'),
            array('id' => '2629','genus_name' => 'Eucalyptus','species_name' => 'botryoides','common_name' => 'Southern mahogany','growth_rate' => 'Fast','height_at_maturity' => '115'),
            array('id' => '2630','genus_name' => 'Eucalyptus','species_name' => 'bosistoana','common_name' => 'Coast grey box','growth_rate' => 'Moderate','height_at_maturity' => '198'),
            array('id' => '2631','genus_name' => 'Eugenia','species_name' => 'boqueronensis','common_name' => 'Sierra de cayey stopper','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2632','genus_name' => 'Eugenia','species_name' => 'borinquensis','common_name' => 'Guayabota de sierra','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2634','genus_name' => 'Eucalyptus','species_name' => 'brookeriana','common_name' => 'Brooker\'s gum','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '2635','genus_name' => 'Eucalyptus','species_name' => 'bridgesiana','common_name' => 'Applebox','growth_rate' => 'Fast','height_at_maturity' => '75'),
            array('id' => '2636','genus_name' => 'Eucalyptus','species_name' => 'brachycalyx','common_name' => 'Gilja','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '2637','genus_name' => 'Eugenia','species_name' => 'brasiliensis','common_name' => 'Brazilian cherry','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '2639','genus_name' => 'Eucalyptus','species_name' => 'burgessiana','common_name' => 'Faulconbridge malle ash','growth_rate' => 'Slow','height_at_maturity' => '23'),
            array('id' => '2640','genus_name' => 'Euonymus','species_name' => 'bungeanum','common_name' => 'Winterberry','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2641','genus_name' => 'Eucalyptus','species_name' => 'calophylla','common_name' => 'Redgum','growth_rate' => 'Fast','height_at_maturity' => '75'),
            array('id' => '2642','genus_name' => 'Eucalyptus','species_name' => 'camaldulensis','common_name' => 'Red gum eucalyptus','growth_rate' => 'Fast','height_at_maturity' => '120'),
            array('id' => '2643','genus_name' => 'Eugenia','species_name' => 'cacuminis','common_name' => 'Cerro torrecilla stopper','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2644','genus_name' => 'Eucalyptus','species_name' => 'cadens','common_name' => 'Tumble-down Swamp Gum','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2645','genus_name' => 'Eucalyptus','species_name' => 'camfieldii','common_name' => 'Camfield\'s Stringybark','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '2646','genus_name' => 'Eucalyptus','species_name' => 'calycogona','common_name' => 'Square-fruited Mallee','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '2647','genus_name' => 'Euphorbia','species_name' => 'candelabrum','common_name' => 'Candelabra tree','growth_rate' => 'Fast','height_at_maturity' => '19'),
            array('id' => '2648','genus_name' => 'Eugenia','species_name' => 'caryophyllus','common_name' => 'cloves','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '2649','genus_name' => 'Eucalyptus','species_name' => 'camaldulensis ovata','common_name' => 'River red gum','growth_rate' => 'Moderate','height_at_maturity' => '149'),
            array('id' => '2650','genus_name' => 'Eucalyptus','species_name' => 'camphora','common_name' => 'Swamp gum eucalyptus','growth_rate' => 'Fast','height_at_maturity' => '75'),
            array('id' => '2651','genus_name' => 'Eucalyptus','species_name' => 'caesia','common_name' => 'Gungurru','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '2652','genus_name' => 'Eucalyptus','species_name' => 'caliginosa','common_name' => 'Broad-leaved stringybark','growth_rate' => 'Moderate','height_at_maturity' => '116'),
            array('id' => '2653','genus_name' => 'Eucalyptus','species_name' => 'cameronii','common_name' => 'Diehard stringybark','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '2654','genus_name' => 'Eucalyptus','species_name' => 'canaliculata','common_name' => 'Large-fruit grey gum','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '2655','genus_name' => 'Eucalyptus','species_name' => 'capitellata','common_name' => 'Brown stringybark','growth_rate' => 'Moderate','height_at_maturity' => '82'),
            array('id' => '2656','genus_name' => 'Eucalyptus','species_name' => 'carnea','common_name' => 'Broad-leaf White Mahogany','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2657','genus_name' => 'Eucalyptus','species_name' => 'caleyi','common_name' => 'Caley\'s Ironbark','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '2658','genus_name' => 'Eucalyptus','species_name' => 'camaldulensis x ovata','common_name' => 'Eucalyptus camaldulensis','growth_rate' => 'Moderate','height_at_maturity' => '148'),
            array('id' => '2659','genus_name' => 'Eucalyptus','species_name' => 'cephalocarpa','common_name' => 'Silver stringybark','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '2660','genus_name' => 'Eucalyptus','species_name' => 'chapmaniana','common_name' => 'Bogong gum','growth_rate' => 'Moderate','height_at_maturity' => '116'),
            array('id' => '2661','genus_name' => 'Eucalyptus','species_name' => 'chloroclada','common_name' => 'Baradine Red Gum','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2663','genus_name' => 'Eucalyptus','species_name' => 'cinerea','common_name' => 'Silver dollar eucalyptus','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '2665','genus_name' => 'Eucalyptus','species_name' => 'cladocalyx','common_name' => 'Sugargum','growth_rate' => 'Fast','height_at_maturity' => '75'),
            array('id' => '2666','genus_name' => 'Eucalyptus','species_name' => 'cloeziana','common_name' => 'Gympie Messmate','growth_rate' => 'Moderate','height_at_maturity' => '55'),
            array('id' => '2667','genus_name' => 'Eucalyptus','species_name' => 'cladocalyx v. nana','common_name' => 'Dwarf Sugar gum','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '2668','genus_name' => 'Eucalyptus','species_name' => 'cneorifolia','common_name' => 'Kangaroo Narrow Mallee','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '2669','genus_name' => 'Eucalyptus','species_name' => 'conferruminata','common_name' => 'Bald island marlock','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '2670','genus_name' => 'Eucalyptus','species_name' => 'coccifera','common_name' => 'Tasmanian snow gum','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '2671','genus_name' => 'Eucalyptus','species_name' => 'cosmophylla','common_name' => 'Cup Gum','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '2672','genus_name' => 'Eugenia','species_name' => 'corozalensis','common_name' => 'Sperry guava','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2673','genus_name' => 'Eucalyptus','species_name' => 'conica','common_name' => 'Fuzzy box','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '2674','genus_name' => 'Euphorbia','species_name' => 'cotinifolia','common_name' => 'Mexican shrubby spurge','growth_rate' => 'Slow','height_at_maturity' => '38'),
            array('id' => '2675','genus_name' => 'Eucalyptus','species_name' => 'cornuta','common_name' => 'Yate','growth_rate' => 'Fast','height_at_maturity' => '75')
        );

        Tree::insert($trees);

        $seeder = new TreeSpeciesSeeder4;
        $seeder->run();

    }
}