<?php

namespace Database\Seeders\TreeSpecies;

use App\Models\Trees\Tree;
use Illuminate\Database\Seeder;

class TreeSpeciesSeeder0 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $trees = array(
            array('id' => '1','genus_name' => 'Dovyalis','species_name' => 'abyssinica','common_name' => 'Abyssinian Gooseberry','growth_rate' => 'Fast','height_at_maturity' => '28'),
            array('id' => '2','genus_name' => 'Adonidia','species_name' => 'alba','common_name' => 'Silver fir','growth_rate' => 'Slow','height_at_maturity' => '88'),
            array('id' => '3','genus_name' => 'Abies','species_name' => 'alba','common_name' => 'European silver fir','growth_rate' => 'Slow','height_at_maturity' => '147'),
            array('id' => '4','genus_name' => 'Abies','species_name' => 'amabilis','common_name' => 'Pacific silver fir','growth_rate' => 'Slow','height_at_maturity' => '165'),
            array('id' => '5','genus_name' => 'Abies','species_name' => 'balsamea','common_name' => 'Balsam fir','growth_rate' => 'Slow','height_at_maturity' => '60'),
            array('id' => '6','genus_name' => 'Abutilon','species_name' => 'berlandieri','common_name' => 'Berlandier indian mallow','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '7','genus_name' => 'Abies','species_name' => 'x borisii-regis','common_name' => 'Bulgarian fir','growth_rate' => 'Slow','height_at_maturity' => '96'),
            array('id' => '8','genus_name' => 'Abies','species_name' => 'bracteata','common_name' => 'Bristlecone fir','growth_rate' => 'Slow','height_at_maturity' => '105'),
            array('id' => '9','genus_name' => 'Abies','species_name' => 'cephalonica','common_name' => 'Greek Fir','growth_rate' => 'Moderate','height_at_maturity' => '49'),
            array('id' => '10','genus_name' => 'Abelia','species_name' => 'chinensis','common_name' => 'Abelia','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '11','genus_name' => 'Abies','species_name' => 'cilicica','common_name' => 'Syrian Fir','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '12','genus_name' => 'Abies','species_name' => 'concolor','common_name' => 'White fir','growth_rate' => 'Slow','height_at_maturity' => '120'),
            array('id' => '14','genus_name' => 'Abies','species_name' => 'delavayi','common_name' => 'Delavay\'s Fir','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '15','genus_name' => 'Abutilon','species_name' => 'eremitopetalum','common_name' => 'Hiddenpetal indian mallow','growth_rate' => 'Moderate','height_at_maturity' => '2'),
            array('id' => '16','genus_name' => 'Abies','species_name' => 'fargesii','common_name' => 'Farges Fir','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '17','genus_name' => 'Abies','species_name' => 'firma','common_name' => 'Momi Fir','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '18','genus_name' => 'Abies','species_name' => 'forrestii var. georgei','common_name' => 'George\'s Fir','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '19','genus_name' => 'Abies','species_name' => 'fraseri','common_name' => 'Fraser fir','growth_rate' => 'Moderate','height_at_maturity' => '55'),
            array('id' => '21','genus_name' => 'Abies','species_name' => 'grandis','common_name' => 'Grand fir','growth_rate' => 'Moderate','height_at_maturity' => '150'),
            array('id' => '22','genus_name' => 'Abutilon','species_name' => 'grandifolium','common_name' => 'Hairy indian mallow','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '23','genus_name' => 'Abelia','species_name' => 'x grandiflora','common_name' => 'Glossy abelia','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '24','genus_name' => 'Abies','species_name' => 'holophylla','common_name' => 'Manchurian fir','growth_rate' => 'Slow','height_at_maturity' => '100'),
            array('id' => '25','genus_name' => 'Abies','species_name' => 'homolepis','common_name' => 'Japanese fir','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '26','genus_name' => 'Abies','species_name' => 'koreana','common_name' => 'Korean Fir','growth_rate' => 'Fast','height_at_maturity' => '9'),
            array('id' => '27','genus_name' => 'Abies','species_name' => 'lasiocarpa','common_name' => 'Subalpine fir','growth_rate' => 'Slow','height_at_maturity' => '90'),
            array('id' => '29','genus_name' => 'Abies','species_name' => 'concolor v lowiana','common_name' => 'Sierra white fir','growth_rate' => 'Slow','height_at_maturity' => '96'),
            array('id' => '30','genus_name' => 'Abies','species_name' => 'magnifica','common_name' => 'California red fir','growth_rate' => 'Slow','height_at_maturity' => '150'),
            array('id' => '31','genus_name' => 'Abies','species_name' => 'x masjoannis','common_name' => 'Masjoannis fir','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '32','genus_name' => 'Abutilon','species_name' => 'megapotamicum','common_name' => 'Abutilon megapotamicum','growth_rate' => 'Fast','height_at_maturity' => '13'),
            array('id' => '33','genus_name' => 'Abutilon','species_name' => 'menziesii','common_name' => 'Ko\'oloa \'ula','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '34','genus_name' => 'Abies','species_name' => 'nordmanniana','common_name' => 'Nordmann fir','growth_rate' => 'Slow','height_at_maturity' => '63'),
            array('id' => '35','genus_name' => 'Abies','species_name' => 'numidica','common_name' => 'Algerian Fir','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '36','genus_name' => 'Abutilon','species_name' => 'palmeri','common_name' => 'Palmer\'s indian mallow','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '37','genus_name' => 'Abies','species_name' => 'x phanerolepis','common_name' => 'Bracted balsam fir','growth_rate' => 'Slow','height_at_maturity' => '96'),
            array('id' => '38','genus_name' => 'Abies','species_name' => 'pinsapo','common_name' => 'Spanish fir','growth_rate' => 'Slow','height_at_maturity' => '96'),
            array('id' => '39','genus_name' => 'Abies','species_name' => 'procera','common_name' => 'Noble fir','growth_rate' => 'Fast','height_at_maturity' => '230'),
            array('id' => '40','genus_name' => 'Abies','species_name' => 'religiosa','common_name' => 'Sacred fir','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '41','genus_name' => 'Abutilon','species_name' => 'sandwicense','common_name' => 'Greenflower indian mallow','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '42','genus_name' => 'Abies','species_name' => 'x shastensis','common_name' => 'Shasta red fir','growth_rate' => 'Slow','height_at_maturity' => '96'),
            array('id' => '43','genus_name' => 'Abelia','species_name' => 'triflora','common_name' => 'Indian abelia','growth_rate' => 'Fast','height_at_maturity' => '13'),
            array('id' => '44','genus_name' => 'Abies','species_name' => 'veitchii','common_name' => 'Veitch\'s Silver Fir','growth_rate' => 'Fast','height_at_maturity' => '22'),
            array('id' => '45','genus_name' => 'Abutilon','species_name' => 'virginianum','common_name' => 'Van dyke\'s indian mallow','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '46','genus_name' => 'Acacia','species_name' => 'abyssinica','common_name' => 'Flat top acacia','growth_rate' => 'Fast','height_at_maturity' => '55'),
            array('id' => '47','genus_name' => 'Acacia','species_name' => 'acradenia','common_name' => 'Silky Wattle','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '48','genus_name' => 'Acacia','species_name' => 'acuminata','common_name' => 'Raspberry Jam Wattle','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '50','genus_name' => 'Acer','species_name' => 'mandshuricum','common_name' => 'Acer mandshuricum','growth_rate' => '','height_at_maturity' => '90'),
            array('id' => '51','genus_name' => 'Acacia','species_name' => 'modesta','common_name' => 'Phulai','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '52','genus_name' => 'Acacia','species_name' => 'adunca','common_name' => 'Wallangara Wattle','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '53','genus_name' => 'Acacia','species_name' => 'albida','common_name' => 'White acacia','growth_rate' => 'Fast','height_at_maturity' => '87'),
            array('id' => '54','genus_name' => 'Acacia','species_name' => 'amoena','common_name' => 'Boomerang Wattle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '55','genus_name' => 'Acalypha','species_name' => 'amentacea','common_name' => 'Catch me if you can','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '56','genus_name' => 'Acacia','species_name' => 'aneura','common_name' => 'Mulga','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '57','genus_name' => 'Acacia','species_name' => 'anceps','common_name' => 'Two-edged Wattle','growth_rate' => 'Slow','height_at_maturity' => '3'),
            array('id' => '58','genus_name' => 'Acacia','species_name' => 'anfractuosa','common_name' => 'Acacia anfractuosa','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '59','genus_name' => 'Acacia','species_name' => 'angustissima','common_name' => 'Prairie acacia','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '60','genus_name' => 'Acacia','species_name' => 'anegadensis','common_name' => 'Blackbrush wattle','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '61','genus_name' => 'Acnistus','species_name' => 'arborescens','common_name' => 'Hollowheart','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '62','genus_name' => 'Acacia','species_name' => 'argyrophylla','common_name' => 'Silver Mulga','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '64','genus_name' => 'Acacia','species_name' => 'assimilis','common_name' => 'Wodjil','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '66','genus_name' => 'Acacia','species_name' => 'auriculaeformis','common_name' => 'Earleaf acacia','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '67','genus_name' => 'Acacia','species_name' => 'aulacocarpa','common_name' => 'Golden-flowered Salwood','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '68','genus_name' => 'Acacia','species_name' => 'auriculiformis','common_name' => 'Northern Black Wattle','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '69','genus_name' => 'Acacia','species_name' => 'axillaris','common_name' => 'Midlands Wattle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '70','genus_name' => 'Acer','species_name' => 'barbatum','common_name' => 'Florida maple','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '71','genus_name' => 'Acacia','species_name' => 'bakeri','common_name' => 'Baker\'s Wattle','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '72','genus_name' => 'Acacia','species_name' => 'baileyana','common_name' => 'Bailey acacia','growth_rate' => 'Fast','height_at_maturity' => '18'),
            array('id' => '73','genus_name' => 'Acacia','species_name' => 'bancroftiorum','common_name' => 'Bancroft\'s Wattle','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '74','genus_name' => 'Acacia','species_name' => 'berlandieri','common_name' => 'Guajillo','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '75','genus_name' => 'Acacia','species_name' => 'beckleri','common_name' => 'Barrier Range Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '77','genus_name' => 'Acacia','species_name' => 'binervia','common_name' => 'Coast Mayll','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '78','genus_name' => 'Acacia','species_name' => 'binervata','common_name' => 'Two-veined Hickory','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '79','genus_name' => 'Acalypha','species_name' => 'bisetosa','common_name' => 'Streambank copperleaf','growth_rate' => '','height_at_maturity' => '2'),
            array('id' => '80','genus_name' => 'Acacia','species_name' => 'blakelyi','common_name' => 'Blakelyi\'s Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '81','genus_name' => 'Acacia','species_name' => 'boormanii','common_name' => 'Snowy River Wattle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '82','genus_name' => 'Acacia','species_name' => 'brachybotrya','common_name' => 'Grey Mulga','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '83','genus_name' => 'Acacia','species_name' => 'brevispica','common_name' => 'Wait-a-bit Thorn','growth_rate' => 'Slow','height_at_maturity' => '24'),
            array('id' => '84','genus_name' => 'Acer','species_name' => 'buergerianum','common_name' => 'Trident maple','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '85','genus_name' => 'Acacia','species_name' => 'buxifolia','common_name' => 'Box-leaf Wattle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '86','genus_name' => 'Acer','species_name' => 'campestre','common_name' => 'Hedge maple','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '87','genus_name' => 'Acacia','species_name' => 'cardiophylla','common_name' => 'Wyalong wattle','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '88','genus_name' => 'Acacia','species_name' => 'caven','common_name' => 'Roman cassie','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '89','genus_name' => 'Acer','species_name' => 'cappadocicum','common_name' => 'Cappadocian Maple','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '90','genus_name' => 'Acer','species_name' => 'carpinifolium','common_name' => 'Hornbeam Maple','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '91','genus_name' => 'Acacia','species_name' => 'caroleae','common_name' => 'Narrow-leaf Currawang','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '92','genus_name' => 'Acacia','species_name' => 'calamifolia','common_name' => 'Wallowa','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '93','genus_name' => 'Acacia','species_name' => 'cambagei','common_name' => 'Gidgee','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '94','genus_name' => 'Acer','species_name' => 'capillipes','common_name' => 'Red snakebark maple','growth_rate' => 'Moderate','height_at_maturity' => '49'),
            array('id' => '95','genus_name' => 'Acer','species_name' => 'campestre \'Queen Elizabeth\'','common_name' => 'Queen eliz hedge maple','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '96','genus_name' => 'Acacia','species_name' => 'celastrifolia','common_name' => 'Glowing Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '97','genus_name' => 'Acacia','species_name' => 'choriophylla','common_name' => 'Cinnecord','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '98','genus_name' => 'Acacia','species_name' => 'chrysella','common_name' => 'Acacia chrysella','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '99','genus_name' => 'Actinidia','species_name' => 'chinensis','common_name' => 'Actinidia chinensis','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '100','genus_name' => 'Acer','species_name' => 'circinatum','common_name' => 'Vine maple','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '101','genus_name' => 'Acer','species_name' => 'cissifolium','common_name' => 'Vine-leaved Maple','growth_rate' => 'Moderate','height_at_maturity' => '9'),
            array('id' => '102','genus_name' => 'Acacia','species_name' => 'confusa','common_name' => 'Small philippine acacia','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '103','genus_name' => 'Acacia','species_name' => 'cochlearis','common_name' => 'Rigid Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '105','genus_name' => 'Acacia','species_name' => 'constricta','common_name' => 'Whitethorn acacia','growth_rate' => 'Slow','height_at_maturity' => '9'),
            array('id' => '106','genus_name' => 'Acacia','species_name' => 'colletioides','common_name' => 'Wait-a-while','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '107','genus_name' => 'Acacia','species_name' => 'complanata','common_name' => 'Long Pod Wattle','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '108','genus_name' => 'Acacia','species_name' => 'cornigera','common_name' => 'Bullhorn wattle','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '109','genus_name' => 'Acacia','species_name' => 'concurrens','common_name' => 'Curracabah','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '110','genus_name' => 'Acacia','species_name' => 'conferta','common_name' => 'Crowded-leaf Wattle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '111','genus_name' => 'Acacia','species_name' => 'coriacea','common_name' => 'Wirewood','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '112','genus_name' => 'Acacia','species_name' => 'cowleana','common_name' => 'Halls Creek Wattle','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '113','genus_name' => 'Acer','species_name' => 'crataegifolium','common_name' => 'Hawthorn-leaved Maple','growth_rate' => 'Moderate','height_at_maturity' => '9'),
            array('id' => '114','genus_name' => 'Acacia','species_name' => 'crassicarpa','common_name' => 'Thick-podded Salwood','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '115','genus_name' => 'Acacia','species_name' => 'craspedocarpa','common_name' => 'Hop Mulga','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '116','genus_name' => 'Acacia','species_name' => 'cultriformis','common_name' => 'Knife-leaf Wattle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '117','genus_name' => 'Acacia','species_name' => 'curranii','common_name' => 'Curly-bark Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '118','genus_name' => 'Acacia','species_name' => 'curvinervia','common_name' => 'Acacia curvinervia','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '119','genus_name' => 'Acacia','species_name' => 'cyperophylla','common_name' => 'Red Mulga','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '120','genus_name' => 'Acacia','species_name' => 'cyclops','common_name' => 'Cyclops acacia','growth_rate' => 'Moderate','height_at_maturity' => '24'),
            array('id' => '121','genus_name' => 'Acer','species_name' => 'davidii','common_name' => 'Pere David\'s Maple','growth_rate' => 'Moderate','height_at_maturity' => '14'),
            array('id' => '122','genus_name' => 'Acacia','species_name' => 'dawsonii','common_name' => 'Poverty wattle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '123','genus_name' => 'Acer','species_name' => 'davidii ssp. grosseri','common_name' => 'Snakebark maple','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '124','genus_name' => 'Acacia','species_name' => 'decurrens','common_name' => 'Green acacia','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '125','genus_name' => 'Acacia','species_name' => 'deanei','common_name' => 'Deane\'s Wattle','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '126','genus_name' => 'Acacia','species_name' => 'decora','common_name' => 'Showy Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '127','genus_name' => 'Acacia','species_name' => 'dealbata','common_name' => 'Silver wattle','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '128','genus_name' => 'Acacia','species_name' => 'dempsteri','common_name' => 'Acacia dempsteri','growth_rate' => 'Slow','height_at_maturity' => '3'),
            array('id' => '129','genus_name' => 'Acacia','species_name' => 'desmondii','common_name' => 'Des Nelson Wattle','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '130','genus_name' => 'Actinidia','species_name' => 'deliciosa','common_name' => 'Kiwifruit','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '131','genus_name' => 'Acer','species_name' => 'distylum','common_name' => 'Lime-leaved Maple','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '132','genus_name' => 'Acacia','species_name' => 'difformis','common_name' => 'Drooping Wattle','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '133','genus_name' => 'Acacia','species_name' => 'dictyophleba','common_name' => 'Sandhill Wattle','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '134','genus_name' => 'Acacia','species_name' => 'dodonaeifolia','common_name' => 'Hop-leaved Wattle','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '135','genus_name' => 'Acacia','species_name' => 'doratoxylon','common_name' => 'Currawang','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '136','genus_name' => 'Acacia','species_name' => 'dunnii','common_name' => 'Elephant-ear Wattle','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '137','genus_name' => 'Acacia','species_name' => 'elata','common_name' => 'Cedar wattle','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '138','genus_name' => 'Acacia','species_name' => 'elongata','common_name' => 'Swamp Wattle','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '139','genus_name' => 'Acacia','species_name' => 'ensifolia','common_name' => 'Sickle-shaped Acacia','growth_rate' => 'Moderate','height_at_maturity' => '9'),
            array('id' => '140','genus_name' => 'Acacia','species_name' => 'excelsa','common_name' => 'Ironwood','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '141','genus_name' => 'Acacia','species_name' => 'extensa','common_name' => 'Wiry Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '142','genus_name' => 'Acacia','species_name' => 'farnesiana','common_name' => 'Sweet acacia','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '143','genus_name' => 'Acacia','species_name' => 'falcata','common_name' => 'Burra','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '144','genus_name' => 'Acacia','species_name' => 'falciformis','common_name' => 'Large-leaf Hickory Wattle','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '145','genus_name' => 'Acacia','species_name' => 'fimbriata','common_name' => 'Fringed Wattle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '146','genus_name' => 'Acacia','species_name' => 'filifolia','common_name' => 'Acacia filifolia','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '147','genus_name' => 'Acacia','species_name' => 'floribunda','common_name' => 'Gossamer wattle','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '148','genus_name' => 'Acacia','species_name' => 'flavescens','common_name' => 'Red Wattle','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '149','genus_name' => 'Acer','species_name' => 'forrestii','common_name' => 'Forrest\'s Maple','growth_rate' => 'Moderate','height_at_maturity' => '17'),
            array('id' => '150','genus_name' => 'Acer','species_name' => 'x freemanii','common_name' => 'Freeman maple','growth_rate' => 'Fast','height_at_maturity' => '63'),
            array('id' => '151','genus_name' => 'Acacia','species_name' => 'frigescens','common_name' => 'Montane Wattle','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '152','genus_name' => 'Acradenia','species_name' => 'frankliniae','common_name' => 'Whitey Wood','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '153','genus_name' => 'Acer','species_name' => 'x freemanii \'Jeffersred\'','common_name' => 'Autumn blaze','growth_rate' => 'Moderate','height_at_maturity' => '43'),
            array('id' => '154','genus_name' => 'Acer','species_name' => 'ginnala','common_name' => 'Amur maple','growth_rate' => 'Moderate','height_at_maturity' => '58'),
            array('id' => '155','genus_name' => 'Acacia','species_name' => 'gillii','common_name' => 'Gill\'s Wattle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '156','genus_name' => 'Acer','species_name' => 'glabrum','common_name' => 'Rocky mountain maple','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '157','genus_name' => 'Acacia','species_name' => 'gladiiformis','common_name' => 'Sword-leaf Wattle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '158','genus_name' => 'Acer','species_name' => 'griseum','common_name' => 'Paperbark maple','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '159','genus_name' => 'Acacia','species_name' => 'grasbyi','common_name' => 'Minni Ritchie','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '160','genus_name' => 'Acacia','species_name' => 'greggii','common_name' => 'Catclaw acacia','growth_rate' => 'Slow','height_at_maturity' => '23'),
            array('id' => '161','genus_name' => 'Acer','species_name' => 'grandidentatum','common_name' => 'Bigtooth maple','growth_rate' => 'Moderate','height_at_maturity' => '58'),
            array('id' => '162','genus_name' => 'Acacia','species_name' => 'hakeoides','common_name' => 'Hakea-leaved Wattle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '163','genus_name' => 'Acacia','species_name' => 'harpophylla','common_name' => 'Brigalow','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '164','genus_name' => 'Acacia','species_name' => 'havilandiorum','common_name' => 'Haviland\'s Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '165','genus_name' => 'Acacia','species_name' => 'hemignosta','common_name' => 'Club-leaf Wattle','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '166','genus_name' => 'Acacia','species_name' => 'heteroclita','common_name' => 'Acacia heteroclita','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '167','genus_name' => 'Acer','species_name' => 'heldreichii','common_name' => 'Heldreich\'s Maple','growth_rate' => 'Moderate','height_at_maturity' => '19'),
            array('id' => '168','genus_name' => 'Acalypha','species_name' => 'hispida','common_name' => 'Bristly copperleaf','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '169','genus_name' => 'Acacia','species_name' => 'howittii','common_name' => 'Sticky Wattle','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '170','genus_name' => 'Acacia','species_name' => 'holosericea','common_name' => 'Silver-leaf Wattle','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '171','genus_name' => 'Acacia','species_name' => 'humifusa','common_name' => 'Acacia humifusa','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '172','genus_name' => 'Acer','species_name' => 'hyrcanum','common_name' => 'Balkan Maple','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '173','genus_name' => 'Acacia','species_name' => 'implexa','common_name' => 'Lightwood','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '174','genus_name' => 'Acacia','species_name' => 'irrorata','common_name' => 'Green Wattle','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '175','genus_name' => 'Acacia','species_name' => 'iteaphylla','common_name' => 'Flinders range wattle','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '176','genus_name' => 'Acacia','species_name' => 'ixiophylla','common_name' => 'Acacia ixiophylla','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '177','genus_name' => 'Acer','species_name' => 'japonicum','common_name' => 'Fullmoon maple','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '178','genus_name' => 'Acacia','species_name' => 'jennerae','common_name' => 'Coonavittra Wattle','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '179','genus_name' => 'Acacia','species_name' => 'johnsonii','common_name' => 'Gereera Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '180','genus_name' => 'Acacia','species_name' => 'jucunda','common_name' => 'Yetman Wattle','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '181','genus_name' => 'Acacia','species_name' => 'juncifolia','common_name' => 'Rush-leaf Wattle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '182','genus_name' => 'Acacia','species_name' => 'julifera','common_name' => 'Julie\'s Wattle','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '183','genus_name' => 'Acacia','species_name' => 'karoo','common_name' => 'Sweet thorn','growth_rate' => '','height_at_maturity' => '32'),
            array('id' => '184','genus_name' => 'Acacia','species_name' => 'kempeana','common_name' => 'Witchetty Bush','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '185','genus_name' => 'Acacia','species_name' => 'kettlewelliae','common_name' => 'Buffalo Wattle','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '186','genus_name' => 'Acacia','species_name' => 'koa','common_name' => 'Koa','growth_rate' => 'Moderate','height_at_maturity' => '110'),
            array('id' => '187','genus_name' => 'Acacia','species_name' => 'koaia','common_name' => 'Koaoha','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '188','genus_name' => 'Acacia','species_name' => 'latzii','common_name' => 'Latz\'s Wattle','growth_rate' => 'Slow','height_at_maturity' => '7'),
            array('id' => '189','genus_name' => 'Acer','species_name' => 'leucoderme','common_name' => 'Chalk maple','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '190','genus_name' => 'Acacia','species_name' => 'leucoclada','common_name' => 'Northern Silver Wattle','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '191','genus_name' => 'Acacia','species_name' => 'leichhardtii','common_name' => 'Leichhardt\'s Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '192','genus_name' => 'Acacia','species_name' => 'leiocalyx','common_name' => 'Early Flower Black Wattle','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '193','genus_name' => 'Acacia','species_name' => 'leptostachya','common_name' => 'Townsville Wattle','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '195','genus_name' => 'Acacia','species_name' => 'linifolia','common_name' => 'Flax-leaved Wattle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '196','genus_name' => 'Acacia','species_name' => 'ligulata','common_name' => 'Dune Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '197','genus_name' => 'Acacia','species_name' => 'longifolia','common_name' => 'Sydney golden wattle','growth_rate' => 'Fast','height_at_maturity' => '41'),
            array('id' => '198','genus_name' => 'Acacia','species_name' => 'loderi','common_name' => 'Broken Hill Gidgee','growth_rate' => 'Slow','height_at_maturity' => '7'),
            array('id' => '199','genus_name' => 'Acacia','species_name' => 'longiphyllodinea','common_name' => 'Yalgoo','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '200','genus_name' => 'Acacia','species_name' => 'longispicata','common_name' => 'Slender-flowered Wattle','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '201','genus_name' => 'Acacia','species_name' => 'longifolia ssp. longifolia','common_name' => 'Sallow wattle','growth_rate' => 'Moderate','height_at_maturity' => '17'),
            array('id' => '202','genus_name' => 'Acacia','species_name' => 'longifolia ssp. sphorae','common_name' => 'Coastal wattle','growth_rate' => 'Moderate','height_at_maturity' => '17'),
            array('id' => '203','genus_name' => 'Acacia','species_name' => 'lucasii','common_name' => 'Woolly-bear Wattle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '204','genus_name' => 'Acer','species_name' => 'macrophyllum','common_name' => 'Bigleaf maple','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '205','genus_name' => 'Acacia','species_name' => 'maidenii','common_name' => 'Maiden\'s Wattle','growth_rate' => 'Fast','height_at_maturity' => '66'),
            array('id' => '206','genus_name' => 'Acacia','species_name' => 'macracantha','common_name' => 'Porknut','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '207','genus_name' => 'Acacia','species_name' => 'maconochieana','common_name' => 'Mullan Wattle','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '208','genus_name' => 'Acacia','species_name' => 'macradenia','common_name' => 'Zig-zag Wattle','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '209','genus_name' => 'Acacia','species_name' => 'maitlandii','common_name' => 'Maitland\'s Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '210','genus_name' => 'Acacia','species_name' => 'mangium','common_name' => 'brown salwood','growth_rate' => '','height_at_maturity' => '98'),
            array('id' => '211','genus_name' => 'Acacia','species_name' => 'melanoxylon','common_name' => 'Blackwood','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '212','genus_name' => 'Acacia','species_name' => 'meisneri','common_name' => 'Blue Wattle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '213','genus_name' => 'Acacia','species_name' => 'mellifera','common_name' => 'Black thorn acacia','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '214','genus_name' => 'Acrocomia','species_name' => 'media','common_name' => 'Corozo','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '215','genus_name' => 'Acacia','species_name' => 'melleodora','common_name' => 'Waxy Wattle','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '216','genus_name' => 'Acacia','species_name' => 'mearnsii','common_name' => 'Black wattle','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '217','genus_name' => 'Acacia','species_name' => 'millefolia','common_name' => 'Milfoil wattle','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '218','genus_name' => 'Acer','species_name' => 'miyabei','common_name' => 'Miyabe\'s Maple','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '219','genus_name' => 'Acacia','species_name' => 'microbotrya','common_name' => 'Manna Wattle','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '220','genus_name' => 'Acer','species_name' => 'mono','common_name' => 'Painted maple','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '221','genus_name' => 'Acer','species_name' => 'monspessulanum','common_name' => 'Montpelier Maple','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '222','genus_name' => 'Acacia','species_name' => 'montana','common_name' => 'Mallee Wattle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '223','genus_name' => 'Acacia','species_name' => 'monticola','common_name' => 'Scratchy Wattle','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '224','genus_name' => 'Acacia','species_name' => 'muricata','common_name' => 'Spineless wattle','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '225','genus_name' => 'Acacia','species_name' => 'mucronata','common_name' => 'Narrow-leaf Wattle','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '227','genus_name' => 'Acacia','species_name' => 'muelleriana','common_name' => 'Mueller\'s Wattle','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '228','genus_name' => 'Acacia','species_name' => 'murrayana','common_name' => 'Murray\'s Wattle','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '229','genus_name' => 'Acacia','species_name' => 'myrtifolia','common_name' => 'Myrtle Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '230','genus_name' => 'Acer','species_name' => 'negundo','common_name' => 'Boxelder','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '231','genus_name' => 'Acacia','species_name' => 'neriifolia','common_name' => 'Bastard Yarran','growth_rate' => 'Moderate','height_at_maturity' => '9'),
            array('id' => '232','genus_name' => 'Acacia','species_name' => 'neovernicosa','common_name' => 'Viscid acacia','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '233','genus_name' => 'Acer','species_name' => 'nigrum','common_name' => 'Black maple','growth_rate' => 'Moderate','height_at_maturity' => '100'),
            array('id' => '234','genus_name' => 'Acer','species_name' => 'nikoense','common_name' => 'Nikko Maple','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '235','genus_name' => 'Acacia','species_name' => 'nilotica','common_name' => 'Gum arabic tree','growth_rate' => 'Slow','height_at_maturity' => '23'),
            array('id' => '236','genus_name' => 'Acacia','species_name' => 'nigrescens','common_name' => 'Knob thorn','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '237','genus_name' => 'Acacia','species_name' => 'notabilis','common_name' => 'Notable Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '238','genus_name' => 'Acacia','species_name' => 'nyssophylla','common_name' => 'Prickly Wattle','growth_rate' => 'Slow','height_at_maturity' => '3'),
            array('id' => '239','genus_name' => 'Acer','species_name' => 'oblongum','common_name' => 'Evergreen maple','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '240','genus_name' => 'Acokanthera','species_name' => 'oblongifolia','common_name' => 'Dune poison bush','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '241','genus_name' => 'Acacia','species_name' => 'obliquinervia','common_name' => 'Mountain Hickory Wattle','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '242','genus_name' => 'Acacia','species_name' => 'omalophylla','common_name' => 'Yarran','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '243','genus_name' => 'Acer','species_name' => 'opalus','common_name' => 'Italian Maple','growth_rate' => 'Moderate','height_at_maturity' => '19'),
            array('id' => '244','genus_name' => 'Acacia','species_name' => 'oswaldii','common_name' => 'Umbrella Wattle','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '245','genus_name' => 'Acer','species_name' => 'palmatum','common_name' => 'Japanese maple','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '246','genus_name' => 'Acacia','species_name' => 'parvipinnula','common_name' => 'Silver Stemmed Wattle','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '247','genus_name' => 'Acacia','species_name' => 'papyrocarpa','common_name' => 'Western Myall','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '248','genus_name' => 'Acacia','species_name' => 'pataczekii','common_name' => 'Wally\'s Wattle','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '249','genus_name' => 'Acacia','species_name' => 'paradoxa','common_name' => 'Paradox acacia','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '250','genus_name' => 'Acacia','species_name' => 'parramattensis','common_name' => 'South wales wattle','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '251','genus_name' => 'Acer','species_name' => 'palmatum var. dissectum','common_name' => 'Lace-leaf maple','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '252','genus_name' => 'Acer','species_name' => 'pensylvanicum','common_name' => 'Striped maple','growth_rate' => 'Slow','height_at_maturity' => '35'),
            array('id' => '253','genus_name' => 'Acacia','species_name' => 'pendula','common_name' => 'Weeping myall','growth_rate' => '','height_at_maturity' => '39'),
            array('id' => '254','genus_name' => 'Acacia','species_name' => 'pennatula','common_name' => 'Fern-leaf acacia','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '255','genus_name' => 'Acacia','species_name' => 'penninervis','common_name' => 'Mountain Hickory','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '256','genus_name' => 'Acacia','species_name' => 'pentadenia','common_name' => 'Karri Wattle','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '257','genus_name' => 'Acacia','species_name' => 'perangusta','common_name' => 'Eprapah Wattle','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '258','genus_name' => 'Acacia','species_name' => 'peuce','common_name' => 'Waddy','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '259','genus_name' => 'Acacia','species_name' => 'phasmoides','common_name' => 'Phantom Wattle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '260','genus_name' => 'Acacia','species_name' => 'pinetorum','common_name' => 'Pineland wattle','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '261','genus_name' => 'Acer','species_name' => 'platanoides','common_name' => 'Norway maple','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '262','genus_name' => 'Acacia','species_name' => 'platycarpa','common_name' => 'Ghost Wattle','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '263','genus_name' => 'Acer','species_name' => 'platanoides \'Crimson King\'','common_name' => 'Crimson king norway maple','growth_rate' => '','height_at_maturity' => '45'),
            array('id' => '264','genus_name' => 'Acer','species_name' => 'platanoides \'Columnare\'','common_name' => 'Columnar maple','growth_rate' => '','height_at_maturity' => '35'),
            array('id' => '267','genus_name' => 'Acer','species_name' => 'platanoides \'Schwedleri\'','common_name' => 'Schwedleri norway maple','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '268','genus_name' => 'Acacia','species_name' => 'podalyriaefolia','common_name' => 'Queensland Silver Wattle','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '270','genus_name' => 'Acacia','species_name' => 'podalyriifolia','common_name' => 'Pearl wattle','growth_rate' => 'Fast','height_at_maturity' => '16'),
            array('id' => '271','genus_name' => 'Acacia','species_name' => 'polyacantha','common_name' => 'Catechu tree','growth_rate' => 'Fast','height_at_maturity' => '48'),
            array('id' => '273','genus_name' => 'Acacia','species_name' => 'pravissima','common_name' => 'Ovens wattle','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '274','genus_name' => 'Acacia','species_name' => 'prominens','common_name' => 'Golden rain wattle','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '275','genus_name' => 'Acacia','species_name' => 'pruinocarpa','common_name' => 'Black Gidgee','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '276','genus_name' => 'Acer','species_name' => 'pseudoplatanus','common_name' => 'Sycamore maple','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '277','genus_name' => 'Acer','species_name' => 'pseudosieboldianum','common_name' => 'Korean maple','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '279','genus_name' => 'Acacia','species_name' => 'pubescens','common_name' => 'Downy Wattle','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '280','genus_name' => 'Acacia','species_name' => 'pyrifolia','common_name' => 'Kanji Bush','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '281','genus_name' => 'Acacia','species_name' => 'pycnantha','common_name' => 'Golden wattle','growth_rate' => 'Fast','height_at_maturity' => '26'),
            array('id' => '282','genus_name' => 'Acacia','species_name' => 'quadrilateralis','common_name' => 'Acacia quadrilateralis','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '283','genus_name' => 'Acacia','species_name' => 'quornensis','common_name' => 'Quorn Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '284','genus_name' => 'Acacia','species_name' => 'reficiens','common_name' => 'Acacia reficiens','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '285','genus_name' => 'Acacia','species_name' => 'retivenea','common_name' => 'Acacia retivenea','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '286','genus_name' => 'Acacia','species_name' => 'retinodes','common_name' => 'Water wattle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '287','genus_name' => 'Acacia','species_name' => 'retusa','common_name' => 'Catch and keep','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '288','genus_name' => 'Acacia','species_name' => 'redolens','common_name' => 'Bank catclaw','growth_rate' => 'Fast','height_at_maturity' => '5'),
            array('id' => '289','genus_name' => 'Acacia','species_name' => 'rhigiophylla','common_name' => 'Dagger-leaved Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '290','genus_name' => 'Acacia','species_name' => 'rigidula','common_name' => 'Blackbrush acacia','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '291','genus_name' => 'Acacia','species_name' => 'riceana','common_name' => 'Rice\'s Wattle','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '292','genus_name' => 'Acacia','species_name' => 'rigens','common_name' => 'Needle Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '293','genus_name' => 'Acacia','species_name' => 'rivalis','common_name' => 'Creek Wattle','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '294','genus_name' => 'Acacia','species_name' => 'roemeriana','common_name' => 'Roundflower catclaw','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '295','genus_name' => 'Acacia','species_name' => 'rostellifera','common_name' => 'Summer-scented Wattle','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '296','genus_name' => 'Acacia','species_name' => 'roycei','common_name' => 'Acacia roycei','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '297','genus_name' => 'Acer','species_name' => 'rubrum','common_name' => 'Red maple','growth_rate' => 'Fast','height_at_maturity' => '68'),
            array('id' => '298','genus_name' => 'Acacia','species_name' => 'rubida','common_name' => 'Red-stem Wattle','growth_rate' => 'Fast','height_at_maturity' => '16'),
            array('id' => '299','genus_name' => 'Acacia','species_name' => 'ruppii','common_name' => 'Rupp\'s Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '300','genus_name' => 'Acer','species_name' => 'rufinerve','common_name' => 'Grey-budded Snake-bark','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '301','genus_name' => 'Acer','species_name' => 'rubrum \'Armstrong\'','common_name' => 'Armstrong maple','growth_rate' => '','height_at_maturity' => '55'),
            array('id' => '304','genus_name' => 'Acer','species_name' => 'rubrum \'Drummondii\'','common_name' => 'Drummond\'s maple','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '305','genus_name' => 'Acer','species_name' => 'rubrum \'Gerling\'','common_name' => 'Gerling red maple','growth_rate' => '','height_at_maturity' => '32'),
            array('id' => '306','genus_name' => 'Acer','species_name' => 'rubrum \'Morgan\'','common_name' => 'Morgan red maple','growth_rate' => '','height_at_maturity' => '45'),
            array('id' => '307','genus_name' => 'Acer','species_name' => 'rubrum \'October glory\'','common_name' => 'October glory red maple','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '308','genus_name' => 'Acer','species_name' => 'rubrum \'Red Sunset\'','common_name' => 'Red sunset red maple','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '309','genus_name' => 'Acacia','species_name' => 'saligna','common_name' => 'Orange wattle','growth_rate' => 'Fast','height_at_maturity' => '18'),
            array('id' => '310','genus_name' => 'Acer','species_name' => 'saccharinum','common_name' => 'Silver maple','growth_rate' => 'Fast','height_at_maturity' => '90'),
            array('id' => '311','genus_name' => 'Acer','species_name' => 'saccharum','common_name' => 'Sugar maple','growth_rate' => 'Slow','height_at_maturity' => '100'),
            array('id' => '312','genus_name' => 'Acer','species_name' => 'saccharum \'Green Mountain\'','common_name' => 'Green mountain sugar maple','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '313','genus_name' => 'Acacia','species_name' => 'salicina','common_name' => 'Willow acacia','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '314','genus_name' => 'Acacia','species_name' => 'schottii','common_name' => 'Schott\'s wattle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '315','genus_name' => 'Acacia','species_name' => 'sclerosperma','common_name' => 'Limestone Wattle','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '316','genus_name' => 'Acacia','species_name' => 'schaffneri','common_name' => 'Schaffner\'s wattle','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '317','genus_name' => 'Acokanthera','species_name' => 'schimperi','common_name' => 'Arrow-poison tree','growth_rate' => 'Moderate','height_at_maturity' => '17'),
            array('id' => '318','genus_name' => 'Acacia','species_name' => 'semperflorens','common_name' => 'Aromo en flor','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '319','genus_name' => 'Acer','species_name' => 'sempervirens','common_name' => 'Cretan Maple','growth_rate' => 'Moderate','height_at_maturity' => '9'),
            array('id' => '320','genus_name' => 'Acca','species_name' => 'sellowiana','common_name' => 'Feijoa','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '321','genus_name' => 'Acacia','species_name' => 'semirigida','common_name' => 'Stony Ridge Wattle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '322','genus_name' => 'Acacia','species_name' => 'semilunata','common_name' => 'Moon Wattle','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '323','genus_name' => 'Acacia','species_name' => 'seyal','common_name' => 'Red acacia','growth_rate' => 'Fast','height_at_maturity' => '23'),
            array('id' => '324','genus_name' => 'Acacia','species_name' => 'siculiformis','common_name' => 'Dagger Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '325','genus_name' => 'Acacia','species_name' => 'simsii','common_name' => 'Sim\'s Wattle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '326','genus_name' => 'Acer','species_name' => 'spicatum','common_name' => 'Mountain maple','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '327','genus_name' => 'Acacia','species_name' => 'spectabilis','common_name' => 'Mudgee Wattle','growth_rate' => 'Fast','height_at_maturity' => '13'),
            array('id' => '328','genus_name' => 'Achyranthes','species_name' => 'splendens','common_name' => 'Maui chaff flower','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '329','genus_name' => 'Acacia','species_name' => 'sphaerocephala','common_name' => 'Bee wattle','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '330','genus_name' => 'Acacia','species_name' => 'spathulifolia','common_name' => 'Spoon Leaf Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '331','genus_name' => 'Acacia','species_name' => 'sparsiflora','common_name' => 'Currawong','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '332','genus_name' => 'Acacia','species_name' => 'stenophylla','common_name' => 'Shoestring acacia','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '333','genus_name' => 'Acacia','species_name' => 'stricta','common_name' => 'Hop Wattle','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '334','genus_name' => 'Acacia','species_name' => 'suaveolens','common_name' => 'Sweet Wattle','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '335','genus_name' => 'Acacia','species_name' => 'subulata','common_name' => 'Awl Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '336','genus_name' => 'Acer','species_name' => 'tataricum','common_name' => 'Tatar maple','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '337','genus_name' => 'Acer','species_name' => 'tataricum \'Summer Splendor\'','common_name' => 'Summer splendor tartarian maple','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '338','genus_name' => 'Acacia','species_name' => 'terminalis','common_name' => 'Sunshine Wattle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '339','genus_name' => 'Acacia','species_name' => 'tenuissima','common_name' => 'Mulga Wattle','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '340','genus_name' => 'Acacia','species_name' => 'tetragonophylla','common_name' => 'Dead Finish','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '341','genus_name' => 'Acacia','species_name' => 'tortuosa','common_name' => 'Twisted acacia','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '342','genus_name' => 'Acacia','species_name' => 'torulosa','common_name' => 'Deep Gold Wattle','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '343','genus_name' => 'Acacia','species_name' => 'tortilis','common_name' => 'Umbrella thorn','growth_rate' => 'Fast','height_at_maturity' => '41'),
            array('id' => '344','genus_name' => 'Acrocomia','species_name' => 'totai','common_name' => 'Grugru palm','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '345','genus_name' => 'Acer','species_name' => 'truncatum','common_name' => 'Purple blow maple','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '346','genus_name' => 'Acer','species_name' => 'triflorum','common_name' => 'Three-flower maple','growth_rate' => 'Slow','height_at_maturity' => '46'),
            array('id' => '347','genus_name' => 'Acacia','species_name' => 'trinervata','common_name' => 'Three-nerved Wattle','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '348','genus_name' => 'Acacia','species_name' => 'trineura','common_name' => 'Hindmarsh Wattle','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '349','genus_name' => 'Acacia','species_name' => 'triptera','common_name' => 'Spur-wing Wattle','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '350','genus_name' => 'Acacia','species_name' => 'umbellata','common_name' => 'Acacia umbellata','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '351','genus_name' => 'Acacia','species_name' => 'uncifera','common_name' => 'Acacia uncifera','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '352','genus_name' => 'Acacia','species_name' => 'undoolyana','common_name' => 'Undoolya Wattle','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '353','genus_name' => 'Acacia','species_name' => 'urophylla','common_name' => 'Tailed-leaved Acacia','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '354','genus_name' => 'Acacia','species_name' => 'verniciflua','common_name' => 'Varnish wattle','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '355','genus_name' => 'Acer','species_name' => 'velutinum','common_name' => 'Velvet maple','growth_rate' => 'Moderate','height_at_maturity' => '22'),
            array('id' => '356','genus_name' => 'Acacia','species_name' => 'verticillata','common_name' => 'Prickly moses','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '357','genus_name' => 'Acacia','species_name' => 'vestita','common_name' => 'Hairy Wattle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '358','genus_name' => 'Acacia','species_name' => 'venulosa','common_name' => 'Veiny Wattle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '360','genus_name' => 'Acacia','species_name' => 'visco','common_name' => 'Acacia visco','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '361','genus_name' => 'Acacia','species_name' => 'victoriae','common_name' => 'Elegant Wattle','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '362','genus_name' => 'Acrocomia','species_name' => 'vinifera','common_name' => 'Coyol palm','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '363','genus_name' => 'Acacia','species_name' => 'vogeliana','common_name' => 'Macata bourse bastard','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '364','genus_name' => 'Acacia','species_name' => 'wardellii','common_name' => 'Wardell\'s Wattle','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '365','genus_name' => 'Acacia','species_name' => 'wattsiana','common_name' => 'Dog Wattle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '366','genus_name' => 'Acalypha','species_name' => 'wilkesiana','common_name' => 'Copperleaf','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '367','genus_name' => 'Acacia','species_name' => 'wiseana','common_name' => 'Acacia wiseana','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '368','genus_name' => 'Acoelorrhaphe','species_name' => 'wrightii','common_name' => 'Paurotis palm','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '369','genus_name' => 'Acacia','species_name' => 'greggii var. wrightii','common_name' => 'Wright acacia','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '370','genus_name' => 'Acacia','species_name' => 'xanthina','common_name' => 'White Stemmed Wattle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '371','genus_name' => 'Adolphia','species_name' => 'californica','common_name' => 'California prickbush','growth_rate' => '','height_at_maturity' => '4'),
            array('id' => '372','genus_name' => 'Adansonia','species_name' => 'digitata','common_name' => 'Baobab','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '373','genus_name' => 'Adenostoma','species_name' => 'fasciculatum','common_name' => 'Chamise','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '374','genus_name' => 'Adenaria','species_name' => 'floribunda','common_name' => 'Adenaria floribunda','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '375','genus_name' => 'Adansonia','species_name' => 'gregorii','common_name' => 'Boab','growth_rate' => 'Fast','height_at_maturity' => '23'),
            array('id' => '376','genus_name' => 'Adolphia','species_name' => 'infesta','common_name' => 'Junco','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '377','genus_name' => 'Adenocarpus','species_name' => 'lainzii','common_name' => 'Adenocarpus lainzii','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '378','genus_name' => 'Adonidia','species_name' => 'merrilli','common_name' => 'Manilla palm','growth_rate' => 'Fast','height_at_maturity' => '16'),
            array('id' => '380','genus_name' => 'Adenanthera','species_name' => 'pavonina','common_name' => 'Red beadtree','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '381','genus_name' => 'Adelia','species_name' => 'ricinella','common_name' => 'Wild lime','growth_rate' => '','height_at_maturity' => '33'),
            array('id' => '382','genus_name' => 'Adenostoma','species_name' => 'sparsifolium','common_name' => 'Redshank','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '383','genus_name' => 'Adelia','species_name' => 'vaseyi','common_name' => 'Vasey\'s wild lime','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '384','genus_name' => 'Aesculus','species_name' => 'x bushii','common_name' => 'Bush\'s chesnut','growth_rate' => 'Moderate','height_at_maturity' => '69'),
            array('id' => '385','genus_name' => 'Aesculus','species_name' => 'x carnea','common_name' => 'Red horsechestnut','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '386','genus_name' => 'Aesculus','species_name' => 'californica','common_name' => 'California buckeye','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '387','genus_name' => 'Aesculus','species_name' => 'x carnea \'Briottii\'','common_name' => 'Briottii horsechestnut','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '389','genus_name' => 'Aesculus','species_name' => 'chinensis','common_name' => 'Aesculus chinensis','growth_rate' => 'Moderate','height_at_maturity' => '69'),
            array('id' => '391','genus_name' => 'Aesculus','species_name' => 'flava','common_name' => 'Yellow buckeye','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '392','genus_name' => 'Aesculus','species_name' => 'glabra','common_name' => 'Ohio buckeye','growth_rate' => 'Fast','height_at_maturity' => '68'),
            array('id' => '393','genus_name' => 'Aeonium','species_name' => 'haworthii','common_name' => 'Haworth\'s aeonium','growth_rate' => '','height_at_maturity' => '2'),
            array('id' => '394','genus_name' => 'Aesculus','species_name' => 'hippocastanum','common_name' => 'Horse chestnut','growth_rate' => 'Moderate','height_at_maturity' => '63'),
            array('id' => '395','genus_name' => 'Aesculus','species_name' => 'x hybrida','common_name' => 'Hybrid chesnut','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '396','genus_name' => 'Aesculus','species_name' => 'indica','common_name' => 'Indian Horse Chestnut','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '398','genus_name' => 'Aegiphila','species_name' => 'martinicensis','common_name' => 'Caribbean spiritweed','growth_rate' => 'Fast','height_at_maturity' => '18'),
            array('id' => '399','genus_name' => 'Aesculus','species_name' => 'x marylandica','common_name' => 'Maryland chesnut','growth_rate' => 'Moderate','height_at_maturity' => '69'),
            array('id' => '400','genus_name' => 'Aegle','species_name' => 'marmelos','common_name' => 'bael fruit','growth_rate' => 'Slow','height_at_maturity' => '45'),
            array('id' => '402','genus_name' => 'Aesculus','species_name' => 'x mutabilis','common_name' => 'Chesnut','growth_rate' => 'Moderate','height_at_maturity' => '69'),
            array('id' => '403','genus_name' => 'Aesculus','species_name' => 'x neglecta','common_name' => 'Dwarf buckeye','growth_rate' => 'Moderate','height_at_maturity' => '69'),
            array('id' => '404','genus_name' => 'Aesculus','species_name' => 'pavia','common_name' => 'Red buckeye','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '405','genus_name' => 'Aesculus','species_name' => 'parviflora','common_name' => 'Bottlebrush buckeye','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '407','genus_name' => 'Aesculus','species_name' => 'sylvatica','common_name' => 'Painted buckeye','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '408','genus_name' => 'Aesculus','species_name' => 'turbinata','common_name' => 'Japanese Horse Chestnut','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '409','genus_name' => 'Aesculus','species_name' => 'x woerlitzensis','common_name' => 'Aesculus x woerlitzensis','growth_rate' => 'Moderate','height_at_maturity' => '69'),
            array('id' => '410','genus_name' => 'Afrocarpus','species_name' => 'falcatus','common_name' => 'Outeniqua yellowwood','growth_rate' => 'Moderate','height_at_maturity' => '82'),
            array('id' => '412','genus_name' => 'Agave','species_name' => 'attenuata','common_name' => 'Agave attenuata','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '413','genus_name' => 'Agathis','species_name' => 'australis','common_name' => 'Kauri','growth_rate' => 'Moderate','height_at_maturity' => '165'),
            array('id' => '414','genus_name' => 'Agrostis','species_name' => 'curtisii','common_name' => 'Bristle bent','growth_rate' => '','height_at_maturity' => '2'),
            array('id' => '415','genus_name' => 'Agonis','species_name' => 'flexuosa','common_name' => 'Peppermint tree','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '416','genus_name' => 'Ageratina','species_name' => 'havanensis','common_name' => 'Havana snakeroot','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '417','genus_name' => 'Agathis','species_name' => 'lanceolata','common_name' => 'Koghis kauri','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '418','genus_name' => 'Agathis','species_name' => 'macrophylla','common_name' => 'Pacific kauri','growth_rate' => 'Fast','height_at_maturity' => '90'),
            array('id' => '419','genus_name' => 'Aglaia','species_name' => 'mariannensis','common_name' => 'Titimel','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '420','genus_name' => 'Agarista','species_name' => 'populifolia','common_name' => 'Florida hobblebush','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '421','genus_name' => 'Ageratina','species_name' => 'resiniflua','common_name' => 'Resinous snakeroot','growth_rate' => '','height_at_maturity' => '16'),
            array('id' => '422','genus_name' => 'Agathis','species_name' => 'robusta','common_name' => 'Queensland kauri','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '423','genus_name' => 'Ailanthus','species_name' => 'altissima','common_name' => 'Tree of heaven','growth_rate' => 'Fast','height_at_maturity' => '55'),
            array('id' => '424','genus_name' => 'Aidia','species_name' => 'canthioides','common_name' => 'Aidia canthioides','growth_rate' => 'Moderate','height_at_maturity' => ''),
            array('id' => '425','genus_name' => 'Aidia','species_name' => 'cochinchinensis','common_name' => 'Archer Cherry','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '427','genus_name' => 'Aiphanes','species_name' => 'horrida','common_name' => 'Aiphanes horrida','growth_rate' => 'Moderate','height_at_maturity' => '59'),
            array('id' => '430','genus_name' => 'Alnus','species_name' => 'acuminata','common_name' => 'Mexican Alder','growth_rate' => 'Moderate','height_at_maturity' => '46'),
            array('id' => '431','genus_name' => 'Alstonia','species_name' => 'actinophylla','common_name' => 'Northern Milkwood','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '432','genus_name' => 'Albizia','species_name' => 'adinocephala','common_name' => 'Cream albizia','growth_rate' => 'Fast','height_at_maturity' => '44'),
            array('id' => '433','genus_name' => 'Alvaradoa','species_name' => 'amorphoides','common_name' => 'Mexican alvaradoa','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '435','genus_name' => 'Aloe','species_name' => 'arborescens','common_name' => 'Tree aloe','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '436','genus_name' => 'Allamanda','species_name' => 'blanchetii','common_name' => 'Purple allamanda','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '437','genus_name' => 'Alsophila','species_name' => 'bryophila','common_name' => 'Helecho gigante de sierra','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '438','genus_name' => 'Albizia','species_name' => 'carbonaria','common_name' => 'Naked albizia','growth_rate' => 'Fast','height_at_maturity' => '44'),
            array('id' => '439','genus_name' => 'Albizia','species_name' => 'chinensis','common_name' => 'Chinese albizia','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '441','genus_name' => 'Alnus','species_name' => 'cordata','common_name' => 'Italian alder','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '443','genus_name' => 'Allocasuarina','species_name' => 'distyla','common_name' => 'Shrubby She-oak','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '444','genus_name' => 'Allophylus','species_name' => 'edulis','common_name' => 'Chal-chal','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '445','genus_name' => 'Allocasuarina','species_name' => 'emuina','common_name' => 'Emu Mountain She-oak','growth_rate' => 'Moderate','height_at_maturity' => '2'),
            array('id' => '446','genus_name' => 'Alectryon','species_name' => 'excelsus','common_name' => 'Titoki','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '447','genus_name' => 'Alphitonia','species_name' => 'excelsa','common_name' => 'Red Ash','growth_rate' => 'Moderate','height_at_maturity' => '69'),
            array('id' => '448','genus_name' => 'Albizia','species_name' => 'moluccana','common_name' => 'Moluca albizia','growth_rate' => 'Fast','height_at_maturity' => '120'),
            array('id' => '449','genus_name' => 'Alnus','species_name' => 'x fallacina','common_name' => 'Alder','growth_rate' => 'Moderate','height_at_maturity' => '63'),
            array('id' => '450','genus_name' => 'Albizia','species_name' => 'ferruginea','common_name' => 'Albizia','growth_rate' => 'Fast','height_at_maturity' => '44'),
            array('id' => '451','genus_name' => 'Alnus','species_name' => 'firma','common_name' => 'Alnus firma','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '452','genus_name' => 'Alloxylon','species_name' => 'flammeum','common_name' => 'Red Silky Oak','growth_rate' => 'Moderate','height_at_maturity' => '109'),
            array('id' => '455','genus_name' => 'Aleurites','species_name' => 'fordii','common_name' => 'Tung oil tree','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '456','genus_name' => 'Allocasuarina','species_name' => 'fraseriana','common_name' => 'She-oak','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '457','genus_name' => 'Alnus','species_name' => 'glutinosa','common_name' => 'European alder','growth_rate' => 'Fast','height_at_maturity' => '45'),
            array('id' => '459','genus_name' => 'Alchornea','species_name' => 'grandiflora','common_name' => 'Alchornea grandiflora','growth_rate' => 'Fast','height_at_maturity' => '59'),
            array('id' => '460','genus_name' => 'Aloysia','species_name' => 'gratissima','common_name' => 'Whitebrush','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '461','genus_name' => 'Alnus','species_name' => 'hirsuta','common_name' => 'Manchurian alder','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '462','genus_name' => 'Alnus','species_name' => 'incana','common_name' => 'Grey alder','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '463','genus_name' => 'Alnus','species_name' => 'jorullensis','common_name' => 'Evergreen alder','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '465','genus_name' => 'Albizia','species_name' => 'julibrissin','common_name' => 'Persian silk tree','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '466','genus_name' => 'Alchornea','species_name' => 'latifolia','common_name' => 'Achiotillo','growth_rate' => 'Slow','height_at_maturity' => '52'),
            array('id' => '467','genus_name' => 'Albizia','species_name' => 'lebbeck','common_name' => 'Acacia amarilla','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '469','genus_name' => 'Albizia','species_name' => 'lebbekoides','common_name' => 'Indian albizia','growth_rate' => 'Fast','height_at_maturity' => '44'),
            array('id' => '470','genus_name' => 'Allocasuarina','species_name' => 'littoralis','common_name' => 'Black she-oak','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '471','genus_name' => 'Albizia','species_name' => 'lophantha','common_name' => 'Cape Wattle','growth_rate' => 'Fast','height_at_maturity' => '44'),
            array('id' => '472','genus_name' => 'Allocasuarina','species_name' => 'luehmannii','common_name' => 'Bulloak','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '473','genus_name' => 'Alnus','species_name' => 'maritima','common_name' => 'Seaside alder','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '474','genus_name' => 'Alberta','species_name' => 'magna','common_name' => 'Natal flame bush','growth_rate' => 'Slow','height_at_maturity' => '13'),
            array('id' => '475','genus_name' => 'Alhagi','species_name' => 'maurorum','common_name' => 'Camelthorn','growth_rate' => '','height_at_maturity' => '4'),
            array('id' => '476','genus_name' => 'Alstonia','species_name' => 'macrophylla','common_name' => 'Deviltree','growth_rate' => '','height_at_maturity' => '90'),
            array('id' => '477','genus_name' => 'Alectryon','species_name' => 'macrococcum','common_name' => 'Hawai\'i alectryon','growth_rate' => '','height_at_maturity' => '22'),
            array('id' => '478','genus_name' => 'Aloysia','species_name' => 'macrostachya','common_name' => 'Rio grande beebrush','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '479','genus_name' => 'Aleurites','species_name' => 'moluccanus','common_name' => 'Indian walnut','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '480','genus_name' => 'Allocasuarina','species_name' => 'monilifera','common_name' => 'Necklace She-oak','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '481','genus_name' => 'Aleurites','species_name' => 'montanus','common_name' => 'Mu oil tree','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '482','genus_name' => 'Allocasuarina','species_name' => 'muelleriana','common_name' => 'Slaty She-oak','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '483','genus_name' => 'Allocasuarina','species_name' => 'nana','common_name' => 'Stunted She-oak','growth_rate' => 'Moderate','height_at_maturity' => '2'),
            array('id' => '484','genus_name' => 'Alnus','species_name' => 'nepalensis','common_name' => 'Nepal alder','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '485','genus_name' => 'Alnus','species_name' => 'oblongifolia','common_name' => 'Arizona alder','growth_rate' => 'Moderate','height_at_maturity' => '63'),
            array('id' => '486','genus_name' => 'Albizia','species_name' => 'occidentalis','common_name' => 'Albizia occidentalis','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '487','genus_name' => 'Allocasuarina','species_name' => 'paludosa','common_name' => 'Scrub Sheoak','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '488','genus_name' => 'Alphitonia','species_name' => 'petriei','common_name' => 'Pink Ash','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '490','genus_name' => 'Alloxylon','species_name' => 'pinnatum','common_name' => 'Doringo Warratah','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '493','genus_name' => 'Alphitonia','species_name' => 'ponderosa','common_name' => 'Hawai\'i kauilatree','growth_rate' => '','height_at_maturity' => '80'),
            array('id' => '495','genus_name' => 'Albizia','species_name' => 'procera','common_name' => 'Tall Albizia','growth_rate' => 'Fast','height_at_maturity' => '80'),
            array('id' => '496','genus_name' => 'Allocasuarina','species_name' => 'pusilla','common_name' => 'Dwarf She-oak','growth_rate' => 'Moderate','height_at_maturity' => '2'),
            array('id' => '497','genus_name' => 'Allophylus','species_name' => 'racemosus','common_name' => 'Palo de caja','growth_rate' => '','height_at_maturity' => '32'),
            array('id' => '498','genus_name' => 'Alnus','species_name' => 'rhombifolia','common_name' => 'White alder','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '499','genus_name' => 'Alnus','species_name' => 'incana ssp. rugosa','common_name' => 'Speckled alder','growth_rate' => 'Fast','height_at_maturity' => '16'),
            array('id' => '500','genus_name' => 'Alnus','species_name' => 'rubra','common_name' => 'Red alder','growth_rate' => 'Fast','height_at_maturity' => '90'),
            array('id' => '501','genus_name' => 'Albizia','species_name' => 'saman','common_name' => 'Albizia saman','growth_rate' => 'Slow','height_at_maturity' => '66'),
            array('id' => '502','genus_name' => 'Albizia','species_name' => 'saponaria','common_name' => 'Whiteflower albizia','growth_rate' => 'Fast','height_at_maturity' => '44'),
            array('id' => '503','genus_name' => 'Alstonia','species_name' => 'scholaris','common_name' => 'White Cheesewood','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '504','genus_name' => 'Alnus','species_name' => 'serrulata','common_name' => 'Hazel alder','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '506','genus_name' => 'Alnus','species_name' => 'viridis ssp. sinuata','common_name' => 'Sitka alder','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '507','genus_name' => 'Allocasuarina','species_name' => 'striata','common_name' => 'Small Bull-oak','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '508','genus_name' => 'Alectryon','species_name' => 'subcinereus','common_name' => 'Bird\'s Eye','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '509','genus_name' => 'Alnus','species_name' => 'tenuifolia','common_name' => 'Mountain alder','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '510','genus_name' => 'Allosyncarpia','species_name' => 'ternata','common_name' => 'Allosyncarpia','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '511','genus_name' => 'Allophylus','species_name' => 'ternatus','common_name' => 'chebeludes','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '513','genus_name' => 'Allocasuarina','species_name' => 'torulosa','common_name' => 'Rose she-oak','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '514','genus_name' => 'Alectryon','species_name' => 'tomentosus','common_name' => 'Hairy Bird\'s Eye','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '516','genus_name' => 'Aleurites','species_name' => 'trisperma','common_name' => 'Philippine tung','growth_rate' => '','height_at_maturity' => '75'),
            array('id' => '517','genus_name' => 'Aloysia','species_name' => 'triphylla','common_name' => 'Lemon beebrush','growth_rate' => '','height_at_maturity' => '5'),
            array('id' => '518','genus_name' => 'Allocasuarina','species_name' => 'verticillata','common_name' => 'Drooping she-oak','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '519','genus_name' => 'Alnus','species_name' => 'viridis','common_name' => 'Green alder','growth_rate' => 'Fast','height_at_maturity' => '35'),
            array('id' => '521','genus_name' => 'Amelanchier','species_name' => 'arborea','common_name' => 'Downy serviceberry','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '522','genus_name' => 'Ampelopsis','species_name' => 'arborea','common_name' => 'Peppervine','growth_rate' => 'Fast','height_at_maturity' => '35'),
            array('id' => '523','genus_name' => 'Amelanchier','species_name' => 'asiatica','common_name' => 'Korean Juneberry','growth_rate' => 'Fast','height_at_maturity' => '8'),
            array('id' => '524','genus_name' => 'Amelanchier','species_name' => 'bartramiana','common_name' => 'Oblongfruit serviceberry','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '525','genus_name' => 'Amyris','species_name' => 'balsamifera','common_name' => 'Balsam torchwood','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '526','genus_name' => 'Amelanchier','species_name' => 'canadensis','common_name' => 'Eastern service berry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '527','genus_name' => 'Amorpha','species_name' => 'canescens','common_name' => 'Lead plant','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '528','genus_name' => 'Amorpha','species_name' => 'californica','common_name' => 'California false indigo','growth_rate' => 'Moderate','height_at_maturity' => '9'),
            array('id' => '531','genus_name' => 'Amyris','species_name' => 'elemifera','common_name' => 'Torchwood','growth_rate' => 'Moderate','height_at_maturity' => '16'),
            array('id' => '532','genus_name' => 'Amelanchier','species_name' => 'alnifolia','common_name' => 'Western serviceberry','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '533','genus_name' => 'Amorpha','species_name' => 'fruticosa','common_name' => 'Desert false indigo','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '534','genus_name' => 'Amphipappus','species_name' => 'fremontii','common_name' => 'Fremont\'s chaffbush','growth_rate' => '','height_at_maturity' => '2'),
            array('id' => '535','genus_name' => 'Amorpha','species_name' => 'georgiana','common_name' => 'Georgia false indigo','growth_rate' => '','height_at_maturity' => '3'),
            array('id' => '537','genus_name' => 'Amelanchier','species_name' => 'x grandiflora \'Autumn\'','common_name' => 'Apple serviceberry','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '539','genus_name' => 'Amorpha','species_name' => 'herbacea','common_name' => 'Clusterspike false indigo','growth_rate' => '','height_at_maturity' => '3'),
            array('id' => '540','genus_name' => 'Amelanchier','species_name' => 'humilis','common_name' => 'Low serviceberry','growth_rate' => 'Moderate','height_at_maturity' => '16'),
            array('id' => '542','genus_name' => 'Amelanchier','species_name' => 'interior','common_name' => 'Pacific serviceberry','growth_rate' => 'Moderate','height_at_maturity' => '36'),
            array('id' => '543','genus_name' => 'Amelanchier','species_name' => 'x intermedia','common_name' => 'Intermediate serviceberry','growth_rate' => 'Moderate','height_at_maturity' => '21'),
            array('id' => '544','genus_name' => 'Amelasorbus','species_name' => 'jackii','common_name' => 'Jack\'s amelasorbus','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '545','genus_name' => 'Amelanchier','species_name' => 'laevis','common_name' => 'Smooth service berry','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '546','genus_name' => 'Amphitecna','species_name' => 'latifolia','common_name' => 'Black calabash','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '547','genus_name' => 'Amorpha','species_name' => 'laevigata','common_name' => 'Smooth false indigo','growth_rate' => '','height_at_maturity' => '8'),
            array('id' => '548','genus_name' => 'Amyris','species_name' => 'madrensis','common_name' => 'Mountain torchwood','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '549','genus_name' => 'Amelanchier','species_name' => 'nantucketense','common_name' => 'Nantucket serviceberry','growth_rate' => 'Moderate','height_at_maturity' => '6')
        );
          Tree::insert($trees);

          $seeder = new TreeSpeciesSeeder1;
          $seeder->run();
    }
}