<?php

namespace Database\Seeders\TreeSpecies;

use App\Models\Tree\Tree;
use Illuminate\Database\Seeder;

class TreeSpeciesSeeder4 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $trees = array(
            array('id' => '2677','genus_name' => 'Eugenia','species_name' => 'cordata','common_name' => 'Lathberry','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2678','genus_name' => 'Eucalyptus','species_name' => 'consideniana','common_name' => 'Yertchuk','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '2679','genus_name' => 'Eucalyptus','species_name' => 'cordata','common_name' => 'Herat-leaved silver gum','growth_rate' => 'Slow','height_at_maturity' => '66'),
            array('id' => '2680','genus_name' => 'Eucalyptus','species_name' => 'conglobata','common_name' => 'Port Lincoln Mallee','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '2681','genus_name' => 'Eucalyptus','species_name' => 'coolabah','common_name' => 'Coolabah','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '2682','genus_name' => 'Eucalyptus','species_name' => 'crebra','common_name' => 'Narrowleaf red ironbark','growth_rate' => 'Fast','height_at_maturity' => '75'),
            array('id' => '2683','genus_name' => 'Eucalyptus','species_name' => 'crenulata','common_name' => 'Buxton gum','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '2684','genus_name' => 'Eucalyptus','species_name' => 'crucis','common_name' => 'South Cross Silver Mallee','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '2685','genus_name' => 'Eucalyptus','species_name' => 'cunninghamii','common_name' => 'Cliff mallee ash','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '2686','genus_name' => 'Eucalyptus','species_name' => 'curtisii','common_name' => 'Plunkett mallee','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '2687','genus_name' => 'Euphorbia','species_name' => 'curtisii','common_name' => 'Curtis\' spurge','growth_rate' => 'Slow','height_at_maturity' => '38'),
            array('id' => '2688','genus_name' => 'Eucalyptus','species_name' => 'cyanophylla','common_name' => 'Ghost Mallee','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '2689','genus_name' => 'Eucalyptus','species_name' => 'cypellocarpa','common_name' => 'Mountain Grey Gum','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '2690','genus_name' => 'Eucalyptus','species_name' => 'delegatensis','common_name' => 'Alpine ash','growth_rate' => 'Moderate','height_at_maturity' => '165'),
            array('id' => '2691','genus_name' => 'Eucalyptus','species_name' => 'dendromorpha','common_name' => 'Budawang Ash','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '2692','genus_name' => 'Eucalyptus','species_name' => 'denticulata','common_name' => 'Shining gum','growth_rate' => 'Moderate','height_at_maturity' => '116'),
            array('id' => '2693','genus_name' => 'Eucalyptus','species_name' => 'deuaensis','common_name' => 'Mongamulla mallee','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '2694','genus_name' => 'Eucalyptus','species_name' => 'dalrympleana','common_name' => 'Mountain white gum','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '2695','genus_name' => 'Eucalyptus','species_name' => 'dawsonii','common_name' => 'Slaty box','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '2696','genus_name' => 'Eucalyptus','species_name' => 'deglupta','common_name' => 'Mindanao gum','growth_rate' => 'Fast','height_at_maturity' => '88'),
            array('id' => '2697','genus_name' => 'Eucalyptus','species_name' => 'dealbata','common_name' => 'Tumble-down red gum','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '2698','genus_name' => 'Euphorbia','species_name' => 'dendroides','common_name' => 'Tree spurge','growth_rate' => 'Slow','height_at_maturity' => '38'),
            array('id' => '2699','genus_name' => 'Eucalyptus','species_name' => 'deanei','common_name' => 'Roundleaf gum','growth_rate' => 'Fast','height_at_maturity' => '180'),
            array('id' => '2700','genus_name' => 'Eucalyptus','species_name' => 'decorticans','common_name' => 'Gum-topped ironbark','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '2701','genus_name' => 'Eucalyptus','species_name' => 'decipiens','common_name' => 'Red Heart','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '2702','genus_name' => 'Eucalyptus','species_name' => 'desmondensis','common_name' => 'Desmond mallee','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2703','genus_name' => 'Eucalyptus','species_name' => 'diversicolor','common_name' => 'Karri eucalyptus','growth_rate' => 'Fast','height_at_maturity' => '75'),
            array('id' => '2704','genus_name' => 'Eucalyptus','species_name' => 'dives','common_name' => 'Broad-leaved peppermint','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '2705','genus_name' => 'Eucalyptus','species_name' => 'dielsii','common_name' => 'Cap-fruited Mallee','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '2706','genus_name' => 'Eucalyptus','species_name' => 'diversifolia','common_name' => 'Soap Mallee','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '2707','genus_name' => 'Eugenia','species_name' => 'domingensis','common_name' => 'Serrette guave','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2708','genus_name' => 'Eucalyptus','species_name' => 'dolichocarpa','common_name' => 'Eucalyptus dolichocarpa','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '2709','genus_name' => 'Eucalyptus','species_name' => 'dorrigoensis','common_name' => 'Dorrigo white gum','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '2710','genus_name' => 'Eucalyptus','species_name' => 'dumosa','common_name' => 'White mallee','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '2711','genus_name' => 'Eucalyptus','species_name' => 'dunnii','common_name' => 'Dunn\'s white gum','growth_rate' => 'Moderate','height_at_maturity' => '165'),
            array('id' => '2712','genus_name' => 'Eucalyptus','species_name' => 'dwyeri','common_name' => 'Dwyer\'s red gum','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '2713','genus_name' => 'Eugenia','species_name' => 'earhartii','common_name' => 'Earhart\'s stopper','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2714','genus_name' => 'Euterpe','species_name' => 'edulis','common_name' => 'assai palm','growth_rate' => '','height_at_maturity' => '26'),
            array('id' => '2715','genus_name' => 'Eugenia','species_name' => 'eggersii','common_name' => 'Guasabara','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2716','genus_name' => 'Eucalyptus','species_name' => 'elata','common_name' => 'River peppermint','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '2717','genus_name' => 'Eucalyptus','species_name' => 'elliptica','common_name' => 'Bendemeer white gum','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '2718','genus_name' => 'Eucalyptus','species_name' => 'erythrocorys','common_name' => 'Red-cap gum','growth_rate' => 'Fast','height_at_maturity' => ''),
            array('id' => '2719','genus_name' => 'Eucalyptus','species_name' => 'eremophila','common_name' => 'Sand Mallee','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '2720','genus_name' => 'Eucalyptus','species_name' => 'erythronema','common_name' => 'Red-flowered Mallee','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '2721','genus_name' => 'Euonymus','species_name' => 'europaeus','common_name' => 'European spindletree','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2722','genus_name' => 'Eucalyptus','species_name' => 'eugenioides','common_name' => 'Thin-leaved stringybark','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '2723','genus_name' => 'Eucalyptus','species_name' => 'exserta','common_name' => 'Queensland Peppermint','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2725','genus_name' => 'Eucalyptus','species_name' => 'fasciculosa','common_name' => 'Pink gum','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '2726','genus_name' => 'Eucalyptus','species_name' => 'fastigata','common_name' => 'Brown barrel','growth_rate' => 'Moderate','height_at_maturity' => '198'),
            array('id' => '2727','genus_name' => 'Euroschinus','species_name' => 'falcata','common_name' => 'Ribbonwood','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '2728','genus_name' => 'Eucalyptus','species_name' => 'fibrosa','common_name' => 'Broad-leaved red ironbark','growth_rate' => 'Moderate','height_at_maturity' => '116'),
            array('id' => '2729','genus_name' => 'Eucalyptus','species_name' => 'flindersii','common_name' => 'Mallee red gum','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '2730','genus_name' => 'Corymbia','species_name' => 'ficifolia','common_name' => 'Redflower gum','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '2732','genus_name' => 'Euonymus','species_name' => 'fortunei','common_name' => 'Winter creeper','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '2733','genus_name' => 'Eucalyptus','species_name' => 'forrestiana','common_name' => 'Fuchsia gum','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '2734','genus_name' => 'Eugenia','species_name' => 'foetida','common_name' => 'Boxleaf stopper','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '2735','genus_name' => 'Eucalyptus','species_name' => 'fraxinoides','common_name' => 'White mountain ash','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '2736','genus_name' => 'Eucalyptus','species_name' => 'froggatti','common_name' => 'Kamarooka Mallee','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '2737','genus_name' => 'Eucalyptus','species_name' => 'fusiformis','common_name' => 'Nambucca Ironbark','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '2738','genus_name' => 'Eucalyptus','species_name' => 'fulgens','common_name' => 'Green Scentbark','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2739','genus_name' => 'Eucalyptus','species_name' => 'gillenii','common_name' => 'Mt Gillen Mallee','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '2740','genus_name' => 'Eucalyptus','species_name' => 'gillii','common_name' => 'Curly Mallee','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '2741','genus_name' => 'Eucalyptus','species_name' => 'globulus','common_name' => 'Blue gum eucalyptus','growth_rate' => 'Fast','height_at_maturity' => '160'),
            array('id' => '2742','genus_name' => 'Eucalyptus','species_name' => 'glaucina','common_name' => 'Slaty red gum','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '2743','genus_name' => 'Eucalyptus','species_name' => 'globoidea','common_name' => 'White stringybark','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '2744','genus_name' => 'Eucryphia','species_name' => 'glutinosa','common_name' => 'Nirrhe','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '2745','genus_name' => 'Eucalyptus','species_name' => 'glaucescens','common_name' => 'Tingiringi Gum','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '2746','genus_name' => 'Eugenia','species_name' => 'glabrata','common_name' => 'Smooth rodwood','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2747','genus_name' => 'Eucalyptus','species_name' => 'globulus v compacta','common_name' => 'Dwarf blue gum','growth_rate' => 'Fast','height_at_maturity' => ''),
            array('id' => '2748','genus_name' => 'Eucalyptus','species_name' => 'gomphocephala','common_name' => 'Tuart','growth_rate' => 'Fast','height_at_maturity' => '45'),
            array('id' => '2749','genus_name' => 'Eucalyptus','species_name' => 'goniocalyx','common_name' => 'Mountain graygum','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '2750','genus_name' => 'Eucalyptus','species_name' => 'globulus ssp. bicostata','common_name' => 'Southern blue gum','growth_rate' => 'Fast','height_at_maturity' => '148'),
            array('id' => '2751','genus_name' => 'Eucalyptus','species_name' => 'globulus ssp. maidenii','common_name' => 'Maiden\'s gum','growth_rate' => 'Fast','height_at_maturity' => '165'),
            array('id' => '2752','genus_name' => 'Eucalyptus','species_name' => 'grandis','common_name' => 'Flooded gum eucalyptus','growth_rate' => 'Fast','height_at_maturity' => '160'),
            array('id' => '2753','genus_name' => 'Eucalyptus','species_name' => 'gregsoniana','common_name' => 'Wolgan snow gum','growth_rate' => 'Slow','height_at_maturity' => '13'),
            array('id' => '2754','genus_name' => 'Eucalyptus','species_name' => 'gracilis','common_name' => 'Yorrel','growth_rate' => 'Slow','height_at_maturity' => '7'),
            array('id' => '2755','genus_name' => 'Eucalyptus','species_name' => 'grossa','common_name' => 'Coarse-leaved Mallee','growth_rate' => 'Slow','height_at_maturity' => '3'),
            array('id' => '2756','genus_name' => 'Eucalyptus','species_name' => 'gunnii','common_name' => 'Cider gum eucalyptus','growth_rate' => 'Fast','height_at_maturity' => '75'),
            array('id' => '2757','genus_name' => 'Eucalyptus','species_name' => 'gummifera','common_name' => 'Red bloodwood','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '2758','genus_name' => 'Eucalyptus','species_name' => 'haemastoma','common_name' => 'Scribbly gum','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '2759','genus_name' => 'Eucalyptus','species_name' => 'hallii','common_name' => 'Goodwood gum','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '2760','genus_name' => 'Euphorbia','species_name' => 'haeleeleana','common_name' => 'Kauai spurge','growth_rate' => 'Slow','height_at_maturity' => '38'),
            array('id' => '2761','genus_name' => 'Eugenia','species_name' => 'haematocarpa','common_name' => 'Luquillo mountain stopper','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2762','genus_name' => 'Euonymus','species_name' => 'hamiltonianus','common_name' => 'Hamilton\'s spindletree','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2763','genus_name' => 'Eucalyptus','species_name' => 'herbertiana','common_name' => 'Kalumburu Gum','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '2764','genus_name' => 'Eucalyptus','species_name' => 'ignorabilis','common_name' => 'Grey Scentbark','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2765','genus_name' => 'Eucalyptus','species_name' => 'imlayensis','common_name' => 'Mount Imlay Mallee','growth_rate' => 'Slow','height_at_maturity' => '7'),
            array('id' => '2766','genus_name' => 'Eugenia','species_name' => 'involucrata','common_name' => 'Cerejeira-do-rio-grande','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2767','genus_name' => 'Eucalyptus','species_name' => 'incrassata','common_name' => 'Lerp Mallee','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '2768','genus_name' => 'Eucalyptus','species_name' => 'intertexta','common_name' => 'Inland Red Box','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2770','genus_name' => 'Euonymus','species_name' => 'japonicus','common_name' => 'Evergreen euonymus','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2771','genus_name' => 'Eurya','species_name' => 'japonica','common_name' => 'Japanese eurya','growth_rate' => '','height_at_maturity' => '3'),
            array('id' => '2772','genus_name' => 'Eugenia','species_name' => 'javanica','common_name' => 'wax apple','growth_rate' => '','height_at_maturity' => '36'),
            array('id' => '2773','genus_name' => 'Euonymus','species_name' => 'japonica Aureomarginatus','common_name' => 'Golden euonymus','growth_rate' => 'Slow','height_at_maturity' => '3'),
            array('id' => '2774','genus_name' => 'Eucalyptus','species_name' => 'kartzoffiana','common_name' => 'Araluen Gum','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '2775','genus_name' => 'Eucalyptus','species_name' => 'kitsoniana','common_name' => 'Gippsland mallee','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '2776','genus_name' => 'Eucalyptus','species_name' => 'kingsmillii','common_name' => 'Kingsmill\'s Mallee','growth_rate' => 'Slow','height_at_maturity' => '7'),
            array('id' => '2777','genus_name' => 'Euonymus','species_name' => 'kiautschovica','common_name' => 'Creeping strawberry bush','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2778','genus_name' => 'Eugenia','species_name' => 'koolauensis','common_name' => 'Nioi','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2779','genus_name' => 'Eucalyptus','species_name' => 'kruseana','common_name' => 'Bookleaf Mallee','growth_rate' => 'Slow','height_at_maturity' => '3'),
            array('id' => '2780','genus_name' => 'Eucalyptus','species_name' => 'kybeanensis','common_name' => 'Kybean Mallee Ash','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '2781','genus_name' => 'Eucalyptus','species_name' => 'lacrimans','common_name' => 'Weeping snowgum','growth_rate' => 'Slow','height_at_maturity' => '40'),
            array('id' => '2782','genus_name' => 'Eucalyptus','species_name' => 'lansdowneana','common_name' => 'Red-flowered mallee box','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '2783','genus_name' => 'Eucalyptus','species_name' => 'largiflorens','common_name' => 'Black box','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '2784','genus_name' => 'Eucalyptus','species_name' => 'laevopinea','common_name' => 'Silvertop Stringybark','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '2785','genus_name' => 'Euonymus','species_name' => 'latifolius','common_name' => 'Large-leaved Spindle','growth_rate' => 'Slow','height_at_maturity' => '3'),
            array('id' => '2786','genus_name' => 'Eupomatia','species_name' => 'laurina','common_name' => 'Bolwarra','growth_rate' => 'Fast','height_at_maturity' => '5'),
            array('id' => '2787','genus_name' => 'Eucalyptus','species_name' => 'largeana','common_name' => 'Craven Grey Box','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '2788','genus_name' => 'Euphorbia','species_name' => 'lactea','common_name' => 'Mottled spurge','growth_rate' => 'Slow','height_at_maturity' => '38'),
            array('id' => '2789','genus_name' => 'Eugenia','species_name' => 'laevis','common_name' => 'Bayamon stopper','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2790','genus_name' => 'Eucalyptus','species_name' => 'leucoxylon','common_name' => 'White ironbark','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '2791','genus_name' => 'Eucalyptus','species_name' => 'leptophylla','common_name' => 'Narrow-leaved Red Mallee','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '2792','genus_name' => 'Eucalyptus','species_name' => 'lehmannii','common_name' => 'Bushy yate','growth_rate' => 'Fast','height_at_maturity' => ''),
            array('id' => '2793','genus_name' => 'Euphorbia','species_name' => 'leucocephala','common_name' => 'Pascuita','growth_rate' => 'Slow','height_at_maturity' => '38'),
            array('id' => '2794','genus_name' => 'Eucalyptus','species_name' => 'leucoxylon ssp. leucoxylon','common_name' => 'Yellow gum','growth_rate' => 'Moderate','height_at_maturity' => '83'),
            array('id' => '2795','genus_name' => 'Eucalyptus','species_name' => 'leucoxylon ssp. megalocarpa','common_name' => 'Large fruit yellow gum','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '2796','genus_name' => 'Eugenia','species_name' => 'ligustrina','common_name' => 'Privet stopper','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2797','genus_name' => 'Eucalyptus','species_name' => 'ligustrina','common_name' => 'Privet-leaved stringybark','growth_rate' => 'Slow','height_at_maturity' => '23'),
            array('id' => '2798','genus_name' => 'Eucalyptus','species_name' => 'longifolia','common_name' => 'Woollybutt','growth_rate' => 'Moderate','height_at_maturity' => '116'),
            array('id' => '2799','genus_name' => 'Eucalyptus','species_name' => 'longirostrata','common_name' => 'Eucalyptus longirostrata','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '2800','genus_name' => 'Euphorbia','species_name' => 'longana','common_name' => 'Euphorbia longana','growth_rate' => 'Moderate','height_at_maturity' => ''),
            array('id' => '2801','genus_name' => 'Eucalyptus','species_name' => 'luehmanniana','common_name' => 'Yellow-top mallee ash','growth_rate' => 'Slow','height_at_maturity' => '23'),
            array('id' => '2802','genus_name' => 'Euonymus','species_name' => 'lucidus','common_name' => 'Spindle','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '2803','genus_name' => 'Eucalyptus','species_name' => 'lucens','common_name' => 'Glistening Mallee','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '2804','genus_name' => 'Eucryphia','species_name' => 'lucida','common_name' => 'Leatherwood','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '2805','genus_name' => 'Eucalyptus','species_name' => 'macrocarpa','common_name' => 'Bluebush','growth_rate' => 'Fast','height_at_maturity' => ''),
            array('id' => '2806','genus_name' => 'Eucalyptus','species_name' => 'macrandra','common_name' => 'River yate','growth_rate' => 'Slow','height_at_maturity' => '13'),
            array('id' => '2807','genus_name' => 'Eucalyptus','species_name' => 'mannifera ssp. mannifera','common_name' => 'Brittle gum','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '2808','genus_name' => 'Eucalyptus','species_name' => 'macarthurii','common_name' => 'Camden woollybutt','growth_rate' => 'Fast','height_at_maturity' => ''),
            array('id' => '2809','genus_name' => 'Eucalyptus','species_name' => 'macrorhyncha','common_name' => 'Red stringybark','growth_rate' => 'Moderate','height_at_maturity' => '116'),
            array('id' => '2810','genus_name' => 'Eucalyptus','species_name' => 'macrorhyncha ssp. cannonii','common_name' => 'Capertee Stringybark','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '2811','genus_name' => 'Eucalyptus','species_name' => 'marginata','common_name' => 'Jarrah','growth_rate' => 'Fast','height_at_maturity' => '115'),
            array('id' => '2812','genus_name' => 'Eucalyptus','species_name' => 'major','common_name' => 'Queensland grey gum','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '2813','genus_name' => 'Eucalyptus','species_name' => 'mannifera','common_name' => 'Red spotted gum','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '2814','genus_name' => 'Eucalyptus','species_name' => 'malacoxylon','common_name' => 'Moonbi Apple Box','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2815','genus_name' => 'Eucalyptus','species_name' => 'mckieana','common_name' => 'McKie\'s Stringybark','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '2816','genus_name' => 'Eucalyptus','species_name' => 'melliodora','common_name' => 'Yellow box','growth_rate' => 'Fast','height_at_maturity' => ''),
            array('id' => '2817','genus_name' => 'Eucalyptus','species_name' => 'melanophloia','common_name' => 'Silver-leaved Ironbark','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2818','genus_name' => 'Eucalyptus','species_name' => 'microcorys','common_name' => 'Australian tallowwood','growth_rate' => 'Fast','height_at_maturity' => '148'),
            array('id' => '2819','genus_name' => 'Eucalyptus','species_name' => 'miniata','common_name' => 'Darwin Woollybutt','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '2820','genus_name' => 'Eucalyptus','species_name' => 'microtheca','common_name' => 'Coolibah tree','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '2821','genus_name' => 'Eucalyptus','species_name' => 'microcarpa','common_name' => 'Narrow-leaved box','growth_rate' => 'Moderate','height_at_maturity' => '82'),
            array('id' => '2822','genus_name' => 'Euphorbia','species_name' => 'misera','common_name' => 'Cliff spurge','growth_rate' => 'Slow','height_at_maturity' => '38'),
            array('id' => '2823','genus_name' => 'Eucalyptus','species_name' => 'mitchelliana','common_name' => 'Mount Buffalo gum','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '2824','genus_name' => 'Eucalyptus','species_name' => 'michaeliana','common_name' => 'Hillgrove gum','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '2825','genus_name' => 'Euphorbia','species_name' => 'milii','common_name' => 'Christplant','growth_rate' => 'Slow','height_at_maturity' => '38'),
            array('id' => '2826','genus_name' => 'Eugenia','species_name' => 'monticola','common_name' => 'Birdcherry','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2827','genus_name' => 'Eucalyptus','species_name' => 'moluccana','common_name' => 'Gum-topped box','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '2828','genus_name' => 'Eucalyptus','species_name' => 'moorei','common_name' => 'Narrow-leaved sally','growth_rate' => 'Slow','height_at_maturity' => '23'),
            array('id' => '2829','genus_name' => 'Eucalyptus','species_name' => 'morrisbyi','common_name' => 'Morrisby\'s gum','growth_rate' => 'Moderate','height_at_maturity' => '53'),
            array('id' => '2830','genus_name' => 'Eucalyptus','species_name' => 'morrisii','common_name' => 'Grey Mallee','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '2831','genus_name' => 'Eucalyptus','species_name' => 'x mortoniana','common_name' => 'Morton eucalyptus','growth_rate' => 'Fast','height_at_maturity' => '75'),
            array('id' => '2833','genus_name' => 'Eucalyptus','species_name' => 'multicaulis','common_name' => 'Whipstick mallee ash','growth_rate' => 'Slow','height_at_maturity' => '26'),
            array('id' => '2834','genus_name' => 'Eucalyptus','species_name' => 'muelleriana','common_name' => 'Yellow Stringybark','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '2837','genus_name' => 'Eucalyptus','species_name' => 'neglecta','common_name' => 'Omeo gum','growth_rate' => 'Slow','height_at_maturity' => '23'),
            array('id' => '2839','genus_name' => 'Euphorbia','species_name' => 'neriifolia','common_name' => 'Indian spurgetree','growth_rate' => 'Slow','height_at_maturity' => '38'),
            array('id' => '2840','genus_name' => 'Eucalyptus','species_name' => 'nicholii','common_name' => 'Willow-leaved gimlet','growth_rate' => 'Fast','height_at_maturity' => ''),
            array('id' => '2841','genus_name' => 'Eucalyptus','species_name' => 'nitens','common_name' => 'Silvertop','growth_rate' => 'Moderate','height_at_maturity' => '231'),
            array('id' => '2842','genus_name' => 'Eucalyptus','species_name' => 'nitida','common_name' => 'Shining Peppermint','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '2843','genus_name' => 'Eucalyptus','species_name' => 'nortonii','common_name' => 'Long-leaved box','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '2844','genus_name' => 'Eucalyptus','species_name' => 'notabilis','common_name' => 'Blue Mountains mahogany','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '2845','genus_name' => 'Eucalyptus','species_name' => 'nova-anglica','common_name' => 'New England Peppermint','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '2846','genus_name' => 'Eucalyptus','species_name' => 'nutans','common_name' => 'Red-flowered moort','growth_rate' => 'Fast','height_at_maturity' => ''),
            array('id' => '2848','genus_name' => 'Eucalyptus','species_name' => 'obliqua','common_name' => 'Messmate stringybark','growth_rate' => 'Moderate','height_at_maturity' => '297'),
            array('id' => '2849','genus_name' => 'Eucalyptus','species_name' => 'obtusiflora','common_name' => 'Dongarra mallee','growth_rate' => 'Slow','height_at_maturity' => '13'),
            array('id' => '2850','genus_name' => 'Euonymus','species_name' => 'occidentalis','common_name' => 'Western wahoo','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2851','genus_name' => 'Eucalyptus','species_name' => 'occidentalis','common_name' => 'Flat-top yate','growth_rate' => '','height_at_maturity' => '70'),
            array('id' => '2852','genus_name' => 'Eucalyptus','species_name' => 'odorata','common_name' => 'Peppermint box','growth_rate' => 'Fast','height_at_maturity' => ''),
            array('id' => '2853','genus_name' => 'Eucalyptus','species_name' => 'olsenii','common_name' => 'Woila gum','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '2854','genus_name' => 'Eucalyptus','species_name' => 'oleosa ssp. oleosa','common_name' => 'Red Morrell','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '2856','genus_name' => 'Eucalyptus','species_name' => 'orbifolia','common_name' => 'Round-leaved Mallee','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '2857','genus_name' => 'Eucalyptus','species_name' => 'oreades','common_name' => 'Blue Mountains Ash','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '2859','genus_name' => 'Eucalyptus','species_name' => 'ovata v. ovata','common_name' => 'Swamp gum','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '2860','genus_name' => 'Eucalyptus','species_name' => 'paniculata','common_name' => 'Gray ironbark','growth_rate' => 'Fast','height_at_maturity' => '130'),
            array('id' => '2861','genus_name' => 'Eucalyptus','species_name' => 'parramattensis','common_name' => 'Calgaroo','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '2862','genus_name' => 'Eugenia','species_name' => 'padronii','common_name' => 'Padron\'s stopper','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2866','genus_name' => 'Eucalyptus','species_name' => 'pachyphylla','common_name' => 'Red Bud Mallee','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '2867','genus_name' => 'Eucalyptus','species_name' => 'pauciflora ssp. niphophila','common_name' => 'White Sallee','growth_rate' => 'Slow','height_at_maturity' => '7'),
            array('id' => '2868','genus_name' => 'Eucalyptus','species_name' => 'pauciflora ssp. pauciflora','common_name' => 'Snow gum','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '2869','genus_name' => 'Eucalyptus','species_name' => 'paliformis','common_name' => 'Wadbilliga Ash','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '2872','genus_name' => 'Eucalyptus','species_name' => 'pellita','common_name' => 'Large-fruit red mahogany','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '2873','genus_name' => 'Eucalyptus','species_name' => 'perriniana','common_name' => 'Spinning gum','growth_rate' => 'Slow','height_at_maturity' => '23'),
            array('id' => '2874','genus_name' => 'Euphorbia','species_name' => 'pereskiifolia','common_name' => 'Euphorbia pereskiifolia','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '2875','genus_name' => 'Euphorbia','species_name' => 'petiolaris','common_name' => 'Manchineel berry','growth_rate' => 'Slow','height_at_maturity' => '38'),
            array('id' => '2876','genus_name' => 'Eucalyptus','species_name' => 'phenax','common_name' => 'Kangaroo Island Mallee','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '2877','genus_name' => 'Eucalyptus','species_name' => 'phoenicea','common_name' => 'Scarlet Gum','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '2878','genus_name' => 'Euonymus','species_name' => 'phellomanus','common_name' => 'Corktree','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2879','genus_name' => 'Eucalyptus','species_name' => 'pilularis','common_name' => 'Blackbutt','growth_rate' => 'Fast','height_at_maturity' => '164'),
            array('id' => '2880','genus_name' => 'Eucalyptus','species_name' => 'pilligaensis','common_name' => 'Narrow-leaved grey box','growth_rate' => 'Moderate','height_at_maturity' => '82'),
            array('id' => '2881','genus_name' => 'Eucalyptus','species_name' => 'piperita','common_name' => 'Sydney peppermint','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '2882','genus_name' => 'Eucalyptus','species_name' => 'platypus','common_name' => 'Moort','growth_rate' => 'Slow','height_at_maturity' => '26'),
            array('id' => '2883','genus_name' => 'Eucalyptus','species_name' => 'planchoniana','common_name' => 'Needlebark Stringybark','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2884','genus_name' => 'Eucalyptus','species_name' => 'polyanthemos','common_name' => 'Sliver dollar eucalyptus','growth_rate' => 'Fast','height_at_maturity' => '45'),
            array('id' => '2885','genus_name' => 'Eucalyptus','species_name' => 'polybractea','common_name' => 'Blue-leaved mallee','growth_rate' => 'Slow','height_at_maturity' => '26'),
            array('id' => '2886','genus_name' => 'Eucalyptus','species_name' => 'populnea','common_name' => 'Poplar Box','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2887','genus_name' => 'Eucalyptus','species_name' => 'porosa','common_name' => 'South Aust. Mallee Box','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '2888','genus_name' => 'Eucalyptus','species_name' => 'polyanthemos ssp. polyanthemos','common_name' => 'Red box','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '2889','genus_name' => 'Eucalyptus','species_name' => 'propinqua','common_name' => 'Small-fruited Grey Gum','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '2892','genus_name' => 'Eugenia','species_name' => 'procera','common_name' => 'Rockmyrtle','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2893','genus_name' => 'Eugenia','species_name' => 'pseudopsidium','common_name' => 'Christmas cherry','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2894','genus_name' => 'Eucalyptus','species_name' => 'pseudoglobulus','common_name' => 'Victorian eurabbie','growth_rate' => 'Moderate','height_at_maturity' => '148'),
            array('id' => '2895','genus_name' => 'Eucalyptus','species_name' => 'pulchella','common_name' => 'White peppermint','growth_rate' => 'Fast','height_at_maturity' => '75'),
            array('id' => '2896','genus_name' => 'Eucalyptus','species_name' => 'punctata','common_name' => 'Grey gum','growth_rate' => 'Moderate','height_at_maturity' => '116'),
            array('id' => '2897','genus_name' => 'Eucalyptus','species_name' => 'pulverulenta','common_name' => 'Silverleaf mountain gum','growth_rate' => 'Fast','height_at_maturity' => '28'),
            array('id' => '2898','genus_name' => 'Eucalyptus','species_name' => 'pumila','common_name' => 'Pokolbin Mallee','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '2900','genus_name' => 'Euphorbia','species_name' => 'pulcherrima','common_name' => 'Poinsettia','growth_rate' => 'Slow','height_at_maturity' => '38'),
            array('id' => '2901','genus_name' => 'Eucalyptus','species_name' => 'pyriformis','common_name' => 'Dowerin Rose','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '2902','genus_name' => 'Eucalyptus','species_name' => 'quadrangulata','common_name' => 'White-topped box','growth_rate' => 'Moderate','height_at_maturity' => '165'),
            array('id' => '2903','genus_name' => 'Eucalyptus','species_name' => 'quadricostata','common_name' => 'Square-fruited ironbark','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '2904','genus_name' => 'Eucalyptus','species_name' => 'radiata','common_name' => 'Narrow-leaved peppermint','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '2905','genus_name' => 'Euclea','species_name' => 'racemosa','common_name' => 'Sea guarrie','growth_rate' => 'Fast','height_at_maturity' => '23'),
            array('id' => '2906','genus_name' => 'Eucalyptus','species_name' => 'raveretiana','common_name' => 'Black ironbox','growth_rate' => 'Fast','height_at_maturity' => '75'),
            array('id' => '2907','genus_name' => 'Eucalyptus','species_name' => 'radiata ssp. radiata','common_name' => 'Narrow-leaf peppermint','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '2908','genus_name' => 'Eucalyptus','species_name' => 'racemosa ssp. racemosa','common_name' => 'Snappy gum','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '2909','genus_name' => 'Eucalyptus','species_name' => 'racemosa ssp. rossii','common_name' => 'Inland scribbly gum','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '2910','genus_name' => 'Eucalyptus','species_name' => 'redunca','common_name' => 'Black marlock','growth_rate' => 'Fast','height_at_maturity' => ''),
            array('id' => '2911','genus_name' => 'Eucalyptus','species_name' => 'recurva','common_name' => 'Mongarlow Mallee','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '2912','genus_name' => 'Eucalyptus','species_name' => 'resinifera','common_name' => 'Redmahogany','growth_rate' => 'Fast','height_at_maturity' => '123'),
            array('id' => '2913','genus_name' => 'Eucalyptus','species_name' => 'regnans','common_name' => 'Mountain Ash','growth_rate' => 'Moderate','height_at_maturity' => '90'),
            array('id' => '2914','genus_name' => 'Eugenia','species_name' => 'reinwardtiana','common_name' => 'Mountain stopper','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2915','genus_name' => 'Eugenia','species_name' => 'rhombea','common_name' => 'Red stopper','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2916','genus_name' => 'Eucalyptus','species_name' => 'risdonii','common_name' => 'Risdon Peppermint','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '2917','genus_name' => 'Eucalyptus','species_name' => 'robusta','common_name' => 'Beakpod euclayptus','growth_rate' => 'Fast','height_at_maturity' => '160'),
            array('id' => '2918','genus_name' => 'Eucalyptus','species_name' => 'rodwayi','common_name' => 'Swamp Peppermint','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2920','genus_name' => 'Eucalyptus','species_name' => 'rudis','common_name' => 'Desert gum eucalyptus','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '2921','genus_name' => 'Eucalyptus','species_name' => 'rubida','common_name' => 'Candlebark','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '2922','genus_name' => 'Eucalyptus','species_name' => 'rudderi','common_name' => 'Rudder\'s box','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '2923','genus_name' => 'Eucalyptus','species_name' => 'rugosa','common_name' => 'Kingscote Mallee','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '2924','genus_name' => 'Eucalyptus','species_name' => 'rummeryi','common_name' => 'Steel Box','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '2925','genus_name' => 'Eucalyptus','species_name' => 'saligna','common_name' => 'Sydney blue gum','growth_rate' => 'Fast','height_at_maturity' => '160'),
            array('id' => '2926','genus_name' => 'Eucalyptus','species_name' => 'salmonophloia','common_name' => 'Salmon gum','growth_rate' => 'Moderate','height_at_maturity' => '83'),
            array('id' => '2927','genus_name' => 'Eucalyptus','species_name' => 'salubris','common_name' => 'Gimlet','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '2928','genus_name' => 'Eucalyptus','species_name' => 'saxatilis','common_name' => 'Suggan Buggan mallee','growth_rate' => 'Slow','height_at_maturity' => '16'),
            array('id' => '2929','genus_name' => 'Eucalyptus','species_name' => 'sargentii','common_name' => 'Salt River Gum','growth_rate' => 'Slow','height_at_maturity' => '11'),
            array('id' => '2930','genus_name' => 'Eurya','species_name' => 'sandwicensis','common_name' => 'Anini','growth_rate' => 'Slow','height_at_maturity' => '19'),
            array('id' => '2931','genus_name' => 'Eucalyptus','species_name' => 'saligna x botryoides','common_name' => 'Eucalyptus saligna','growth_rate' => 'Moderate','height_at_maturity' => '182'),
            array('id' => '2932','genus_name' => 'Eucalyptus','species_name' => 'scoparia','common_name' => 'Wallangarra white gum','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '2933','genus_name' => 'Eucalyptus','species_name' => 'seeana','common_name' => 'Narrow-leaved red gum','growth_rate' => 'Moderate','height_at_maturity' => '59'),
            array('id' => '2934','genus_name' => 'Eucalyptus','species_name' => 'serraensis','common_name' => 'Grampians Stringybark','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '2935','genus_name' => 'Eugenia','species_name' => 'sessiliflora','common_name' => 'Sessileleaf stopper','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2936','genus_name' => 'Eucalyptus','species_name' => 'sessilis','common_name' => 'Finke River Mallee','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '2937','genus_name' => 'Eugenia','species_name' => 'serrasuela','common_name' => 'Serrasuela','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2938','genus_name' => 'Eucalyptus','species_name' => 'sideroxylon','common_name' => 'Mugga ironbark','growth_rate' => 'Fast','height_at_maturity' => '73'),
            array('id' => '2939','genus_name' => 'Eucalyptus','species_name' => 'sieberi','common_name' => 'Silvertop ash','growth_rate' => 'Moderate','height_at_maturity' => '116'),
            array('id' => '2940','genus_name' => 'Eucalyptus','species_name' => 'simmondsii','common_name' => 'Smithton peppermint','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '2941','genus_name' => 'Eucalyptus','species_name' => 'siderophloia','common_name' => 'Ironbark','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2943','genus_name' => 'Eucalyptus','species_name' => 'sideroxylon Rosea','common_name' => 'Mugga','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2945','genus_name' => 'Eucalyptus','species_name' => 'smithii','common_name' => 'Gully gum','growth_rate' => 'Moderate','height_at_maturity' => '148'),
            array('id' => '2946','genus_name' => 'Eucalyptus','species_name' => 'socialis','common_name' => 'Red mallee','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '2948','genus_name' => 'Eucalyptus','species_name' => 'spathulata','common_name' => 'Narrow-leaved gimlet','growth_rate' => 'Fast','height_at_maturity' => ''),
            array('id' => '2949','genus_name' => 'Eucalyptus','species_name' => 'squamosa','common_name' => 'Scaly bark','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '2950','genus_name' => 'Eucalyptus','species_name' => 'stellulata','common_name' => 'Black sally','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '2951','genus_name' => 'Eucalyptus','species_name' => 'stricta','common_name' => 'Blue Mountains mallee ash','growth_rate' => 'Slow','height_at_maturity' => '23'),
            array('id' => '2952','genus_name' => 'Eucalyptus','species_name' => 'stenostoma','common_name' => 'Jillaga Ash','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2953','genus_name' => 'Eugenia','species_name' => 'stahlii','common_name' => 'Stahl\'s stopper','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2954','genus_name' => 'Eucalyptus','species_name' => 'stoatei','common_name' => 'Scarlet Pear Gum','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '2955','genus_name' => 'Eucalyptus','species_name' => 'stricklandii','common_name' => 'Stickland\'s Gum','growth_rate' => 'Moderate','height_at_maturity' => '9'),
            array('id' => '2956','genus_name' => 'Eugenia','species_name' => 'stewardsonii','common_name' => 'Stewardson\'s stopper','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2957','genus_name' => 'Eucalyptus','species_name' => 'strzeleckii','common_name' => 'Wax-tip','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '2958','genus_name' => 'Eucalyptus','species_name' => 'sturgissiana','common_name' => 'Ettrema Mallee','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '2959','genus_name' => 'Eucalyptus','species_name' => 'subcrenulata','common_name' => 'Tasmania Alpine YellowGum','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2960','genus_name' => 'Euphorbia','species_name' => 'tanquahuete','common_name' => 'Palo amarillo','growth_rate' => 'Fast','height_at_maturity' => '8'),
            array('id' => '2961','genus_name' => 'Eucalyptus','species_name' => 'tereticornis','common_name' => 'Horn cap eucalyptus','growth_rate' => 'Fast','height_at_maturity' => '75'),
            array('id' => '2962','genus_name' => 'Eucalyptus','species_name' => 'pleurocarpa','common_name' => 'Tallerack','growth_rate' => 'Slow','height_at_maturity' => '16'),
            array('id' => '2963','genus_name' => 'Eucalyptus','species_name' => 'tenuiramis','common_name' => 'Silver Peppermint','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2964','genus_name' => 'Eucalyptus','species_name' => 'tetrapleura','common_name' => 'Square-fruited Iron Bark','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '2965','genus_name' => 'Eucalyptus','species_name' => 'tetraptera','common_name' => 'Four Wing Mallee','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '2966','genus_name' => 'Eucalyptus','species_name' => 'tereticornis ssp. mediana','common_name' => 'Gippsland Red Gum','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2967','genus_name' => 'Eucalyptus','species_name' => 'thozetiana','common_name' => 'Thozets Box','growth_rate' => 'Moderate','height_at_maturity' => '17'),
            array('id' => '2969','genus_name' => 'Euphorbia','species_name' => 'tirucalli','common_name' => 'Indiantree spurge','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2970','genus_name' => 'Eucalyptus','species_name' => 'tindaliae','common_name' => 'Tindal\'s Stringybark','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '2971','genus_name' => 'Eucalyptus','species_name' => 'tintinnans','common_name' => 'Ringing Gum','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '2973','genus_name' => 'Eucalyptus','species_name' => 'todtiana','common_name' => 'Prickly Bark','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '2975','genus_name' => 'Eucalyptus','species_name' => 'torquata','common_name' => 'Coral gum','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2976','genus_name' => 'Eucalyptus','species_name' => 'tricarpa','common_name' => 'Red ironbark','growth_rate' => 'Moderate','height_at_maturity' => '116'),
            array('id' => '2977','genus_name' => 'Eucalyptus','species_name' => 'triflora','common_name' => 'Pigeon House Ash','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '2978','genus_name' => 'Eucalyptus','species_name' => 'trivalva','common_name' => 'Desert Mallee','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '2979','genus_name' => 'Eucommia','species_name' => 'ulmoides','common_name' => 'Hardy rubber tree','growth_rate' => 'Moderate','height_at_maturity' => '43'),
            array('id' => '2980','genus_name' => 'Eucalyptus','species_name' => 'umbra','common_name' => 'Broad leaf white mahogany','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '2983','genus_name' => 'Eugenia','species_name' => 'underwoodii','common_name' => 'Underwood\'s stopper','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '2984','genus_name' => 'Eugenia','species_name' => 'uniflora','common_name' => 'Surinam cherry','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '2985','genus_name' => 'Eucalyptus','species_name' => 'urophylla','common_name' => 'Timor white gum','growth_rate' => 'Fast','height_at_maturity' => '75'),
            array('id' => '2986','genus_name' => 'Eucalyptus','species_name' => 'urnigera','common_name' => 'Urn Gum','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '2987','genus_name' => 'Eucalyptus','species_name' => 'verrucata','common_name' => 'Mt Abrupt stringybark','growth_rate' => 'Slow','height_at_maturity' => '16'),
            array('id' => '2988','genus_name' => 'Eucalyptus','species_name' => 'vernicosa','common_name' => 'Varnished Gum','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '2989','genus_name' => 'Eucalyptus','species_name' => 'viminalis','common_name' => 'Ribbon gum eucalyptus','growth_rate' => 'Fast','height_at_maturity' => '70'),
            array('id' => '2990','genus_name' => 'Eucalyptus','species_name' => 'viridis','common_name' => 'Green mallee','growth_rate' => 'Slow','height_at_maturity' => '26'),
            array('id' => '2991','genus_name' => 'Eucalyptus','species_name' => 'victoriana','common_name' => 'Eucalyptus victoriana','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '2992','genus_name' => 'Eucalyptus','species_name' => 'viminalis ssp. pryoriana','common_name' => 'Gippsland manna gum','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '2993','genus_name' => 'Eucalyptus','species_name' => 'viminalis ssp. viminalis','common_name' => 'Manna gum','growth_rate' => 'Moderate','height_at_maturity' => '297'),
            array('id' => '2994','genus_name' => 'Eucalyptus','species_name' => 'viridis ssp. Wimmerensis','common_name' => 'Broad-leaved green mallee','growth_rate' => 'Slow','height_at_maturity' => '26'),
            array('id' => '2995','genus_name' => 'Eucalyptus','species_name' => 'websteriana','common_name' => 'Websters Mallee','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '2996','genus_name' => 'Eucalyptus','species_name' => 'wilcoxii','common_name' => 'Deua Gum','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '2997','genus_name' => 'Eucalyptus','species_name' => 'willisii ssp. willisii','common_name' => 'Grampians Peppermint','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '2998','genus_name' => 'Eucalyptus','species_name' => 'woodwardii','common_name' => 'Lemon-flowered Gum','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '2999','genus_name' => 'Eucalyptus','species_name' => 'woodwardii x torquata','common_name' => 'Torwood Gum','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '3000','genus_name' => 'Eugenia','species_name' => 'woodburyana','common_name' => 'Woodbury\'s stopper','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '3001','genus_name' => 'Eugenia','species_name' => 'xerophytica','common_name' => 'Aridland stopper','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '3002','genus_name' => 'Eucalyptus','species_name' => 'yarraensis','common_name' => 'Yarra gum','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '3003','genus_name' => 'Eucalyptus','species_name' => 'youmanii','common_name' => 'Yourman\'s stringybark','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '3004','genus_name' => 'Excoecaria','species_name' => 'agallocha','common_name' => 'blinding tree','growth_rate' => '','height_at_maturity' => '45'),
            array('id' => '3005','genus_name' => 'Exocarpos','species_name' => 'aphyllus','common_name' => 'Leafless Ballart','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '3007','genus_name' => 'Exocarpos','species_name' => 'cupressiformis','common_name' => 'Cherry Ballart','growth_rate' => 'Slow','height_at_maturity' => '26'),
            array('id' => '3012','genus_name' => 'Exothea','species_name' => 'paniculata','common_name' => 'Butterbough','growth_rate' => 'Slow','height_at_maturity' => '60'),
            array('id' => '3013','genus_name' => 'Exochorda','species_name' => 'racemosa','common_name' => 'Common pearlbrush','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '3014','genus_name' => 'Exostema','species_name' => 'sanctae-luciae','common_name' => 'Exostema sanctae-luciae','growth_rate' => '','height_at_maturity' => '45'),
            array('id' => '3015','genus_name' => 'Exocarpos','species_name' => 'sparteus','common_name' => 'Broom Ballart','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '3016','genus_name' => 'Exocarpos','species_name' => 'strictus','common_name' => 'Pale-fruit Ballart','growth_rate' => 'Moderate','height_at_maturity' => '2'),
            array('id' => '3017','genus_name' => 'Exocarpos','species_name' => 'syrticola','common_name' => 'Coast Ballart','growth_rate' => 'Moderate','height_at_maturity' => '2'),
            array('id' => '3021','genus_name' => 'Eysenhardtia','species_name' => 'texana','common_name' => 'Texas kidneywood','growth_rate' => '','height_at_maturity' => '8'),
            array('id' => '3023','genus_name' => 'Fagus','species_name' => 'crenata','common_name' => 'Japanese beech','growth_rate' => 'Slow','height_at_maturity' => '87'),
            array('id' => '3024','genus_name' => 'Fagus','species_name' => 'grandifolia','common_name' => 'American beech','growth_rate' => 'Slow','height_at_maturity' => '80'),
            array('id' => '3025','genus_name' => 'Fatsia','species_name' => 'japonica','common_name' => 'Japanese aralia','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '3026','genus_name' => 'Fagus','species_name' => 'mexicana','common_name' => 'Mexican beech','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '3027','genus_name' => 'Faramea','species_name' => 'occidentalis','common_name' => 'False coffee','growth_rate' => 'Slow','height_at_maturity' => '65'),
            array('id' => '3028','genus_name' => 'Fagus','species_name' => 'orientalis','common_name' => 'Oriental beech','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '3030','genus_name' => 'Fagus','species_name' => 'sylvatica','common_name' => 'European beech','growth_rate' => 'Slow','height_at_maturity' => '85'),
            array('id' => '3031','genus_name' => 'Fagus','species_name' => 'sylvatica \'Asplenifolia\'','common_name' => 'Fern leaved beech','growth_rate' => 'Moderate','height_at_maturity' => '49'),
            array('id' => '3032','genus_name' => 'Fagus','species_name' => 'sylvatica \'Purpurea\'','common_name' => 'Copper beech','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '3035','genus_name' => 'Feijoa','species_name' => 'sellowiana','common_name' => 'Pineapple guava','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '3037','genus_name' => 'Ferocactus','species_name' => 'wislizeni','common_name' => 'Candy barrelcactus','growth_rate' => 'Slow','height_at_maturity' => '11'),
            array('id' => '3039','genus_name' => 'Ficus','species_name' => 'altissima','common_name' => 'Council tree','growth_rate' => 'Fast','height_at_maturity' => '71'),
            array('id' => '3040','genus_name' => 'Ficus','species_name' => 'americana','common_name' => 'Jamaican cherry fig','growth_rate' => 'Fast','height_at_maturity' => '71'),
            array('id' => '3041','genus_name' => 'Ficus','species_name' => 'aurea','common_name' => 'Florida strangler fig','growth_rate' => 'Fast','height_at_maturity' => '55'),
            array('id' => '3042','genus_name' => 'Ficus','species_name' => 'auriculata','common_name' => 'Roxburgh fig','growth_rate' => '','height_at_maturity' => '33'),
            array('id' => '3043','genus_name' => 'Ficus','species_name' => 'benjamina','common_name' => 'Benjamin fig','growth_rate' => 'Fast','height_at_maturity' => '53'),
            array('id' => '3044','genus_name' => 'Ficus','species_name' => 'benghalensis','common_name' => 'Indian banyan','growth_rate' => 'Fast','height_at_maturity' => '63'),
            array('id' => '3045','genus_name' => 'Ficus','species_name' => 'binnendijkii','common_name' => 'Long-leaf fig','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '3046','genus_name' => 'Ficus','species_name' => 'carica','common_name' => 'Common fig','growth_rate' => 'Fast','height_at_maturity' => '71'),
            array('id' => '3047','genus_name' => 'Ficus','species_name' => 'citrifolia','common_name' => 'Wild banyantree','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '3049','genus_name' => 'Ficus','species_name' => 'coronata','common_name' => 'Creek sandpaper fig','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '3050','genus_name' => 'Ficus','species_name' => 'coronulata','common_name' => 'Peach-Leaf Fig','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '3051','genus_name' => 'Ficus','species_name' => 'cotinifolia','common_name' => 'Ficus cotinifolia','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '3052','genus_name' => 'Fitzroya','species_name' => 'cupressoides','common_name' => 'Patagonian Cypress','growth_rate' => 'Moderate','height_at_maturity' => '45'),
            array('id' => '3053','genus_name' => 'Ficus','species_name' => 'destruens','common_name' => 'Boonjee','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '3055','genus_name' => 'Ficus','species_name' => 'drupacea','common_name' => 'Brown-woolly fig','growth_rate' => 'Fast','height_at_maturity' => '71'),
            array('id' => '3056','genus_name' => 'Ficus','species_name' => 'elastica','common_name' => 'Rubber plant','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '3058','genus_name' => 'Ficus','species_name' => 'sur','common_name' => 'Cape fig','growth_rate' => '','height_at_maturity' => '45'),
            array('id' => '3059','genus_name' => 'Ficus','species_name' => 'fraseri','common_name' => 'White Sandpaper Fig','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '3064','genus_name' => 'Ficus','species_name' => 'irisana','common_name' => 'Ficus irisana','growth_rate' => 'Moderate','height_at_maturity' => ''),
            array('id' => '3065','genus_name' => 'Ficus','species_name' => 'lyrata','common_name' => 'Fiddle leaf fig','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '3066','genus_name' => 'Ficus','species_name' => 'macrocarpa','common_name' => 'Ficus macrocarpa','growth_rate' => 'Fast','height_at_maturity' => '71'),
            array('id' => '3067','genus_name' => 'Ficus','species_name' => 'macrophylla','common_name' => 'Moreton bay fig','growth_rate' => 'Moderate','height_at_maturity' => '58'),
            array('id' => '3070','genus_name' => 'Ficus','species_name' => 'thonningii','common_name' => 'Strangler fig','growth_rate' => 'Fast','height_at_maturity' => '71'),
            array('id' => '3071','genus_name' => 'Ficus','species_name' => 'microcarpa v. hillii','common_name' => 'Hill\'s weeping fig','growth_rate' => 'Moderate','height_at_maturity' => '59'),
            array('id' => '3074','genus_name' => 'Ficus','species_name' => 'lutea','common_name' => 'Lagos rubbertree','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '3075','genus_name' => 'Ficus','species_name' => 'nota','common_name' => 'Tibig','growth_rate' => 'Fast','height_at_maturity' => '71'),
            array('id' => '3076','genus_name' => 'Ficus','species_name' => 'obtusifolia','common_name' => 'Amate','growth_rate' => 'Fast','height_at_maturity' => '71'),
            array('id' => '3077','genus_name' => 'Ficus','species_name' => 'obliqua','common_name' => 'Small-leaved Fig','growth_rate' => 'Moderate','height_at_maturity' => '165'),
            array('id' => '3078','genus_name' => 'Ficus','species_name' => 'opposita','common_name' => 'Figwood','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '3079','genus_name' => 'Ficus','species_name' => 'organensis','common_name' => 'Figueira nativa','growth_rate' => 'Fast','height_at_maturity' => '71'),
            array('id' => '3080','genus_name' => 'Ficus','species_name' => 'padifolia','common_name' => 'Ficus padifolia','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '3081','genus_name' => 'Ficus','species_name' => 'palmata','common_name' => 'Punjab fig','growth_rate' => 'Fast','height_at_maturity' => '71'),
            array('id' => '3082','genus_name' => 'Ficus','species_name' => 'petiolaris','common_name' => 'Petiolate fig','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '3083','genus_name' => 'Ficus','species_name' => 'platypoda','common_name' => 'Rock fig','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '3084','genus_name' => 'Ficus','species_name' => 'prinoides','common_name' => 'Higuito/Laurel','growth_rate' => 'Fast','height_at_maturity' => '98'),
            array('id' => '3085','genus_name' => 'Ficus','species_name' => 'prolixa','common_name' => 'banyan','growth_rate' => '','height_at_maturity' => '90'),
            array('id' => '3086','genus_name' => 'Ficus','species_name' => 'pumila','common_name' => 'Climbingfig','growth_rate' => 'Fast','height_at_maturity' => '71'),
            array('id' => '3087','genus_name' => 'Ficus','species_name' => 'racemosa','common_name' => 'Cluster Fig','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3088','genus_name' => 'Ficus','species_name' => 'religiosa','common_name' => 'Peepul tree','growth_rate' => 'Fast','height_at_maturity' => '63'),
            array('id' => '3090','genus_name' => 'Ficus','species_name' => 'rubiginosa','common_name' => 'Rustyleaf fig','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '3093','genus_name' => 'Ficus','species_name' => 'scobina','common_name' => 'Sandpaper figs','growth_rate' => 'Fast','height_at_maturity' => '8'),
            array('id' => '3094','genus_name' => 'Ficus','species_name' => 'septica','common_name' => 'Hauli tree','growth_rate' => 'Moderate','height_at_maturity' => ''),
            array('id' => '3095','genus_name' => 'Firmiana','species_name' => 'simplex','common_name' => 'Chinese parasoltree','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '3096','genus_name' => 'Fitchia','species_name' => 'speciosa','common_name' => 'Burrdaisytree','growth_rate' => '','height_at_maturity' => '21'),
            array('id' => '3097','genus_name' => 'Ficus','species_name' => 'stahlii','common_name' => 'Jaguey','growth_rate' => 'Fast','height_at_maturity' => '71'),
            array('id' => '3098','genus_name' => 'Ficus','species_name' => 'superba v. henneana','common_name' => 'Cedar fig','growth_rate' => 'Moderate','height_at_maturity' => '116'),
            array('id' => '3099','genus_name' => 'Ficus','species_name' => 'superba','common_name' => 'Sea figs','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '3101','genus_name' => 'Ficus','species_name' => 'sycomorus','common_name' => 'sycamore fig','growth_rate' => '','height_at_maturity' => '65'),
            array('id' => '3103','genus_name' => 'Ficus','species_name' => 'trigonata','common_name' => 'Jaguey blanco','growth_rate' => 'Fast','height_at_maturity' => '71'),
            array('id' => '3104','genus_name' => 'Ficus','species_name' => 'variegata','common_name' => 'Red stem-fig','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '3105','genus_name' => 'Ficus','species_name' => 'vasta','common_name' => 'Fig tree','growth_rate' => 'Moderate','height_at_maturity' => '165'),
            array('id' => '3106','genus_name' => 'Ficus','species_name' => 'virens','common_name' => 'White Fig','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '3109','genus_name' => 'Flindersia','species_name' => 'australis','common_name' => 'Crows Ash','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '3110','genus_name' => 'Flindersia','species_name' => 'bennettiana','common_name' => 'Bennett\'s Ash','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '3111','genus_name' => 'Flindersia','species_name' => 'brayleyana','common_name' => 'Queensland maple','growth_rate' => '','height_at_maturity' => '70'),
            array('id' => '3113','genus_name' => 'Flacourtia','species_name' => 'indica','common_name' => 'Governor\'s plum','growth_rate' => '','height_at_maturity' => '32'),
            array('id' => '3115','genus_name' => 'Flindersia','species_name' => 'maculosa','common_name' => 'Leopard-wood','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '3116','genus_name' => 'Flueggea','species_name' => 'neowawraea','common_name' => 'Mehamehame','growth_rate' => '','height_at_maturity' => '98'),
            array('id' => '3117','genus_name' => 'Floydia','species_name' => 'praealta','common_name' => 'Floydia','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '3118','genus_name' => 'Flacourtia','species_name' => 'rukam','common_name' => 'rukam','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '3119','genus_name' => 'Flindersia','species_name' => 'schottiana','common_name' => 'Cudgerie','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '3120','genus_name' => 'Forestiera','species_name' => 'acuminata','common_name' => 'Swamp privet','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '3121','genus_name' => 'Forestiera','species_name' => 'angustifolia','common_name' => 'Texas swampprivet','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '3123','genus_name' => 'Forestiera','species_name' => 'eggersiana','common_name' => 'Inkbush','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '3124','genus_name' => 'Fouquieria','species_name' => 'formosa','common_name' => 'Fouquieria formosa','growth_rate' => '','height_at_maturity' => '8'),
            array('id' => '3125','genus_name' => 'Fothergilla','species_name' => 'gardenii','common_name' => 'Dwarf witchalder','growth_rate' => 'Slow','height_at_maturity' => '3'),
            array('id' => '3126','genus_name' => 'Forestiera','species_name' => 'godfreyi','common_name' => 'Godfrey\'s swampprivet','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '3127','genus_name' => 'Forsythia','species_name' => 'x intermedia','common_name' => 'Showy forsythia','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '3128','genus_name' => 'Fortunella','species_name' => 'japonica','common_name' => 'Round kumquat','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '3129','genus_name' => 'Forestiera','species_name' => 'ligustrina','common_name' => 'Upland swampprivet','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '3130','genus_name' => 'Fothergilla','species_name' => 'major','common_name' => 'Mountain witchalder','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '3131','genus_name' => 'Fortunella','species_name' => 'margarita','common_name' => 'Oval kumquat','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '3132','genus_name' => 'Forsythia','species_name' => 'ovata','common_name' => 'Early forsythia','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '3135','genus_name' => 'Forestiera','species_name' => 'pubescens','common_name' => 'Stretchberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '3136','genus_name' => 'Forestiera','species_name' => 'reticulata','common_name' => 'Netleaf swampprivet','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '3137','genus_name' => 'Forestiera','species_name' => 'rhamnifolia','common_name' => 'Caca ravet','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '3138','genus_name' => 'Forestiera','species_name' => 'segregata','common_name' => 'Florida swampprivet','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '3139','genus_name' => 'Forestiera','species_name' => 'shrevei','common_name' => 'Desert olive','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '3140','genus_name' => 'Fouquieria','species_name' => 'splendens','common_name' => 'Ocotillo','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '3141','genus_name' => 'Forsythia','species_name' => 'suspensa','common_name' => 'Weeping forsythia','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '3142','genus_name' => 'Forsythia','species_name' => 'viridissima','common_name' => 'Greenstem forsythia','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '3144','genus_name' => 'Franklinia','species_name' => 'alatamaha','common_name' => 'Franklin tree','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '3145','genus_name' => 'Fraxinus','species_name' => 'americana','common_name' => 'White ash','growth_rate' => 'Moderate','height_at_maturity' => '90'),
            array('id' => '3146','genus_name' => 'Fraxinus','species_name' => 'americana Autumn Applause','common_name' => 'Autumn applause ash','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '3147','genus_name' => 'Fraxinus','species_name' => 'americana \'Autumn Purple\'','common_name' => 'Autumn purple ash','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '3148','genus_name' => 'Fraxinus','species_name' => 'americana \'Champaign County\'','common_name' => 'Champaign county ash','growth_rate' => '','height_at_maturity' => '45'),
            array('id' => '3149','genus_name' => 'Fraxinus','species_name' => 'americana \'Rosehill\'','common_name' => 'Rosehill ash','growth_rate' => '','height_at_maturity' => '42'),
            array('id' => '3150','genus_name' => 'Fraxinus','species_name' => 'anomala','common_name' => 'Singleleaf ash','growth_rate' => 'Fast','height_at_maturity' => '83'),
            array('id' => '3151','genus_name' => 'Fraxinus','species_name' => 'angustifolia','common_name' => 'Narrow-leafed ash','growth_rate' => 'Moderate','height_at_maturity' => '60'),
            array('id' => '3152','genus_name' => 'Fraxinus','species_name' => 'angustifolia ssp. angustifolia','common_name' => 'Desert ash','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '3154','genus_name' => 'Fraxinus','species_name' => 'berlandieriana','common_name' => 'Arizona ash','growth_rate' => 'Fast','height_at_maturity' => '83'),
            array('id' => '3157','genus_name' => 'Fraxinus','species_name' => 'caroliniana','common_name' => 'Carolina ash','growth_rate' => 'Moderate','height_at_maturity' => '39'),
            array('id' => '3158','genus_name' => 'Frangula','species_name' => 'californica','common_name' => 'California buckthorn','growth_rate' => '','height_at_maturity' => '16'),
            array('id' => '3159','genus_name' => 'Fremontodendron','species_name' => 'californicum','common_name' => 'California flannelbush','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '3160','genus_name' => 'Fraxinus','species_name' => 'chinensis','common_name' => 'Chinese ash','growth_rate' => 'Fast','height_at_maturity' => '83'),
            array('id' => '3161','genus_name' => 'Fraxinus','species_name' => 'cuspidata','common_name' => 'Fragrant ash','growth_rate' => 'Fast','height_at_maturity' => '83'),
            array('id' => '3162','genus_name' => 'Fremontodendron','species_name' => 'decumbens','common_name' => 'Pine hill flannelbush','growth_rate' => 'Moderate','height_at_maturity' => '24'),
            array('id' => '3163','genus_name' => 'Fraxinus','species_name' => 'dipetala','common_name' => 'California ash','growth_rate' => 'Fast','height_at_maturity' => '83'),
            array('id' => '3164','genus_name' => 'Fraxinus','species_name' => 'excelsior','common_name' => 'European ash','growth_rate' => 'Fast','height_at_maturity' => '63'),
            array('id' => '3166','genus_name' => 'Fraxinus','species_name' => 'excelsior \'Aurea\'','common_name' => 'Golden ash','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '3167','genus_name' => 'Fraxinus','species_name' => 'excelsior \'Hessei\'','common_name' => 'Hesse ash','growth_rate' => '','height_at_maturity' => '55'),
            array('id' => '3169','genus_name' => 'Fraxinus','species_name' => 'gooddingii','common_name' => 'Goodding\'s ash','growth_rate' => 'Fast','height_at_maturity' => '83'),
            array('id' => '3170','genus_name' => 'Fraxinus','species_name' => 'greggii','common_name' => 'Gregg ash','growth_rate' => 'Fast','height_at_maturity' => '83'),
            array('id' => '3171','genus_name' => 'Fraxinus','species_name' => 'griffithii','common_name' => 'Evergreen Ash','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '3172','genus_name' => 'Fraxinus','species_name' => 'holotricha','common_name' => 'Moraine ash','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '3173','genus_name' => 'Fraxinus','species_name' => 'latifolia','common_name' => 'Oregon ash','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '3177','genus_name' => 'Fremontodendron','species_name' => 'mexicanum','common_name' => 'Mexican flannelbush','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '3178','genus_name' => 'Fraxinus','species_name' => 'nigra','common_name' => 'Black ash','growth_rate' => 'Slow','height_at_maturity' => '65'),
            array('id' => '3179','genus_name' => 'Fraxinus','species_name' => 'ornus','common_name' => 'Flowering ash','growth_rate' => 'Slow','height_at_maturity' => '35'),
            array('id' => '3180','genus_name' => 'Fraxinus','species_name' => 'oxycarpa','common_name' => 'Caucasian ash','growth_rate' => 'Fast','height_at_maturity' => '83'),
            array('id' => '3182','genus_name' => 'Fraxinus','species_name' => 'oxycarpa \'Flame\'','common_name' => 'Flame ash','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '3183','genus_name' => 'Fraxinus','species_name' => 'papillosa','common_name' => 'Chihuahuan ash','growth_rate' => 'Fast','height_at_maturity' => '83'),
            array('id' => '3184','genus_name' => 'Fraxinus','species_name' => 'pennsylvanica','common_name' => 'Green ash','growth_rate' => 'Fast','height_at_maturity' => '80'),
            array('id' => '3185','genus_name' => 'Fraxinus','species_name' => 'pennsylvanica \'Marshall seedless\'','common_name' => 'Marshall ash','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '3186','genus_name' => 'Fraxinus','species_name' => 'pennsylvanica \'Patmore\'','common_name' => 'Patmore ash','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '3188','genus_name' => 'Fraxinus','species_name' => 'pennsylvanica \'Summit\'','common_name' => 'Summit ash','growth_rate' => '','height_at_maturity' => '55'),
            array('id' => '3189','genus_name' => 'Fraxinus','species_name' => 'profunda','common_name' => 'Pumpkin ash','growth_rate' => 'Fast','height_at_maturity' => '120'),
            array('id' => '3190','genus_name' => 'Fraxinus','species_name' => 'quadrangulata','common_name' => 'Blue ash','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '3194','genus_name' => 'Fraxinus','species_name' => 'texensis','common_name' => 'Texas ash','growth_rate' => 'Slow','height_at_maturity' => '38'),
            array('id' => '3195','genus_name' => 'Fraxinus','species_name' => 'uhdei','common_name' => 'Shamel ash','growth_rate' => 'Fast','height_at_maturity' => '43'),
            array('id' => '3196','genus_name' => 'Fraxinus','species_name' => 'velutina','common_name' => 'Velvet ash','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '3199','genus_name' => 'Furcraea','species_name' => 'andina','common_name' => 'Fique','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '3200','genus_name' => 'Fuchsia','species_name' => 'boliviana','common_name' => 'Bolivian fuchsia','growth_rate' => '','height_at_maturity' => '11'),
            array('id' => '3201','genus_name' => 'Funtumia','species_name' => 'elastica','common_name' => 'Silkrubber','growth_rate' => '','height_at_maturity' => '100'),
            array('id' => '3204','genus_name' => 'Fuchsia','species_name' => 'paniculata','common_name' => 'Shrubby fuchsia','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '3206','genus_name' => 'Gardenia','species_name' => 'augusta','common_name' => 'Cape jasmine','growth_rate' => 'Moderate','height_at_maturity' => '19'),
            array('id' => '3207','genus_name' => 'Gaussia','species_name' => 'attenuata','common_name' => 'Llume','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '3209','genus_name' => 'Gastrolobium','species_name' => 'bilobum','common_name' => 'Poison Pea','growth_rate' => 'Fast','height_at_maturity' => '4'),
            array('id' => '3210','genus_name' => 'Gardenia','species_name' => 'brighamii','common_name' => 'Forest gardenia','growth_rate' => 'Moderate','height_at_maturity' => '19'),
            array('id' => '3212','genus_name' => 'Garrya','species_name' => 'buxifolia','common_name' => 'Dwarf silktassel','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '3214','genus_name' => 'Garrya','species_name' => 'congdonii','common_name' => 'Chaparral silktassel','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '3215','genus_name' => 'Garcinia','species_name' => 'dulcis','common_name' => 'Gourka','growth_rate' => 'Moderate','height_at_maturity' => '58'),
            array('id' => '3216','genus_name' => 'Garrya','species_name' => 'elliptica','common_name' => 'Wavyleaf silktassel','growth_rate' => 'Moderate','height_at_maturity' => ''),
            array('id' => '3217','genus_name' => 'Ganophyllum','species_name' => 'falcatum','common_name' => 'Scaly Ash','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '3218','genus_name' => 'Garrya','species_name' => 'fadyenia','common_name' => 'Fadyen\'s silktassel','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '3219','genus_name' => 'Garrya','species_name' => 'flavescens','common_name' => 'Silktassel','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '3220','genus_name' => 'Garrya','species_name' => 'fremontii','common_name' => 'Silk tassle','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '3222','genus_name' => 'Gardenia','species_name' => 'fucata','common_name' => 'Gardenia fucata','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '3225','genus_name' => 'Garcinia','species_name' => 'hessii','common_name' => 'Lemon saptree','growth_rate' => 'Moderate','height_at_maturity' => '58'),
            array('id' => '3227','genus_name' => 'Garcinia','species_name' => 'madruno','common_name' => 'Charichuelo','growth_rate' => 'Slow','height_at_maturity' => '66'),
            array('id' => '3228','genus_name' => 'Garcinia','species_name' => 'mangostana','common_name' => 'Mangosteen','growth_rate' => 'Moderate','height_at_maturity' => '58'),
            array('id' => '3229','genus_name' => 'Gardenia','species_name' => 'mannii','common_name' => 'Oahu gardenia','growth_rate' => 'Moderate','height_at_maturity' => '19'),
            array('id' => '3230','genus_name' => 'Gardenia','species_name' => 'megasperma','common_name' => 'Bush Gardenia','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '3232','genus_name' => 'Garcinia','species_name' => 'myrtifolia','common_name' => 'garcinia','growth_rate' => '','height_at_maturity' => '65'),
            array('id' => '3235','genus_name' => 'Garrya','species_name' => 'ovata','common_name' => 'Eggleaf silktassel','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '3237','genus_name' => 'Garcinia','species_name' => 'portoricensis','common_name' => 'Palo de cruz','growth_rate' => 'Moderate','height_at_maturity' => '58'),
            array('id' => '3238','genus_name' => 'Gardenia','species_name' => 'remyi','common_name' => 'Remy\'s gardenia','growth_rate' => 'Moderate','height_at_maturity' => '19'),
            array('id' => '3240','genus_name' => 'Gardenia','species_name' => 'taitensis','common_name' => 'Tahitian gardenia','growth_rate' => 'Moderate','height_at_maturity' => '19'),
            array('id' => '3243','genus_name' => 'Garrya','species_name' => 'veatchii','common_name' => 'Canyon silktassel','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '3244','genus_name' => 'Garrya','species_name' => 'wrightii','common_name' => 'Wright\'s silktassel','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '3245','genus_name' => 'Garcinia','species_name' => 'xanthochymus','common_name' => 'False mangosteen','growth_rate' => '','height_at_maturity' => '16'),
            array('id' => '3246','genus_name' => 'Genista','species_name' => 'aetnensis','common_name' => 'Mt. Etna Broom','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '3247','genus_name' => 'Genipa','species_name' => 'americana','common_name' => 'Jagua','growth_rate' => '','height_at_maturity' => '65'),
            array('id' => '3249','genus_name' => 'Genista','species_name' => 'canariensis','common_name' => 'Canary broom','growth_rate' => 'Moderate','height_at_maturity' => '27'),
            array('id' => '3253','genus_name' => 'Geonoma','species_name' => 'interrupta','common_name' => 'Geonoma interrupta','growth_rate' => 'Slow','height_at_maturity' => '16'),
            array('id' => '3254','genus_name' => 'Geijera','species_name' => 'linearifolia','common_name' => 'Sheep bush','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '3255','genus_name' => 'Genista','species_name' => 'linifolia','common_name' => 'Mediterranean broom','growth_rate' => 'Moderate','height_at_maturity' => '27'),
            array('id' => '3256','genus_name' => 'Genista','species_name' => 'maderensis','common_name' => 'Madeira dyer\'s greenweed','growth_rate' => 'Moderate','height_at_maturity' => '27'),
            array('id' => '3257','genus_name' => 'Genista','species_name' => 'monspessulana','common_name' => 'French broom','growth_rate' => 'Moderate','height_at_maturity' => '27'),
            array('id' => '3259','genus_name' => 'Geijera','species_name' => 'parviflora','common_name' => 'Wilga; australian willow','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '3260','genus_name' => 'Gesneria','species_name' => 'pedunculosa','common_name' => 'Arbol de navidad','growth_rate' => 'Slow','height_at_maturity' => '13'),
            array('id' => '3262','genus_name' => 'Gelsemium','species_name' => 'sempervirens','common_name' => 'Evening trumpetflower','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3263','genus_name' => 'Genista','species_name' => 'stenopetala','common_name' => 'Leafy broom','growth_rate' => 'Moderate','height_at_maturity' => '27'),
            array('id' => '3264','genus_name' => 'Genista','species_name' => 'tinctoria','common_name' => 'Dyer\'s greenweed','growth_rate' => 'Moderate','height_at_maturity' => '27'),
            array('id' => '3266','genus_name' => 'Ginkgo','species_name' => 'biloba','common_name' => 'Ginkgo','growth_rate' => 'Slow','height_at_maturity' => '80'),
            array('id' => '3267','genus_name' => 'Ginkgo','species_name' => 'biloba \'Autumn Gold\'','common_name' => 'Ginkgo \'Autumn Gold\'','growth_rate' => '','height_at_maturity' => '45'),
            array('id' => '3268','genus_name' => 'Ginkgo','species_name' => 'biloba \'Fairmont\'','common_name' => 'Ginkgo \'Fairmont\'','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '3269','genus_name' => 'Ginkgo','species_name' => 'biloba \'Fastigiata\'','common_name' => 'Sentry ginkgo','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '3272','genus_name' => 'Gleditsia','species_name' => 'aquatica','common_name' => 'Water locust','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '3273','genus_name' => 'Gleditsia','species_name' => 'caspia','common_name' => 'Caspina honeylocust','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '3275','genus_name' => 'Glochidion','species_name' => 'ferdinandi','common_name' => 'Cheese Tree','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '3276','genus_name' => 'Gleditsia','species_name' => 'japonica','common_name' => 'Saikachi','growth_rate' => '','height_at_maturity' => '65'),
            array('id' => '3277','genus_name' => 'Glochidion','species_name' => 'marianum','common_name' => 'luwekienloal','growth_rate' => '','height_at_maturity' => '36'),
            array('id' => '3280','genus_name' => 'Glochidion','species_name' => 'phillppicum','common_name' => 'Little cheese tree','growth_rate' => 'Moderate','height_at_maturity' => ''),
            array('id' => '3281','genus_name' => 'Gliricidia','species_name' => 'sepium','common_name' => 'Quickstick','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '3282','genus_name' => 'Gleditsia','species_name' => 'x texana','common_name' => 'Texan locust','growth_rate' => '','height_at_maturity' => '77'),
            array('id' => '3284','genus_name' => 'Gleditsia','species_name' => 'triacanthos','common_name' => 'Honeylocust','growth_rate' => 'Fast','height_at_maturity' => '70'),
            array('id' => '3285','genus_name' => 'Gleditsia','species_name' => 'triacanthos v. inermis \'Imperial\'','common_name' => 'Imperial honeylocust','growth_rate' => '','height_at_maturity' => '35')
        );

        Tree::insert($trees);

        $seeder = new TreeSpeciesSeeder5;
        $seeder->run();
    }
}
