<?php

namespace Database\Seeders\TreeSpecies;

use App\Models\Tree\Tree;
use Illuminate\Database\Seeder;

class TreeSpeciesSeeder5 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $trees = array(
            array('id' => '3287','genus_name' => 'Gleditsia','species_name' => 'triacanthos v. inermis \'Shademaster\'','common_name' => 'Shademaster honeylocust','growth_rate' => '','height_at_maturity' => '55'),
            array('id' => '3288','genus_name' => 'Gleditsia','species_name' => 'triacanthos v. inermis \'Sunburst\'','common_name' => 'Sunburst honeylocust','growth_rate' => '','height_at_maturity' => '35'),
            array('id' => '3289','genus_name' => 'Gmelina','species_name' => 'arborea','common_name' => 'Gumhar','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '3290','genus_name' => 'Gmelina','species_name' => 'asiatica','common_name' => 'Asian bushbeech','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '3291','genus_name' => 'Gmelina','species_name' => 'leichardtii','common_name' => 'White Beech','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '3292','genus_name' => 'Gordonia','species_name' => 'axillaris','common_name' => 'Fired egg plant','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '3293','genus_name' => 'Gossypium','species_name' => 'barbadense','common_name' => 'Creole cotton','growth_rate' => '','height_at_maturity' => '5'),
            array('id' => '3295','genus_name' => 'Goetzea','species_name' => 'elegans','common_name' => 'Mata buey','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '3298','genus_name' => 'Gonzalagunia','species_name' => 'hirsuta','common_name' => 'Mata de mariposa','growth_rate' => 'Fast','height_at_maturity' => '13'),
            array('id' => '3300','genus_name' => 'Gordonia','species_name' => 'lasianthus','common_name' => 'Loblolly bay','growth_rate' => 'Slow','height_at_maturity' => '65'),
            array('id' => '3301','genus_name' => 'Gompholobium','species_name' => 'latifolium','common_name' => 'Giant Wedge-pea','growth_rate' => 'Fast','height_at_maturity' => '2'),
            array('id' => '3303','genus_name' => 'Goodia','species_name' => 'lotifolia','common_name' => 'Golden-tip','growth_rate' => 'Fast','height_at_maturity' => '3'),
            array('id' => '3312','genus_name' => 'Gordonia','species_name' => 'yunnanense \'Silk Screen\'','common_name' => 'Silk Screen Gordonia','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3313','genus_name' => 'Grevillea','species_name' => 'alpina','common_name' => 'Cat\'s Claws','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '3314','genus_name' => 'Grevillea','species_name' => 'angulata','common_name' => 'Holy Leaf Grevillea','growth_rate' => 'Fast','height_at_maturity' => '2'),
            array('id' => '3315','genus_name' => 'Grevillea','species_name' => 'arenaria','common_name' => 'Nepean Spider Flower','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '3316','genus_name' => 'Grevillea','species_name' => 'aspleniifolia','common_name' => 'Fern-leaf Grevillea','growth_rate' => 'Moderate','height_at_maturity' => '16'),
            array('id' => '3317','genus_name' => 'Grevillea','species_name' => 'aspera','common_name' => 'Rough Grevillea','growth_rate' => 'Moderate','height_at_maturity' => '2'),
            array('id' => '3318','genus_name' => 'Grevillea','species_name' => 'banksii','common_name' => 'Kahiliflower','growth_rate' => 'Fast','height_at_maturity' => '63'),
            array('id' => '3319','genus_name' => 'Grevillea','species_name' => 'baileyana','common_name' => 'Scrub Beefwood','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '3320','genus_name' => 'Grevillea','species_name' => 'barklyana','common_name' => 'Gully Grevillea','growth_rate' => 'Fast','height_at_maturity' => '8'),
            array('id' => '3321','genus_name' => 'Grewia','species_name' => 'biloba','common_name' => 'Bilobed grewia','growth_rate' => 'Moderate','height_at_maturity' => '19'),
            array('id' => '3323','genus_name' => 'Grevillea','species_name' => 'decurrens','common_name' => 'Red Grevillea','growth_rate' => 'Fast','height_at_maturity' => '5'),
            array('id' => '3324','genus_name' => 'Grevillea','species_name' => 'dimorpha','common_name' => 'Flame Grevillea','growth_rate' => 'Fast','height_at_maturity' => '1'),
            array('id' => '3325','genus_name' => 'Grevillea','species_name' => 'dryandri','common_name' => 'Dryander\'s Grevillea','growth_rate' => 'Fast','height_at_maturity' => '2'),
            array('id' => '3326','genus_name' => 'Grevillea','species_name' => 'dryophylla','common_name' => 'Goldfields Grevillea','growth_rate' => 'Fast','height_at_maturity' => '1'),
            array('id' => '3327','genus_name' => 'Grewia','species_name' => 'ferruginea','common_name' => 'Grewia ferruginea','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3328','genus_name' => 'Grevillea','species_name' => 'floribunda','common_name' => 'Seven dwarfs Grevillea','growth_rate' => 'Fast','height_at_maturity' => '2'),
            array('id' => '3329','genus_name' => 'Grevillea','species_name' => 'formosa','common_name' => 'Mt. Brockman Grevillea','growth_rate' => 'Fast','height_at_maturity' => ''),
            array('id' => '3330','genus_name' => 'Grevillea','species_name' => 'goodii ssp. pluricaulis','common_name' => 'Grevillea goodii pluricau','growth_rate' => 'Fast','height_at_maturity' => '3'),
            array('id' => '3331','genus_name' => 'Grevillea','species_name' => 'heliosperma','common_name' => 'Rock Grevillea','growth_rate' => 'Fast','height_at_maturity' => '7'),
            array('id' => '3332','genus_name' => 'Grevillea','species_name' => 'hilliana','common_name' => 'White Yiel Yiel','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '3333','genus_name' => 'Grevillea','species_name' => 'huegelii','common_name' => 'Comb Grevillea','growth_rate' => 'Fast','height_at_maturity' => '4'),
            array('id' => '3334','genus_name' => 'Grevillea','species_name' => 'ilicifolia','common_name' => 'Holly Grevillea','growth_rate' => 'Fast','height_at_maturity' => '2'),
            array('id' => '3335','genus_name' => 'Grevillea','species_name' => 'juniperina','common_name' => 'Prickly Grevillea','growth_rate' => 'Fast','height_at_maturity' => '2'),
            array('id' => '3336','genus_name' => 'Grevillea','species_name' => 'lanigera','common_name' => 'Woolly Grevillea','growth_rate' => 'Fast','height_at_maturity' => '2'),
            array('id' => '3339','genus_name' => 'Grevillea','species_name' => 'miqueliana','common_name' => 'Oval-leaf Grevillea','growth_rate' => 'Fast','height_at_maturity' => '2'),
            array('id' => '3340','genus_name' => 'Grevillea','species_name' => 'nematophylla','common_name' => 'Silver Leaved Water Bush','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '3341','genus_name' => 'Grevillea','species_name' => 'x Noellii','common_name' => 'Noel\'s Grevillea','growth_rate' => 'Fast','height_at_maturity' => '63'),
            array('id' => '3343','genus_name' => 'Grevillea','species_name' => 'parallela','common_name' => 'Silver Oak','growth_rate' => 'Fast','height_at_maturity' => '7'),
            array('id' => '3345','genus_name' => 'Grevillea','species_name' => 'pterosperma','common_name' => 'Desert Grevillea','growth_rate' => 'Fast','height_at_maturity' => '4'),
            array('id' => '3346','genus_name' => 'Grevillea','species_name' => 'ramosissima','common_name' => 'Branching Grevillea','growth_rate' => 'Fast','height_at_maturity' => '2'),
            array('id' => '3347','genus_name' => 'Grevillea','species_name' => 'refracta','common_name' => 'Silver-Leaf Grevillea','growth_rate' => 'Fast','height_at_maturity' => '5'),
            array('id' => '3348','genus_name' => 'Grevillea','species_name' => 'robusta','common_name' => 'Silk oak','growth_rate' => 'Fast','height_at_maturity' => '105'),
            array('id' => '3349','genus_name' => 'Grevillea','species_name' => 'rosmarinifolia','common_name' => 'Rosemary Grevillea','growth_rate' => 'Fast','height_at_maturity' => '2'),
            array('id' => '3350','genus_name' => 'Grevillea','species_name' => 'striata','common_name' => 'Beefwood','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '3351','genus_name' => 'Grevillea','species_name' => 'victoriae','common_name' => 'Royal Grevillea','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '3353','genus_name' => 'Guadua','species_name' => 'angustifolia','common_name' => 'Guadua mansa','growth_rate' => 'Fast','height_at_maturity' => '66'),
            array('id' => '3359','genus_name' => 'Guapira','species_name' => 'discolor','common_name' => 'Beeftree','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '3362','genus_name' => 'Guapira','species_name' => 'fragrans','common_name' => 'Black mampoo','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '3363','genus_name' => 'Guapira','species_name' => 'globosa','common_name' => 'Roundleaf blolly','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '3365','genus_name' => 'Guarea','species_name' => 'guidonia','common_name' => 'American muskwood','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '3370','genus_name' => 'Guamia','species_name' => 'mariannae','common_name' => 'paipai','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '3372','genus_name' => 'Guapira','species_name' => 'obtusata','common_name' => 'Corcho prieto','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '3374','genus_name' => 'Guaiacum','species_name' => 'officinale','common_name' => 'Roughbark lignum-vitae','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '3378','genus_name' => 'Guaiacum','species_name' => 'sanctum','common_name' => 'Lignum-vitae','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '3380','genus_name' => 'Guioa','species_name' => 'semiglauca','common_name' => 'Guoia','growth_rate' => 'Moderate','height_at_maturity' => '82'),
            array('id' => '3381','genus_name' => 'Guettarda','species_name' => 'speciosa','common_name' => 'beach gardenia','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '3382','genus_name' => 'Guazuma','species_name' => 'ulmifolia','common_name' => 'Guacima','growth_rate' => '','height_at_maturity' => '45'),
            array('id' => '3384','genus_name' => 'Gyrocarpus','species_name' => 'americanus','common_name' => 'Volador','growth_rate' => 'Fast','height_at_maturity' => '72'),
            array('id' => '3385','genus_name' => 'Gymnocladus','species_name' => 'dioicus','common_name' => 'Kentucky coffeetree','growth_rate' => 'Slow','height_at_maturity' => '100'),
            array('id' => '3388','genus_name' => 'Gymnostoma','species_name' => 'papuanum','common_name' => 'Papuan She-Oak','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '3391','genus_name' => 'Hamelia','species_name' => 'axillaris','common_name' => 'Balsamillo','growth_rate' => 'Fast','height_at_maturity' => '18'),
            array('id' => '3392','genus_name' => 'Haematoxylum','species_name' => 'brasiletto','common_name' => 'Brasil','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '3393','genus_name' => 'Halesia','species_name' => 'carolina','common_name' => 'Snowdrop tree','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '3394','genus_name' => 'Harpephyllum','species_name' => 'caffrum','common_name' => 'Wild Plum','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '3395','genus_name' => 'Haematoxylum','species_name' => 'campechianum','common_name' => 'Bloodwoodtree','growth_rate' => '','height_at_maturity' => '21'),
            array('id' => '3396','genus_name' => 'Harpephyllum','species_name' => 'carolina','common_name' => 'Kaffir plum','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '3400','genus_name' => 'Hakea','species_name' => 'dactyloides','common_name' => 'Finger Hakea','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '3402','genus_name' => 'Halesia','species_name' => 'diptera','common_name' => 'Two-wing silverbell','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '3403','genus_name' => 'Hakea','species_name' => 'divaricata','common_name' => 'Fork-Leaved Corkwood','growth_rate' => 'Slow','height_at_maturity' => '7'),
            array('id' => '3404','genus_name' => 'Hakea','species_name' => 'eriantha','common_name' => 'Tree Hakea','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '3405','genus_name' => 'Hakea','species_name' => 'francisiana','common_name' => 'Grass-leaf Hakea','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '3409','genus_name' => 'Hakea','species_name' => 'leucoptera','common_name' => 'Silver Needlewood','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '3410','genus_name' => 'Hakea','species_name' => 'lissosperma','common_name' => 'Mountain Needlewood','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '3411','genus_name' => 'Hakea','species_name' => 'lorea','common_name' => 'Long Leaf Corkwood','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '3412','genus_name' => 'Hakea','species_name' => 'macraeana','common_name' => 'Macrae\'s Hakea','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '3413','genus_name' => 'Hakea','species_name' => 'microcarpa','common_name' => 'Small-fruited Hakea','growth_rate' => 'Moderate','height_at_maturity' => '2'),
            array('id' => '3414','genus_name' => 'Hakea','species_name' => 'mitchellii','common_name' => 'Desert Hakea','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '3415','genus_name' => 'Hamamelis','species_name' => 'mollis','common_name' => 'Chinese witchhazel','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '3416','genus_name' => 'Hakea','species_name' => 'nodosa','common_name' => 'Yellow Hakea','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '3419','genus_name' => 'Hamelia','species_name' => 'patens','common_name' => 'Scarletbush','growth_rate' => 'Fast','height_at_maturity' => '11'),
            array('id' => '3420','genus_name' => 'Hakea','species_name' => 'petiolaris','common_name' => 'Sea Urchin Hakea','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '3421','genus_name' => 'Harpullia','species_name' => 'pendula','common_name' => 'Tulipwood','growth_rate' => 'Moderate','height_at_maturity' => '82'),
            array('id' => '3423','genus_name' => 'Hakea','species_name' => 'rostrata','common_name' => 'Beaked Hakea','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '3424','genus_name' => 'Hakea','species_name' => 'rugosa','common_name' => 'Dwarf Hakea','growth_rate' => 'Moderate','height_at_maturity' => '2'),
            array('id' => '3425','genus_name' => 'Hakea','species_name' => 'salicifolia','common_name' => 'Willow-leaved hakea','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '3427','genus_name' => 'Hakea','species_name' => 'sericea','common_name' => 'Needlebush','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '3428','genus_name' => 'Hakea','species_name' => 'suaveolens','common_name' => 'Sweet hakea','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '3429','genus_name' => 'Hakea','species_name' => 'tephrosperma','common_name' => 'Hooked Needlewood','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '3430','genus_name' => 'Hakea','species_name' => 'teretifolia','common_name' => 'Dagger Hakea','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '3431','genus_name' => 'Halesia','species_name' => 'tetraptera','common_name' => 'Mountain silverbell','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '3432','genus_name' => 'Hakea','species_name' => 'ulicina','common_name' => 'Furze Hakea','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '3434','genus_name' => 'Hamamelis','species_name' => 'vernalis','common_name' => 'Ozark witchhazel','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '3435','genus_name' => 'Hamamelis','species_name' => 'virginiana','common_name' => 'Witch hazel','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '3437','genus_name' => 'Hedycarya','species_name' => 'angustfolia','common_name' => 'Austral Mulberry','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '3438','genus_name' => 'Heteromeles','species_name' => 'arbutifolia','common_name' => 'Toyon','growth_rate' => 'Moderate','height_at_maturity' => '11'),
            array('id' => '3439','genus_name' => 'Hesperomannia','species_name' => 'arbuscula','common_name' => 'Maui island-aster','growth_rate' => '','height_at_maturity' => '9'),
            array('id' => '3441','genus_name' => 'Hesperomannia','species_name' => 'arborescens','common_name' => 'Lanai island-aster','growth_rate' => '','height_at_maturity' => '11'),
            array('id' => '3443','genus_name' => 'Hevea','species_name' => 'brasiliensis','common_name' => 'para rubber tree','growth_rate' => '','height_at_maturity' => '100'),
            array('id' => '3449','genus_name' => 'Heliocarpus','species_name' => 'donnellsmithii','common_name' => 'Heliocarpus donnellsmithii','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '3450','genus_name' => 'Heterospathe','species_name' => 'elata','common_name' => 'sagasi palm','growth_rate' => '','height_at_maturity' => '45'),
            array('id' => '3454','genus_name' => 'Hedyotis','species_name' => 'fosbergii','common_name' => 'Fosberg\'s starviolet','growth_rate' => '','height_at_maturity' => '7'),
            array('id' => '3457','genus_name' => 'Hedera','species_name' => 'helix','common_name' => 'English ivy','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '3458','genus_name' => 'Hemiptelea','species_name' => 'davidii','common_name' => 'Thorn-elm','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '3459','genus_name' => 'Hedyotis','species_name' => 'hillebrandii','common_name' => 'Manono','growth_rate' => '','height_at_maturity' => '13'),
            array('id' => '3460','genus_name' => 'Helicteres','species_name' => 'jamaicensis','common_name' => 'Screwtree','growth_rate' => 'Fast','height_at_maturity' => '22'),
            array('id' => '3464','genus_name' => 'Heritiera','species_name' => 'longipetiolata','common_name' => 'ufa halemtano','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '3465','genus_name' => 'Hesperomannia','species_name' => 'lydgatei','common_name' => 'Kauai island-aster','growth_rate' => '','height_at_maturity' => '8'),
            array('id' => '3473','genus_name' => 'Heliocarpus','species_name' => 'popayanensis','common_name' => 'White moho','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '3479','genus_name' => 'Heliocarpus','species_name' => 'terebinthinaceus','common_name' => 'Heliocarpus terebinthinaceus','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '3480','genus_name' => 'Hedyotis','species_name' => 'terminalis','common_name' => 'Variable starviolet','growth_rate' => '','height_at_maturity' => '26'),
            array('id' => '3482','genus_name' => 'Hibiscus','species_name' => 'arnottianus','common_name' => 'White rosemallow','growth_rate' => 'Fast','height_at_maturity' => '63'),
            array('id' => '3484','genus_name' => 'Hibiscus','species_name' => 'brackenridgei','common_name' => 'Brackenridge\'s rosemallow','growth_rate' => 'Fast','height_at_maturity' => '63'),
            array('id' => '3485','genus_name' => 'Hibiscus','species_name' => 'calyphyllus','common_name' => 'Lemonyellow rosemallow','growth_rate' => 'Fast','height_at_maturity' => '63'),
            array('id' => '3486','genus_name' => 'Hibiscus','species_name' => 'clayi','common_name' => 'Red kauai rosemallow','growth_rate' => 'Fast','height_at_maturity' => '63'),
            array('id' => '3487','genus_name' => 'Hibiscus','species_name' => 'clypeatus','common_name' => 'Congo mahoe','growth_rate' => 'Fast','height_at_maturity' => '63'),
            array('id' => '3488','genus_name' => 'Hibiscadelphus','species_name' => 'crucibracteatus','common_name' => 'Lava hau kuahiwi','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '3489','genus_name' => 'Hibiscadelphus','species_name' => 'distans','common_name' => 'Kauai hau kuahiwi','growth_rate' => '','height_at_maturity' => '16'),
            array('id' => '3490','genus_name' => 'Hibiscus','species_name' => 'elatus','common_name' => 'Mahoe','growth_rate' => 'Fast','height_at_maturity' => '82'),
            array('id' => '3491','genus_name' => 'Hibiscadelphus','species_name' => 'giffardianus','common_name' => 'Kilauea hau kuahiwi','growth_rate' => '','height_at_maturity' => '23'),
            array('id' => '3492','genus_name' => 'Hibiscus','species_name' => 'grandiflorus','common_name' => 'Swamp rosemallow','growth_rate' => 'Fast','height_at_maturity' => '63'),
            array('id' => '3493','genus_name' => 'Hibiscus','species_name' => 'heterophyllus','common_name' => 'Native Rosella','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '3494','genus_name' => 'Hibiscadelphus','species_name' => 'hualalaiensis','common_name' => 'Hualalai hau kuahiwi','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '3495','genus_name' => 'Hibiscus','species_name' => 'kokio','common_name' => 'Red rosemallow','growth_rate' => 'Fast','height_at_maturity' => '23'),
            array('id' => '3496','genus_name' => 'Hippomane','species_name' => 'mancinella','common_name' => 'Manchineel','growth_rate' => '','height_at_maturity' => '66'),
            array('id' => '3497','genus_name' => 'Hibiscus','species_name' => 'macrophyllus','common_name' => 'Largeleaf rosemallow','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '3498','genus_name' => 'Hibiscus','species_name' => 'moscheutos','common_name' => 'Rose mallow hibiscus','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '3499','genus_name' => 'Hibiscus','species_name' => 'mutabilis','common_name' => 'Dixie rosemallow','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '3501','genus_name' => 'Hibiscus','species_name' => 'pernambucensis','common_name' => 'Seaside mahoe','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '3504','genus_name' => 'Hippophae','species_name' => 'rhamnoides','common_name' => 'Seabuckthorn','growth_rate' => 'Fast','height_at_maturity' => '18'),
            array('id' => '3507','genus_name' => 'Hibiscus','species_name' => 'splendens','common_name' => 'Pink Hibiscus','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '3508','genus_name' => 'Hibiscus','species_name' => 'syriacus','common_name' => 'Rose-of-sharon','growth_rate' => 'Fast','height_at_maturity' => '63'),
            array('id' => '3509','genus_name' => 'Hibiscus','species_name' => 'tiliaceus','common_name' => 'Sea hibiscus','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '3510','genus_name' => 'Hibiscus','species_name' => 'tiliaceus var rubra','common_name' => 'Red Beach Hibiscus','growth_rate' => 'Fast','height_at_maturity' => '8'),
            array('id' => '3512','genus_name' => 'Hibiscus','species_name' => 'vitifolius','common_name' => 'Tropical rose mallow','growth_rate' => 'Fast','height_at_maturity' => '63'),
            array('id' => '3513','genus_name' => 'Hibiscus','species_name' => 'waimeae','common_name' => 'White kauai rosemallow','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '3514','genus_name' => 'Hibiscadelphus','species_name' => 'wilderianus','common_name' => 'Maui hau kuahiwi','growth_rate' => '','height_at_maturity' => '16'),
            array('id' => '3515','genus_name' => 'Hibiscadelphus','species_name' => 'woodii','common_name' => 'Wood\'s hau kuahiwi','growth_rate' => '','height_at_maturity' => '13'),
            array('id' => '3516','genus_name' => 'Horsfieldia','species_name' => 'amklaal','common_name' => 'emeklachel','growth_rate' => '','height_at_maturity' => '21'),
            array('id' => '3517','genus_name' => 'Horsfieldia','species_name' => 'australiana','common_name' => 'Nut Horsfieldia','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '3518','genus_name' => 'Howea','species_name' => 'belmoreana','common_name' => 'Curly Palm','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '3520','genus_name' => 'Hovenia','species_name' => 'dulcis','common_name' => 'Japanese raisin tree','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '3522','genus_name' => 'Howea','species_name' => 'forsteriana','common_name' => 'Kentia palm','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '3524','genus_name' => 'Hoheria','species_name' => 'lyallii','common_name' => 'Mountain Ribbonwood','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '3525','genus_name' => 'Horsfieldia','species_name' => 'nunu','common_name' => 'nunu','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '3527','genus_name' => 'Horsfieldia','species_name' => 'palauensis','common_name' => 'chersachel','growth_rate' => '','height_at_maturity' => '21'),
            array('id' => '3528','genus_name' => 'Hoheria','species_name' => 'populnea','common_name' => 'Houhere','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '3529','genus_name' => 'Hoheria','species_name' => 'populnea \'Albal Variegata\'','common_name' => 'Variegated Houhere','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '3532','genus_name' => 'Hura','species_name' => 'crepitans','common_name' => 'Possumwood','growth_rate' => 'Fast','height_at_maturity' => '70'),
            array('id' => '3533','genus_name' => 'Hura','species_name' => 'polyandra','common_name' => 'Sandbox tree','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '3535','genus_name' => 'Hyophorbe','species_name' => 'amaricaulis','common_name' => 'Loneliest palm','growth_rate' => 'Moderate','height_at_maturity' => ''),
            array('id' => '3536','genus_name' => 'Hypericum','species_name' => 'androsaemum','common_name' => 'Sweet amber','growth_rate' => 'Fast','height_at_maturity' => '3'),
            array('id' => '3537','genus_name' => 'Hydnocarpus','species_name' => 'anthelminthicus','common_name' => 'Hydnocarpus anthelminthicus','growth_rate' => '','height_at_maturity' => '82'),
            array('id' => '3538','genus_name' => 'Hydrangea','species_name' => 'arborescens','common_name' => 'Wild hydrangea','growth_rate' => 'Fast','height_at_maturity' => '5'),
            array('id' => '3542','genus_name' => 'Hyeronima','species_name' => 'clusioides','common_name' => 'Cedro macho','growth_rate' => 'Slow','height_at_maturity' => '60'),
            array('id' => '3543','genus_name' => 'Hymenaea','species_name' => 'courbaril','common_name' => 'Courbaril','growth_rate' => 'Slow','height_at_maturity' => '65'),
            array('id' => '3544','genus_name' => 'Hypericum','species_name' => 'densiflorum','common_name' => 'Bushy st. johnswort','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '3552','genus_name' => 'Hypericum','species_name' => 'kalmianum','common_name' => 'Kalm\'s st. johnswort','growth_rate' => '','height_at_maturity' => '3'),
            array('id' => '3553','genus_name' => 'Hyophorbe','species_name' => 'lagenicaulis','common_name' => 'Bottle palm','growth_rate' => '','height_at_maturity' => '16'),
            array('id' => '3554','genus_name' => 'Hyperbaena','species_name' => 'laurifolia','common_name' => 'Limestone snakevine','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '3558','genus_name' => 'Hydrangea','species_name' => 'macrophylla','common_name' => 'French hydrangea','growth_rate' => 'Fast','height_at_maturity' => '9'),
            array('id' => '3564','genus_name' => 'Hydrangea','species_name' => 'paniculata','common_name' => 'Panicled hydrangea','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '3565','genus_name' => 'Hypericum','species_name' => 'prolificum','common_name' => 'Shrubby st. johnswort','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '3566','genus_name' => 'Hydrangea','species_name' => 'quercifolia','common_name' => 'Oakleaf hydrangea','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '3568','genus_name' => 'Hypericum','species_name' => 'revolutum','common_name' => 'Curry bush','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '3570','genus_name' => 'Hydrangea','species_name' => 'serrata','common_name' => 'mountain hydrangea','growth_rate' => '','height_at_maturity' => '4'),
            array('id' => '3572','genus_name' => 'Hypelate','species_name' => 'trifoliata','common_name' => 'Inkwood','growth_rate' => '','height_at_maturity' => '26'),
            array('id' => '3574','genus_name' => 'Hyophorbe','species_name' => 'verschaffeltii','common_name' => 'Spindle palm','growth_rate' => '','height_at_maturity' => '22'),
            array('id' => '3575','genus_name' => 'Hydriastele','species_name' => 'wendlandiana','common_name' => 'Florence Falls Palm','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '3576','genus_name' => 'Ilex','species_name' => 'x altaclarensis','common_name' => 'Wilson holly','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '3577','genus_name' => 'Ilex','species_name' => 'ambigua','common_name' => 'Carolina holly','growth_rate' => 'Slow','height_at_maturity' => '46'),
            array('id' => '3578','genus_name' => 'Ilex','species_name' => 'amelanchier','common_name' => 'Sarvis holly','growth_rate' => 'Slow','height_at_maturity' => '16'),
            array('id' => '3579','genus_name' => 'Ilex','species_name' => 'anomala','common_name' => 'Hawai\'i holly','growth_rate' => 'Slow','height_at_maturity' => '46'),
            array('id' => '3580','genus_name' => 'Illicium','species_name' => 'anisatum','common_name' => 'Japanese Staranise','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '3581','genus_name' => 'Ilex','species_name' => 'aquifolium','common_name' => 'English holly','growth_rate' => 'Slow','height_at_maturity' => '38'),
            array('id' => '3582','genus_name' => 'Ilex','species_name' => 'x attenuata','common_name' => 'Topal holly','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '3583','genus_name' => 'Ilex','species_name' => 'cassine','common_name' => 'Dahoon','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '3584','genus_name' => 'Ilex','species_name' => 'coriacea','common_name' => 'Large gallberry','growth_rate' => 'Slow','height_at_maturity' => '46'),
            array('id' => '3585','genus_name' => 'Ilex','species_name' => 'cornuta','common_name' => 'Chinese holly','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '3586','genus_name' => 'Ilex','species_name' => 'cookii','common_name' => 'Te','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '3587','genus_name' => 'Ilex','species_name' => 'crenata','common_name' => 'Japanese holly','growth_rate' => 'Slow','height_at_maturity' => '46'),
            array('id' => '3588','genus_name' => 'Ilex','species_name' => 'cuthbertii','common_name' => 'Cuthbert\'s holly','growth_rate' => 'Slow','height_at_maturity' => '46'),
            array('id' => '3589','genus_name' => 'Ilex','species_name' => 'decidua','common_name' => 'Possum haw','growth_rate' => 'Slow','height_at_maturity' => '18'),
            array('id' => '3590','genus_name' => 'Illicium','species_name' => 'floridanum','common_name' => 'Florida anisetree','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '3591','genus_name' => 'Ilex','species_name' => 'glabra','common_name' => 'Inkberry','growth_rate' => 'Slow','height_at_maturity' => '46'),
            array('id' => '3592','genus_name' => 'Ilex','species_name' => 'guianensis','common_name' => 'Maconcona','growth_rate' => 'Slow','height_at_maturity' => '46'),
            array('id' => '3593','genus_name' => 'Ilex','species_name' => 'hypaneura','common_name' => 'Luquillo mountain holly','growth_rate' => 'Slow','height_at_maturity' => '46'),
            array('id' => '3594','genus_name' => 'Ilex','species_name' => 'krugiana','common_name' => 'Tawnyberry holly','growth_rate' => 'Slow','height_at_maturity' => '46'),
            array('id' => '3595','genus_name' => 'Ilex','species_name' => 'laevigata','common_name' => 'Smooth winterberry','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '3597','genus_name' => 'Ilex','species_name' => 'longipes','common_name' => 'Georgia holly','growth_rate' => 'Slow','height_at_maturity' => '46'),
            array('id' => '3598','genus_name' => 'Ilex','species_name' => 'macfadyenii','common_name' => 'Caribbean holly','growth_rate' => 'Slow','height_at_maturity' => '46'),
            array('id' => '3599','genus_name' => 'Ilex','species_name' => 'montana','common_name' => 'Mountain winterberry','growth_rate' => 'Slow','height_at_maturity' => '46'),
            array('id' => '3600','genus_name' => 'Ilex','species_name' => 'myrtifolia','common_name' => 'Myrtle dahoon','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '3601','genus_name' => 'Ilex','species_name' => 'nitida','common_name' => 'Puerto rico holly','growth_rate' => 'Slow','height_at_maturity' => '40'),
            array('id' => '3602','genus_name' => 'Ilex','species_name' => 'opaca','common_name' => 'American holly','growth_rate' => 'Slow','height_at_maturity' => '40'),
            array('id' => '3603','genus_name' => 'Ilex','species_name' => 'x attenuata \'Savannah\'','common_name' => 'Savannah holly','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '3604','genus_name' => 'Illicium','species_name' => 'parviflorum','common_name' => 'Yellow anisetree','growth_rate' => 'Moderate','height_at_maturity' => '21'),
            array('id' => '3605','genus_name' => 'Ilex','species_name' => 'paraguayensis','common_name' => 'Paraguay tea','growth_rate' => 'Slow','height_at_maturity' => '60'),
            array('id' => '3606','genus_name' => 'Ilex','species_name' => 'purpurea','common_name' => 'Java Holly','growth_rate' => 'Fast','height_at_maturity' => '12'),
            array('id' => '3608','genus_name' => 'Ilex','species_name' => 'sideroxyloides','common_name' => 'Gongolin','growth_rate' => 'Slow','height_at_maturity' => '46'),
            array('id' => '3609','genus_name' => 'Ilex','species_name' => 'sintenisii','common_name' => 'Sintenis\' holly','growth_rate' => 'Slow','height_at_maturity' => '46'),
            array('id' => '3610','genus_name' => 'Ilex','species_name' => 'urbaniana','common_name' => 'Urban\'s holly','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '3611','genus_name' => 'Ilex','species_name' => 'verticillata','common_name' => 'Common winterberry','growth_rate' => 'Moderate','height_at_maturity' => '46'),
            array('id' => '3612','genus_name' => 'Ilex','species_name' => 'vomitoria','common_name' => 'Yaupon','growth_rate' => 'Slow','height_at_maturity' => '17'),
            array('id' => '3613','genus_name' => 'Indigofera','species_name' => 'australis','common_name' => 'Austral Indigo','growth_rate' => 'Moderate','height_at_maturity' => '2'),
            array('id' => '3614','genus_name' => 'Intsia','species_name' => 'bijuga','common_name' => 'ipil','growth_rate' => 'Slow','height_at_maturity' => '160'),
            array('id' => '3618','genus_name' => 'Inocarpus','species_name' => 'fagifer','common_name' => 'tahitian chestnut','growth_rate' => '','height_at_maturity' => '65'),
            array('id' => '3620','genus_name' => 'Inga','species_name' => 'ingoides','common_name' => 'Icecream bean','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '3621','genus_name' => 'Indigofera','species_name' => 'kirilowii','common_name' => 'Kirilow\'s indigo','growth_rate' => '','height_at_maturity' => '3'),
            array('id' => '3622','genus_name' => 'Inga','species_name' => 'laurina','common_name' => 'Sweetpea','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '3623','genus_name' => 'Inga','species_name' => 'marginata','common_name' => 'Inga-feijao','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '3624','genus_name' => 'Inga','species_name' => 'nobilis','common_name' => 'Guama venezolano','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '3625','genus_name' => 'Inga','species_name' => 'paterno','common_name' => 'Paterno','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3627','genus_name' => 'Inga','species_name' => 'spectabilis','common_name' => 'Ice cream bean','growth_rate' => 'Fast','height_at_maturity' => '46'),
            array('id' => '3630','genus_name' => 'Inga','species_name' => 'uraguensis','common_name' => 'Iganzeiro','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '3631','genus_name' => 'Inga','species_name' => 'vera','common_name' => 'River koko','growth_rate' => 'Fast','height_at_maturity' => '47'),
            array('id' => '3632','genus_name' => 'Ipomoea','species_name' => 'arborescens','common_name' => 'Tree morning glory','growth_rate' => 'Fast','height_at_maturity' => '4'),
            array('id' => '3633','genus_name' => 'Ipomoea','species_name' => 'carnea fistulosa','common_name' => 'Bush morning glory','growth_rate' => '','height_at_maturity' => '3'),
            array('id' => '3634','genus_name' => 'Ipomoea','species_name' => 'murucoides','common_name' => 'Foolish dove','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '3637','genus_name' => 'Isertia','species_name' => 'haenkeana','common_name' => 'Firecracker plant','growth_rate' => 'Moderate','height_at_maturity' => '16'),
            array('id' => '3643','genus_name' => 'Itea','species_name' => 'ilicifolia','common_name' => 'Hollyleaf Sweetspire','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '3644','genus_name' => 'Itea','species_name' => 'virginica','common_name' => 'Virginia sweetspire','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '3648','genus_name' => 'Ixora','species_name' => 'ferrea','common_name' => 'Palo de hierro','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '3657','genus_name' => 'Jatropha','species_name' => 'curcas','common_name' => 'Barbados nut','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '3658','genus_name' => 'Jacksonia','species_name' => 'dilatata','common_name' => 'Jacksonia','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '3659','genus_name' => 'Jatropha','species_name' => 'dioica','common_name' => 'Leatherstem','growth_rate' => 'Moderate','height_at_maturity' => '2'),
            array('id' => '3660','genus_name' => 'Jatropha','species_name' => 'gossypiifolia','common_name' => 'Bellyache bush','growth_rate' => 'Fast','height_at_maturity' => '13'),
            array('id' => '3662','genus_name' => 'Jatropha','species_name' => 'integerrima','common_name' => 'Peregrina','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '3663','genus_name' => 'Jacquinia','species_name' => 'keyensis','common_name' => 'Joewood','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '3665','genus_name' => 'Jacaranda','species_name' => 'mimosifolia','common_name' => 'Blue jacaranda','growth_rate' => 'Fast','height_at_maturity' => '43'),
            array('id' => '3669','genus_name' => 'Jasminum','species_name' => 'nudiflorum','common_name' => 'Winter jasmine','growth_rate' => 'Fast','height_at_maturity' => '12'),
            array('id' => '3670','genus_name' => 'Jasminum','species_name' => 'officinale','common_name' => 'Poet\'s jasmine','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '3673','genus_name' => 'Jagera','species_name' => 'pseudorhus','common_name' => 'Foambark','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '3675','genus_name' => 'Jacksonia','species_name' => 'scoparia','common_name' => 'Dogwood','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '3676','genus_name' => 'Jacaratia','species_name' => 'spinosa','common_name' => 'wild papaya','growth_rate' => '','height_at_maturity' => '98'),
            array('id' => '3680','genus_name' => 'Juglans','species_name' => 'ailanthifolia','common_name' => 'Japanese walnut','growth_rate' => 'Moderate','height_at_maturity' => '86'),
            array('id' => '3681','genus_name' => 'Juglans','species_name' => 'ailantifolia','common_name' => 'Juglans ailantifolia','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '3682','genus_name' => 'Juniperus','species_name' => 'ashei','common_name' => 'Ashe juniper','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '3683','genus_name' => 'Juglans','species_name' => 'x bixbyi','common_name' => 'Bixby walnut','growth_rate' => 'Moderate','height_at_maturity' => '86'),
            array('id' => '3685','genus_name' => 'Juniperus','species_name' => 'californica','common_name' => 'California juniper','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '3686','genus_name' => 'Juglans','species_name' => 'californica','common_name' => 'Southern California walnut','growth_rate' => 'Moderate','height_at_maturity' => '86'),
            array('id' => '3689','genus_name' => 'Juniperus','species_name' => 'chinensis','common_name' => 'Chinese juniper','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '3690','genus_name' => 'Jubaea','species_name' => 'chilensis','common_name' => 'Chilean Wine Palm','growth_rate' => 'Moderate','height_at_maturity' => '82'),
            array('id' => '3691','genus_name' => 'Juniperus','species_name' => 'chinensis \'Aurea\'','common_name' => 'Golden Chinese Juniper','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '3693','genus_name' => 'Juniperus','species_name' => 'chinensis \'Torulosa\'','common_name' => 'Hollywood juniper','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '3694','genus_name' => 'Juglans','species_name' => 'cinerea','common_name' => 'Butternut','growth_rate' => 'Fast','height_at_maturity' => '80'),
            array('id' => '3695','genus_name' => 'Juniperus','species_name' => 'communis','common_name' => 'Common juniper','growth_rate' => 'Slow','height_at_maturity' => '41'),
            array('id' => '3696','genus_name' => 'Juniperus','species_name' => 'communis v. suecica','common_name' => 'Swedish Juniper','growth_rate' => 'Slow','height_at_maturity' => '7'),
            array('id' => '3697','genus_name' => 'Juniperus','species_name' => 'coahuilensis','common_name' => 'Redberry juniper','growth_rate' => 'Slow','height_at_maturity' => '27'),
            array('id' => '3698','genus_name' => 'Juniperus','species_name' => 'conferta','common_name' => 'Shore juniper','growth_rate' => 'Slow','height_at_maturity' => '41'),
            array('id' => '3699','genus_name' => 'Juniperus','species_name' => 'deppeana','common_name' => 'Alligator juniper','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '3700','genus_name' => 'Juniperus','species_name' => 'drupacea','common_name' => 'Syrian Juniper','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '3701','genus_name' => 'Juniperus','species_name' => 'excelsa','common_name' => 'Junipero','growth_rate' => 'Slow','height_at_maturity' => '82'),
            array('id' => '3702','genus_name' => 'Juniperus','species_name' => 'flaccida','common_name' => 'Drooping juniper','growth_rate' => 'Slow','height_at_maturity' => '41'),
            array('id' => '3703','genus_name' => 'Juniperus','species_name' => 'formosana','common_name' => 'Formosan juniper','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '3704','genus_name' => 'Juglans','species_name' => 'hindsii','common_name' => 'Hind walnut','growth_rate' => 'Moderate','height_at_maturity' => '77'),
            array('id' => '3705','genus_name' => 'Juglans','species_name' => 'x intermedia','common_name' => 'Intermediate walnut','growth_rate' => 'Moderate','height_at_maturity' => '86'),
            array('id' => '3706','genus_name' => 'Juglans','species_name' => 'jamaicensis','common_name' => 'West indian walnut','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '3707','genus_name' => 'Juglans','species_name' => 'major','common_name' => 'Arizona walnut','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '3708','genus_name' => 'Juglans','species_name' => 'mandshurica','common_name' => 'Manchurain walnut','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '3709','genus_name' => 'Juglans','species_name' => 'microcarpa','common_name' => 'Little walnut','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '3710','genus_name' => 'Juniperus','species_name' => 'monosperma','common_name' => 'One seed juniper','growth_rate' => 'Slow','height_at_maturity' => '41'),
            array('id' => '3711','genus_name' => 'Juniperus','species_name' => 'monticola','common_name' => 'Mexican juniper','growth_rate' => '','height_at_maturity' => '4'),
            array('id' => '3712','genus_name' => 'Juglans','species_name' => 'mollis','common_name' => 'Juglans mollis','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '3713','genus_name' => 'Juglans','species_name' => 'nigra','common_name' => 'Black walnut','growth_rate' => 'Moderate','height_at_maturity' => '100'),
            array('id' => '3714','genus_name' => 'Juniperus','species_name' => 'occidentalis','common_name' => 'Western juniper','growth_rate' => 'Slow','height_at_maturity' => '41'),
            array('id' => '3715','genus_name' => 'Juniperus','species_name' => 'osteosperma','common_name' => 'Utah juniper','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '3716','genus_name' => 'Juniperus','species_name' => 'x pfitzeriana','common_name' => 'Pfitzer juniper','growth_rate' => 'Fast','height_at_maturity' => '9'),
            array('id' => '3717','genus_name' => 'Juniperus','species_name' => 'pinchotii','common_name' => 'Pinchot juniper','growth_rate' => 'Slow','height_at_maturity' => '41'),
            array('id' => '3718','genus_name' => 'Juniperus','species_name' => 'procumbens','common_name' => 'Japanese garden juniper','growth_rate' => '','height_at_maturity' => '1'),
            array('id' => '3719','genus_name' => 'Juniperus','species_name' => 'procera','common_name' => 'African juniper','growth_rate' => 'Slow','height_at_maturity' => '43'),
            array('id' => '3720','genus_name' => 'Juglans','species_name' => 'x quadrangulata','common_name' => 'Juglans x quadrangulata','growth_rate' => 'Moderate','height_at_maturity' => '86'),
            array('id' => '3721','genus_name' => 'Juglans','species_name' => 'regia','common_name' => 'English walnut','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '3722','genus_name' => 'Juniperus','species_name' => 'recurva','common_name' => 'Himalayan Juniper','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '3723','genus_name' => 'Juniperus','species_name' => 'rigida','common_name' => 'Temple Juniper','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '3724','genus_name' => 'Juniperus','species_name' => 'sabina','common_name' => 'Savine','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '3725','genus_name' => 'Juniperus','species_name' => 'scopulorum','common_name' => 'Rocky mountain juniper','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '3726','genus_name' => 'Juniperus','species_name' => 'virginiana v. silicicola','common_name' => 'Southern redcedar','growth_rate' => 'Slow','height_at_maturity' => '65'),
            array('id' => '3727','genus_name' => 'Juniperus','species_name' => 'virginiana','common_name' => 'Eastern red cedar','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '3732','genus_name' => 'Karwinskia','species_name' => 'humboldtiana','common_name' => 'Coyotillo','growth_rate' => '','height_at_maturity' => '24'),
            array('id' => '3734','genus_name' => 'Kalmia','species_name' => 'latifolia','common_name' => 'Mountain laurel','growth_rate' => 'Slow','height_at_maturity' => '7'),
            array('id' => '3737','genus_name' => 'Kalopanax','species_name' => 'septemlobus','common_name' => 'Castor aralia','growth_rate' => 'Slow','height_at_maturity' => '82'),
            array('id' => '3741','genus_name' => 'Kerria','species_name' => 'japonica','common_name' => 'Japanese rose','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '3745','genus_name' => 'Khaya','species_name' => 'anthotheca','common_name' => 'east african mahogany','growth_rate' => '','height_at_maturity' => '140'),
            array('id' => '3746','genus_name' => 'Khaya','species_name' => 'grandifoliola','common_name' => 'Big Leaf Mahogany','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '3747','genus_name' => 'Khaya','species_name' => 'nyasica','common_name' => 'Nyasaland mahogany','growth_rate' => '','height_at_maturity' => '67'),
            array('id' => '3748','genus_name' => 'Khaya','species_name' => 'senegalensis','common_name' => 'Senegal mahogany','growth_rate' => '','height_at_maturity' => '100'),
            array('id' => '3750','genus_name' => 'Kigelia','species_name' => 'africana','common_name' => 'Sausage tree','growth_rate' => 'Moderate','height_at_maturity' => '60'),
            array('id' => '3751','genus_name' => 'Kleinhovia','species_name' => 'hospita','common_name' => 'Guest tree','growth_rate' => '','height_at_maturity' => '67'),
            array('id' => '3752','genus_name' => 'Kolkwitzia','species_name' => 'amabilis','common_name' => 'Beautybush','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '3753','genus_name' => 'Koelreuteria','species_name' => 'bipinnata','common_name' => 'Chinese flame tree','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '3754','genus_name' => 'Kokia','species_name' => 'cookei','common_name' => 'Molokai treecotton','growth_rate' => '','height_at_maturity' => '13'),
            array('id' => '3755','genus_name' => 'Kokia','species_name' => 'drynarioides','common_name' => 'Hawai\'i treecotton','growth_rate' => '','height_at_maturity' => '27'),
            array('id' => '3756','genus_name' => 'Koelreuteria','species_name' => 'elegans','common_name' => 'Flamegold','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '3758','genus_name' => 'Kokia','species_name' => 'kauaiensis','common_name' => 'Kauai treecotton','growth_rate' => '','height_at_maturity' => '33'),
            array('id' => '3760','genus_name' => 'Koelreuteria','species_name' => 'paniculata','common_name' => 'Goldenrain tree','growth_rate' => 'Slow','height_at_maturity' => '45'),
            array('id' => '3761','genus_name' => 'Koelreuteria','species_name' => 'paniculata \'Fastigiata\'','common_name' => 'Goldenrain \'Fastigiata\'','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '3763','genus_name' => 'Koeberlinia','species_name' => 'spinosa','common_name' => 'Crown of thorns','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '3764','genus_name' => 'Krugiodendron','species_name' => 'ferreum','common_name' => 'Leadwood','growth_rate' => '','height_at_maturity' => '48'),
            array('id' => '3767','genus_name' => 'Kunzea','species_name' => 'ambigua','common_name' => 'White Kunzea','growth_rate' => 'Fast','height_at_maturity' => '3'),
            array('id' => '3768','genus_name' => 'Kunzea','species_name' => 'ericoides','common_name' => 'Burgan','growth_rate' => 'Fast','height_at_maturity' => '5'),
            array('id' => '3770','genus_name' => 'Laburnum','species_name' => 'alpinum','common_name' => 'Alpine laburnum','growth_rate' => 'Fast','height_at_maturity' => '5'),
            array('id' => '3771','genus_name' => 'Laburnum','species_name' => 'anagyroides','common_name' => 'Golden-chain tree','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3772','genus_name' => 'Lavandula','species_name' => 'angustifolia','common_name' => 'English lavender','growth_rate' => 'Slow','height_at_maturity' => '3'),
            array('id' => '3773','genus_name' => 'Lagerstroemia','species_name' => 'archeriana','common_name' => 'N. Kimberly Crepe Myrtle','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '3778','genus_name' => 'Larix','species_name' => 'decidua','common_name' => 'European larch','growth_rate' => 'Moderate','height_at_maturity' => '99'),
            array('id' => '3781','genus_name' => 'Larix','species_name' => 'decidua \'Pendula\'','common_name' => 'Weeping european larch','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '3782','genus_name' => 'Lansium','species_name' => 'domesticum','common_name' => 'Langsat','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '3783','genus_name' => 'Larix','species_name' => 'x eurolepis','common_name' => 'Dunkeld Larch','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '3785','genus_name' => 'Labordia','species_name' => 'fagraeoidea','common_name' => 'Summit labordia','growth_rate' => '','height_at_maturity' => '5'),
            array('id' => '3786','genus_name' => 'Lagarostrobos','species_name' => 'franklinii','common_name' => 'Huon Pine','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '3787','genus_name' => 'Larix','species_name' => 'gmelinii','common_name' => 'Dahurian Larch','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '3791','genus_name' => 'Labordia','species_name' => 'hirtella','common_name' => 'Mountain labordia','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '3793','genus_name' => 'Lagerstroemia','species_name' => 'indica','common_name' => 'Common crapemyrtle','growth_rate' => 'Moderate','height_at_maturity' => '16'),
            array('id' => '3794','genus_name' => 'Lagerstroemia','species_name' => 'indica \'Magenta\'','common_name' => 'Magenta crepe myrtle','growth_rate' => '','height_at_maturity' => '4'),
            array('id' => '3796','genus_name' => 'Lantana','species_name' => 'involucrata','common_name' => 'Buttonsage','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '3797','genus_name' => 'Lawsonia','species_name' => 'inermis','common_name' => 'Henna','growth_rate' => '','height_at_maturity' => '23'),
            array('id' => '3798','genus_name' => 'Labordia','species_name' => 'kaalae','common_name' => 'Waianae range labordia','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '3799','genus_name' => 'Larix','species_name' => 'kaempferi','common_name' => 'Japanese larch','growth_rate' => 'Fast','height_at_maturity' => '98'),
            array('id' => '3800','genus_name' => 'Larix','species_name' => 'laricina','common_name' => 'Tamarack','growth_rate' => 'Fast','height_at_maturity' => '80'),
            array('id' => '3801','genus_name' => 'Larix','species_name' => 'lyallii','common_name' => 'Subalpine larch','growth_rate' => 'Slow','height_at_maturity' => '40'),
            array('id' => '3803','genus_name' => 'Larix','species_name' => 'leptolepis','common_name' => 'Larix leptolepis','growth_rate' => 'Fast','height_at_maturity' => '98'),
            array('id' => '3806','genus_name' => 'Lagerstroemia','species_name' => 'indica \'Muskogee\'','common_name' => 'Muskogee crapemyrtle','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '3807','genus_name' => 'Lagerstroemia','species_name' => 'indica \'Natchez\'','common_name' => 'Natchez crapemyrtle','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '3808','genus_name' => 'Laurus','species_name' => 'nobilis','common_name' => 'Bay laurel','growth_rate' => 'Slow','height_at_maturity' => '60'),
            array('id' => '3809','genus_name' => 'Larix','species_name' => 'occidentalis','common_name' => 'Western larch','growth_rate' => 'Fast','height_at_maturity' => '200'),
            array('id' => '3810','genus_name' => 'Lagunaria','species_name' => 'patersonii','common_name' => 'Primrose tree','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '3812','genus_name' => 'Larix','species_name' => 'potaninii','common_name' => 'Tibetan Larch','growth_rate' => 'Moderate','height_at_maturity' => '21'),
            array('id' => '3816','genus_name' => 'Laguncularia','species_name' => 'racemosa','common_name' => 'White mangrove','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '3819','genus_name' => 'Larix','species_name' => 'sibirica','common_name' => 'Siberian larch','growth_rate' => 'Moderate','height_at_maturity' => '100'),
            array('id' => '3820','genus_name' => 'Lagerstroemia','species_name' => 'speciosa','common_name' => 'Queen\'s crapemyrtle','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '3821','genus_name' => 'Lafoensia','species_name' => 'speciosa','common_name' => 'Lafoensia speciosa','growth_rate' => 'Moderate','height_at_maturity' => '49'),
            array('id' => '3824','genus_name' => 'Labordia','species_name' => 'tinifolia','common_name' => 'Paleflower labordia','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '3826','genus_name' => 'Labordia','species_name' => 'triflora','common_name' => 'three flower labordia','growth_rate' => '','height_at_maturity' => '7'),
            array('id' => '3827','genus_name' => 'Lagerstroemia','species_name' => 'indica \'Tuscarora\'','common_name' => 'Tuscarora crapemyrtle','growth_rate' => 'Fast','height_at_maturity' => '16'),
            array('id' => '3828','genus_name' => 'Lagerstroemia','species_name' => 'indica \'Tuskegee\'','common_name' => 'Tuskegee crapemyrtle','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '3832','genus_name' => 'Laburnum','species_name' => 'x watereri','common_name' => 'Golden chain tree','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '3834','genus_name' => 'Labordia','species_name' => 'waiolani','common_name' => 'Nevada peavine','growth_rate' => '','height_at_maturity' => '7'),
            array('id' => '3835','genus_name' => 'Leptomeria','species_name' => 'acida','common_name' => 'Sour Currant-bush','growth_rate' => 'Fast','height_at_maturity' => '3'),
            array('id' => '3836','genus_name' => 'Leptomeria','species_name' => 'aphylla','common_name' => 'Leafless Currant-bush','growth_rate' => 'Fast','height_at_maturity' => '2'),
            array('id' => '3837','genus_name' => 'Leucadendron','species_name' => 'argenteum','common_name' => 'Silver Tree','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '3838','genus_name' => 'Leucothoe','species_name' => 'axillaris','common_name' => 'Coastal doghobble','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '3839','genus_name' => 'Lespedeza','species_name' => 'bicolor','common_name' => 'Bicolor lespedeza','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '3840','genus_name' => 'Leptospermum','species_name' => 'brevipes','common_name' => 'Slender Tea Tree','growth_rate' => 'Fast','height_at_maturity' => '4'),
            array('id' => '3843','genus_name' => 'Leptospermum','species_name' => 'continentale','common_name' => 'Tea-tree','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '3845','genus_name' => 'Leucaena','species_name' => 'cuspidata','common_name' => 'Leucaena cuspidata','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '3848','genus_name' => 'Leucaena','species_name' => 'esculenta','common_name' => 'Leucaena esculenta','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '3849','genus_name' => 'Leitneria','species_name' => 'floridana','common_name' => 'Corkwood','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '3850','genus_name' => 'Leptospermum','species_name' => 'flavescens','common_name' => 'Common teatree','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '3851','genus_name' => 'Leucothoe','species_name' => 'fontanesiana','common_name' => 'Highland doghobble','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '3854','genus_name' => 'Leucophyllum','species_name' => 'frutescens','common_name' => 'Texas barometer bush','growth_rate' => '','height_at_maturity' => '8'),
            array('id' => '3855','genus_name' => 'Ledum','species_name' => 'glandulosum','common_name' => 'Western labrador tea','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '3856','genus_name' => 'Ledum','species_name' => 'groenlandicum','common_name' => 'Labrador tea','growth_rate' => 'Slow','height_at_maturity' => '4'),
            array('id' => '3857','genus_name' => 'Leea','species_name' => 'guineensis','common_name' => 'West Indian holly','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '3858','genus_name' => 'Leucaena','species_name' => 'insularum','common_name' => 'Mohemohe','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '3861','genus_name' => 'Leptospermum','species_name' => 'lanigerum','common_name' => 'Woolly Tea-tree','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '3862','genus_name' => 'Leptospermum','species_name' => 'laevigatum','common_name' => 'Coastal Tea-tree','growth_rate' => 'Fast','height_at_maturity' => '8'),
            array('id' => '3863','genus_name' => 'Leptospermum','species_name' => 'laevigata','common_name' => 'Coastal teatree','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '3866','genus_name' => 'Leucaena','species_name' => 'leucocephala','common_name' => 'White lead tree','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3868','genus_name' => 'Leptospermum','species_name' => 'madidum','common_name' => 'Weeping Tea-tree','growth_rate' => 'Fast','height_at_maturity' => '9'),
            array('id' => '3870','genus_name' => 'Leptospermum','species_name' => 'morrisonii','common_name' => 'large-leaf yellow teatree','growth_rate' => '','height_at_maturity' => '9'),
            array('id' => '3871','genus_name' => 'Leptospermum','species_name' => 'obovatum','common_name' => 'River Tea-tree','growth_rate' => 'Fast','height_at_maturity' => '4'),
            array('id' => '3873','genus_name' => 'Leptospermum','species_name' => 'petersonii','common_name' => 'Lemon tea-tree','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '3876','genus_name' => 'Leucaena','species_name' => 'pulverulenta','common_name' => 'Great leadtree','growth_rate' => 'Moderate','height_at_maturity' => '55'),
            array('id' => '3879','genus_name' => 'Leucaena','species_name' => 'retusa','common_name' => 'Littleleaf leadtree','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '3881','genus_name' => 'Leptospermum','species_name' => 'scoparium','common_name' => 'Broom teatree','growth_rate' => 'Fast','height_at_maturity' => '67'),
            array('id' => '3882','genus_name' => 'Lepidospartum','species_name' => 'squamatum','common_name' => 'California broomsage','growth_rate' => '','height_at_maturity' => '5'),
            array('id' => '3883','genus_name' => 'Leptospermum','species_name' => 'trinervium','common_name' => 'Paperbark Tea-tree','growth_rate' => 'Fast','height_at_maturity' => '5'),
            array('id' => '3885','genus_name' => 'Ligustrum','species_name' => 'amurense','common_name' => 'Amur privet','growth_rate' => 'Fast','height_at_maturity' => '39'),
            array('id' => '3887','genus_name' => 'Livistona','species_name' => 'australis','common_name' => 'Australian fan palm','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '3888','genus_name' => 'Lindera','species_name' => 'benzoin','common_name' => 'Spicebush','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '3889','genus_name' => 'Libocedrus','species_name' => 'bidwilli','common_name' => 'New Zealand Cedar','growth_rate' => 'Moderate','height_at_maturity' => '21'),
            array('id' => '3892','genus_name' => 'Livistona','species_name' => 'chinensis','common_name' => 'Chinese fan palm','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '3893','genus_name' => 'Liriodendron','species_name' => 'chinense','common_name' => 'Chinese tulip tree','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '3894','genus_name' => 'Litchi','species_name' => 'chinensis','common_name' => 'Lychee','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '3895','genus_name' => 'Lithocarpus','species_name' => 'densiflorus','common_name' => 'Tanoak','growth_rate' => 'Moderate','height_at_maturity' => '125'),
            array('id' => '3896','genus_name' => 'Livistona','species_name' => 'decipiens','common_name' => 'Ribbon palm','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '3897','genus_name' => 'Liquidambar','species_name' => 'formosana','common_name' => 'Chinese sweet gum','growth_rate' => 'Moderate','height_at_maturity' => '60'),
            array('id' => '3900','genus_name' => 'Livistona','species_name' => 'humilis','common_name' => 'Sand Palm','growth_rate' => 'Slow','height_at_maturity' => '3'),
            array('id' => '3901','genus_name' => 'Livistona','species_name' => 'inermis','common_name' => 'Wispy Fan Palm','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '3902','genus_name' => 'Ligustrum','species_name' => 'japonicum','common_name' => 'Japanese privet','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '3903','genus_name' => 'Ligustrum','species_name' => 'japonicum \'Variegatum\'','common_name' => 'Variegated privet','growth_rate' => 'Fast','height_at_maturity' => '3'),
            array('id' => '3905','genus_name' => 'Ligustrum','species_name' => 'lucidum','common_name' => 'Glossy privet','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '3906','genus_name' => 'Ligustrum','species_name' => 'lucidum Tricolor','common_name' => 'Tri-colour Privet','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '3907','genus_name' => 'Lindera','species_name' => 'melissifolia','common_name' => 'Southern spicebush','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '3911','genus_name' => 'Ligustrum','species_name' => 'obtusifolium','common_name' => 'Border privet','growth_rate' => 'Fast','height_at_maturity' => '39'),
            array('id' => '3912','genus_name' => 'Lindera','species_name' => 'obtusiloba','common_name' => 'Japanese spicebush','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '3913','genus_name' => 'Liquidambar','species_name' => 'orientalis','common_name' => 'Oriental sweetgum','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '3914','genus_name' => 'Ligustrum','species_name' => 'ovalifolium','common_name' => 'California privet','growth_rate' => 'Fast','height_at_maturity' => '16'),
            array('id' => '3915','genus_name' => 'Ligustrum','species_name' => 'ovalifolium \'Aureum\'','common_name' => 'Golden privet','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '3916','genus_name' => 'Licaria','species_name' => 'parvifolia','common_name' => 'Puerto Rican cinnamon','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '3917','genus_name' => 'Libocedrus','species_name' => 'plumosa','common_name' => 'Kawaka','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '3918','genus_name' => 'Ligustrum','species_name' => 'quihoui','common_name' => 'Waxyleaf privet','growth_rate' => 'Fast','height_at_maturity' => '39'),
            array('id' => '3919','genus_name' => 'Livistona','species_name' => 'rigida','common_name' => 'Mataranka Fan Palm','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '3921','genus_name' => 'Ligustrum','species_name' => 'sinense','common_name' => 'Chinese privet','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '3922','genus_name' => 'Liquidambar','species_name' => 'styraciflua','common_name' => 'Sweetgum','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '3923','genus_name' => 'Liquidambar','species_name' => 'styracifula \'Moraine\'','common_name' => 'Moraine Sweetgum','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '3924','genus_name' => 'Lindera','species_name' => 'subcoriacea','common_name' => 'Bog spicebush','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '3925','genus_name' => 'Licania','species_name' => 'tomentosa','common_name' => 'Oiti','growth_rate' => 'Moderate','height_at_maturity' => '59'),
            array('id' => '3926','genus_name' => 'Licaria','species_name' => 'triandra','common_name' => 'Pepperleaf sweetwood','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '3927','genus_name' => 'Liriodendron','species_name' => 'tulipifera','common_name' => 'Tulip tree','growth_rate' => 'Fast','height_at_maturity' => '120'),
            array('id' => '3928','genus_name' => 'Liriodendron','species_name' => 'tulipifera \'Aureomarginatum\'','common_name' => 'Variegated Tulip Tree','growth_rate' => 'Fast','height_at_maturity' => '36'),
            array('id' => '3929','genus_name' => 'Liriodendron','species_name' => 'tulipifera \'Fastigiatum\'','common_name' => 'Narrow Tulip Tree','growth_rate' => 'Fast','height_at_maturity' => '13'),
            array('id' => '3930','genus_name' => 'Ligustrum','species_name' => 'vulgare','common_name' => 'Common privet','growth_rate' => 'Fast','height_at_maturity' => '39'),
            array('id' => '3931','genus_name' => 'Lonicera','species_name' => 'albiflora','common_name' => 'Western white honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3932','genus_name' => 'Lonicera','species_name' => 'arizonica','common_name' => 'Arizona honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3933','genus_name' => 'Lonicera','species_name' => 'x bella','common_name' => 'Bell\'s honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3935','genus_name' => 'Lophomyrtus','species_name' => 'bullata','common_name' => 'Ramarama','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '3936','genus_name' => 'Lonicera','species_name' => 'canadensis','common_name' => 'American fly honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3937','genus_name' => 'Lonicera','species_name' => 'caerulea','common_name' => 'Sweetberry honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3938','genus_name' => 'Loropetalum','species_name' => 'chinense','common_name' => 'Fringe flower','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '3939','genus_name' => 'Lonicera','species_name' => 'ciliosa','common_name' => 'Orange honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3940','genus_name' => 'Lonicera','species_name' => 'conjugialis','common_name' => 'Purpleflower honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3941','genus_name' => 'Lophostemon','species_name' => 'confertus','common_name' => 'Vinegartree','growth_rate' => '','height_at_maturity' => '67'),
            array('id' => '3942','genus_name' => 'Lophostemon','species_name' => 'confertus \'Variegatus\'','common_name' => 'Variegated Brush Box','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '3943','genus_name' => 'Lonchocarpus','species_name' => 'domingensis','common_name' => 'Geno geno','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '3945','genus_name' => 'Lonicera','species_name' => 'flava','common_name' => 'Yellow honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3946','genus_name' => 'Lonicera','species_name' => 'fragrantissima','common_name' => 'Sweet breath of spring','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3947','genus_name' => 'Lomatia','species_name' => 'fraseri','common_name' => 'Forest Lomatia','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '3950','genus_name' => 'Lophostemon','species_name' => 'grandiflorus','common_name' => 'Northen Swamp Mahogany','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '3951','genus_name' => 'Lophostemon','species_name' => 'grandiflorus ssp. riparus','common_name' => 'Northern Swamp Box','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '3954','genus_name' => 'Lonicera','species_name' => 'x heckrottii','common_name' => 'Goldflame honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3955','genus_name' => 'Lonchocarpus','species_name' => 'heptaphyllus','common_name' => 'Broadleaf lancepod','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '3958','genus_name' => 'Lomatia','species_name' => 'ilicifolia','common_name' => 'Holly Lomatia','growth_rate' => 'Slow','height_at_maturity' => '3'),
            array('id' => '3959','genus_name' => 'Lonicera','species_name' => 'involucrata','common_name' => 'Twinberry honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3960','genus_name' => 'Lonicera','species_name' => 'japonica','common_name' => 'Japanese honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3962','genus_name' => 'Lonicera','species_name' => 'korolkowii','common_name' => 'Blueleaf honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3963','genus_name' => 'Lonicera','species_name' => 'maackii','common_name' => 'Amur honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '13'),
            array('id' => '3964','genus_name' => 'Lonicera','species_name' => 'x minutiflora','common_name' => 'Smallflower honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3965','genus_name' => 'Lonicera','species_name' => 'morrowii','common_name' => 'Morrow honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3968','genus_name' => 'Lomatia','species_name' => 'myricoides','common_name' => 'Long-leaf Lomatia','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '3970','genus_name' => 'Lonicera','species_name' => 'x notha','common_name' => 'Honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3972','genus_name' => 'Lonicera','species_name' => 'oblongifolia','common_name' => 'Swamp fly honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3973','genus_name' => 'Lophomyrtus','species_name' => 'obcordata','common_name' => 'Rohutu','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '3975','genus_name' => 'Lonicera','species_name' => 'reticulata','common_name' => 'Grape honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3976','genus_name' => 'Lonicera','species_name' => 'ruprechtiana','common_name' => 'Manchurian honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3977','genus_name' => 'Lonchocarpus','species_name' => 'sanctae-marthae','common_name' => 'Macurutu','growth_rate' => 'Moderate','height_at_maturity' => '98'),
            array('id' => '3978','genus_name' => 'Lonicera','species_name' => 'standishii','common_name' => 'Standish\'s honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3979','genus_name' => 'Lophostemon','species_name' => 'suaveolens','common_name' => 'Swamp Box','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '3980','genus_name' => 'Lonicera','species_name' => 'subspicata','common_name' => 'Southern honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3981','genus_name' => 'Lonicera','species_name' => 'tatarica','common_name' => 'Tartarian honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3982','genus_name' => 'Lonicera','species_name' => 'utahensis','common_name' => 'Utah honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3983','genus_name' => 'Lonicera','species_name' => 'villosa','common_name' => 'Mountain fly honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3985','genus_name' => 'Lonicera','species_name' => 'xylosteum','common_name' => 'Dwarf honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3986','genus_name' => 'Lonicera','species_name' => 'x xylosteoides','common_name' => 'Fly honeysuckle','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '3987','genus_name' => 'Eugenia','species_name' => 'apiculata','common_name' => 'Shortleaf stopper','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '3992','genus_name' => 'Lumnitzera','species_name' => 'littorea','common_name' => 'red flower black mangrove','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '3994','genus_name' => 'Lysiloma','species_name' => 'acapulcense','common_name' => 'Bastard mahogany','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '3997','genus_name' => 'Lysiloma','species_name' => 'bahamensis','common_name' => 'Wild tamarind','growth_rate' => 'Moderate','height_at_maturity' => '63'),
            array('id' => '4004','genus_name' => 'Lysiloma','species_name' => 'divaricatum','common_name' => 'Mauto','growth_rate' => 'Fast','height_at_maturity' => '18'),
            array('id' => '4014','genus_name' => 'Lysiloma','species_name' => 'latisiliquum','common_name' => 'Bahama lysiloma','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '4016','genus_name' => 'Lyonia','species_name' => 'lucida','common_name' => 'Fetterbush lyonia','growth_rate' => '','height_at_maturity' => '5'),
            array('id' => '4020','genus_name' => 'Lysiloma','species_name' => 'microphyllum','common_name' => 'Desert fern','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '4027','genus_name' => 'Lyonia','species_name' => 'rubiginosa','common_name' => 'St. thomas staggerbush','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '4029','genus_name' => 'Lysiloma','species_name' => 'sabicu','common_name' => 'Horseflesh mahogany','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '4032','genus_name' => 'Lysiloma','species_name' => 'watsonii','common_name' => 'Feather bush','growth_rate' => 'Moderate','height_at_maturity' => '63'),
            array('id' => '4039','genus_name' => 'Magnolia','species_name' => 'acuminata','common_name' => 'Cucumber tree','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '4042','genus_name' => 'Mammea','species_name' => 'americana','common_name' => 'Mammee apple','growth_rate' => 'Fast','height_at_maturity' => '55'),
            array('id' => '4043','genus_name' => 'Maackia','species_name' => 'amurensis','common_name' => 'Amur maackia','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '4045','genus_name' => 'Matayba','species_name' => 'apetala','common_name' => 'Matayba apetala','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '4047','genus_name' => 'Malvaviscus','species_name' => 'arboreus','common_name' => 'Wax mallow','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '4048','genus_name' => 'Malus','species_name' => 'x arnoldiana','common_name' => 'Arnold\'s apple','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '4049','genus_name' => 'Magnolia','species_name' => 'ashei','common_name' => 'Ashe magnolia','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '4050','genus_name' => 'Manilkara','species_name' => 'bahamensis','common_name' => 'Manilkara bahamensis','growth_rate' => 'Moderate','height_at_maturity' => '45'),
            array('id' => '4051','genus_name' => 'Malus','species_name' => 'baccata v purpurea','common_name' => 'Manzano de flor','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '4052','genus_name' => 'Mahonia','species_name' => 'bealei','common_name' => 'Leatherleaf mahonia','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '4053','genus_name' => 'Manilkara','species_name' => 'bidentata','common_name' => 'Balata','growth_rate' => 'Slow','height_at_maturity' => '100'),
            array('id' => '4054','genus_name' => 'Maytenus','species_name' => 'boaria','common_name' => 'Mayten','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '4055','genus_name' => 'Magnolia','species_name' => 'campbellii','common_name' => 'Campbell\'s Magnolia','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '4056','genus_name' => 'Manihot','species_name' => 'caudata','common_name' => 'Manihot caudata','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '4057','genus_name' => 'Mangifera','species_name' => 'caesia','common_name' => 'Binjai','growth_rate' => 'Fast','height_at_maturity' => '98'),
            array('id' => '4060','genus_name' => 'Maranthes','species_name' => 'corymbosa','common_name' => 'White Cloud Tree','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '4061','genus_name' => 'Macrozamia','species_name' => 'communis','common_name' => 'Burrawang','growth_rate' => 'Slow','height_at_maturity' => '2'),
            array('id' => '4062','genus_name' => 'Malpighia','species_name' => 'coccigera','common_name' => 'Singapore holly','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '4063','genus_name' => 'Matisia','species_name' => 'cordata','common_name' => 'Zapote','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '4066','genus_name' => 'Maytenus','species_name' => 'cymosa','common_name' => 'Caribbean mayten','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '4068','genus_name' => 'Malus','species_name' => 'x dawsoniana','common_name' => 'Dawson crabapple','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '4069','genus_name' => 'Magnolia','species_name' => 'denudata','common_name' => 'Chinese magnolia','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '4070','genus_name' => 'Magnolia','species_name' => 'delavayi','common_name' => 'Delavay\'s Magnolia','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '4073','genus_name' => 'Malus','species_name' => 'domestica','common_name' => 'Common apple','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '4075','genus_name' => 'Matayba','species_name' => 'domingensis','common_name' => 'Negra lora','growth_rate' => '','height_at_maturity' => '65'),
            array('id' => '4076','genus_name' => 'Maytenus','species_name' => 'elongata','common_name' => 'Puerto rico mayten','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '4077','genus_name' => 'Malpighia','species_name' => 'emarginata','common_name' => 'Barbados cherry','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '4078','genus_name' => 'Maesopsis','species_name' => 'eminii','common_name' => 'Umbrella-tree','growth_rate' => 'Fast','height_at_maturity' => '132'),
            array('id' => '4079','genus_name' => 'Malus','species_name' => 'floribunda','common_name' => 'Japanese flower crabapple','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '4080','genus_name' => 'Mastichodendron','species_name' => 'foetidissium','common_name' => 'False mastic','growth_rate' => 'Moderate','height_at_maturity' => '78'),
            array('id' => '4082','genus_name' => 'Magnolia','species_name' => 'fraseri','common_name' => 'Fraser magnolia','growth_rate' => 'Fast','height_at_maturity' => '75'),
            array('id' => '4084','genus_name' => 'Malpighia','species_name' => 'fucata','common_name' => 'Palo bronco','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '4085','genus_name' => 'Malus','species_name' => 'glaucescens','common_name' => 'Dunbar crabapple','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '4086','genus_name' => 'Malus','species_name' => 'glabrata','common_name' => 'Biltmore crabapple','growth_rate' => 'Moderate','height_at_maturity' => '17'),
            array('id' => '4087','genus_name' => 'Manihot','species_name' => 'glaziovii','common_name' => 'Ceara rubbertree','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '4088','genus_name' => 'Malpighia','species_name' => 'glabra','common_name' => 'Wild crapemyrtle','growth_rate' => 'Slow','height_at_maturity' => '13'),
            array('id' => '4089','genus_name' => 'Magnolia','species_name' => 'grandiflora','common_name' => 'Southern magnolia','growth_rate' => 'Moderate','height_at_maturity' => '100'),
            array('id' => '4090','genus_name' => 'Manihot','species_name' => 'grahamii','common_name' => 'Graham\'s manihot','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '4091','genus_name' => 'Magnolia','species_name' => 'grandiflora \'Little Gem\'','common_name' => 'Little Gem South Magnolia','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '4093','genus_name' => 'Malus','species_name' => '\'Harvest Gold\'','common_name' => 'Harvest Gold crabapple','growth_rate' => '','height_at_maturity' => '22'),
            array('id' => '4097','genus_name' => 'Magnolia','species_name' => 'hypoleuca','common_name' => 'Japanese big-leaf Magnolia','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '4099','genus_name' => 'Mangifera','species_name' => 'indica','common_name' => 'Mango','growth_rate' => 'Moderate','height_at_maturity' => '65')
        );

        Tree::insert($trees);

        $seeder = new TreeSpeciesSeeder6;
        $seeder->run();
    }
}
