<?php

namespace Database\Seeders\TreeSpecies;

use App\Models\Trees\Tree;
use Illuminate\Database\Seeder;

class TreeSpeciesSeeder6 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $trees = array(
            array('id' => '4103','genus_name' => 'Macadamia','species_name' => 'integrifolia','common_name' => 'Macadamia nut','growth_rate' => 'Slow','height_at_maturity' => '35'),
            array('id' => '4104','genus_name' => 'Malus','species_name' => 'ioensis \'Plena\'','common_name' => 'Betchel crabapple','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '4105','genus_name' => 'Malus','species_name' => '\'Indian Summer\'','common_name' => 'Indian Summer crabapple','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '4106','genus_name' => 'Mahonia','species_name' => 'japonica','common_name' => 'Japanese mahonia','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '4107','genus_name' => 'Manilkara','species_name' => 'jaimiqui','common_name' => 'Wild dilly','growth_rate' => 'Moderate','height_at_maturity' => '62'),
            array('id' => '4108','genus_name' => 'Malus','species_name' => 'John Downie','common_name' => 'John Downie','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '4109','genus_name' => 'Magnolia','species_name' => 'kobus','common_name' => 'Kobushi Magnolia','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '4110','genus_name' => 'Maesa','species_name' => 'lanceolata','common_name' => 'False assegai','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '4111','genus_name' => 'Malosma','species_name' => 'laurina','common_name' => 'Laurel sumac','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '4112','genus_name' => 'Maytenus','species_name' => 'laevigata','common_name' => 'White cinnamon','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '4113','genus_name' => 'Magnolia','species_name' => 'liliiflora','common_name' => 'Lily Magnolia','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '4114','genus_name' => 'Malpighia','species_name' => 'linearis','common_name' => 'Bastard cherry','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '4115','genus_name' => 'Mahonia','species_name' => 'lomariifolia','common_name' => 'Chinese Holly Grape','growth_rate' => 'Slow','height_at_maturity' => '3'),
            array('id' => '4116','genus_name' => 'Magnolia','species_name' => 'x loebneri \'leonard messel\'','common_name' => 'Leonard Messel magnolia','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '4118','genus_name' => 'Markhamia','species_name' => 'lutea','common_name' => 'Siala','growth_rate' => '','height_at_maturity' => '41'),
            array('id' => '4119','genus_name' => 'Magnolia','species_name' => 'macrophylla','common_name' => 'Bigleaf magnolia','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '4120','genus_name' => 'Macaranga','species_name' => 'mappa','common_name' => 'Pengua','growth_rate' => '','height_at_maturity' => '33'),
            array('id' => '4121','genus_name' => 'Malus','species_name' => 'x magdeburgensis','common_name' => 'Magdeburg crabapple','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '4122','genus_name' => 'Malus','species_name' => 'mandshurica','common_name' => 'Manchurian crabapple','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '4129','genus_name' => 'Mangifera','species_name' => 'odorata','common_name' => 'kwini','growth_rate' => '','height_at_maturity' => '45'),
            array('id' => '4130','genus_name' => 'Mammea','species_name' => 'odorata','common_name' => 'chopak','growth_rate' => '','height_at_maturity' => '24'),
            array('id' => '4131','genus_name' => 'Magnolia','species_name' => 'officinalis','common_name' => 'Magnolia bark','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '4135','genus_name' => 'Maytenus','species_name' => 'phyllanthoides','common_name' => 'Florida mayten','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '4136','genus_name' => 'Mallotus','species_name' => 'philippensis','common_name' => 'Kamala tree','growth_rate' => '','height_at_maturity' => '33'),
            array('id' => '4138','genus_name' => 'Malus','species_name' => 'x platycarpa','common_name' => 'Bigfruit crab','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '4139','genus_name' => 'Manilkara','species_name' => 'pleeana','common_name' => 'Zapote de costa','growth_rate' => 'Moderate','height_at_maturity' => '62'),
            array('id' => '4140','genus_name' => 'Maclura','species_name' => 'pomifera','common_name' => 'Osage orange','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '4141','genus_name' => 'Magnolia','species_name' => 'portoricensis','common_name' => 'Puerto rico magnolia','growth_rate' => 'Slow','height_at_maturity' => '77'),
            array('id' => '4142','genus_name' => 'Maytenus','species_name' => 'ponceana','common_name' => 'Ponce mayten','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '4144','genus_name' => 'Maclura','species_name' => 'pomifera \'Wichita\'','common_name' => 'Wichita Osage Orange','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '4145','genus_name' => 'Malus','species_name' => 'prunifolia','common_name' => 'Plumleaf crabapple','growth_rate' => 'Moderate','height_at_maturity' => '27'),
            array('id' => '4146','genus_name' => 'Malus','species_name' => 'pumila','common_name' => 'Paradise apple','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '4147','genus_name' => 'Malus','species_name' => 'x purpurea \'Eleyi\'','common_name' => 'Eleyi crapapple','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '4149','genus_name' => 'Magnolia','species_name' => 'pyramidata','common_name' => 'Pyramid magnolia','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '4150','genus_name' => 'Mappia','species_name' => 'racemosa','common_name' => 'Palo de cana','growth_rate' => '','height_at_maturity' => '36'),
            array('id' => '4153','genus_name' => 'Magnolia','species_name' => 'salicifolia','common_name' => 'Willow-leaved Magnolia','growth_rate' => 'Slow','height_at_maturity' => '7'),
            array('id' => '4155','genus_name' => 'Malus','species_name' => 'sargentii','common_name' => 'Sargent\'s apple','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '4156','genus_name' => 'Magnolia','species_name' => 'schiedeana','common_name' => 'Magnolia schiedeana','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '4157','genus_name' => 'Malpighia','species_name' => 'setosa','common_name' => 'Bristly stingingbush','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '4158','genus_name' => 'Maytenus','species_name' => 'senegalensis','common_name' => 'Staff tree','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '4159','genus_name' => 'Magnolia','species_name' => 'sieboldii','common_name' => 'Oyama Magnolia','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '4161','genus_name' => 'Malus','species_name' => 'sieboldii','common_name' => 'Toringa crabapple','growth_rate' => 'Moderate','height_at_maturity' => '32'),
            array('id' => '4162','genus_name' => 'Magnolia','species_name' => 'x soulangeana','common_name' => 'Saucer magnolia','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '4163','genus_name' => 'Malus','species_name' => 'x soulardii','common_name' => 'Soulard crab','growth_rate' => 'Moderate','height_at_maturity' => '17'),
            array('id' => '4165','genus_name' => 'Magnolia','species_name' => 'splendens','common_name' => 'Laurel magnolia','growth_rate' => 'Moderate','height_at_maturity' => '54'),
            array('id' => '4166','genus_name' => 'Malus','species_name' => 'spectabilis','common_name' => 'Asiatic apple','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '4167','genus_name' => 'Machaerium','species_name' => 'spinosum','common_name' => 'Varoblanco','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '4169','genus_name' => 'Magnolia','species_name' => 'stellata','common_name' => 'Star magnolia','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '4170','genus_name' => 'Malus','species_name' => '\'Sugar Tyme\'','common_name' => 'Crabapple \'Sugar Tyme\'','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '4174','genus_name' => 'Malus','species_name' => 'sylvestris','common_name' => 'European crabapple','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '4175','genus_name' => 'Macaranga','species_name' => 'tanarius','common_name' => 'Parasol leaf tree','growth_rate' => 'Fast','height_at_maturity' => '67'),
            array('id' => '4176','genus_name' => 'Macadamia','species_name' => 'tetraphylla','common_name' => 'Rough-shell macadamia','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '4177','genus_name' => 'Macadamia','species_name' => 'ternifolia','common_name' => 'Small fruited Queensland Nut','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '4178','genus_name' => 'Macaranga','species_name' => 'thompsonii','common_name' => 'Macaranga thompsonii','growth_rate' => '','height_at_maturity' => '45'),
            array('id' => '4179','genus_name' => 'Machaerium','species_name' => 'tipu','common_name' => 'Tipa','growth_rate' => 'Fast','height_at_maturity' => '67'),
            array('id' => '4180','genus_name' => 'Maclura','species_name' => 'tinctoria','common_name' => 'Fustictree','growth_rate' => 'Fast','height_at_maturity' => '58'),
            array('id' => '4181','genus_name' => 'Malus','species_name' => 'toringoides','common_name' => 'Cutleaf Crab','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '4183','genus_name' => 'Magnolia','species_name' => 'tripetala','common_name' => 'Umbrella magnolia','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '4185','genus_name' => 'Malus','species_name' => 'tschonoskii','common_name' => 'crabapple','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '4186','genus_name' => 'Manilkara','species_name' => 'valenzuela','common_name' => 'Nisperillo','growth_rate' => 'Moderate','height_at_maturity' => '62'),
            array('id' => '4187','genus_name' => 'Magnolia','species_name' => 'virginiana','common_name' => 'Sweetbay','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '4188','genus_name' => 'Magnolia','species_name' => 'wilsonii','common_name' => 'Wilson\'s Magnolia','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '4189','genus_name' => 'Malpighia','species_name' => 'woodburyana','common_name' => 'Woodbury\'s stingingbush','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '4191','genus_name' => 'Malus','species_name' => 'x robusta','common_name' => 'Cherry-crab','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '4192','genus_name' => 'Manilkara','species_name' => 'zapota','common_name' => 'Sapodilla','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '4193','genus_name' => 'Machilus','species_name' => 'zuihoensis','common_name' => 'Machilus zuihensis','growth_rate' => 'Moderate','height_at_maturity' => ''),
            array('id' => '4194','genus_name' => 'Melaleuca','species_name' => 'acuminata','common_name' => 'Mallee Honey Myrtle','growth_rate' => 'Moderate','height_at_maturity' => '2'),
            array('id' => '4196','genus_name' => 'Melaleuca','species_name' => 'alternifolia','common_name' => 'Tea Tree','growth_rate' => 'Moderate','height_at_maturity' => '7'),
            array('id' => '4197','genus_name' => 'Meliosma','species_name' => 'alba','common_name' => 'Meliosma alba','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '4198','genus_name' => 'Metroxylon','species_name' => 'amicarum','common_name' => 'ivory-nut palm','growth_rate' => '','height_at_maturity' => '66'),
            array('id' => '4201','genus_name' => 'Melaleuca','species_name' => 'argentea','common_name' => 'Silver Cadjeput','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '4202','genus_name' => 'Melia','species_name' => 'azedarach','common_name' => 'Chinaberry','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '4203','genus_name' => 'Melia','species_name' => 'azedarch','common_name' => 'Rosary Tree','growth_rate' => 'Fast','height_at_maturity' => '12'),
            array('id' => '4205','genus_name' => 'Melicope','species_name' => 'barbigera','common_name' => 'Uahiapele','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '4206','genus_name' => 'Melicoccus','species_name' => 'bijugatus','common_name' => 'Spanish lime','growth_rate' => 'Moderate','height_at_maturity' => '60'),
            array('id' => '4207','genus_name' => 'Melaleuca','species_name' => 'biconvexa','common_name' => 'Biconvex Paperbark','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '4208','genus_name' => 'Melaleuca','species_name' => 'bracteata','common_name' => 'Black teatree','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '4210','genus_name' => 'Melaleuca','species_name' => 'cajuputi','common_name' => 'Gelam','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '4212','genus_name' => 'Melastoma','species_name' => 'candidum','common_name' => 'Asian melastome','growth_rate' => '','height_at_maturity' => '17'),
            array('id' => '4214','genus_name' => 'Melicope','species_name' => 'christophersenii','common_name' => 'Waianae range melicope','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '4215','genus_name' => 'Melicope','species_name' => 'cinerea','common_name' => 'Manena','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '4216','genus_name' => 'Melicope','species_name' => 'clusiifolia','common_name' => 'Kukaemoa','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '4217','genus_name' => 'Melicope','species_name' => 'cruciata','common_name' => 'Pilo \'ula','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '4218','genus_name' => 'Melaleuca','species_name' => 'decussata','common_name' => 'Melaleuca lilac','growth_rate' => 'Fast','height_at_maturity' => '46'),
            array('id' => '4219','genus_name' => 'Melaleuca','species_name' => 'decora','common_name' => 'Feather Honey Myrtle','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '4220','genus_name' => 'Melaleuca','species_name' => 'dealbata','common_name' => 'Silver-leafed Paperbark','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '4222','genus_name' => 'Melaleuca','species_name' => 'diosmifolia','common_name' => 'Green Honey Myrtle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '4223','genus_name' => 'Melicope','species_name' => 'elleryana','common_name' => 'Pink Doughwood','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '4224','genus_name' => 'Melicope','species_name' => 'elliptica','common_name' => 'Leiohi\'iaka','growth_rate' => '','height_at_maturity' => '21'),
            array('id' => '4225','genus_name' => 'Melaleuca','species_name' => 'ericifolia','common_name' => 'Heath melaleuca','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '4226','genus_name' => 'Megaskepasma','species_name' => 'erythrochlamys','common_name' => 'Brazilian red cloak','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '4227','genus_name' => 'Metrosideros','species_name' => 'excelsa','common_name' => 'New zealand chrstmas tree','growth_rate' => '','height_at_maturity' => '65'),
            array('id' => '4230','genus_name' => 'Melaleuca','species_name' => 'fulgens','common_name' => 'Scarlet Honey Myrtle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '4231','genus_name' => 'Mespilus','species_name' => 'germanica','common_name' => 'European medlar','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '4232','genus_name' => 'Metasequoia','species_name' => 'glyptostroboides','common_name' => 'Dawn redwood','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '4233','genus_name' => 'Melaleuca','species_name' => 'glomerata','common_name' => 'Inland Paperbark','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '4235','genus_name' => 'Melaleuca','species_name' => 'halmaturorum','common_name' => 'Coastal Paperbark','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '4236','genus_name' => 'Melicope','species_name' => 'haupuensis','common_name' => 'Haupa mountain melicope','growth_rate' => '','height_at_maturity' => '26'),
            array('id' => '4237','genus_name' => 'Melicope','species_name' => 'hawaiensis','common_name' => 'Mokihana kukae moa','growth_rate' => '','height_at_maturity' => '21'),
            array('id' => '4238','genus_name' => 'Melicope','species_name' => 'haleakalae','common_name' => 'Haleakala melicope','growth_rate' => '','height_at_maturity' => '8'),
            array('id' => '4239','genus_name' => 'Meliosma','species_name' => 'herbertii','common_name' => 'Aguacatillo','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '4241','genus_name' => 'Melaleuca','species_name' => 'huegelii','common_name' => 'Chenille Honey Myrtle','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '4242','genus_name' => 'Melaleuca','species_name' => 'hypericifolia','common_name' => 'Hillock Bush','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '4243','genus_name' => 'Melaleuca','species_name' => 'incana','common_name' => 'Grey Honey Myrtle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '4244','genus_name' => 'Melicope','species_name' => 'kaalaensis','common_name' => 'Kaala melicope','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '4246','genus_name' => 'Metrosideros','species_name' => 'kermadecensis','common_name' => 'Kermadec pohutakawa','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '4247','genus_name' => 'Melicope','species_name' => 'knudsenii','common_name' => 'Olokele valley melicope','growth_rate' => '','height_at_maturity' => '24'),
            array('id' => '4248','genus_name' => 'Melaleuca','species_name' => 'lanceolata','common_name' => 'Rottnest Teatree','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '4249','genus_name' => 'Melaleuca','species_name' => 'lateritia','common_name' => 'Robin Red Breast Myrtle','growth_rate' => 'Moderate','height_at_maturity' => '2'),
            array('id' => '4250','genus_name' => 'Mecranium','species_name' => 'latifolium','common_name' => 'Camasey almendre','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '4251','genus_name' => 'Melaleuca','species_name' => 'leucadendra','common_name' => 'White paperbark','growth_rate' => 'Moderate','height_at_maturity' => '132'),
            array('id' => '4252','genus_name' => 'Melaleuca','species_name' => 'linariifolia','common_name' => 'Cajeput tree','growth_rate' => 'Fast','height_at_maturity' => '18'),
            array('id' => '4256','genus_name' => 'Metrosideros','species_name' => 'macropus','common_name' => '\'ohi\'a','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '4258','genus_name' => 'Melicope','species_name' => 'makahae','common_name' => 'Makaha valley melicope','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '4260','genus_name' => 'Melaleuca','species_name' => 'minutifolia','common_name' => 'Paperbark','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '4261','genus_name' => 'Melicope','species_name' => 'molokaiensis','common_name' => 'Molokai melicope','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '4262','genus_name' => 'Melanolepis','species_name' => 'multiglandulosa','common_name' => 'alom','growth_rate' => '','height_at_maturity' => '45'),
            array('id' => '4263','genus_name' => 'Melicope','species_name' => 'mucronulata','common_name' => 'Alani','growth_rate' => '','height_at_maturity' => '13'),
            array('id' => '4265','genus_name' => 'Melaleuca','species_name' => 'nesophila','common_name' => 'Pink melaleuca','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '4268','genus_name' => 'Melicope','species_name' => 'oahuensis','common_name' => 'Oahu melicope','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '4269','genus_name' => 'Meliosma','species_name' => 'obtusifolia','common_name' => 'Cacaillo','growth_rate' => '','height_at_maturity' => '65'),
            array('id' => '4271','genus_name' => 'Melicoccus','species_name' => 'oliviformis','common_name' => 'Cotopri','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '4272','genus_name' => 'Melicope','species_name' => 'orbicularis','common_name' => 'Honokahua melicope','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '4273','genus_name' => 'Melicope','species_name' => 'ovalis','common_name' => 'Hana melicope','growth_rate' => '','height_at_maturity' => '16'),
            array('id' => '4275','genus_name' => 'Melaleuca','species_name' => 'parvistaminea','common_name' => 'Broad-leaved paperbark','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '4276','genus_name' => 'Melicope','species_name' => 'pallida','common_name' => 'Pale melicope','growth_rate' => '','height_at_maturity' => '26'),
            array('id' => '4278','genus_name' => 'Melicope','species_name' => 'peduncularis','common_name' => 'Boxfruit alani','growth_rate' => '','height_at_maturity' => '8'),
            array('id' => '4280','genus_name' => 'Metrosideros','species_name' => 'polymorpha','common_name' => '\'ohi\'a lehua','growth_rate' => 'Slow','height_at_maturity' => '65'),
            array('id' => '4281','genus_name' => 'Melaleuca','species_name' => 'preissiana','common_name' => 'Moonah','growth_rate' => 'Moderate','height_at_maturity' => '9'),
            array('id' => '4283','genus_name' => 'Melicope','species_name' => 'pseudoanisata','common_name' => 'Kohala summit melicope','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '4284','genus_name' => 'Melicope','species_name' => 'puberula','common_name' => 'Hairy melicope','growth_rate' => '','height_at_maturity' => '21'),
            array('id' => '4285','genus_name' => 'Melaleuca','species_name' => 'quinquenervia','common_name' => 'Punk tree','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '4287','genus_name' => 'Melicope','species_name' => 'radiata','common_name' => 'Kapu melicope','growth_rate' => '','height_at_maturity' => '13'),
            array('id' => '4289','genus_name' => 'Metrosideros','species_name' => 'robusta','common_name' => 'Northern Rata','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '4290','genus_name' => 'Melicope','species_name' => 'rotundifolia','common_name' => 'Roundleaf melicope','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '4291','genus_name' => 'Metrosideros','species_name' => 'rugosa','common_name' => 'Lehua papa','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '4292','genus_name' => 'Melastoma','species_name' => 'sanguineum','common_name' => 'Red melastome','growth_rate' => '','height_at_maturity' => '27'),
            array('id' => '4293','genus_name' => 'Melicope','species_name' => 'saint-johnii','common_name' => 'St. john\'s melicope','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '4294','genus_name' => 'Melicope','species_name' => 'sandwicensis','common_name' => 'Mt. kaala melicope','growth_rate' => '','height_at_maturity' => '21'),
            array('id' => '4295','genus_name' => 'Metroxylon','species_name' => 'sagu','common_name' => 'true sago palm','growth_rate' => '','height_at_maturity' => '80'),
            array('id' => '4298','genus_name' => 'Meryta','species_name' => 'sinclairii','common_name' => 'Puka','growth_rate' => 'Fast','height_at_maturity' => '8'),
            array('id' => '4300','genus_name' => 'Melaleuca','species_name' => 'squamea','common_name' => 'Swamp Honey-myrtle','growth_rate' => 'Moderate','height_at_maturity' => '3'),
            array('id' => '4301','genus_name' => 'Melaleuca','species_name' => 'squarrosa','common_name' => 'Scented Paperbark','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '4302','genus_name' => 'Melaleuca','species_name' => 'styphelioides','common_name' => 'Prickly-leaved paperbark','growth_rate' => 'Fast','height_at_maturity' => '35'),
            array('id' => '4303','genus_name' => 'Melaleuca','species_name' => 'stypheloidies','common_name' => 'Melaleuca stypheloidies','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '4304','genus_name' => 'Metopium','species_name' => 'toxiferum','common_name' => 'Florida poisontree','growth_rate' => 'Moderate','height_at_maturity' => '48'),
            array('id' => '4305','genus_name' => 'Melochia','species_name' => 'tomentosa','common_name' => 'teabush','growth_rate' => '','height_at_maturity' => '5'),
            array('id' => '4306','genus_name' => 'Metrosideros','species_name' => 'tremuloides','common_name' => 'Lehua \'ahihi','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '4307','genus_name' => 'Melochia','species_name' => 'umbellata','common_name' => 'Hierba del soldado','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '4309','genus_name' => 'Melicope','species_name' => 'volcanica','common_name' => 'Volcanic melicope','growth_rate' => '','height_at_maturity' => '23'),
            array('id' => '4310','genus_name' => 'Metrosideros','species_name' => 'waialealae','common_name' => 'Kauai bottlebrush','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '4311','genus_name' => 'Melicope','species_name' => 'waialealae','common_name' => 'Alani wai','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '4313','genus_name' => 'Melicope','species_name' => 'wawraeana','common_name' => 'Monoa melicope','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '4314','genus_name' => 'Melicope','species_name' => 'zahlbruckneri','common_name' => 'Kipuka piaula','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '4315','genus_name' => 'Mimosa','species_name' => 'aculeaticarpa','common_name' => 'Catclaw mimosa','growth_rate' => '','height_at_maturity' => '8'),
            array('id' => '4320','genus_name' => 'Mimosa','species_name' => 'arenosa','common_name' => 'Elegant mimosa','growth_rate' => 'Fast','height_at_maturity' => '17'),
            array('id' => '4322','genus_name' => 'Mimosa','species_name' => 'benthamii','common_name' => 'Mimosa benthamii','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '4326','genus_name' => 'Miconia','species_name' => 'caudata','common_name' => 'Miconia caudata','growth_rate' => 'Fast','height_at_maturity' => '39'),
            array('id' => '4330','genus_name' => 'Michelia','species_name' => 'champaca','common_name' => 'Michelia champaca','growth_rate' => 'Moderate','height_at_maturity' => '165'),
            array('id' => '4338','genus_name' => 'Mimusops','species_name' => 'elengi','common_name' => 'Mimusop','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '4340','genus_name' => 'Michelia','species_name' => 'figo','common_name' => 'Banana shrub','growth_rate' => 'Moderate','height_at_maturity' => '16'),
            array('id' => '4342','genus_name' => 'Michelia','species_name' => 'formosana','common_name' => 'Michelia formosana','growth_rate' => 'Moderate','height_at_maturity' => ''),
            array('id' => '4346','genus_name' => 'Miconia','species_name' => 'impetiolaris','common_name' => 'Camasey de costilla','growth_rate' => 'Slow','height_at_maturity' => '8'),
            array('id' => '4349','genus_name' => 'Miconia','species_name' => 'laevigata','common_name' => 'Smooth johnnyberry','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '4353','genus_name' => 'Mimosa','species_name' => 'monancistra','common_name' => 'Catclaw','growth_rate' => '','height_at_maturity' => '3'),
            array('id' => '4358','genus_name' => 'Millettia','species_name' => 'pinnata','common_name' => 'Indian Beech','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '4360','genus_name' => 'Miconia','species_name' => 'prasina','common_name' => 'Granadillo bobo','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '4364','genus_name' => 'Miconia','species_name' => 'racemosa','common_name' => 'Camasey de felpa','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '4366','genus_name' => 'Miconia','species_name' => 'serrulata','common_name' => 'Jau jau','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '4373','genus_name' => 'Miconia','species_name' => 'thomasiana','common_name' => 'Camasey tomaso','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '4376','genus_name' => 'Morus','species_name' => 'alba','common_name' => 'White mulberry','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '4377','genus_name' => 'Morus','species_name' => 'alba \'Pendula\'','common_name' => 'Weeping white mullberry','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '4379','genus_name' => 'Montanoa','species_name' => 'arborescens','common_name' => 'Daisy tree','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '4381','genus_name' => 'Morus','species_name' => 'bombycis','common_name' => 'Satin mulberry','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '4382','genus_name' => 'Morus','species_name' => 'celtidifolia','common_name' => 'Texas mulberry','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '4383','genus_name' => 'Morinda','species_name' => 'citrifolia','common_name' => 'Indian mulberry','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '4384','genus_name' => 'Mouriri','species_name' => 'domingensis','common_name' => 'Murta','growth_rate' => '','height_at_maturity' => '55'),
            array('id' => '4385','genus_name' => 'Monotoca','species_name' => 'elliptica','common_name' => 'Tree Broom-heath','growth_rate' => 'Moderate','height_at_maturity' => '16'),
            array('id' => '4386','genus_name' => 'Morella','species_name' => 'faya','common_name' => 'Firetree','growth_rate' => 'Fast','height_at_maturity' => '27'),
            array('id' => '4389','genus_name' => 'Montanoa','species_name' => 'hibiscifolia','common_name' => 'Treedaisy','growth_rate' => '','height_at_maturity' => '12'),
            array('id' => '4392','genus_name' => 'Morella','species_name' => 'inodora','common_name' => 'Scentless bayberry','growth_rate' => 'Moderate','height_at_maturity' => '23'),
            array('id' => '4394','genus_name' => 'Morus','species_name' => 'microphylla','common_name' => 'Smallleaf mulbery','growth_rate' => 'Fast','height_at_maturity' => '58'),
            array('id' => '4395','genus_name' => 'Monodora','species_name' => 'myristica','common_name' => 'calabash nutmeg','growth_rate' => '','height_at_maturity' => '100'),
            array('id' => '4396','genus_name' => 'Morus','species_name' => 'nigra','common_name' => 'Black mulberry','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '4397','genus_name' => 'Moringa','species_name' => 'oleifera','common_name' => 'Horseradishtree','growth_rate' => 'Fast','height_at_maturity' => '36'),
            array('id' => '4398','genus_name' => 'Morus','species_name' => 'platanifolia','common_name' => 'Parasol mullberry','growth_rate' => 'Moderate','height_at_maturity' => '34'),
            array('id' => '4399','genus_name' => 'Morus','species_name' => 'rubra','common_name' => 'Red mulberry','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '4403','genus_name' => 'Thespesia','species_name' => 'grandiflora','common_name' => 'Maga','growth_rate' => 'Slow','height_at_maturity' => '70'),
            array('id' => '4404','genus_name' => 'Moringa','species_name' => 'stenopetala','common_name' => 'Cabbage-tree','growth_rate' => '','height_at_maturity' => '39'),
            array('id' => '4405','genus_name' => 'Morinda','species_name' => 'trimera','common_name' => 'Noni kuahiwi','growth_rate' => 'Moderate','height_at_maturity' => '31'),
            array('id' => '4408','genus_name' => 'Musa','species_name' => 'acuminata','common_name' => 'Edible banana','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '4410','genus_name' => 'Musa','species_name' => 'basjoo','common_name' => 'Japanese Banana','growth_rate' => 'Fast','height_at_maturity' => '4'),
            array('id' => '4411','genus_name' => 'Muntingia','species_name' => 'calabura','common_name' => 'Strawberrytree','growth_rate' => 'Fast','height_at_maturity' => '43'),
            array('id' => '4412','genus_name' => 'Musa','species_name' => 'ensete','common_name' => 'Ethiopian banana','growth_rate' => 'Fast','height_at_maturity' => '8'),
            array('id' => '4413','genus_name' => 'Mussaenda','species_name' => 'frondosa','common_name' => 'dhoobi tree','growth_rate' => '','height_at_maturity' => '5'),
            array('id' => '4414','genus_name' => 'Murraya','species_name' => 'paniculata \'Exotica\'','common_name' => 'Orange-jessamine','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '4415','genus_name' => 'Murraya','species_name' => 'paniculata','common_name' => 'China box','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '4416','genus_name' => 'Musa','species_name' => 'x paradisiaca','common_name' => 'French plantain','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '4417','genus_name' => 'Munroidendron','species_name' => 'racemosum','common_name' => 'False \'ohe','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '4418','genus_name' => 'Musa','species_name' => 'textilis','common_name' => 'abaca','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '4419','genus_name' => 'Musa','species_name' => 'x troglodytarum','common_name' => 'Fe\'l bananas','growth_rate' => 'Fast','height_at_maturity' => '40'),
            array('id' => '4420','genus_name' => 'Musa','species_name' => 'velutina','common_name' => 'Hairy banana','growth_rate' => 'Fast','height_at_maturity' => '5'),
            array('id' => '4421','genus_name' => 'Myoporum','species_name' => 'acuminatum','common_name' => 'Waterbush','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '4423','genus_name' => 'Myrsine','species_name' => 'alyxifolia','common_name' => 'Forest colicwood','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '4424','genus_name' => 'Myrsine','species_name' => 'australis','common_name' => 'Red Matipo','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '4425','genus_name' => 'Myroxylon','species_name' => 'balsamum','common_name' => 'balsam of Tolu','growth_rate' => '','height_at_maturity' => '130'),
            array('id' => '4426','genus_name' => 'Myrciaria','species_name' => 'borinquena','common_name' => 'False tamarisk','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '4428','genus_name' => 'Myrciaria','species_name' => 'cauliflora','common_name' => 'Brazilian Grape Tree','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '4430','genus_name' => 'Myrcia','species_name' => 'citrifolia','common_name' => 'Red rodwood','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '4431','genus_name' => 'Myrtus','species_name' => 'communis','common_name' => 'Myrtle','growth_rate' => 'Moderate','height_at_maturity' => '19'),
            array('id' => '4432','genus_name' => 'Myrsine','species_name' => 'coriacea','common_name' => 'Leathery colicwood','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '4433','genus_name' => 'Myrcia','species_name' => 'deflexa','common_name' => 'Cieneguillo','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '4434','genus_name' => 'Myrsine','species_name' => 'degeneri','common_name' => 'Summit colicwood','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '4435','genus_name' => 'Myrsine','species_name' => 'denticulata','common_name' => 'Bog colicwood','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '4436','genus_name' => 'Myrsine','species_name' => 'emarginata','common_name' => 'Mountain colicwood','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '4438','genus_name' => 'Myrsine','species_name' => 'fernseei','common_name' => 'Streambank colicwood','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '4440','genus_name' => 'Myrciaria','species_name' => 'floribunda','common_name' => 'Guavaberry','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '4441','genus_name' => 'Myrsine','species_name' => 'fosbergii','common_name' => 'Koolau range colicwood','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '4442','genus_name' => 'Myrcianthes','species_name' => 'fragrans','common_name' => 'Twinberry','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '4443','genus_name' => 'Myrospermum','species_name' => 'frutescens','common_name' => 'Cercipo','growth_rate' => '','height_at_maturity' => '32'),
            array('id' => '4444','genus_name' => 'Myristica','species_name' => 'fragrans','common_name' => 'Nutmeg','growth_rate' => '','height_at_maturity' => '43'),
            array('id' => '4446','genus_name' => 'Myrica','species_name' => 'gale','common_name' => 'Sweetgale','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '4447','genus_name' => 'Myrtillocactus','species_name' => 'geomentrizana','common_name' => 'Blue candle','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '4449','genus_name' => 'Myrica','species_name' => 'hartwegii','common_name' => 'Sierra bayberry','growth_rate' => 'Fast','height_at_maturity' => '33'),
            array('id' => '4451','genus_name' => 'Myrsine','species_name' => 'helleri','common_name' => 'Wahiawa bog colicwood','growth_rate' => 'Moderate','height_at_maturity' => '17'),
            array('id' => '4452','genus_name' => 'Myoporum','species_name' => 'insulare','common_name' => 'Boobialla','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '4453','genus_name' => 'Myristica','species_name' => 'insipida','common_name' => 'Australian Nutmeg','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '4455','genus_name' => 'Myrsine','species_name' => 'juddii','common_name' => 'Cloudswept colicwood','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '4456','genus_name' => 'Myrsine','species_name' => 'kauaiensis','common_name' => 'Kauai colicwood','growth_rate' => 'Moderate','height_at_maturity' => '9'),
            array('id' => '4457','genus_name' => 'Myrsine','species_name' => 'knudsenii','common_name' => 'Kokee colicwood','growth_rate' => 'Moderate','height_at_maturity' => '15'),
            array('id' => '4458','genus_name' => 'Myoporum','species_name' => 'laetum','common_name' => 'Mioporo','growth_rate' => 'Fast','height_at_maturity' => '23'),
            array('id' => '4460','genus_name' => 'Myrsine','species_name' => 'lanaiensis','common_name' => 'Lanai colicwood','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '4462','genus_name' => 'Myrsine','species_name' => 'lessertiana','common_name' => 'Kolea lau nui','growth_rate' => 'Moderate','height_at_maturity' => '27'),
            array('id' => '4463','genus_name' => 'Myrsine','species_name' => 'linearifolia','common_name' => 'Narrowleaf colicwood','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '4466','genus_name' => 'Myrsine','species_name' => 'mezii','common_name' => 'Hanapepe river colicwood','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '4469','genus_name' => 'Myrciaria','species_name' => 'myrtifolia','common_name' => 'Ridgetop guavaberry','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '4474','genus_name' => 'Myrsine','species_name' => 'petiolata','common_name' => 'Swamp colicwood','growth_rate' => 'Moderate','height_at_maturity' => '11'),
            array('id' => '4475','genus_name' => 'Myoporum','species_name' => 'platycarpum','common_name' => 'False sandalwood','growth_rate' => 'Fast','height_at_maturity' => '4'),
            array('id' => '4476','genus_name' => 'Myrcia','species_name' => 'popayanensis','common_name' => 'Arrayan','growth_rate' => 'Slow','height_at_maturity' => '33'),
            array('id' => '4478','genus_name' => 'Myrsine','species_name' => 'pukooensis','common_name' => 'Molokai colicwood','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '4479','genus_name' => 'Myrsine','species_name' => 'punctata','common_name' => 'Dotted colicwood','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '4482','genus_name' => 'Myrica','species_name' => 'rubra','common_name' => 'red bayberry','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '4483','genus_name' => 'Myoporum','species_name' => 'sandwicense','common_name' => 'Naio','growth_rate' => 'Fast','height_at_maturity' => '15'),
            array('id' => '4484','genus_name' => 'Myrsine','species_name' => 'sandwicensis','common_name' => 'Kokea lau li\'i','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '4485','genus_name' => 'Myrcia','species_name' => 'splendens','common_name' => 'Punchberry','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '4487','genus_name' => 'Myrtus','species_name' => 'ugni','common_name' => 'Chilean Guava','growth_rate' => 'Moderate','height_at_maturity' => '2'),
            array('id' => '4489','genus_name' => 'Myrsine','species_name' => 'vaccinioides','common_name' => 'Violet lake colicwood','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '4491','genus_name' => 'Myrsine','species_name' => 'wawraea','common_name' => 'Mt. kahili colicwood','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '4495','genus_name' => 'Nauclea','species_name' => 'orientalis','common_name' => 'Leichardt Pine','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '4497','genus_name' => 'Neviusia','species_name' => 'alabamensis','common_name' => 'Alabama snow-wreath','growth_rate' => 'Slow','height_at_maturity' => '6'),
            array('id' => '4499','genus_name' => 'Neea','species_name' => 'buxifolia','common_name' => 'Saltwood','growth_rate' => 'Slow','height_at_maturity' => '23'),
            array('id' => '4500','genus_name' => 'Neolamarckia','species_name' => 'cadamba','common_name' => 'Kadam','growth_rate' => '','height_at_maturity' => '100'),
            array('id' => '4501','genus_name' => 'Neuburgia','species_name' => 'celebica','common_name' => 'kalm','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '4503','genus_name' => 'Nectandra','species_name' => 'coriacea','common_name' => 'Lancewood','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '4506','genus_name' => 'Neonauclea','species_name' => 'forsteri','common_name' => 'afa','growth_rate' => '','height_at_maturity' => '45'),
            array('id' => '4508','genus_name' => 'Nectandra','species_name' => 'hihua','common_name' => 'Shinglewood','growth_rate' => 'Moderate','height_at_maturity' => '63'),
            array('id' => '4510','genus_name' => 'Nectandra','species_name' => 'krugii','common_name' => 'Krug\'s sweetwood','growth_rate' => 'Moderate','height_at_maturity' => '63'),
            array('id' => '4512','genus_name' => 'Nephelium','species_name' => 'lappaceum','common_name' => 'Rambutan','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '4513','genus_name' => 'Nectandra','species_name' => 'membranacea','common_name' => 'Sweetwood','growth_rate' => 'Moderate','height_at_maturity' => '80'),
            array('id' => '4515','genus_name' => 'Nemopanthus','species_name' => 'mucronatus','common_name' => 'Catberry','growth_rate' => 'Slow','height_at_maturity' => '15'),
            array('id' => '4516','genus_name' => 'Nerium','species_name' => 'oleander','common_name' => 'Oleander','growth_rate' => 'Fast','height_at_maturity' => '12'),
            array('id' => '4518','genus_name' => 'Neisosperma','species_name' => 'oppositifolia','common_name' => 'Twin-Apple','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '4520','genus_name' => 'Nectandra','species_name' => 'patens','common_name' => 'Capberry','growth_rate' => 'Moderate','height_at_maturity' => '63'),
            array('id' => '4521','genus_name' => 'Nesoluma','species_name' => 'polynesicum','common_name' => 'Keahi','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '4526','genus_name' => 'Nematolepis','species_name' => 'squameum','common_name' => 'Satinwood','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '4527','genus_name' => 'Nectandra','species_name' => 'turbacensis','common_name' => 'Laurel amarillo','growth_rate' => 'Moderate','height_at_maturity' => '63'),
            array('id' => '4530','genus_name' => 'Nicotiana','species_name' => 'glauca','common_name' => 'Tree tobacco','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '4531','genus_name' => 'Nothofagus','species_name' => 'alpina','common_name' => 'RaulÃ','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '4532','genus_name' => 'Nothofagus','species_name' => 'antarctica','common_name' => 'Antarctic Beech','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '4533','genus_name' => 'Nolina','species_name' => 'bigelovii','common_name' => 'Bigelow\'s nolina','growth_rate' => '','height_at_maturity' => '7'),
            array('id' => '4534','genus_name' => 'Nothocestrum','species_name' => 'breviflorum','common_name' => 'Smallflower aiea','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '4535','genus_name' => 'Nothofagus','species_name' => 'cunninghamii','common_name' => 'Myrtle Beech','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '4536','genus_name' => 'Nothofagus','species_name' => 'dombeyi','common_name' => 'Coigue','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '4537','genus_name' => 'Nothofagus','species_name' => 'fusca','common_name' => 'New Zealand Red Beech','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '4539','genus_name' => 'Nothocestrum','species_name' => 'latifolium','common_name' => 'Broadleaf aiea','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '4540','genus_name' => 'Notelaea','species_name' => 'ligustrina','common_name' => 'Native Olive','growth_rate' => 'Moderate','height_at_maturity' => '12'),
            array('id' => '4541','genus_name' => 'Nothocestrum','species_name' => 'longifolium','common_name' => 'Longleaf aiea','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '4542','genus_name' => 'Notelaea','species_name' => 'longifolia','common_name' => 'Long-leaved olive','growth_rate' => 'Moderate','height_at_maturity' => '9'),
            array('id' => '4543','genus_name' => 'Nothofagus','species_name' => 'obliqua','common_name' => 'Roble','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '4544','genus_name' => 'Nolina','species_name' => 'parryi','common_name' => 'Parry\'s beargrass','growth_rate' => '','height_at_maturity' => '6'),
            array('id' => '4545','genus_name' => 'Nolina','species_name' => 'parviflora','common_name' => 'Mexican bear grass','growth_rate' => 'Slow','height_at_maturity' => '5'),
            array('id' => '4546','genus_name' => 'Nothocestrum','species_name' => 'peltatum','common_name' => 'Oahu aiea','growth_rate' => '','height_at_maturity' => '27'),
            array('id' => '4547','genus_name' => 'Nothofagus','species_name' => 'pumilio','common_name' => 'Lenga','growth_rate' => 'Moderate','height_at_maturity' => '100'),
            array('id' => '4548','genus_name' => 'Nototrichium','species_name' => 'sandwicense','common_name' => 'Hawai\'i rockwort','growth_rate' => '','height_at_maturity' => '14'),
            array('id' => '4549','genus_name' => 'Nuytsia','species_name' => 'floribunda','common_name' => 'W.A. Christmas tree','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '4550','genus_name' => 'Nyssa','species_name' => 'aquatica','common_name' => 'Water tupelo','growth_rate' => 'Moderate','height_at_maturity' => '100'),
            array('id' => '4551','genus_name' => 'Nyssa','species_name' => 'biflora','common_name' => 'Swamp tupelo','growth_rate' => 'Moderate','height_at_maturity' => '115'),
            array('id' => '4554','genus_name' => 'Nyssa','species_name' => 'ogeche','common_name' => 'Ogeechee tupelo','growth_rate' => 'Fast','height_at_maturity' => '43'),
            array('id' => '4555','genus_name' => 'Nyssa','species_name' => 'selvatica','common_name' => 'Sour gum','growth_rate' => 'Moderate','height_at_maturity' => '60'),
            array('id' => '4556','genus_name' => 'Nyssa','species_name' => 'sinensis','common_name' => 'Chinese Tupelo','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '4557','genus_name' => 'Nyssa','species_name' => 'sylvatica','common_name' => 'Black tupelo','growth_rate' => 'Moderate','height_at_maturity' => '95'),
            array('id' => '4558','genus_name' => 'Nyssa','species_name' => 'sylvatica \'Firestarter\'','common_name' => 'Firestarted black gum','growth_rate' => '','height_at_maturity' => '35'),
            array('id' => '4559','genus_name' => 'Nyssa','species_name' => 'sylvatica \'Green Gable\'','common_name' => 'Green Gable black gum','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '4560','genus_name' => 'Nyssa','species_name' => 'ursina','common_name' => 'Bear tupelo','growth_rate' => 'Slow','height_at_maturity' => '92'),
            array('id' => '4561','genus_name' => 'Ochrosia','species_name' => 'compta','common_name' => 'Holei','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '4562','genus_name' => 'Ochrosia','species_name' => 'elliptica','common_name' => 'Elliptic yellowwood','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '4563','genus_name' => 'Ocotea','species_name' => 'floribunda','common_name' => 'Laurel espada','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '4565','genus_name' => 'Ochrosia','species_name' => 'haleakalae','common_name' => 'Island yellowwood','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '4568','genus_name' => 'Ochrosia','species_name' => 'kauaiensis','common_name' => 'Kauai yellowwood','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '4569','genus_name' => 'Ochrosia','species_name' => 'kilaueaensis','common_name' => 'Hawai\'i yellowwood','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '4570','genus_name' => 'Ocotea','species_name' => 'leucoxylon','common_name' => 'Loblolly sweetwood','growth_rate' => '','height_at_maturity' => '70'),
            array('id' => '4571','genus_name' => 'Ocotea','species_name' => 'moschata','common_name' => 'Nemoca','growth_rate' => '','height_at_maturity' => '80'),
            array('id' => '4576','genus_name' => 'Ochroma','species_name' => 'pyramidale','common_name' => 'West indian balsa','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '4578','genus_name' => 'Ocotea','species_name' => 'spathulata','common_name' => 'Nemoca cimarrona','growth_rate' => '','height_at_maturity' => '45'),
            array('id' => '4583','genus_name' => 'Oemleria','species_name' => 'cerasiformis','common_name' => 'Indian plum','growth_rate' => 'Fast','height_at_maturity' => '5'),
            array('id' => '4584','genus_name' => 'Olearia','species_name' => 'argophylla','common_name' => 'Musk Daisy Bush','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '4585','genus_name' => 'Olea','species_name' => 'emarginata','common_name' => 'Madagascar olive','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '4586','genus_name' => 'Olea','species_name' => 'europaea','common_name' => 'Olive','growth_rate' => 'Slow','height_at_maturity' => '35'),
            array('id' => '4588','genus_name' => 'Olea','species_name' => 'europaea ssp. Africana','common_name' => 'African Olive','growth_rate' => 'Fast','height_at_maturity' => '12'),
            array('id' => '4589','genus_name' => 'Olea','species_name' => 'europaea ssp. Europea','common_name' => 'European Olive','growth_rate' => 'Fast','height_at_maturity' => '12'),
            array('id' => '4590','genus_name' => 'Olea','species_name' => 'ferruginea','common_name' => 'Kahu','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '4591','genus_name' => 'Olneya','species_name' => 'tesota','common_name' => 'Desert ironwood','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '4592','genus_name' => 'Homalanthus','species_name' => 'populifolius','common_name' => 'Queensland Poplar','growth_rate' => 'Fast','height_at_maturity' => '8'),
            array('id' => '4599','genus_name' => 'Opuntia','species_name' => 'ficus-indica','common_name' => 'Tuna cactus','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '4615','genus_name' => 'Ormosia','species_name' => 'krugii','common_name' => 'Peronia','growth_rate' => '','height_at_maturity' => '67'),
            array('id' => '4618','genus_name' => 'Oreopanax','species_name' => 'xalapensis','common_name' => 'Oreopanax xalapensis','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '4619','genus_name' => 'Osmanthus','species_name' => 'americanus','common_name' => 'Devilwood','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '4621','genus_name' => 'Ostrya','species_name' => 'carpinifolia','common_name' => 'Hop hornbeam','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '4622','genus_name' => 'Osyris','species_name' => 'compressa','common_name' => 'Cape sumach','growth_rate' => 'Moderate','height_at_maturity' => '21'),
            array('id' => '4623','genus_name' => 'Osmanthus','species_name' => 'fragrans','common_name' => 'Sweet olive','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '4624','genus_name' => 'Osmanthus','species_name' => 'heterophyllus','common_name' => 'Holly osmanthus','growth_rate' => 'Slow','height_at_maturity' => '12'),
            array('id' => '4625','genus_name' => 'Ostrya','species_name' => 'knowltonii','common_name' => 'Knowlton hophornbeam','growth_rate' => 'Slow','height_at_maturity' => '40'),
            array('id' => '4627','genus_name' => 'Ostrya','species_name' => 'virginiana','common_name' => 'Eastern hophornbeam','growth_rate' => 'Slow','height_at_maturity' => '45'),
            array('id' => '4628','genus_name' => 'Ottoschulzia','species_name' => 'rhodoxylon','common_name' => 'Pincho palo de rosa','growth_rate' => '','height_at_maturity' => '45'),
            array('id' => '4630','genus_name' => 'Ouratea','species_name' => 'ilicifolia','common_name' => 'Rose wood','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '4631','genus_name' => 'Ouratea','species_name' => 'litoralis','common_name' => 'Abey amarillo','growth_rate' => '','height_at_maturity' => '20'),
            array('id' => '4633','genus_name' => 'Oxydendrum','species_name' => 'arboreum','common_name' => 'Sourwood','growth_rate' => 'Slow','height_at_maturity' => '35'),
            array('id' => '4634','genus_name' => 'Oxylobium','species_name' => 'arborescens','common_name' => 'Tall Oxylobium','growth_rate' => 'Fast','height_at_maturity' => '2'),
            array('id' => '4635','genus_name' => 'Oxylobium','species_name' => 'ilicifolium','common_name' => 'Prickly Oxylobium','growth_rate' => 'Fast','height_at_maturity' => '3'),
            array('id' => '4638','genus_name' => 'Parkinsonia','species_name' => 'aculeata','common_name' => 'Jerusalem thorn','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '4643','genus_name' => 'Pachira','species_name' => 'aquatica','common_name' => 'guiana chestnut','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '4648','genus_name' => 'Parkinsonia','species_name' => 'x \'Desert Museum\'','common_name' => 'Desert Museum paloverde','growth_rate' => 'Fast','height_at_maturity' => '25'),
            array('id' => '4652','genus_name' => 'Parathesis','species_name' => 'crenulata','common_name' => 'Scratchthroat','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '4653','genus_name' => 'Palicourea','species_name' => 'crocea','common_name' => 'Red cappel','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '4655','genus_name' => 'Pangium','species_name' => 'edule','common_name' => 'keluak','growth_rate' => '','height_at_maturity' => '180'),
            array('id' => '4657','genus_name' => 'Paulownia','species_name' => 'fortunei','common_name' => 'Paulownia','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '4660','genus_name' => 'Palicourea','species_name' => 'guianensis','common_name' => 'Showy cappel','growth_rate' => '','height_at_maturity' => '13'),
            array('id' => '4662','genus_name' => 'Pachira','species_name' => 'insignis','common_name' => 'Wild chestnut','growth_rate' => 'Moderate','height_at_maturity' => '68'),
            array('id' => '4665','genus_name' => 'Paraserianthes','species_name' => 'lophantha','common_name' => 'Plume albizia','growth_rate' => 'Fast','height_at_maturity' => '27'),
            array('id' => '4666','genus_name' => 'Paraserianthes','species_name' => 'lophantha lop.','common_name' => 'Cape leeuwin wattle','growth_rate' => 'Moderate','height_at_maturity' => '26'),
            array('id' => '4668','genus_name' => 'Paxistima','species_name' => 'myrsinites','common_name' => 'Oregon boxleaf','growth_rate' => 'Slow','height_at_maturity' => '1'),
            array('id' => '4669','genus_name' => 'Parinari','species_name' => 'pachyphylla','common_name' => 'Perehuetano','growth_rate' => 'Slow','height_at_maturity' => '98'),
            array('id' => '4672','genus_name' => 'Parrotia','species_name' => 'persica','common_name' => 'Persian ironwood','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '4674','genus_name' => 'Parkinsonia','species_name' => 'praecox','common_name' => 'Sonoran palo verde','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '4675','genus_name' => 'Parthenocissus','species_name' => 'quinquefolia','common_name' => 'Virginia creeper','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '4676','genus_name' => 'Pachira','species_name' => 'quinata','common_name' => 'Pochote','growth_rate' => 'Moderate','height_at_maturity' => '39'),
            array('id' => '4679','genus_name' => 'Paliurus','species_name' => 'spina-christi','common_name' => 'Jeruselem thorn','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '4680','genus_name' => 'Paeonia','species_name' => 'x suffruticosa','common_name' => 'Tree Peony','growth_rate' => 'Fast','height_at_maturity' => '3'),
            array('id' => '4681','genus_name' => 'Parkinsonia','species_name' => 'texana','common_name' => 'Texas paloverde','growth_rate' => 'Fast','height_at_maturity' => '13'),
            array('id' => '4682','genus_name' => 'Pandanus','species_name' => 'tectorius','common_name' => 'Tahitian screwpine','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '4683','genus_name' => 'Parkia','species_name' => 'timoriana','common_name' => 'tree bean','growth_rate' => '','height_at_maturity' => '90'),
            array('id' => '4684','genus_name' => 'Paulownia','species_name' => 'tomentosa','common_name' => 'Royal paulownia','growth_rate' => 'Fast','height_at_maturity' => '70'),
            array('id' => '4685','genus_name' => 'Parthenocissus','species_name' => 'tricuspidata','common_name' => 'Boston ivy','growth_rate' => 'Fast','height_at_maturity' => '50'),
            array('id' => '4686','genus_name' => 'Pandanus','species_name' => 'utilis','common_name' => 'Common screwpine','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '4687','genus_name' => 'Pandanus','species_name' => 'veitchii','common_name' => 'Veitch\'s screwpine','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '4688','genus_name' => 'Passiflora','species_name' => 'x violacea','common_name' => 'Violet passion flower','growth_rate' => 'Fast','height_at_maturity' => '26'),
            array('id' => '4690','genus_name' => 'Pemphis','species_name' => 'acidula','common_name' => 'Pemphis','growth_rate' => '','height_at_maturity' => '18'),
            array('id' => '4691','genus_name' => 'Persea','species_name' => 'americana','common_name' => 'Avocado','growth_rate' => 'Moderate','height_at_maturity' => '38'),
            array('id' => '4693','genus_name' => 'Persea','species_name' => 'borbonia','common_name' => 'Redbay','growth_rate' => 'Moderate','height_at_maturity' => '70'),
            array('id' => '4694','genus_name' => 'Peumus','species_name' => 'boldus','common_name' => 'Boldo','growth_rate' => 'Slow','height_at_maturity' => '20'),
            array('id' => '4696','genus_name' => 'Pentadesma','species_name' => 'butyracea','common_name' => 'butter tree','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '4697','genus_name' => 'Persea','species_name' => 'caerulea','common_name' => 'Persea caerulea','growth_rate' => 'Moderate','height_at_maturity' => '66'),
            array('id' => '4698','genus_name' => 'Petitia','species_name' => 'domingensis','common_name' => 'Bastard stopper','growth_rate' => 'Slow','height_at_maturity' => '43'),
            array('id' => '4700','genus_name' => 'Peltophorum','species_name' => 'dubia','common_name' => 'Horsebush','growth_rate' => 'Fast','height_at_maturity' => '64'),
            array('id' => '4701','genus_name' => 'Persoonia','species_name' => 'falcata','common_name' => 'Geebung','growth_rate' => 'Moderate','height_at_maturity' => '5'),
            array('id' => '4704','genus_name' => 'Pereskia','species_name' => 'guamacho','common_name' => 'Guamacho','growth_rate' => 'Slow','height_at_maturity' => '26'),
            array('id' => '4705','genus_name' => 'Persea','species_name' => 'humilis','common_name' => 'Silk bay','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '4707','genus_name' => 'Pentzia','species_name' => 'incana','common_name' => 'African sheepbush','growth_rate' => '','height_at_maturity' => '1'),
            array('id' => '4708','genus_name' => 'Persea','species_name' => 'krugii','common_name' => 'Canela','growth_rate' => 'Moderate','height_at_maturity' => '56'),
            array('id' => '4709','genus_name' => 'Petalostylis','species_name' => 'labicheoides','common_name' => 'Slender Petalostylis','growth_rate' => 'Moderate','height_at_maturity' => '4'),
            array('id' => '4710','genus_name' => 'Persea','species_name' => 'lingue','common_name' => 'Lingue','growth_rate' => 'Moderate','height_at_maturity' => '56'),
            array('id' => '4712','genus_name' => 'Persea','species_name' => 'palustris','common_name' => 'Swamp bay','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '4713','genus_name' => 'Peltophorum','species_name' => 'pterocarpum','common_name' => 'Yellow flametree','growth_rate' => 'Fast','height_at_maturity' => '48'),
            array('id' => '4714','genus_name' => 'Petalostigma','species_name' => 'pubescens','common_name' => 'Quinine Tree','growth_rate' => 'Moderate','height_at_maturity' => '6'),
            array('id' => '4716','genus_name' => 'Perrottetia','species_name' => 'sandwicensis','common_name' => 'Olomea','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '4717','genus_name' => 'Peucephyllum','species_name' => 'schottii','common_name' => 'Schott\'s pygmycedar','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '4718','genus_name' => 'Persea','species_name' => 'thunbergii','common_name' => 'Japanese bay tree','growth_rate' => 'Slow','height_at_maturity' => '30'),
            array('id' => '4721','genus_name' => 'Persea','species_name' => 'urbaniana','common_name' => 'Aquacatillo','growth_rate' => 'Moderate','height_at_maturity' => '56'),
            array('id' => '4722','genus_name' => 'Phyllanthus','species_name' => 'acidus','common_name' => 'Tahitian gooseberry tree','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '4723','genus_name' => 'Phyllanthus','species_name' => 'acuminatus','common_name' => 'Jamaican gooseberry tree','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '4725','genus_name' => 'Phyllocladus','species_name' => 'alpinus Cockannes Blue','common_name' => 'Mountain Toatoa','growth_rate' => 'Moderate','height_at_maturity' => '9'),
            array('id' => '4726','genus_name' => 'Phellodendron','species_name' => 'amurense','common_name' => 'Amur corktree','growth_rate' => 'Moderate','height_at_maturity' => '50'),
            array('id' => '4730','genus_name' => 'Phyllocladus','species_name' => 'asplenifolius','common_name' => 'Celerytop pine','growth_rate' => 'Slow','height_at_maturity' => '18'),
            array('id' => '4731','genus_name' => 'Phyllostachys','species_name' => 'bambusoides Castillon','common_name' => 'Castillon Bamboo','growth_rate' => 'Fast','height_at_maturity' => '10'),
            array('id' => '4732','genus_name' => 'Photinia','species_name' => 'beauverdiana','common_name' => 'Christmas berry','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '4733','genus_name' => 'Philodendron','species_name' => 'bipinnatifidum','common_name' => 'Tree philodendron','growth_rate' => '','height_at_maturity' => '15'),
            array('id' => '4734','genus_name' => 'Phytolacca','species_name' => 'bogotensis','common_name' => 'Southern pokeweed','growth_rate' => 'Fast','height_at_maturity' => '6'),
            array('id' => '4735','genus_name' => 'Phoenix','species_name' => 'canariensis','common_name' => 'Canary island date palm','growth_rate' => 'Slow','height_at_maturity' => '60'),
            array('id' => '4738','genus_name' => 'Philadelphus','species_name' => 'coronarius','common_name' => 'Sweet mock orange','growth_rate' => 'Fast','height_at_maturity' => '12'),
            array('id' => '4743','genus_name' => 'Phoenix','species_name' => 'dactylifera','common_name' => 'Date palm','growth_rate' => 'Slow','height_at_maturity' => '65'),
            array('id' => '4744','genus_name' => 'Photinia','species_name' => 'davidiana','common_name' => 'Chinese photinia','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '4745','genus_name' => 'Phytolacca','species_name' => 'dioica','common_name' => 'Ombu','growth_rate' => 'Fast','height_at_maturity' => '38'),
            array('id' => '4746','genus_name' => 'Phyllanthus','species_name' => 'distichus','common_name' => 'Pamakani mahu','growth_rate' => '','height_at_maturity' => '3'),
            array('id' => '4747','genus_name' => 'Phytolacca','species_name' => 'dodecandra','common_name' => 'African soapberry','growth_rate' => 'Fast','height_at_maturity' => '22'),
            array('id' => '4748','genus_name' => 'Phyllostachys','species_name' => 'edulis','common_name' => 'Noble Bamboo','growth_rate' => 'Fast','height_at_maturity' => '22'),
            array('id' => '4749','genus_name' => 'Phyllanthus','species_name' => 'emblica','common_name' => 'Emblic','growth_rate' => '','height_at_maturity' => '60'),
            array('id' => '4753','genus_name' => 'Photinia','species_name' => 'floribunda','common_name' => 'Purple chokeberry','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '4754','genus_name' => 'Photinia','species_name' => 'x fraseri','common_name' => 'Fraser photinia','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '4758','genus_name' => 'Photinia','species_name' => 'glabra','common_name' => 'Japanese photinia','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '4760','genus_name' => 'Phytolacca','species_name' => 'heterosepala','common_name' => 'Mexican pokeweed','growth_rate' => 'Fast','height_at_maturity' => '60'),
            array('id' => '4765','genus_name' => 'Phellodendron','species_name' => 'japonicum','common_name' => 'Japanese corktree','growth_rate' => 'Moderate','height_at_maturity' => '63'),
            array('id' => '4768','genus_name' => 'Phillyrea','species_name' => 'latifolia','common_name' => 'Broad-leaved phillyrea','growth_rate' => 'Slow','height_at_maturity' => '26'),
            array('id' => '4774','genus_name' => 'Photinia','species_name' => 'melanocarpa','common_name' => 'Black chokeberry','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '4777','genus_name' => 'Physocarpus','species_name' => 'monogynus','common_name' => 'Mountain ninebark','growth_rate' => '','height_at_maturity' => '3'),
            array('id' => '4779','genus_name' => 'Phyllostachys','species_name' => 'nigra','common_name' => 'Black Bamboo','growth_rate' => 'Fast','height_at_maturity' => '9'),
            array('id' => '4781','genus_name' => 'Physocarpus','species_name' => 'opulifolius','common_name' => 'Common ninebark','growth_rate' => 'Moderate','height_at_maturity' => '10'),
            array('id' => '4789','genus_name' => 'Photinia','species_name' => 'pyrifolia','common_name' => 'Red chokeberry','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '4790','genus_name' => 'Phoenix','species_name' => 'reclinata','common_name' => 'Senegal date palm','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '4791','genus_name' => 'Phoenix','species_name' => 'reclinata x canariensis','common_name' => 'Senegal Date hybrid','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '4792','genus_name' => 'Phoenix','species_name' => 'reclinata x sylvestris','common_name' => 'Senegal date','growth_rate' => 'Moderate','height_at_maturity' => '33'),
            array('id' => '4793','genus_name' => 'Phoenix','species_name' => 'roebelenii','common_name' => 'Pygmy date palm','growth_rate' => 'Slow','height_at_maturity' => '9'),
            array('id' => '4794','genus_name' => 'Philadelphus','species_name' => 'schrenkii','common_name' => 'Mock orange','growth_rate' => '','height_at_maturity' => '13'),
            array('id' => '4795','genus_name' => 'Photinia','species_name' => 'serratifolia','common_name' => 'Taiwanese photinia','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '4796','genus_name' => 'Photinia','species_name' => 'serrulata','common_name' => 'Photinia','growth_rate' => 'Moderate','height_at_maturity' => '16'),
            array('id' => '4800','genus_name' => 'Phoenix','species_name' => 'sylvestris','common_name' => 'Wild date palm','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '4804','genus_name' => 'Photinia','species_name' => 'villosa','common_name' => 'Oriental photinia','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '4807','genus_name' => 'Picea','species_name' => 'abies','common_name' => 'Norway spruce','growth_rate' => 'Slow','height_at_maturity' => '130'),
            array('id' => '4808','genus_name' => 'Picea','species_name' => 'abies x asperata','common_name' => 'Norway x chinese spruce','growth_rate' => 'Moderate','height_at_maturity' => '76'),
            array('id' => '4809','genus_name' => 'Pictetia','species_name' => 'aculeata','common_name' => 'Fustic','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '4810','genus_name' => 'Pisonia','species_name' => 'aculeata','common_name' => 'Pullback','growth_rate' => 'Moderate','height_at_maturity' => '67'),
            array('id' => '4812','genus_name' => 'Piper','species_name' => 'aduncum','common_name' => 'Matico pepper','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '4813','genus_name' => 'Pinus','species_name' => 'albicaulis','common_name' => 'Whitebark pine','growth_rate' => 'Slow','height_at_maturity' => '65'),
            array('id' => '4814','genus_name' => 'Pipturus','species_name' => 'albidus','common_name' => 'Waimea pipturus','growth_rate' => '','height_at_maturity' => '10'),
            array('id' => '4815','genus_name' => 'Pisonia','species_name' => 'albida','common_name' => 'Corcho bobo','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '4816','genus_name' => 'Piper','species_name' => 'amalago','common_name' => 'Amalago pepper','growth_rate' => '','height_at_maturity' => '50'),
            array('id' => '4818','genus_name' => 'Pittosporum','species_name' => 'angustifolium','common_name' => 'Native Apricot','growth_rate' => 'Moderate','height_at_maturity' => '8'),
            array('id' => '4819','genus_name' => 'Picrasma','species_name' => 'antillana','common_name' => 'Bitter ash','growth_rate' => '','height_at_maturity' => '23'),
            array('id' => '4821','genus_name' => 'Pinus','species_name' => 'aristata','common_name' => 'Bristlecone pine','growth_rate' => 'Slow','height_at_maturity' => '40'),
            array('id' => '4822','genus_name' => 'Pinus','species_name' => 'armandii','common_name' => 'David\'s pine','growth_rate' => 'Moderate','height_at_maturity' => '60'),
            array('id' => '4823','genus_name' => 'Cojoba','species_name' => 'arborea','common_name' => 'Cojoba','growth_rate' => '','height_at_maturity' => '56'),
            array('id' => '4824','genus_name' => 'Pittosporum','species_name' => 'argentifolium','common_name' => 'Hawai\'i poisonberry tree','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '4825','genus_name' => 'Pinus','species_name' => 'arizonica','common_name' => 'Arizona pine','growth_rate' => 'Slow','height_at_maturity' => '70'),
            array('id' => '4829','genus_name' => 'Picea','species_name' => 'asperata','common_name' => 'Chinese spruce','growth_rate' => 'Slow','height_at_maturity' => '80'),
            array('id' => '4830','genus_name' => 'Pinus','species_name' => 'attenuata','common_name' => 'Knobcone pine','growth_rate' => 'Fast','height_at_maturity' => '70'),
            array('id' => '4831','genus_name' => 'Pinus','species_name' => 'x attenuradiata','common_name' => 'Pinus x attenuradiata','growth_rate' => 'Slow','height_at_maturity' => '70'),
            array('id' => '4832','genus_name' => 'Pistacia','species_name' => 'atlantica','common_name' => 'Mt. atlas mastic tree','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '4833','genus_name' => 'Piper','species_name' => 'auritum','common_name' => 'Vera cruz pepper','growth_rate' => '','height_at_maturity' => '17'),
            array('id' => '4835','genus_name' => 'Pinus','species_name' => 'ayacahuite','common_name' => 'Mexican White Pine','growth_rate' => 'Moderate','height_at_maturity' => '148'),
            array('id' => '4836','genus_name' => 'Pinus','species_name' => 'banksiana','common_name' => 'Jack pine','growth_rate' => 'Fast','height_at_maturity' => '80'),
            array('id' => '4837','genus_name' => 'Pinus','species_name' => 'balfouriana','common_name' => 'Foxtail pine','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '4838','genus_name' => 'Picea','species_name' => 'bicolor','common_name' => 'Alcock spruce','growth_rate' => 'Slow','height_at_maturity' => '76'),
            array('id' => '4839','genus_name' => 'Pittosporum','species_name' => 'bicolor','common_name' => 'Banyalla','growth_rate' => 'Slow','height_at_maturity' => '10'),
            array('id' => '4841','genus_name' => 'Picea','species_name' => 'brewerana','common_name' => 'Brewer spruce','growth_rate' => 'Slow','height_at_maturity' => '100'),
            array('id' => '4842','genus_name' => 'Picea','species_name' => 'brachytyla','common_name' => 'Sargent\'s Spruce','growth_rate' => 'Moderate','height_at_maturity' => '30'),
            array('id' => '4843','genus_name' => 'Pinus','species_name' => 'brutia','common_name' => 'Turkish pine','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '4844','genus_name' => 'Pisonia','species_name' => 'brunoniana','common_name' => 'Australasia catchbirdtree','growth_rate' => 'Fast','height_at_maturity' => '35'),
            array('id' => '4845','genus_name' => 'Picea','species_name' => 'breweriana','common_name' => 'Brewer\'s Weeping Spruce','growth_rate' => 'Slow','height_at_maturity' => '40'),
            array('id' => '4846','genus_name' => 'Pinus','species_name' => 'bungeana','common_name' => 'Lacebark pine','growth_rate' => 'Slow','height_at_maturity' => '38'),
            array('id' => '4847','genus_name' => 'Pinus','species_name' => 'canariensis','common_name' => 'Canary island pine','growth_rate' => 'Slow','height_at_maturity' => '98'),
            array('id' => '4848','genus_name' => 'Pisonia','species_name' => 'capitata','common_name' => 'Mexican devil\'s-claws','growth_rate' => 'Fast','height_at_maturity' => '20'),
            array('id' => '4849','genus_name' => 'Pinus','species_name' => 'californiarum','common_name' => 'California pine','growth_rate' => 'Slow','height_at_maturity' => '70'),
            array('id' => '4851','genus_name' => 'Piscidia','species_name' => 'carthagenensis','common_name' => 'Stinkwood','growth_rate' => 'Fast','height_at_maturity' => '30'),
            array('id' => '4852','genus_name' => 'Pinus','species_name' => 'cembroides','common_name' => 'Mexican pinyon','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '4853','genus_name' => 'Pinus','species_name' => 'cembra','common_name' => 'Swiss stone pine','growth_rate' => 'Slow','height_at_maturity' => '65'),
            array('id' => '4854','genus_name' => 'Pistacia','species_name' => 'chinensis','common_name' => 'Chinese pistache','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '4856','genus_name' => 'Pinus','species_name' => 'clausa','common_name' => 'Sand pine','growth_rate' => 'Slow','height_at_maturity' => '80'),
            array('id' => '4857','genus_name' => 'Pinus','species_name' => 'contorta','common_name' => 'Lodgepole pine','growth_rate' => 'Fast','height_at_maturity' => '99'),
            array('id' => '4858','genus_name' => 'Pinus','species_name' => 'coulteri','common_name' => 'Coulter pine','growth_rate' => 'Slow','height_at_maturity' => '80'),
            array('id' => '4859','genus_name' => 'Pittosporum','species_name' => 'confertiflorum','common_name' => 'Ho\'awa','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '4860','genus_name' => 'Pinus','species_name' => 'contorta var. bolanderi','common_name' => 'Bolander beach pine','growth_rate' => 'Slow','height_at_maturity' => '70'),
            array('id' => '4861','genus_name' => 'Pinus','species_name' => 'contorta var. latifolia','common_name' => 'Tall lodgepole pine','growth_rate' => 'Slow','height_at_maturity' => '65'),
            array('id' => '4862','genus_name' => 'Pinus','species_name' => 'contorta v murrayana','common_name' => 'Murray\'s lodgepole pine','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '4863','genus_name' => 'Pittosporum','species_name' => 'crassifolium','common_name' => 'Stiffleaf cheesewood','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '4865','genus_name' => 'Pinus','species_name' => 'densiflora','common_name' => 'Japanese red pine','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '4866','genus_name' => 'Pinus','species_name' => 'devoniana','common_name' => 'Michoacan pine','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '4867','genus_name' => 'Pinus','species_name' => 'discolor','common_name' => 'Border pinyon','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '4869','genus_name' => 'Pimenta','species_name' => 'dioica','common_name' => 'Allspice','growth_rate' => 'Moderate','height_at_maturity' => '40'),
            array('id' => '4870','genus_name' => 'Pinus','species_name' => 'douglasiana','common_name' => 'Douglas pine','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '4871','genus_name' => 'Pithecellobium','species_name' => 'dulce','common_name' => 'Monkeypod','growth_rate' => 'Fast','height_at_maturity' => '67'),
            array('id' => '4872','genus_name' => 'Pinus','species_name' => 'duranguensis','common_name' => 'Durango pine','growth_rate' => '','height_at_maturity' => '30'),
            array('id' => '4873','genus_name' => 'Pinus','species_name' => 'echinata','common_name' => 'Shortleaf pine','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '4874','genus_name' => 'Pinus','species_name' => 'edulis','common_name' => 'Pinyon pine','growth_rate' => 'Slow','height_at_maturity' => '50'),
            array('id' => '4875','genus_name' => 'Pinus','species_name' => 'elliottii','common_name' => 'Slash pine','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '4876','genus_name' => 'Pinus','species_name' => 'eldarica','common_name' => 'Afghan pine','growth_rate' => 'Fast','height_at_maturity' => '65'),
            array('id' => '4877','genus_name' => 'Picea','species_name' => 'engelmannii','common_name' => 'Engelmann spruce','growth_rate' => 'Slow','height_at_maturity' => '120'),
            array('id' => '4878','genus_name' => 'Pinus','species_name' => 'engelmannii','common_name' => 'Apache pine','growth_rate' => 'Slow','height_at_maturity' => '82'),
            array('id' => '4879','genus_name' => 'Pittosporum','species_name' => 'eugenioides','common_name' => 'Tarata','growth_rate' => 'Moderate','height_at_maturity' => '35'),
            array('id' => '4880','genus_name' => 'Pittosporum','species_name' => 'eugenoides','common_name' => 'Lemonwood','growth_rate' => 'Moderate','height_at_maturity' => '17'),
            array('id' => '4881','genus_name' => 'Pittosporum','species_name' => 'eugenioides \'Variegatum\'','common_name' => 'Variegated tarata','growth_rate' => 'Moderate','height_at_maturity' => '17'),
            array('id' => '4882','genus_name' => 'Picrasma','species_name' => 'excelsa','common_name' => 'Bitterwood','growth_rate' => '','height_at_maturity' => '40'),
            array('id' => '4884','genus_name' => 'Pinus','species_name' => 'flexilis','common_name' => 'Limber pine','growth_rate' => 'Slow','height_at_maturity' => '66'),
            array('id' => '4885','genus_name' => 'Pieris','species_name' => 'floribunda','common_name' => 'Mountain fetterbush','growth_rate' => 'Slow','height_at_maturity' => '66'),
            array('id' => '4886','genus_name' => 'Pittosporum','species_name' => 'flocculosum','common_name' => 'Waianae range cheesewood','growth_rate' => 'Moderate','height_at_maturity' => '25'),
            array('id' => '4887','genus_name' => 'Pisonia','species_name' => 'floridana','common_name' => 'Rock key devil\'s-claws','growth_rate' => 'Fast','height_at_maturity' => '35'),
            array('id' => '4889','genus_name' => 'Pittosporum','species_name' => 'gayanum','common_name' => 'Waialeale cheesewood','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '4891','genus_name' => 'Picea','species_name' => 'glauca','common_name' => 'White spruce','growth_rate' => 'Slow','height_at_maturity' => '100'),
            array('id' => '4892','genus_name' => 'Pinus','species_name' => 'glabra','common_name' => 'Spruce pine','growth_rate' => 'Fast','height_at_maturity' => '90'),
            array('id' => '4893','genus_name' => 'Picea','species_name' => 'glehnii','common_name' => 'Sakhalin spruce','growth_rate' => 'Fast','height_at_maturity' => '100'),
            array('id' => '4894','genus_name' => 'Pittosporum','species_name' => 'glabrum','common_name' => 'Koolau range cheesewood','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '4897','genus_name' => 'Pinus','species_name' => 'greggii','common_name' => 'Gregg\'s pine','growth_rate' => 'Moderate','height_at_maturity' => '20'),
            array('id' => '4898','genus_name' => 'Pithecellobium','species_name' => 'graciliflorum','common_name' => 'Guadeloupe blackbead','growth_rate' => 'Moderate','height_at_maturity' => '41'),
            array('id' => '4899','genus_name' => 'Pisonia','species_name' => 'grandis','common_name' => 'Grand devil\'s-claws','growth_rate' => 'Fast','height_at_maturity' => '67'),
            array('id' => '4900','genus_name' => 'Pinus','species_name' => 'halepensis','common_name' => 'Aleppo pine','growth_rate' => 'Moderate','height_at_maturity' => '65'),
            array('id' => '4901','genus_name' => 'Pinus','species_name' => 'hartwegii','common_name' => 'Hartweg\'s pine','growth_rate' => '','height_at_maturity' => '25'),
            array('id' => '4902','genus_name' => 'Pittosporum','species_name' => 'hawaiiense','common_name' => 'Hawai\'i cheesewood','growth_rate' => 'Moderate','height_at_maturity' => '13'),
            array('id' => '4903','genus_name' => 'Pinus','species_name' => 'heldreichii','common_name' => 'Heldreich\'s Pine','growth_rate' => 'Slow','height_at_maturity' => '25'),
            array('id' => '4905','genus_name' => 'Pittosporum','species_name' => 'hosmeri','common_name' => 'Kona cheesewood','growth_rate' => 'Moderate','height_at_maturity' => '18'),
            array('id' => '4906','genus_name' => 'Pinus','species_name' => 'x holfordiana','common_name' => 'Holford\'s Pine','growth_rate' => 'Moderate','height_at_maturity' => '28'),
            array('id' => '4907','genus_name' => 'Pinanga','species_name' => 'insignis','common_name' => 'pinang palm','growth_rate' => '','height_at_maturity' => '30')
        );

        Tree::insert($trees);

        $seeder = new TreeSpeciesSeeder7;
        $seeder->run();
    }
}